### ISSUE TITLE
Cannot build PyPy 5.4.0

### ISSUE THREAD

**Issue by alexanderwhatley** [Microsoft/WSL#1052]
Also posted here: https://bitbucket.org/pypy/pypy/issues/2393/cannot-build-pypy-540.

I have tried building PyPy version 5.4.0, following the directions here: http://pypy.readthedocs.io/en/latest/build.html#install-build-time-dependencies, but it does not work:

```
alex@ALEXANDERPC:/mnt/c/Users/Alexander/Google Drive/Programming/PyPy/pypy2-v5.4.0-src/pypy2-v5.4.0-src/pypy/goal$ python2 ../../rpython/bin/rpython --opt=2
[translation:info] 2.7.11 |Anaconda 4.0.0 (64-bit)| (default, Dec  6 2015, 18:08:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
[platform:msg] Set platform with 'host' cc=None, using cc='gcc', version='Unknown'
[translation:info] Translating target as defined by targetpypystandalone
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/gcctest.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/gcctest.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/gcctest.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/gcctest
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/gcctest.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/gcctest.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/gcctest.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/gcctest
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_0.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_0.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_0.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_0
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused -I/mnt/c/Users/Alexander/Google Drive/Programming/PyPy/pypy2-v5.4.0-src/pypy2-v5.4.0-src/rpython/translator/c /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_1.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_1.o
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused -I/mnt/c/Users/Alexander/Google Drive/Programming/PyPy/pypy2-v5.4.0-src/pypy2-v5.4.0-src/rpython/translator/c /mnt/c/Users/Alexander/Google Drive/Programming/PyPy/pypy2-v5.4.0-src/pypy2-v5.4.0-src/rpython/translator/c/src/thread.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/rpython/translator/c/src/thread.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_1.o /tmp/usession-release-pypy2.7-v5.4.0-5/rpython/translator/c/src/thread.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_1
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_2.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_2.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_2.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_2
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_3.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_3.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_3.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_3
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_4.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_4.o
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_5.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_5.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_5.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_5
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_6.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_6.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_6.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_6
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_7.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_7.o
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_8.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_8.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_8.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_8
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_9.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_9.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_9.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_9
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_10.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_10.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_10.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_10
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_11.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_11.o
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_12.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_12.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_12.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_12
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_13.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_13.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_13.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_13
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_14.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_14.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_14.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_14
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_15.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_15.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_15.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_15
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_16.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_16.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_16.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_16
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_17.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_17.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_17.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_17
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_18.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_18.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_18.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_18
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_19.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_19.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_19.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_19
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_20.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_20.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_20.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_20
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_21.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_21.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_21.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_21
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_22.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_22.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_22.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_22
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_23.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_23.o
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_24.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_24.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_24.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_24
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_25.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_25.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_25.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_25
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_26.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_26.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_26.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_26
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_27.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_27.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_27.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_27
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_28.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_28.o
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_29.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_29.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_29.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_29
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_30.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_30.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_30.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_30
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_31.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_31.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_31.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_31
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_32.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_32.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_32.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_32
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_33.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_33.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_33.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_33
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_34.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_34.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_34.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_34
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_35.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_35.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_35.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_35
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_36.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_36.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_36.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_36
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_37.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_37.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_37.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_37
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_38.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_38.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_38.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_38
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_39.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_39.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_39.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_39
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_40.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_40.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_40.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_40
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_41.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_41.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_41.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_41
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_42.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_42.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_42.o -pthread -Wl,--export-dynamic -lutil -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_42
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_43.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_43.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_43.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_43
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_44.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_44.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_44.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_44
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_45.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_45.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_45.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_45
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_46.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_46.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_46.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_46
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_47.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_47.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_47.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_47
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused -fPIC -fvisibility=hidden -g -O0 -DRPY_EXTERN=RPY_EXPORTED -DRPYTHON_LL2CTYPES /tmp/usession-release-pypy2.7-v5.4.0-5/module_cache/module_0.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/module_cache/module_0.o
[platform:execute] gcc -shared /tmp/usession-release-pypy2.7-v5.4.0-5/module_cache/module_0.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/shared_cache/externmod.so
[translation] PyPy config object:
[translation] [objspace]
    [std]
        intshortcut = True
        optimized_list_getitem = True
        withspecialisedtuple = True
    [usemodules]
        __pypy__ = True
        _ast = True
        _cffi_backend = True
        _codecs = True
        _collections = True
        _continuation = True
        _csv = True
        _hashlib = True
        _io = True
        _jitlog = True
        _locale = True
        _lsprof = True
        _md5 = True
        _minimal_curses = True
        _multibytecodec = True
        _multiprocessing = True
        _pickle_support = True
        _pypyjson = True
        _random = True
        _rawffi = True
        _sha = True
        _socket = True
        _sre = True
        _ssl = True
        _testing = True
        _vmprof = True
        _weakref = True
        array = True
        binascii = True
        bz2 = True
        cStringIO = True
        cmath = True
        cppyy = True
        cpyext = True
        crypt = True
        errno = True
        fcntl = True
        gc = True
        imp = True
        marshal = True
        math = True
        micronumpy = True
        mmap = True
        operator = True
        parser = True
        pwd = True
        pyexpat = True
        select = True
        signal = True
        struct = True
        symbol = True
        termios = True
        thread = True
        time = True
        token = True
        unicodedata = True
        zipimport = True
        zlib = True
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_48.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_48.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_48.o -pthread -Wl,--export-dynamic -ldl -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_48
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_49.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_49.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_49.o -pthread -Wl,--export-dynamic -lintl -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_49
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_50.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_50.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_50.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_50
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_51.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_51.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_51.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_51
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_52.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_52.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_52.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_52
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_53.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_53.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_53.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_53
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_54.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_54.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_54.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_54
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_55.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_55.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_55.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_55
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_56.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_56.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_56.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_56
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_57.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_57.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_57.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_57
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_58.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_58.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_58.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_58
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_59.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_59.o
[platform:execute] gcc -c -O3 -pthread -fomit-frame-pointer -Wall -Wno-unused /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_60.c -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_60.o
[platform:execute] gcc /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_60.o -pthread -Wl,--export-dynamic -lrt -o /tmp/usession-release-pypy2.7-v5.4.0-5/platcheck_60
[translation:info] Error:
   File "/mnt/c/Users/Alexander/Google Drive/Programming/PyPy/pypy2-v5.4.0-src/pypy2-v5.4.0-src/rpython/translator/goal/translate.py", line 283, in main
    default_goal='compile')
   File "/mnt/c/Users/Alexander/Google Drive/Programming/PyPy/pypy2-v5.4.0-src/pypy2-v5.4.0-src/rpython/translator/driver.py", line 566, in from_targetspec
    spec = target(driver, args)
   File "targetpypystandalone.py", line 295, in target
    return self.get_entry_point(config)
   File "targetpypystandalone.py", line 343, in get_entry_point
    space = make_objspace(config)
   File "/mnt/c/Users/Alexander/Google Drive/Programming/PyPy/pypy2-v5.4.0-src/pypy2-v5.4.0-src/pypy/tool/option.py", line 35, in make_objspace
    return Space(config)
   File "/mnt/c/Users/Alexander/Google Drive/Programming/PyPy/pypy2-v5.4.0-src/pypy2-v5.4.0-src/pypy/interpreter/baseobjspace.py", line 415, in __init__
    self.initialize()
   File "/mnt/c/Users/Alexander/Google Drive/Programming/PyPy/pypy2-v5.4.0-src/pypy2-v5.4.0-src/pypy/objspace/std/objspace.py", line 100, in initialize
    self.make_builtins()
   File "/mnt/c/Users/Alexander/Google Drive/Programming/PyPy/pypy2-v5.4.0-src/pypy2-v5.4.0-src/pypy/interpreter/baseobjspace.py", line 609, in make_builtins
    self.install_mixedmodule(mixedname, installed_builtin_modules)
   File "/mnt/c/Users/Alexander/Google Drive/Programming/PyPy/pypy2-v5.4.0-src/pypy2-v5.4.0-src/pypy/interpreter/baseobjspace.py", line 640, in install_mixedmodule
    modname = self.setbuiltinmodule(mixedname)
   File "/mnt/c/Users/Alexander/Google Drive/Programming/PyPy/pypy2-v5.4.0-src/pypy2-v5.4.0-src/pypy/interpreter/baseobjspace.py", line 486, in setbuiltinmodule
    mod = Module(self, self.wrap(name))
   File "/mnt/c/Users/Alexander/Google Drive/Programming/PyPy/pypy2-v5.4.0-src/pypy2-v5.4.0-src/pypy/module/cppyy/__init__.py", line 37, in __init__
    from pypy.module.cppyy import capi
   File "/mnt/c/Users/Alexander/Google Drive/Programming/PyPy/pypy2-v5.4.0-src/pypy2-v5.4.0-src/pypy/module/cppyy/capi/__init__.py", line 12, in <module>
    from pypy.module.cppyy.capi.loadable_capi import *
   File "/mnt/c/Users/Alexander/Google Drive/Programming/PyPy/pypy2-v5.4.0-src/pypy2-v5.4.0-src/pypy/module/cppyy/capi/loadable_capi.py", line 2, in <module>
    from rpython.rlib import jit, jit_libffi, libffi, rdynload, objectmodel
   File "/mnt/c/Users/Alexander/Google Drive/Programming/PyPy/pypy2-v5.4.0-src/pypy2-v5.4.0-src/rpython/rlib/jit_libffi.py", line 4, in <module>
    from rpython.rlib import clibffi, jit
   File "/mnt/c/Users/Alexander/Google Drive/Programming/PyPy/pypy2-v5.4.0-src/pypy2-v5.4.0-src/rpython/rlib/clibffi.py", line 82, in <module>
    include_dirs = platform.include_dirs_for_libffi(),
   File "/mnt/c/Users/Alexander/Google Drive/Programming/PyPy/pypy2-v5.4.0-src/pypy2-v5.4.0-src/rpython/translator/platform/__init__.py", line 236, in include_dirs_for_libffi
    dirs = self._include_dirs_for_libffi()
   File "/mnt/c/Users/Alexander/Google Drive/Programming/PyPy/pypy2-v5.4.0-src/pypy2-v5.4.0-src/rpython/translator/platform/linux.py", line 34, in _include_dirs_for_libffi
    check_result_dir=True)
   File "/mnt/c/Users/Alexander/Google Drive/Programming/PyPy/pypy2-v5.4.0-src/pypy2-v5.4.0-src/rpython/translator/platform/posix.py", line 89, in _pkg_config
    raise ValueError(msg)
[translation:ERROR] ValueError: running 'pkg-config libffi --cflags-only-I' failed:
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
and the default ['/usr/include/libffi'] is not a valid directory
[translation] start debugger...
> /mnt/c/Users/Alexander/Google Drive/Programming/PyPy/pypy2-v5.4.0-src/pypy2-v5.4.0-src/rpython/translator/platform/posix.py(89)_pkg_config()
-> raise ValueError(msg)
(Pdb+) exit
alex@ALEXANDERPC:/mnt/c/Users/Alexander/Google Drive/Programming/PyPy/pypy2-v5.4.0-src/pypy2-v5.4.0-src/pypy/goal$ pkg-config libffi
alex@ALEXANDERPC:/mnt/c/Users/Alexander/Google Drive/Programming/PyPy/pypy2-v5.4.0-src/pypy2-v5.4.0-src/pypy/goal$ pkg-config libffi --cflags-only-I
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
```

The issue is that libffi is installed on my system, and according to the PyPy developers, the Linux environment is probably not correctly configured. When I run the failing command by itself, I get this:

```

alex@ALEXANDERPC:/mnt/c/Users/Alexander$ pkg-config libffi --cflags-only-I
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
```

**Comment by sunilmut** [comment]
Which build are you seeing this on? Looks like this is fixed on the 14915 build (which is publicly available through the Windows Insider program).

**Comment by alexanderwhatley** [comment]
I'm still using the Anniversary build. I'm on the Insider slow ring, so I don't think I have access to 14915 yet...

**Comment by andersah** [comment]
You need
sudo apt-get install pkg-config

I found this out while compiling micropython

**Comment by alexanderwhatley** [comment]
@andersah It already is installed, so I think the problem still lies with WSL:

```
alex@ALEXANDERPC:/mnt/c/Users/Alexander$ sudo apt-get install pkg-config
[sudo] password for alex:
Reading package lists... Done
Building dependency tree
Reading state information... Done
pkg-config is already the newest version.
The following packages were automatically installed and are no longer required:
  cpp-5 dh-apparmor intltool libasan2 libblas-dev libbsd-dev libcc1-0
  libcilkrts5 libgcc-5-dev libgmp-dev libgmpxx4ldbl libhawtjni-runtime-java
  libjansi-java libjansi-native-java liblapack-dev liblsan0 libmpx0
  libpcre3-dev libpcrecpp0 libreadline-dev libreadline6-dev libubsan0
  libxml-parser-perl pypy-lib python-scour scala-library
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
```

**Comment by TiberiumPY** [comment]
@alexanderwhatley you can always download pypy binary, and then translate your own build with it(it's a lot faster in translation)

**Comment by alexanderwhatley** [comment]
@TiberiumPY it does not work with the prebuilt binary either.

**Comment by TiberiumPY** [comment]
@alexanderwhatley did you tried portable pypy binary?

**Comment by TiberiumPY** [comment]
@alexanderwhatley https://github.com/squeaky-pl/portable-pypy

**Comment by alexanderwhatley** [comment]
@sunilmut I upgraded to build 14931, and am still getting the same problem.

**Comment by apatrascu** [comment]
@alexanderwhatley I just compiled PyPy latest version on my WSL and worked without any issues. I have Windows 10 (Version 10.0.14393). 

Ubuntu WSL details:

```
root@L:/mnt/c/opt/work/pypy-wsl/pypy/goal# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

PyPy details:

```
root@L:/mnt/c/opt/work/pypy-wsl/pypy/goal# ./pypy-c
Python 2.7.13 (e1fb7a07c627, May 10 2017, 18:10:57)
[PyPy 5.8.0-alpha0 with GCC 4.8.4] on linux2
```

Requirements:

```
sudo apt-get install gcc make libffi-dev pkg-config libz-dev libbz2-dev \
libsqlite3-dev libncurses-dev libexpat1-dev libssl-dev libgdbm-dev \
tk-dev libgc-dev python-cffi \
liblzma-dev
```

Translation line: ```cd pypy/goal && python ../../rpython/bin/rpython --opt=jit```

**Comment by tara-raj** [comment]
Closing issue as it appears to be fixed. Please re-open if you run into this again.
