### ISSUE TITLE
Can't scroll up?

### ISSUE THREAD

**Issue by arpan74** [Microsoft/WSL#1066]
The console is limited to whatever is on my computer monitor. I can't seem to scroll up to see previous commands or output if it exceeds the viewing screen. 

![image](https://cloud.githubusercontent.com/assets/5677429/18337148/fc758f5e-755b-11e6-9285-de317a0483ca.png)

As you can see in the image, there is no scroll bar, and I can't scroll up to see the previous input. Any help would be appreciated. Thanks.

**Comment by zadjii-msft** [comment]
Right click the title bar, "Properties"... "Layout", then change the "Screen Buffer Size" height to something like 9000.

Sometimes, if you change those properties inside an application like vim, the height can get clipped to the window size. I don't have a good repro on the exact steps yet, but the above should fix it.

**Comment by arpan74** [comment]
Awesome, thanks.

**Comment by wizardist** [comment]
You can always pipe the output to `less` as well. You can then scroll it using PgUp/PgDown:

```
apt-get | less
```

**Comment by mstrelan** [comment]
This never used to be an issue for me but has become an issue recently. Has something changed?

**Comment by zadjii-msft** [comment]
@mstrelan It can happen occasionally. It might be due to changing your console settings while in the alternate buffer, but it could also be something else that I don't understand at all. There was a kernel bug a few weeks ago that caused lxss to think the TTY size was the screen buffer size, not the window size, but that was fixed and shouldn't be happening anymore. Fixing the "Screen Buffer Height" property should be enough to fix this behavior (and not have it come back on re-launch)

**Comment by kjohnsen** [comment]
I've changed the screen buffer height property to 999 (it doesn't let me go any higher) and I still have the problem of a very limited scrollback.

**Comment by bitcrazed** [comment]
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).

**Comment by luchillo17** [comment]
Hi there, this just happened to me and the buffer size fix didn't work for me, any suggestions?

**Comment by luchillo17** [comment]
Oops, saw my error, @kjohnsen you were probably making the same mistake, it's the buffer size in the `Layout` tab, not the one in the `Options` tab.

**Comment by bitcrazed** [comment]
@luchillo17 As a matter of interest, are you running Windows 10 > 1903 and not using Windows Terminal?

**Comment by luchillo17** [comment]
Not sure what you mean with Windows Terminal, just using the Ubuntu 20.04 package from the Windows Store, hope this answers your question:
![image](https://user-images.githubusercontent.com/9698639/85886045-f15dc880-b7aa-11ea-8d10-277d583411cc.png)

**Comment by Rich-Farmbrough** [comment]
This just happened to me for the first time too.  Invoking wsl from the windows key.  Windows build 19042.1110

uname -a

Linux Dev13 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
