### ISSUE TITLE
wsl 2 can not use the mount path from dev drive

### ISSUE THREAD

**Issue by leolcao** [microsoft/WSL#10792]
### Windows Version

Microsoft Windows [Version 10.0.22621.2715]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.15.90.1

### Distro Version

Ubuntu 22.04

### Repro Steps

1. create the dev drive from dev home preview app, also from https://learn.microsoft.com/en-us/windows/dev-drive/
2. the dev drive is set to E:, and path is set to D:\packages
3. shutdown wsl by `wsl --shutdown`
4. open the WSL2 Ubuntu 22.04 distro, input `ls /mnt/d/packages`
5. error: `ls: cannot access '/mnt/d/packages': Input/output error`

This error affects the usage of `wsl docker` command from windows host directly, like:

```
wsl docker compose up
```
if there is volume binding in docker-compose.yml file from the path mount from dev drive, also failed, like: `d:\packages\workdir:/opt/workdir`, In before, it works and `d:\packages\workdir` will be converted to `/mnt/d/packages/workdir` in wsl distro

Besides, in the windows terminal setting, if I set the default startingDirectory to "d:\\packages", the wsl terminall will failed also, but in before, wsl terminal can tell the startingDirectory, and convert to '/mnt/d/packages'

### Expected Behavior

wsl 2 can use the path mount from dev drive like before.

### Actual Behavior

leo@LeoCao-OMEN8Pro:~$ ls /mnt/d/packages/
ls: cannot access '/mnt/d/packages/': Input/output error

### Diagnostic Logs

![image](https://github.com/microsoft/WSL/assets/539695/3c099863-60e3-4581-bdd8-6d5cf8f1507f)

[WslLogs-2023-11-22_22-03-38.zip](https://github.com/microsoft/WSL/files/13440529/WslLogs-2023-11-22_22-03-38.zip)

**Comment by leolcao** [comment]
> /logs

Hi I uploaded the logs~

**Comment by OneBlue** [comment]
Thank you @leolcao. Looking at the logs I can see that you have a custom kernel. Can you see if you can reproduce the issue with the official kernel ? If so, please collect /logs again

**Comment by leolcao** [comment]
I just updated the wsl to 2.0.9, and remove the custom kernel, unlucky, this issue still there~

```
> wsl -v
WSL 版本： 2.0.9.0
内核版本： 5.15.133.1-1
WSLg 版本： 1.0.59
MSRDC 版本： 1.2.4677
Direct3D 版本： 1.611.1-81528511
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows 版本： 10.0.22621.2715
```

```.wslconfig
[wsl2]
processors=10
memory=16GB
swap=0
localhostForwarding=true
kernelCommandLine=systemd.unified_cgroup_hierarchy=1 cgroup_no_v1=all
```

```
leo@LeoCao-OMEN8Pro:~$ ls /mnd/d/Projects
ls: cannot access '/mnd/d/Projects': No such file or directory
```

btw, the dev-drive is mount to E:, and it is no error if I use command `ls /mnt/e` in the wsl ubuntu distro. This error is only for the mount path in the ntfs drive from one dev drive.

E:\(dev drive) --> D:\Projects (mount path in ntfs drive)

[WslLogs-2023-11-24_08-38-15.zip](https://github.com/microsoft/WSL/files/13454106/WslLogs-2023-11-24_08-38-15.zip)

**Comment by OneBlue** [comment]
@craigloewen-msft: Looks like we need to update p9rdr.sys to follow dev-drive mounts.

**Comment by GF-Huang** [comment]
Same issue. Dev Drive mount at D:\Dev\

```
>wsl --version
WSL 版本： 2.0.14.0
内核版本： 5.15.133.1-1
WSLg 版本： 1.0.59
MSRDC 版本： 1.2.4677
Direct3D 版本： 1.611.1-81528511
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows 版本： 10.0.22631.3296
```

![image](https://github.com/microsoft/WSL/assets/4510984/3c00ecbc-643d-495b-8e60-c44deec25acf)

![image](https://github.com/microsoft/WSL/assets/4510984/0c75710d-e7ab-47c1-a2a1-48498ebd08f9)

**Comment by OneBlue** [comment]
The issue is fixed with Windows 11 24H2 (the root cause of the issue is in the Windows image so the fix cannot be part of the WSL package).

**Comment by pengweiqhca** [comment]
> The issue is fixed with Windows 11 24H2 (the root cause of the issue is in the Windows image so the fix cannot be part of the WSL package).

Dev drive must have "Drive Letter".

**Comment by codekaizen** [comment]
> The issue is fixed with Windows 11 24H2 (the root cause of the issue is in the Windows image so the fix cannot be part of the WSL package).

I tried the 24H2 release candidate Win11 build but the `fsync` error continues to appear on a Dev Drive.

**Comment by juchom** [comment]
This issue is still present with 24H2, could you please reopen it :

Windows information

```
nu> wsl -v
WSL version: 2.3.24.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2033
```

Docker information

```
nu> docker -v
Docker version 27.2.0, build 3ab4256
```

DevDrive information

```
nu> fsutil devdrv query d:
This is a trusted developer volume.

Developer volumes are protected by antivirus filter.

Filters currently attached to this developer volume:
    WdFilter
```

If you run this command :

```
docker run --rm --name pg-test -e POSTGRES_PASSWORD=Pwd12345! -v d:/dev/pgtest:/var/lib/postgresql/data -p 5432:5432 postgres:15.8
```

You will have this output

```
chmod: changing permissions of '/var/lib/postgresql/data': Operation not permitted
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... initdb: error: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted
```

**Comment by GF-Huang** [comment]
> This issue is still present with 24H2, could you please reopen it :

Agree. Issue still.

```
版本	Windows 11 专业版
版本号	24H2
安装日期	‎2024/‎10/‎2
操作系统版本	26100.2033
体验	Windows Feature Experience Pack 1000.26100.23.0
```

**Comment by juchom** [comment]
This issue is still present with 24H2, could you please reopen it :

Windows information

```
nu> wsl -v
WSL version: 2.3.24.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2033
```

Docker information

```
nu> docker -v
Docker version 27.2.0, build 3ab4256
```

DevDrive information

```
nu> fsutil devdrv query d:
This is a trusted developer volume.

Developer volumes are protected by antivirus filter.

Filters currently attached to this developer volume:
    WdFilter
```

If you run this command :

```
docker run --rm --name pg-test -e POSTGRES_PASSWORD=Pwd12345! -v d:/dev/pgtest:/var/lib/postgresql/data -p 5432:5432 postgres:15.8
```

You will have this output

```
chmod: changing permissions of '/var/lib/postgresql/data': Operation not permitted
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... initdb: error: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted
```

I also tried this according to this doc : https://learn.microsoft.com/en-us/windows/dev-drive/#filters-for-common-scenarios

Adding filters for Docker: Running containers out of Dev Drive `bindFlt, wcifs`

```
fsutil devdrv setfiltersallowed /f /volume D: "bindFlt, wcifs"
```

Make sure they are present

```
nu> fsutil devdrv query d:
This is a trusted developer volume.

Developer volumes are protected by antivirus filter.

Filters allowed on this developer volume:
    bindFlt, wcifs

Filters currently attached to this developer volume:
    WdFilter
```

Full reboot of the system and same issue.

**Comment by kirk-marple** [comment]
This may have broken with a recent Win11 update; this had been working perfectly for months, and last night my system installed a Windows Update and now I can't access anything from my Dev Drive using WSL2.

**Comment by PhiliaTheCat** [comment]
Same issue on my system after a recent system update. Seems that update breaks the compatibility. I think this worth a reopening.

**Comment by OneBlue** [comment]
Reopening due to reports of the issue not being resolved.

@juchom / @kirk-marple, can you capture /logs of the issues you're seeing ?

**Comment by theAeon** [comment]
another +1 on the pile

**Comment by juchom** [comment]
Here are the logs for my case

> Reopening due to reports of the issue not being resolved.
> 
> [@juchom](https://github.com/juchom) / [@kirk-marple](https://github.com/kirk-marple), can you capture /logs of the issues you're seeing ?

[WslLogs-2024-10-16_10-57-38.zip](https://github.com/user-attachments/files/17392682/WslLogs-2024-10-16_10-57-38.zip)

**Comment by Tony763** [comment]
Same issue on linux. (Ubuntu 24.10)

`/var/lib/postgresql/14` is mounted volume.

```
chown -R postgres:postgres /var/lib/postgresql/14/main 
chown: cannot read directory '/var/lib/postgresql/14/main/pg_serial': Permission denied
chown: changing ownership of '/var/lib/postgresql/14/main/postmaster.pid': Operation not permitted
...
```

**Comment by ishpagin** [comment]
+1

**Comment by kirk-marple** [comment]
> Reopening due to reports of the issue not being resolved.
> 
> [@juchom](https://github.com/juchom) / [@kirk-marple](https://github.com/kirk-marple), can you capture /logs of the issues you're seeing ?

My logs are linked to my report of this issue:
https://github.com/microsoft/WSL/issues/12156

**Comment by Nehcknarf** [comment]
I met same problem after update to win11 26100.2161
<3>WSL (1522) ERROR: CreateProcessCommon:551: chdir(/mnt/d/PycharmProjects/) failed 13

**Comment by fgroen** [comment]
Another +1, went from a working setup on win11 insider previer (10.0.26120.2130) to a fresh win11 enterprise install (10.0.26100.2161).
Now WSL cannot access that ReFS drive.

**Comment by cloud-yu** [comment]
win11 26100.2033 works well, after install **`KB5044384`** , DevDriver mount failed in wsl2

**Comment by kirb** [comment]
Also confirming, doing a System Restore to before [KB5044384](https://support.microsoft.com/topic/october-24-2024-kb5044384-os-build-26100-2161-preview-5a4ac390-7c7b-4f7f-81c2-c2b329ac86ab) was installed solved this for me. It will not be listed in the Uninstall Updates page, and trying to do so manually with wusa.exe will say it's "required by your computer and cannot be uninstalled". I also disabled "Get the latest updates as soon as they're available" after the reboot.

The release notes list a new feature related to VHDs that I could imagine is related to the issue.

**Comment by ocdi** [comment]
I was able to uninstall the KB using this command, which fixed WSL for me

```
wusa /uninstall /kb:5044384
```

**Comment by PhiliaTheCat** [comment]
As everything mentioned above, there are ways to bypass the problem. But it doesn't make sense to rollback the system for this, since we have updates based on that KB5044384.

**Comment by paule96** [comment]
@PhiliaTheCat can you describe the bypasses? Would be nice to have workarounds, that doesn't require to leave REFS drivces and copy all to another drive

**Comment by ocdi** [comment]
Yeah I am keen for a permanent solution. I've had to Pause updates to prevent KB5044384 from coming back.

**Comment by yevon** [comment]
Exactly same issue here. I had to revert update KB5044384 as being unable to access files stored in a windows dev drive within WSL. After that I completely lost internet connectivity under latest version of WSL ([2.3.24](https://github.com/microsoft/WSL/releases/tag/2.3.24)) And I had to downgrade to [2.2.4](https://github.com/microsoft/WSL/releases/tag/2.2.4) and restart the computer. Now everything works. I was going crazy with this, as I thought it was permissions problem.

**Comment by alainosorio** [comment]
> I was able to uninstall the KB using this command, which fixed WSL for me
> 
> ```
> wusa /uninstall /kb:5044384
> ```

> Yeah I am keen for a permanent solution. I've had to Pause updates to prevent KB5044384 from coming back.

I can confirm this works

**Comment by matt-gribben** [comment]
I've just run into this error today, Windows 11 Pro 10.0.26.26100.2161, however I'm getting an Error 0x800f0825 when attempting to remove the offending kb:5044384

**Comment by vietbn82** [comment]
> I was able to uninstall the KB using this command, which fixed WSL for me
> 
> ```
> wusa /uninstall /kb:5044384
> ```

It works for me. You saved my day

**Comment by nicholashead** [comment]
The uninstall worked - however now there's a new update - [KB5046617](https://support.microsoft.com/en-us/topic/november-12-2024-kb5046617-os-build-26100-2314-1fa61a6d-a99a-47ca-a169-6974f08c3a0b) - that seems to fix dev drive issue - however since I did `wusa /uninstall /kb:5044384` it appears the new update is failing - Windows Update says error 0x800f0991 - any ideas on how to fix? :)

**Comment by HerrLiljegren** [comment]
> The uninstall worked - however now there's a new update - [KB5046617](https://support.microsoft.com/en-us/topic/november-12-2024-kb5046617-os-build-26100-2314-1fa61a6d-a99a-47ca-a169-6974f08c3a0b) - that seems to fix dev drive issue - however since I did `wusa /uninstall /kb:5044384` it appears the new update is failing - Windows Update says error 0x800f0991 - any ideas on how to fix? :)

just a random thought, does /install work instead of uninstall?

`wusa /install /kb:5044384`

**Comment by nicholashead** [comment]
> > The uninstall worked - however now there's a new update - [KB5046617](https://support.microsoft.com/en-us/topic/november-12-2024-kb5046617-os-build-26100-2314-1fa61a6d-a99a-47ca-a169-6974f08c3a0b) - that seems to fix dev drive issue - however since I did `wusa /uninstall /kb:5044384` it appears the new update is failing - Windows Update says error 0x800f0991 - any ideas on how to fix? :)
> 
> just a random thought, does /install work instead of uninstall?
> 
> `wusa /install /kb:5044384`

Unfortunately no it doesn't work that way. I also tried downloading the KB5044384 files from Windows catalog and installing them (and then hoping to install latest) - but it fails with same error on trying to install KB5044384. 

Has anyone else been able to update with today's update that had uninstalled KB5044384?

**Comment by PhiliaTheCat** [comment]
> > > The uninstall worked - however now there's a new update - [KB5046617](https://support.microsoft.com/en-us/topic/november-12-2024-kb5046617-os-build-26100-2314-1fa61a6d-a99a-47ca-a169-6974f08c3a0b) - that seems to fix dev drive issue - however since I did `wusa /uninstall /kb:5044384` it appears the new update is failing - Windows Update says error 0x800f0991 - any ideas on how to fix? :)
> > 
> > 
> > just a random thought, does /install work instead of uninstall?
> > `wusa /install /kb:5044384`
> 
> Unfortunately no it doesn't work that way. I also tried downloading the KB5044384 files from Windows catalog and installing them (and then hoping to install latest) - but it fails with same error on trying to install KB5044384.
> 
> Has anyone else been able to update with today's update that had uninstalled KB5044384?

Just a guess, if Windows Update works in a way like git, where deltas between different versions are logged, then perhaps a full rollback will solve the problem.

**Comment by yevon** [comment]
I'm unable to install the new update or reinstall the prior one... God... Error - instalación 0x800f081f

**Comment by alirezanet** [comment]
I can confirm after installing the new update it has been fixed 💐 (KB5046617 )

**Comment by yevon** [comment]
Just using restore pc right now -> Correct problems with windows update, reinstall windows. Nothing works, I'm unable to install the update. I guess this will work: 
 ![Image](https://github.com/user-attachments/assets/4adf8f60-230e-4e11-8f13-b60c697562ed)

**Comment by yevon** [comment]
Not even that works, it is unable to reinstall windows. Windows 11 is a disaster of quality, years suffering issues without solutions. Even the new photos gallery in windows explorer full of memory leaks that makes explorer to explode when scrolling, the new task manager that is laggy and slower than before, the windows store... ![Image](https://github.com/user-attachments/assets/6d2c6867-524e-4651-b8de-5d0ca137d1dd)

**Comment by nicholashead** [comment]
What's funny is retrying the update again today - and now it worked/installed!
