### ISSUE TITLE
WSL Server execution failed Error code: Wsl/CallMsi/Install/0x80080005

### ISSUE THREAD

**Issue by DefinetlyNotAI** [microsoft/WSL#11941]
### Windows Version

Microsoft Windows [Version 10.0.22631.4037]

### WSL Version

FAILS: WITH SAME ERROR

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [ ] WSL 1

### Kernel Version

FAILS: WITH SAME ERROR

### Distro Version

CANT ENTER

### Other Software

The main WSL only

### Repro Steps

I have once deleted wsl - A power outage occured in the middle of it deleting, and now its fully corrupted, neither installed or removed, doesnt show up in program and features.

Not sure how to reproduce, its only a rare occuronce so not a bug, BUT nothing works to fix it

Attempted to use dism and sfc, both returned no errors,

### Expected Behavior

To at least operate or open, 

### Actual Behavior

Anything related to wsl just fails entirely and does not in the slightest work or operate, disabling and re-enabling the feature was tried, IT used to work but not anymore (so required window and bios settings are fine) All other applications are operational, only wsl fails, no matter how or where it keeps failing, Also when i view it through the file manager, it shows its a empty folder, when i right click it to select properties i get the error shown in the attached image.

![image](https://github.com/user-attachments/assets/4744bcf6-a734-4dfe-a721-d5a007fc97a8)

Here is the cmd prompt when running any command related to wsl:

```bash
PS C:\Users\Hp> wsl
Server execution failed
Error code: Wsl/CallMsi/Install/0x80080005
PS C:\Users\Hp> wsl.exe --version
Server execution failed
Error code: Wsl/CallMsi/Install/0x80080005
PS C:\Users\Hp> wsl -l -v
Server execution failed
Error code: Wsl/CallMsi/Install/0x80080005
PS C:\Users\Hp> wsl.exe --status
Server execution failed
Error code: Wsl/CallMsi/Install/0x80080005
```

### Diagnostic Logs
[WslLogs-2024-08-20_13-37-56.zip](https://github.com/user-attachments/files/16674428/WslLogs-2024-08-20_13-37-56.zip)

**Comment by DefinetlyNotAI** [comment]
[WslLogs-2024-08-20_13-37-56.zip](https://github.com/user-attachments/files/16674430/WslLogs-2024-08-20_13-37-56.zip)

**Comment by DefinetlyNotAI** [comment]
I have seen the similiar issues, they aren't helpful

**Comment by OneBlue** [comment]
Thank you @DefinetlyNotAI. Looking at logs, it looks like your installation is corrupted. Can you try to download and install the [latest MSI](https://github.com/microsoft/WSL/releases/download/2.3.17/wsl.2.3.17.0.x64.msi) and see if that solves the issue ?

**Comment by DefinetlyNotAI** [comment]
i knew it was corrupted, ill try the msi

**Comment by DefinetlyNotAI** [comment]
I installed the MSI
Now doing wsl or wsl --install takes forever and doesnt actually do anything, just hangs until ctrl-c is used

**Comment by OneBlue** [comment]
Interesting. Can you collect a dump when that happens ? 

/dumps

**Comment by DefinetlyNotAI** [comment]
Ok, Here are the attached logs, BUT just putting it out there, the windows explorer still shows an error

![image](https://github.com/user-attachments/assets/3dc05e0f-f373-494c-90bf-0dbbc1dfabc0)

[WslLogs-2024-08-21_09-30-05.zip](https://github.com/user-attachments/files/16686906/WslLogs-2024-08-21_09-30-05.zip)

**Comment by OneBlue** [comment]
@DefinetlyNotAI: Looking at the logs it still looks like you're on `2.2.4`. Can you confirm that you installed the [2.3.17](https://github.com/microsoft/WSL/releases/download/2.3.17/wsl.2.3.17.0.x64.msi) MSI ?

**Comment by DefinetlyNotAI** [comment]
Yes i have, it said success, then autoclosed the msi installer

**Comment by OneBlue** [comment]
Can you capture logs of installing that MSI ? Something is definitely not right there. 

```
msiexec /i /path/to/msi /L*V C:\wsllogs.txt 
```

**Comment by DefinetlyNotAI** [comment]
```bash
Windows ® Installer. V 5.0.22621.3880 

msiexec /Option <Required Parameter> [Optional Parameter]

Install Options
 </package | /i> <Product.msi>
 Installs or configures a product
 /a <Product.msi>
 Administrative install - Installs a product on the network
 /j<u|m> <Product.msi> [/t <Transform List>] [/g <Language ID>]
 Advertises a product - m to all users, u to current user
 </uninstall | /x> <Product.msi | ProductCode>
 Uninstalls the product
Display Options
 /quiet
 Quiet mode, no user interaction
 /passive
 Unattended mode - progress bar only
 /q[n|b|r|f]
 Sets user interface level
 n - No UI
 b - Basic UI
 r - Reduced UI
 f - Full UI (default)
 /help
 Help information
Restart Options
 /norestart
 Do not restart after the installation is complete
 /promptrestart
 Prompts the user for restart if necessary
 /forcerestart
 Always restart the computer after installation
Logging Options
 /l[i|w|e|a|r|u|c|m|o|p|v|x|+|!|*] <LogFile>
 i - Status messages
 w - Nonfatal warnings
 e - All error messages
 a - Start-up of actions
 r - Action-specific records
 u - User requests
 c - Initial UI parameters
 m - Out-of-memory or fatal exit information
 o - Out-of-disk-space messages
 p - Terminal properties
 v - Verbose output
 x - Extra debugging information
 + - Append to existing log file
 ! - Flush each line to the log
 * - Log all information, except for v and x options
 /log <LogFile>
 Equivalent of /l* <LogFile>
Update Options
 /update <Update1.msp>[;Update2.msp]
 Applies update(s)
 /uninstall <PatchCodeGuid>[;Update2.msp] /package <Product.msi | ProductCode>
 Remove update(s) for a product
Repair Options
 /f[p|e|c|m|s|o|d|a|u|v] <Product.msi | ProductCode>
 Repairs a product
 p - only if file is missing
 o - if file is missing or an older version is installed (default)
 e - if file is missing or an equal or older version is installed
 d - if file is missing or a different version is installed
 c - if file is missing or checksum does not match the calculated value
 a - forces all files to be reinstalled
 u - all required user-specific registry entries (default)
 m - all required computer-specific registry entries (default)
 s - all existing shortcuts (default)
 v - runs from source and recaches local package
Setting Public Properties
 [PROPERTY=PropertyValue]

Consult the Windows ® Installer SDK for additional documentation on the
command line syntax.

Copyright © Microsoft Corporation. All rights reserved.
Portions of this software are based in part on the work of the Independent JPEG Group.
```

**Comment by DefinetlyNotAI** [comment]
Sorry, rate response, i have deleted the msi, im reinstalling it

**Comment by DefinetlyNotAI** [comment]
Now the msi just crashes,

https://github.com/user-attachments/assets/dcfc62ff-0952-4ce0-b7be-0241bdd0d983

**Comment by OneBlue** [comment]
@DefinetlyNotAI: Hmm, msiexec is weird sometimes. What if copy the .msi in C:\ and try to call it with msiexec from there ?

**Comment by OneBlue** [comment]
If it fails again, please share the log, this should contain more information at least

**Comment by DefinetlyNotAI** [comment]
no log is found...
it is in the video

**Comment by DefinetlyNotAI** [comment]
Wait.. now it opened UAC, then crashed

**Comment by OneBlue** [comment]
Ah, I think I know what's missing: Can you try the msiexec command line in an elevated command prompt ?

**Comment by DefinetlyNotAI** [comment]
Im doing this again:
Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
Set-ExecutionPolicy Bypass -Scope Process -Force
.\collect-wsl-logs.ps1

**Comment by DefinetlyNotAI** [comment]
Wait, i do it again?

**Comment by DefinetlyNotAI** [comment]
ok

**Comment by OneBlue** [comment]
Yeah what we need is the installation log, since that's where the issue is coming from

**Comment by DefinetlyNotAI** [comment]
https://github.com/user-attachments/assets/19ad4188-ff48-421c-b254-ebea9fb7c0db

Sadly it still does nothing
and just crashes
no logs are also generated

**Comment by OneBlue** [comment]
This actually looks like the expected behavior. Can you do that and add the logs command line ? Also is the explorer still failing to open \\wsl.localhost now ?

**Comment by DefinetlyNotAI** [comment]
[WslLogs-2024-08-21_23-45-49.zip](https://github.com/user-attachments/files/16698588/WslLogs-2024-08-21_23-45-49.zip)
Is me doing logs again,

And yes explorer fails to open the wsl folder

No logs are generated from previous instructions

Thx for being patient with me

**Comment by DefinetlyNotAI** [comment]
And it shows that not `etl` file is found...?

**Comment by OneBlue** [comment]
Can you run: 

```
msiexec /i <msi> /L*V C:\wsllogs.txt  
``` 

In an administrator cmd.exe ? Now the installer is starting so this must generate a C:\wsllogs.txt

**Comment by DefinetlyNotAI** [comment]
ok

**Comment by DefinetlyNotAI** [comment]
fyi, the msi given to me is version 2.3 something (its name)

**Comment by DefinetlyNotAI** [comment]
https://github.com/user-attachments/assets/ddb3af21-3a28-4fe7-bc31-3a3e29a1d728

**Comment by OneBlue** [comment]
This looks non a non-elevated powershell. Can you run this in an **elevated** cmd.exe ?

**Comment by DefinetlyNotAI** [comment]
ok

**Comment by DefinetlyNotAI** [comment]
![image](https://github.com/user-attachments/assets/e88f5e14-6862-4daa-b21f-b42cc23bf7f9)


BUT the log was generated

[wsllogs.txt](https://github.com/user-attachments/files/16698684/wsllogs.txt)

**Comment by OneBlue** [comment]
Is this the correct path to the MSI ? Can you try to pass "C:\wsl.msi" instead, since this is where you copied it earlier ?

**Comment by DefinetlyNotAI** [comment]
I attached the logs
In the txt file

( In my country its pretty late, so im might go offline for a while to sleep )

**Comment by OneBlue** [comment]
The installation didn't start because the path to the msi file was wrong. can you try to run this again with the right path ? (C:\wsl.msi according to the previous video)

**Comment by DefinetlyNotAI** [comment]
for some reason it didnt open the log, but i attached it

**Comment by DefinetlyNotAI** [comment]
> The installation didn't start because the path to the msi file was wrong. can you try to run this again with the right path ? (C:\wsl.msi according to the previous video)

ok. ill try

**Comment by DefinetlyNotAI** [comment]
ur right:
[wsllogs.txt](https://github.com/user-attachments/files/16698741/wsllogs.txt)

**Comment by OneBlue** [comment]
Thank you @DefinetlyNotAI. Looking at the logs, it looks something is failing while uninstall the previous version, which breaks the installation. 

If you go to installed programs, you should see multiple entries for WSL. Can you try to remove them all ?

**Comment by DefinetlyNotAI** [comment]
Hmm... From my programs this is a peculiar one: 
![image](https://github.com/user-attachments/assets/9d61d827-3b69-494c-b9dd-6c1391329985)

Here is wsl in settings
![image](https://github.com/user-attachments/assets/0fd838fa-d6e6-4d61-bfd2-ff0236a057f4)

Here is wsl in programs and files
![image](https://github.com/user-attachments/assets/8ae5f8b5-8efb-4504-9425-ebe58c8d34c8)

Here is in Programs dir
![image](https://github.com/user-attachments/assets/df76a165-d1e8-425e-b122-4b20b2f2d3f6)

Here is in x86 Programs dir
![image](https://github.com/user-attachments/assets/d59164d0-e61e-43eb-af1c-2e73604d407b)

Root dir
![image](https://github.com/user-attachments/assets/3f74a0ad-097a-4bc4-9c5a-2757aca46bb6)


Search in root dir
![image](https://github.com/user-attachments/assets/d312a6f8-5054-4917-b30a-fe46f757ccda)
(And many more their)

**Comment by DefinetlyNotAI** [comment]
@OneBlue Here

**Comment by DefinetlyNotAI** [comment]
??

**Comment by DefinetlyNotAI** [comment]
Um, please i need a fix... OH, holidays - sorry i forgot different holiday schedules exist - SO SORRY

**Comment by DefinetlyNotAI** [comment]
Umm?

**Comment by DefinetlyNotAI** [comment]
???
Should i open a new issue, getting ridiculous now

**Comment by chris-piekarski** [comment]
I struggled with this for weeks myself. It ended up being a bad intel I9 13th gen CPU chip. I swapped it out with a new 14th gen and all the WSL instability and never ending errors went away. I am currently sending the bad CPU back to intel as part of the over voltage oxidation issue.

**Comment by DefinetlyNotAI** [comment]
Daym, thats really surprising
But not a option for me sadly...

Im on a laptop

**Comment by OneBlue** [comment]
@DefinetlyNotAI: What's the output of `wsl --uninstall` ?

**Comment by DefinetlyNotAI** [comment]
Finally lol,

Still gets stuck, outputs nothing

**Comment by OneBlue** [comment]
Interesting. Can you capture /logs of wsl --uninstall ?

**Comment by DefinetlyNotAI** [comment]
[WslLogs-2024-09-24_09-50-37.zip](https://github.com/user-attachments/files/17108774/WslLogs-2024-09-24_09-50-37.zip)

The cmd is just stuck, shows nothing, no errors at all

**Comment by OneBlue** [comment]
Ok this is most likely caused by a corrupted MSI installation. 

In this case, your best bet would be to try to clean up the previous installation. [This post](https://stackoverflow.com/questions/66877499/is-there-a-best-way-to-forcibly-uninstall-a-product-when-the-msi-fails-durin#comment118247490_66877499) has a couple paths on how to do that.

**Comment by DefinetlyNotAI** [comment]
![image](https://github.com/user-attachments/assets/33752fb3-7891-4f77-9c13-ba49a54dd4df)
AMAZING - What was the problem tho?

(I used the troubleshooter (In uninstall mode), found wsl (As windows subsystem for linux) (DONT choose the other option that has the word `UPDATER`), asked it to uninstall, 2 min, and the image above happened

**Comment by DefinetlyNotAI** [comment]
> ![image](https://private-user-images.githubusercontent.com/150605201/370739429-33752fb3-7891-4f77-9c13-ba49a54dd4df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNzIyNTQsIm5iZiI6MTcyNzI3MTk1NCwicGF0aCI6Ii8xNTA2MDUyMDEvMzcwNzM5NDI5LTMzNzUyZmIzLTc4OTEtNGY3Ny05YzEzLWJhNDlhNTRkZDRkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxMzQ1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTk1ZWQwYWFiYTI0ODc0ZGRhYTg0ZGM4ZjVmNTg4NTQzMmFlZmIxMTU2MzJiNDNkYjE0N2QzODNjNDg3ZGQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xfj2_jO2v3x26al5OmgIvO6T8etNAxZKM0L81W7Kx1E) AMAZING - What was the problem tho?
> 
> (I used the troubleshooter (In uninstall mode), found wsl (As windows subsystem for linux) (DONT choose the other option that has the word `UPDATER`), asked it to uninstall, 2 min, and the image above happened

I used this troubleshooter 
[MicrosoftProgram_Install_and_Uninstall.meta.zip](https://github.com/user-attachments/files/17131879/MicrosoftProgram_Install_and_Uninstall.meta.zip)

**Comment by DefinetlyNotAI** [comment]
( Maybe fix the bot? Not every zip file is for the logs lol )

**Comment by DefinetlyNotAI** [comment]
Oop: It works, but installing distro's now fail


WSL Fails to show distro?
```
C:\Users\Hp>wsl
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore

C:\Users\Hp>wsl --install -d kali-linux
Kali Linux Rolling is already installed.
Launching Kali Linux Rolling...
```

WSL Opening Kali Linux (ERROR):
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80004005
Error: 0x80004005 Unspecified error
```

WSL Working now
```
C:\Users\Hp>wsl --version
Invalid command line option: --version
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]

Arguments for running Linux binaries:

    If no command line is provided, wsl.exe launches the default shell.

    --exec, -e <CommandLine>
        Execute the specified command without using the default Linux shell.

    --
        Pass the remaining command line as is.

Options:
    --cd <Directory>
        Sets the specified directory as the current working directory.
        If ~ is used the Linux user's home path will be used. If the path begins
        with a / character, it will be interpreted as an absolute Linux path.
        Otherwise, the value must be an absolute Windows path.

    --distribution, -d <Distro>
        Run the specified distribution.

    --user, -u <UserName>
        Run as the specified user.

    --system
        Launches a shell for the system distribution.

Arguments for managing Windows Subsystem for Linux:

    --help
        Display usage information.

    --install [Options]
        Install additional Windows Subsystem for Linux distributions.
        For a list of valid distributions, use 'wsl --list --online'.

        Options:
            --distribution, -d [Argument]
                Downloads and installs a distribution by name.

                Arguments:
                    A valid distribution name (not case sensitive).

                Examples:
                    wsl --install -d Ubuntu
                    wsl --install --distribution Debian

            --no-launch, -n
                Do not launch the distribution after install.

    --mount <Disk>
        Attaches and mounts a physical disk in all WSL2 distributions.

        Options:
            --bare
                Attach the disk to WSL2, but don't mount it.

            --type <Type>
                Filesystem to use when mounting a disk, if not specified defaults to ext4.

            --options <Options>
                Additional mount options.

            --partition <Index>
                Index of the partition to mount, if not specified defaults to the whole disk.

    --set-default-version <Version>
        Changes the default install version for new distributions.

    --shutdown
        Immediately terminates all running distributions and the WSL 2
        lightweight utility virtual machine.

    --status
        Show the status of Windows Subsystem for Linux.

    --unmount [Disk]
        Unmounts and detaches a disk from all WSL2 distributions.
        Unmounts and detaches all disks if called without argument.

    --update [Options]
        If no options are specified, download and install WSL from the Microsoft Store.

        Options:
            --rollback
                Revert to the previous version of the WSL 2 kernel.

            --inbox
                Only update the inbox WSL 2 kernel. Do not install WSL from the Microsoft Store.

            --web-download
                Download the most recent version of WSL from the internet instead of the Microsoft Store.
Arguments for managing distributions in Windows Subsystem for Linux:

    --export <Distro> <FileName>
        Exports the distribution to a tar file.
        The filename can be - for standard output.

    --import <Distro> <InstallLocation> <FileName> [Options]
        Imports the specified tar file as a new distribution.
        The filename can be - for standard input.

        Options:
            --version <Version>
                Specifies the version to use for the new distribution.

    --list, -l [Options]
        Lists distributions.

        Options:
            --all
                List all distributions, including distributions that are
                currently being installed or uninstalled.

            --running
                List only distributions that are currently running.

            --quiet, -q
                Only show distribution names.

            --verbose, -v
                Show detailed information about all distributions.

            --online, -o
                Displays a list of available distributions for install with 'wsl --install'.

    --set-default, -s <Distro>
        Sets the distribution as the default.

    --set-version <Distro> <Version>
        Changes the version of the specified distribution.

    --terminate, -t <Distro>
        Terminates the specified distribution.

    --unregister <Distro>
        Unregisters the distribution and deletes the root filesystem.
```

**Comment by OneBlue** [comment]
Thank you @DefinetlyNotAI, this is progress ! Can you collect /logs of the new error ?

**Comment by DefinetlyNotAI** [comment]
Done:
[WslLogs-2024-09-26_09-01-48.zip](https://github.com/user-attachments/files/17142957/WslLogs-2024-09-26_09-01-48.zip)

**Comment by OneBlue** [comment]
@DefinetlyNotAI: It looks like WSL got removed. `wsl --update` should fix that.

**Comment by DefinetlyNotAI** [comment]
Back to square one :(

```
C:\Users\Hp>wsl --update
Installing: Windows Subsystem for Linux
Windows Subsystem for Linux has been installed.

C:\Users\Hp>wsl --install -d kali-linux
Server execution failed
Error code: Wsl/CallMsi/Install/0x80080005

C:\Users\Hp>wsl
Server execution failed
Error code: Wsl/CallMsi/Install/0x80080005
```

**Comment by DefinetlyNotAI** [comment]
...

**Comment by DefinetlyNotAI** [comment]
Hello??

**Comment by DefinetlyNotAI** [comment]
It seems no one can help, so I will end the issue as not fixed, thanks..

I will later reset my computer.
