### ISSUE TITLE
Network device not showed up on WSL

### ISSUE THREAD

**Issue by AchIrsHam** [microsoft/WSL#12221]
I was installing ubuntu on my WSL, and it cant connect to internet then it doesn't showed up the network interface

disclaimer: i never used WSL before

does this problem ever occured before?

```
~$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet 10.255.255.254/32 brd 10.255.255.254 scope global lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever

**Comment by AchIrsHam** [comment]
[WslLogs-2024-10-31_04-52-26.zip](https://github.com/user-attachments/files/17579472/WslLogs-2024-10-31_04-52-26.zip)

it may helps the problem because i dont understand how to get started

**Comment by tim661811** [comment]
I seem to be having the same issue with an existing WSL instance after updating to Windows 11 version 24H2 (OS Build 26100.2033) 🤔

**Comment by AchIrsHam** [comment]
> I seem to be having the same issue with an existing WSL instance after updating to Windows 11 version 24H2 (OS Build 26100.2033) 🤔

do you know where is the issue that has been solved related to this?

**Comment by tim661811** [comment]
Strangely enough, connecting to our office VPN and killing WSL and re-opening it brought back the eth0 interface.

I tried killing WSL (`wsl --shutdown`) and re-opening it before, but this didn't seem to resolve the issue, also rebooting my PC didn't help.

**Comment by AchIrsHam** [comment]
oh yea, i have installed WARP cloudflare VPN on my desktop, does it affect the problem?

**Comment by OneBlue** [comment]
@AchIrsHam: I wonder if WSL is just falling back to no networking because something failed during startup. Could you collect logs of running `wsl --shutdown && wsl echo ok` ? 

/logs

**Comment by AchIrsHam** [comment]
[WslLogs-2024-11-06_10-43-02.zip](https://github.com/user-attachments/files/17641359/WslLogs-2024-11-06_10-43-02.zip)

**Comment by OneBlue** [comment]
Thank you @AchIrsHam. This is unfortunately a known Windows issue. The fix is on the way, but in the meantime WSL might boot without networking as a fallback. One thing you can try is to update to the latest pre-release, which will at least try to give virtio networking. You can do that via:

```wsl --update --pre-release`

**Comment by AchIrsHam** [comment]
> Thank you [@AchIrsHam](https://github.com/AchIrsHam). This is unfortunately a known Windows issue. The fix is on the way, but in the meantime WSL might boot without networking as a fallback. One thing you can try is to update to the latest pre-release, which will at least try to give virtio networking. You can do that via:
> 
> ```wsl --update --pre-release`

it worked and it does give me a bonus of network interface, thanks ```
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet 10.255.255.254/32 brd 10.255.255.254 scope global lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1280 qdisc mq state UP group default qlen 1000
    link/ether 00:15:5d:47:d0:6c brd ff:ff:ff:ff:ff:ff
    inet 172.30.153.246/20 brd 172.30.159.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::215:5dff:fe47:d06c/64 scope link
       valid_lft forever preferred_lft forever
3: lxcbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 00:16:3e:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 10.0.3.1/24 brd 10.0.3.255 scope global lxcbr0
       valid_lft forever preferred_lft forever```

**Comment by AchIrsHam** [comment]
> Thank you [@AchIrsHam](https://github.com/AchIrsHam). This is unfortunately a known Windows issue. The fix is on the way, but in the meantime WSL might boot without networking as a fallback. One thing you can try is to update to the latest pre-release, which will at least try to give virtio networking. You can do that via:
> 
> ```wsl --update --pre-release`

thanks for the solution, now WSL gave me 3 different network interface instead of 2, and all of them works `$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet 10.255.255.254/32 brd 10.255.255.254 scope global lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1280 qdisc mq state UP group default qlen 1000
    link/ether 00:15:5d:47:d0:6c brd ff:ff:ff:ff:ff:ff
    inet 172.30.153.246/20 brd 172.30.159.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::215:5dff:fe47:d06c/64 scope link
       valid_lft forever preferred_lft forever
3: lxcbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 00:16:3e:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 10.0.3.1/24 brd 10.0.3.255 scope global lxcbr0
       valid_lft forever preferred_lft forever`

**Comment by AchIrsHam** [comment]
> Thank you [@AchIrsHam](https://github.com/AchIrsHam). This is unfortunately a known Windows issue. The fix is on the way, but in the meantime WSL might boot without networking as a fallback. One thing you can try is to update to the latest pre-release, which will at least try to give virtio networking. You can do that via:
> 
> ```wsl --update --pre-release`

thanks for the solution, now i have 3 different network interface and all of them works
```$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet 10.255.255.254/32 brd 10.255.255.254 scope global lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1280 qdisc mq state UP group default qlen 1000
    link/ether 00:15:5d:47:d0:6c brd ff:ff:ff:ff:ff:ff
    inet 172.30.153.246/20 brd 172.30.159.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::215:5dff:fe47:d06c/64 scope link
       valid_lft forever preferred_lft forever
3: lxcbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 00:16:3e:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 10.0.3.1/24 brd 10.0.3.255 scope global lxcbr0
       valid_lft forever preferred_lft forever```

**Comment by AchIrsHam** [comment]
> Thank you [@AchIrsHam](https://github.com/AchIrsHam). This is unfortunately a known Windows issue. The fix is on the way, but in the meantime WSL might boot without networking as a fallback. One thing you can try is to update to the latest pre-release, which will at least try to give virtio networking. You can do that via:
> 
> ```wsl --update --pre-release`

thanks for the solution, now i have 3 network interface instead of 2
```
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet 10.255.255.254/32 brd 10.255.255.254 scope global lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1280 qdisc mq state UP group default qlen 1000
    link/ether 00:15:5d:47:d0:6c brd ff:ff:ff:ff:ff:ff
    inet _truncated_/20 brd _truncated_ scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::215:5dff:fe47:d06c/64 scope link
       valid_lft forever preferred_lft forever
3: lxcbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 00:16:3e:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 10.0.3.1/24 brd 10.0.3.255 scope global lxcbr0
       valid_lft forever preferred_lft forever
