### ISSUE TITLE
WSL2 loses networking after resume from hibernate

### ISSUE THREAD

**Issue by jamcpherson-clgx** [microsoft/WSL#12747]
### Windows Version

Microsoft Windows [Version 10.0.26100.3194]

### WSL Version

2.3.26.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.167.4-microsoft-standard-WSL2

### Distro Version

Ubuntu 24.04

### Other Software

Appgate SDP 6.4.1-39256-release
Zscaler 4.3.0.188

### Repro Steps

I have a Dell Latitude 7450 with an "Intel Core Ultra 7" cpu, 32Gb ram.
Due to concerns about mis-interactions on resume with USB3 docking stations, $work has disabled _sleep_ in the bios, leaving only hibernate.

I have noticed that after resume from hibernate my WSL2 vm is unable to make use of any network-related functionality - routing and DNS at a minimum.

The consistent misbehaviour is that I lose the ability to resolve DNS - and I cannot get any ICMP Reply packets when I `ping lo` or `ping loopback0`.

Sometimes after resume I can see traffic on the `eth?` interfaces - including both ICMP Request and Reply - but something is blocking the return path inside the VM for every packet. Other times I cannot see any traffic on the interfaces. I can also see that routes are getting updated but no traffic passes.

I've tried restarting `systemd-networkd` and `systemd-resolved`, setting the links down and then up, and even tried manually adding routes. Nothing works to get networking back.

I noticed this morning that running `reboot` in the VM does not bring the stack back up, I have to use `shutdown -h`.

### Expected Behavior

I expect networking to "just work" after resuming from hibernation

### Actual Behavior

[pcaps.zip](https://github.com/user-attachments/files/19478814/pcaps.zip)

### Diagnostic Logs

[WslLogs-2025-03-27_10-05-36.zip](https://github.com/user-attachments/files/19478815/WslLogs-2025-03-27_10-05-36.zip)

**Comment by jamcpherson-clgx** [comment]
@github-actions bot - please re-scan the description

[WslLogs-2025-03-27_10-05-36.zip](https://github.com/user-attachments/files/19500162/WslLogs-2025-03-27_10-05-36.zip)

**Comment by alexandroid** [comment]
I am not sure if this is related or a different issue, but I have a somewhat similar issue which I think has started after installing Ubuntu system updates. After resuming my PC from sleep, my WSL2 terminal session works just fine and WSL shell can access internet, but the host Windows shell can no longer invoke wsl.exe:
```
]  wsl
Catastrophic failure
Error code: Wsl/Service/E_UNEXPECTED
```
This also breaks VSCode connectivity and requires complete wsl shutdown (`wsl --shutdown`) and then WSL restart. Attaching the minimal log (collected using the [preferred method](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs-recommended-method)) of invoking `wsl.exe` and getting an error.

[WslLogs-2025-03-31_23-13-32.zip](https://github.com/user-attachments/files/19545401/WslLogs-2025-03-31_23-13-32.zip)

**Comment by LiPtP0000** [comment]
@alexandroid I experienced this when I was running [MinerU](https://github.com/opendatalab/MinerU) in WSL distro with CUDA. vscode suddenly losed connection with WSL when processing a specific file and I tried to restart the connection (but not the restart of WSL) . After that the windows terminal shows exactly the same log as you. Maybe I could reproduce this problem later, and I would attach a log file at this issue then.

**Comment by tcostermans** [comment]
I experience the same issue after my system resumes from hibernate and WSL was still running:

![Image](https://github.com/user-attachments/assets/99e8bc1d-bcf6-4a10-ad13-95a9c110f7f0)

I need to run wsl --shutdown and then start a terminal again.

**Comment by bestis** [comment]
One me too, to this that WSL2 is totally broken after hibernate. Running `wsl --shutdown` doesn't seem to fix all things related to WSL. Docker desktop seems to keep in borked state, trying to restart/quit it doesn't do anything so to fix the state is just easiest to reboot. Neither the VSCode seems to be able to reconnect or reload. So easiest seems to be just rebooting the whole system :( 

@alexandroid What is this WSL restart you talk about after shutdown? At least for me, running shutdown and then having wsl running does not fix things.

**Comment by auroradanier** [comment]
I have the same issue too. I just got a new laptop. Now everytime wake up, I have to wsl --shutdown and reopen wsl inorder to connect to wsl from vscode or cursor. How to print the wsl logs?

Thanks

**Comment by lukebehling** [comment]
+ 1 as this is impacting our developers as well.

**Comment by Einhorntom** [comment]
Same here. 

Closing **all** the WSL windows/tabs and restarting it temporarily fixes the issue

**Comment by sirianni** [comment]
+1 this seems to be a regression as I've been running WSL with VScode for months without this issue.  Now it seems to happen every time my PC wakes from sleep.

Related issues:
* https://github.com/microsoft/WSL/issues/9490
* https://github.com/microsoft/WSL/issues/12810

**Comment by usernamenumber** [comment]
I've been having this problem frequently for months now, and it is a serious impediment. Since the only fix I've found is to restart both WSL and vscode, and vscode not only can't save any unsaved work but won't even let me use the UI to copy/paste, unsaved work is just lost as far as I can tell. 

This is seriously affecting the viability of windows + wsl for me as a developer, so I really hope it is fixed soon

**Comment by auroradanier** [comment]
I just found out that when the wsl shows Catastrophic failure, then if I type wsl again, it still shows error. 
But when I open wsl using admin user and type wsl, then it boot up fine. 
And if I go back to previous user window and type wsl, it works fine too.

Seems there are some user right issues?

**Comment by jose-cabral** [comment]
This is also happening to me when I try to open a new terminal ATM (both with admin an non admin user - thanks @auroradanier for the tip).

But I have an active shell session that is working perfectly and the IDE is also partially working. 
The IDE is able to read/update files but not able to use i.e. `git` (it shows the same error on the IDE's git sidebar)

**Comment by lukolszewski** [comment]
+1 it has been making developing on windows a huge pain when every time you sleep the machine WSL needs to be restarted loosing all the sessions.

**Comment by MarcosNeco** [comment]
The same is happening to me suddenly. The workaround it was create a new task in the task scheduler to execute the command to kill the wsl service: `taskkill /f /im wslservice.exe`  every time the computer wakes up.

**Comment by solmon** [comment]
@MarcosNeco  - thanks for the work around

**Comment by marrobi** [comment]
Same issue here, no Docker Desktop installed.

**Comment by djradon** [comment]
Same issue, on wake from sleep, but I don't think it's every time. I can avoid reboot by `rm -rf ~/.vscode-server` but then I have to re-install extensions. Restarting docker doesn't help. `wsl --shutdown` doesn't help either.

**Comment by cpastordev** [comment]
Same issue described above. Sometimes wsl --shutdown (and restarting vscode) resolves the issue, sometimes it also hangs and I have to reboot.

**Comment by lhint** [comment]
Had this issue for over a month, then realised that I had purchased a new dell dock. I updated the firmware for the dock and this issue has resolved.

**Comment by BlackS52** [comment]
> The same is happening to me suddenly. The workaround it was create a new task in the task scheduler to execute the command to kill the wsl service: `taskkill /f /im wslservice.exe` every time the computer wakes up.

Yeah it works but the problem that you are killing all you opened windows and clearing all your context. 
So, I would say that it the reason why this problem is annoyed. 
I've tried to update my laptop firmware too but it couldn't resolve the problem. 
I feel pain of everyday reopening all my context. Maybe anybody know how to resolve this regular and annoying problem ?

**Comment by tjhowse** [comment]
Today, for the first time in several months, I was able to reconnect vscode to WSL2 (Debian) after sleep/hibernation. I was also able to start a new instance of windows terminal and connect to WSL2. Previously both of those failed with the above "Catastrophic failure
Error code: Wsl/Service/E_UNEXPECTED" error. I cannot definitively identify what changed, or if it's actually fixed, but a windows update might've played a role. I will report back if the issue re-occurs.

**Comment by ishevch** [comment]
Issue still present here, OS info

`Windows 11 Pro, Build 22631 (version 10.0.22631)`

I think its related to the network connection being lost when the device goes to sleep because the same issue happens when I switch wifi networks

**Comment by tjhowse** [comment]
Whoops, I spoke too soon. The issue re-occurred this morning.

Microsoft Windows [Version 10.0.19045.6456]

I'm clutching at straws, but a factor might be whether the docker daemon is running in WSL when the machine hibernates. I'll run some tests.

**Comment by sergeyblackwrk-max** [comment]
I've just disable hibernation, flight is normal.
Like a temporary measure

**Comment by caelon** [comment]
@MarcosNeco  - Thanks for the workaround. Still waiting on a solution.

**Comment by agroszer** [comment]
WSL version: 2.6.2.0
Kernel version: 6.6.87.2-1
WSLg version: 1.0.71
MSRDC version: 1.2.6353
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.22631.6199

seems to work better, no disconnects for weeks now

**Comment by tjhowse** [comment]
I updated to windows 11 and the issue persists. The first time I woke the computer from hibernate WSL2 was fine and I found some hope. The second time: The same old problem. This morning it was fine again. The only variable I can think of is whether or not I started the docker daemon inside WSL before hibernating.

If you encounter this issue please post whether you're running the docker daemon inside the WSL2 machine before hibernating. Run `service docker status` to find out, as it may start automatically.

**Comment by tjhowse** [comment]
I just had this issue re-occur without the docker daemon ever having run inside WSL2 since it "booted". Red herring.

**Comment by MaluNoPeleke** [comment]
Seems to be a much older issue: https://github.com/microsoft/WSL/issues/9301

**Comment by jasminemoeller** [comment]
I'm running into this as well, I have docker daemon (but not the desktop) running, but the problem occurred only recently (i.e. not directly related to setting up docker). 

Interestingly, I can reach one single IP - 192.168.0.1 works. All other IPs (whether in the 192.168.0.xxx subnet or elsewhere) don't - the host's IP is 192.168.0.175 BTW - coincidence?

**Comment by ZeroMax-dev** [comment]
I started having this issue just now, for some reason. In the months before it was alright.

**Comment by jasminemoeller** [comment]
> I'm running into this as well, I have docker daemon (but not the desktop) running, but the problem occurred only recently (i.e. not directly related to setting up docker).
> 
> Interestingly, I can reach one single IP - 192.168.0.1 works. All other IPs (whether in the 192.168.0.xxx subnet or elsewhere) don't - the host's IP is 192.168.0.175 BTW - coincidence?

Okay to answer myself, maybe someone has the same problem - I had too many containers and the docker daemon ended up handing out subnets to the containers/stacks that interfered with the local network configuration. You may want to limit the networks the daemon can actually use in daemon.json.

**Comment by rowleya** [comment]
I have also started having this issue recently, though for me it is only a problem when I have a VPN client running on the Windows side.  When I disconnect the VPN, connectivity return, and then it goes away again if I reconnect the VPN.  I do have docker inside WSL but I don't always use it between having issues.  

Doing a ```wsl --shutdown``` always appears to fix it.  This makes me wonder if there is a routing issue going on somewhere...

**Comment by ZeroMax-dev** [comment]
By advice of another comment here somewhere I have updated WSL to v2.6.3 by running `wsl --update` in the cmd. I haven't had this issue since. I have also disabled fast boot on Windows (not hibernation), not sure if this might also be related.

**Comment by rowleya** [comment]
I am on the latest (2.7.0.0) pre-release of WSL, though of course that could cause problems verses the latest release I guess (2.6.3).  I do have fast start-up on as well.

**Comment by randybb** [comment]
I have basically two problems:
- VS Code is not able reconnect to WSL
- network changes (routing for VPN) in OS are not reflected in WSL, thus `wsl --shutdown` is needed to restart networking and gain access to VPN from WSL

**Comment by rowleya** [comment]
I have now tried rolling back to the latest release (2.6.3) and this still seems to happen to me also.  I think this is caused by something in the OS having changed recently rather than WSL, but it would still be useful to have it fixed!  Noting also that I have Fast start-up turned off now also and this hasn't helped.

**Comment by tjhowse** [comment]
Is everyone experiencing this issue using some kind of VPN? My work VPN broke a month ago and I haven't been experiencing this WSL issue.

Yesterday I migrated to Linux Mint on my work development machine, so I am no longer affected by this issue.

**Comment by kenny-lu-hl** [comment]
> I have basically two problems:
> 
> * VS Code is not able reconnect to WSL
> * network changes (routing for VPN) in OS are not reflected in WSL, thus `wsl --shutdown` is needed to restart networking and gain access to VPN from WSL

Seeing the same issue. Very annoying

**Comment by rowleya** [comment]
Yes, for me it is related to VPN.  Turning off the VPN restores networking generally, so it seems like something is disconnected between WSL and the external network state.

**Comment by AnloWho** [comment]
I have also this issue with the more recent versions of WSL2. After resuming from Hibernate it's common that Network is unreachable within wsl. I'm on version 2.6.3.0. Networking mode is set to Mirrored.

**Comment by songdongsheng** [comment]
Same to me, I use `networkingMode=Mirrored`, after hibernate, I lost my WiFi IP address & addapter in the WSL.
Must do restart WSL via `wsl --shutdown`.

**Comment by rowleya** [comment]
I thought I would try some tests this morning when this happened.  I used Wireshark in Windows to see what happens.  Interestingly, I can ping, but I can't use https...

Below are snapshots of the captures.  These are all from the vEthernet adapter that my VPN uses.

This one is from just after resuming from hibernate.  This was first a ```ping google.com``` then a ```curl https://google.com```.
<img width="1398" height="251" alt="Image" src="https://github.com/user-attachments/assets/bfe7e7e0-2710-4915-bc8a-e801680b97ac" />

This one is just after ```wsl --restart``` without the ping, just the curl.
<img width="1424" height="161" alt="Image" src="https://github.com/user-attachments/assets/564e6620-1851-4b86-b8ca-79b500448aed" />

The above looked interesting because it seemed to immediately use TLSv1.2 rather than TLSv1.3.  To confirm that this wasn't the problem, I ran ```curl --tls-max 1.2 https://google.com``` to get the following.
<img width="1410" height="233" alt="Image" src="https://github.com/user-attachments/assets/d3492390-2bf2-47ba-9435-e1d176af97e4" />

**Comment by robotex82** [comment]
Same problem here on a Lenovo Yoga Slim 7 Ultra 14IPH11

Windows Version
10.0.26200.8655


WSL Version
WSL-Version: 2.7.3.0
Kernelversion: 6.6.114.1-1
WSLg-Version: 1.0.73
MSRDC-Version: 1.2.6676
Direct3D-Version: 1.611.1-81528511
DXCore-Version: 10.0.26100.1-240331-1435.ge-release


Are you using WSL 1 or WSL 2?
WSL 2

Distro Version
Ubuntu 24.04

**Comment by jpelton-stroud** [comment]
Started having this issue in the last two weeks with the Antigravity IDE. `wsl --version` confirmed I was on WSL v2.6.3; a quick `wsl --update` brought me up to v2.7.11.0 and immediately resolved the problem.

**Comment by InfantLab** [comment]
Also hitting this on Windows 11 Insider Dev — devcontainer/Docker Desktop (WSL2 backend) becomes unusable after the host hibernates: containers report "Up" but `docker exec` fails at the `nsexec`/`setns` layer (`failed to open /proc/<pid>/ns/ipc: No such file or directory`). Confirmed `wsl --shutdown`, restarting `vmcompute`/`LxssManager`, and removing/recreating the container do **not** fix it — only a full Windows restart recovers.

Worth flagging for anyone seeing a sudden uptick: Windows is rolling out a new adaptive hibernate policy (Insider Preview Build 28120.2630, July 2026) that hibernates more readily at lower battery to reduce Modern Standby drain. That means machines that previously stayed in Modern Standby (and survived fine) are now escalating to full Hibernate far more often — so this long-open bug is getting tripped more frequently, not because anything about our setup changed. For anyone doing dev container work on a laptop, this is a genuine showstopper: the workflow depends on WSL2 state surviving sleep, and right now it doesn't.
