### ISSUE TITLE
On WSL distro with systemd enabled, directory `$XDG_RUNTIME_DIR` is removed minutes after start and breaks apps

### ISSUE THREAD

**Issue by carlosedp** [microsoft/WSL#13562]
### Windows Version

Microsoft Windows [Version 10.0.26100.6725]

### WSL Version

2.6.1.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

6.6.87.2-microsoft-standard-WSL2

### Distro Version

Ubuntu 25.04

### Other Software

Podman desktop on Windows natively and podman installed on WSL distro

### Repro Steps

This is a followup to #10498 which still presents the same problems.

In a WSL distro like Ubuntu with Systemd enabled, the `$XDG_RUNTIME_DIR` directory gets deleted exactly 3 minutes after boot.

This presents a problem to applications which uses $XDG_RUNTIME_DIR like Podman:

```sh
❯ podman ps
Failed to obtain podman configuration: lstat /run/user/1000: no such file or directory
```

If no systemd is used, $XDG_RUNTIME_DIR is mounted to a directory in user's home and the problem with apps like Podman doesn't happen.

It works fine in these 3 minutes after startup where the `/run/user/1000` directory exists (my user id is 1000).

Below is a capture that monitored the directory:

```sh
❯ echo $XDG_RUNTIME_DIR
/run/user/1000/
❯ ll $XDG_RUNTIME_DIR
Permissions Size User      Date Modified Name
drwx------     - carlosedp  3 Oct 18:21    containers/
drwx-----T     - carlosedp  3 Oct 18:21    libpod/
❯ sudo inotifywait -m /run/user/1000
Setting up watches.
Watches established.
/run/user/1000/ ATTRIB,ISDIR libpod
/run/user/1000/ ATTRIB,ISDIR libpod
/run/user/1000/ CREATE,ISDIR systemd
/run/user/1000/ CREATE bus
/run/user/1000/ ATTRIB bus
/run/user/1000/ CREATE,ISDIR gnupg
/run/user/1000/ CREATE pk-debconf-socket
/run/user/1000/ ATTRIB pk-debconf-socket
/run/user/1000/ CREATE,ISDIR podman
/run/user/1000/ CREATE,ISDIR pulse
/run/user/1000/ OPEN,ISDIR pulse
/run/user/1000/ CLOSE_NOWRITE,CLOSE,ISDIR pulse
/run/user/1000/ CREATE wayland-0
/run/user/1000/ CREATE wayland-0.lock
/run/user/1000/ OPEN,ISDIR
/run/user/1000/ ACCESS,ISDIR
/run/user/1000/ DELETE wayland-0.lock
/run/user/1000/ DELETE wayland-0
/run/user/1000/ OPEN,ISDIR pulse
/run/user/1000/ ACCESS,ISDIR pulse
/run/user/1000/ CLOSE_NOWRITE,CLOSE,ISDIR pulse
/run/user/1000/ DELETE,ISDIR pulse
/run/user/1000/ OPEN,ISDIR podman
/run/user/1000/ ACCESS,ISDIR podman
/run/user/1000/ CLOSE_NOWRITE,CLOSE,ISDIR podman
/run/user/1000/ DELETE,ISDIR podman
/run/user/1000/ DELETE pk-debconf-socket
/run/user/1000/ OPEN,ISDIR gnupg
/run/user/1000/ ACCESS,ISDIR gnupg
/run/user/1000/ ACCESS,ISDIR gnupg
/run/user/1000/ CLOSE_NOWRITE,CLOSE,ISDIR gnupg
/run/user/1000/ DELETE,ISDIR gnupg
/run/user/1000/ DELETE bus
/run/user/1000/ OPEN,ISDIR systemd
/run/user/1000/ ACCESS,ISDIR systemd
/run/user/1000/ ACCESS,ISDIR systemd
/run/user/1000/ CLOSE_NOWRITE,CLOSE,ISDIR systemd
/run/user/1000/ DELETE,ISDIR systemd
/run/user/1000/ OPEN,ISDIR containers
/run/user/1000/ ACCESS,ISDIR containers
/run/user/1000/ CLOSE_NOWRITE,CLOSE,ISDIR containers
/run/user/1000/ DELETE,ISDIR containers
/run/user/1000/ OPEN,ISDIR libpod
/run/user/1000/ ACCESS,ISDIR libpod
/run/user/1000/ ACCESS,ISDIR libpod
/run/user/1000/ CLOSE_NOWRITE,CLOSE,ISDIR libpod
/run/user/1000/ DELETE,ISDIR libpod
/run/user/1000/ ACCESS,ISDIR
/run/user/1000/ CLOSE_NOWRITE,CLOSE,ISDIR

^C
❯ ll $XDG_RUNTIME_DIR
"/run/user/1000/": No such file or directory (os error 2)
```

Here's what I found on journal:

```
❯ journalctl -xe|grep "/run/user/1000"
Oct 03 18:21:48 CarlosEDP-Win systemd[1]: Starting user-runtime-dir@1000.service - User Runtime Directory /run/user/1000...
Oct 03 18:21:48 CarlosEDP-Win systemd[1]: Finished user-runtime-dir@1000.service - User Runtime Directory /run/user/1000.
Oct 03 18:22:17 CarlosEDP-Win sudo[1069]: carlosedp : TTY=pts/0 ; PWD=/home/carlosedp ; USER=root ; COMMAND=/usr/bin/inotifywait -m /run/user/1000
Oct 03 18:23:38 CarlosEDP-Win systemd[1]: Stopping user-runtime-dir@1000.service - User Runtime Directory /run/user/1000...
Oct 03 18:23:38 CarlosEDP-Win systemd[1]: Stopped user-runtime-dir@1000.service - User Runtime Directory /run/user/1000.

❯ systemctl status user-runtime-dir@1000
Found existing alias for "systemctl status". You should use: "sc-status"
○ user-runtime-dir@1000.service - User Runtime Directory /run/user/1000
     Loaded: loaded (/usr/lib/systemd/system/user-runtime-dir@.service; static)
     Active: inactive (dead) since Fri 2025-10-03 18:23:38 -03; 7min ago
   Duration: 1min 49.197s
 Invocation: 72fcd8bd188e43dd983daa39d1a57b74
       Docs: man:user@.service(5)
    Process: 740 ExecStart=/usr/lib/systemd/systemd-user-runtime-dir start 1000 (code=exited, status=0/SUCCESS)
    Process: 1394 ExecStop=/usr/lib/systemd/systemd-user-runtime-dir stop 1000 (code=exited, status=0/SUCCESS)
   Main PID: 740 (code=exited, status=0/SUCCESS)
   Mem peak: 1.5M
        CPU: 9ms

Oct 03 18:21:48 CarlosEDP-Win systemd[1]: Starting user-runtime-dir@1000.service - User Runtime Directory /run/user/1000...
Oct 03 18:21:48 CarlosEDP-Win systemd[1]: Finished user-runtime-dir@1000.service - User Runtime Directory /run/user/1000.
Oct 03 18:23:38 CarlosEDP-Win systemd[1]: Stopping user-runtime-dir@1000.service - User Runtime Directory /run/user/1000...
Oct 03 18:23:38 CarlosEDP-Win systemd[1]: user-runtime-dir@1000.service: Deactivated successfully.
Oct 03 18:23:38 CarlosEDP-Win systemd[1]: Stopped user-runtime-dir@1000.service - User Runtime Directory /run/user/1000.

```

### Expected Behavior

To have the $XDG_RUNTIME_DIR persist

### Actual Behavior

Directory disappears and break apps.

### Diagnostic Logs

[WslLogs-2025-10-03_18-20-55.zip](https://github.com/user-attachments/files/22688373/WslLogs-2025-10-03_18-20-55.zip)

**Comment by OneBlue** [comment]
Thank you for reporting this @carlosedp. The 3 minute mark makes this very suspicious, but sadly I can't reproduce it. 

Could please outputs of the following commands during a repro: 

- sudo journalctl -f 
- sudo inotifywait --monitor --timefmt '%F %T' --format '%T %w%f %e' /run/user/1000

With this we should be able to correlate which systemd unit is causing this

**Comment by carlosedp** [comment]
Sure, here it is:

journal:

```
❯ sudo journalctl -f
Oct 04 17:30:14 CarlosEDP-Win unknown: WSL (2 - init-systemd(Ubuntu)) ERROR: WaitForBootProcess:3393: /sbin/init failed to start within 10000ms
Oct 04 17:30:14 CarlosEDP-Win login[641]: pam_unix(login:session): session opened for user carlosedp(uid=1000) by carlosedp(uid=0)
Oct 04 17:30:14 CarlosEDP-Win systemd[1]: Created slice user-1000.slice - User Slice of UID 1000.
Oct 04 17:30:14 CarlosEDP-Win systemd[1]: Starting user-runtime-dir@1000.service - User Runtime Directory /run/user/1000...
Oct 04 17:30:14 CarlosEDP-Win systemd-logind[277]: New session c1 of user carlosedp.
Oct 04 17:30:14 CarlosEDP-Win systemd[1]: Finished user-runtime-dir@1000.service - User Runtime Directory /run/user/1000.
Oct 04 17:30:20 CarlosEDP-Win wsl-pro-service[278]: WARNING Daemon: could not connect to Windows Agent: could not get address: could not read agent port file "/mnt/c/Users/carlosedp/.ubuntupro/.address": open /mnt/c/Users/carlosedp/.ubuntupro/.address: no such file or directory
Oct 04 17:30:23 CarlosEDP-Win systemd[1]: dmesg.service: Deactivated successfully.
Oct 04 17:30:24 CarlosEDP-Win unknown: WSL (2 - Interop) ERROR: CreateLoginSession:2732: Timed out waiting for user session for uid=1000
Oct 04 17:30:31 CarlosEDP-Win sudo[1226]: carlosedp : TTY=pts/3 ; PWD=/home/carlosedp ; USER=root ; COMMAND=/usr/bin/journalctl -f
Oct 04 17:30:31 CarlosEDP-Win sudo[1226]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
Oct 04 17:30:34 CarlosEDP-Win sudo[1233]: carlosedp : TTY=pts/4 ; PWD=/home/carlosedp ; USER=root ; COMMAND=/usr/bin/inotifywait --monitor --timefmt '%F %T' --format '%T %w%f %e' /run/user/1000
Oct 04 17:30:34 CarlosEDP-Win sudo[1233]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
Oct 04 17:30:35 CarlosEDP-Win netavark[268]: timeout met: exiting after 30 secs of inactivity
Oct 04 17:30:35 CarlosEDP-Win systemd[1]: netavark-dhcp-proxy.service: Deactivated successfully.
Oct 04 17:30:36 CarlosEDP-Win wsl-pro-service[278]: WARNING Daemon: could not connect to Windows Agent: could not get address: could not read agent port file "/mnt/c/Users/carlosedp/.ubuntupro/.address": open /mnt/c/Users/carlosedp/.ubuntupro/.address: no such file or directory
Oct 04 17:30:51 CarlosEDP-Win kernel: hv_balloon: Max. dynamic memory size: 32724 MB
Oct 04 17:31:08 CarlosEDP-Win wsl-pro-service[278]: WARNING Daemon: could not connect to Windows Agent: could not get address: could not read agent port file "/mnt/c/Users/carlosedp/.ubuntupro/.address": open /mnt/c/Users/carlosedp/.ubuntupro/.address: no such file or directory
Oct 04 17:31:14 CarlosEDP-Win systemd-logind[277]: Session c1 logged out. Waiting for processes to exit.
Oct 04 17:31:14 CarlosEDP-Win systemd-logind[277]: Removed session c1.
Oct 04 17:31:24 CarlosEDP-Win systemd-resolved[129]: Clock change detected. Flushing caches.
Oct 04 17:32:04 CarlosEDP-Win systemd-networkd-wait-online[342]: Timeout occurred while waiting for network connectivity.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: systemd-networkd-wait-online.service: Main process exited, code=exited, status=1/FAILURE
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: systemd-networkd-wait-online.service: Failed with result 'exit-code'.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Failed to start systemd-networkd-wait-online.service - Wait for Network to be Configured.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Reached target network-online.target - Network is Online.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Started update-notifier-download.timer - Download data for packages that failed at package install time.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Started update-notifier-motd.timer - Check to see whether there is a new version of Ubuntu available.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Reached target timers.target - Timer Units.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: open-iscsi.service - Login to default iSCSI targets was skipped because no trigger condition checks were met.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Reached target remote-fs-pre.target - Preparation for Remote File Systems.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Reached target remote-fs.target - Remote File Systems.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: apport.service - automatic crash report generation was skipped because of an unmet condition check (ConditionVirtualization=!container).
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Starting blk-availability.service - Availability of block devices...
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Started cron.service - Regular background program processing daemon.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Starting landscape-client.service - Landscape client daemons...
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Starting nfs-kernel-server.service - LSB: Kernel NFS server support...
Oct 04 17:32:04 CarlosEDP-Win (cron)[1350]: cron.service: Referenced but unset environment variable evaluates to an empty string: EXTRA_OPTS
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Starting podman-auto-update.service - Podman auto-update service...
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Starting podman-restart.service - Podman Start All Containers With Restart Policy Set To Always...
Oct 04 17:32:04 CarlosEDP-Win cron[1350]: (CRON) INFO (pidfile fd = 3)
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: pollinate.service - Pollinate to seed the pseudo random number generator was skipped because of an unmet condition check (ConditionVirtualization=!container).
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Starting rpc-statd-notify.service - Notify NFS peers of a restart...
Oct 04 17:32:04 CarlosEDP-Win cron[1350]: (CRON) INFO (Running @reboot jobs)
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Starting ssh.service - OpenBSD Secure Shell server...
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: systemd-pcrphase.service - TPM PCR Barrier (User) was skipped because of an unmet condition check (ConditionSecurity=measured-uki).
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Starting systemd-user-sessions.service - Permit User Sessions...
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: ubuntu-advantage.service - Ubuntu Pro Background Auto Attach was skipped because no trigger condition checks were met.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Finished blk-availability.service - Availability of block devices.
Oct 04 17:32:04 CarlosEDP-Win sm-notify[1355]: Version 2.8.2 starting
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Started nfs-kernel-server.service - LSB: Kernel NFS server support.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Started rpc-statd-notify.service - Notify NFS peers of a restart.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Finished systemd-user-sessions.service - Permit User Sessions.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Starting plymouth-quit-wait.service - Hold until boot process finishes up...
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Starting plymouth-quit.service - Terminate Plymouth Boot Screen...
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Starting user@1000.service - User Manager for UID 1000...
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Finished plymouth-quit-wait.service - Hold until boot process finishes up.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Started console-getty.service - Console Getty.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Starting setvtrgb.service - Set console scheme...
Oct 04 17:32:04 CarlosEDP-Win (systemd)[1380]: pam_unix(systemd-user:session): session opened for user carlosedp(uid=1000) by carlosedp(uid=0)
Oct 04 17:32:04 CarlosEDP-Win podman[1354]: time="2025-10-04T17:32:04-03:00" level=info msg="/usr/bin/podman filtering at log level info"
Oct 04 17:32:04 CarlosEDP-Win podman[1354]: time="2025-10-04T17:32:04-03:00" level=info msg="Using sqlite as database backend"
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Finished plymouth-quit.service - Terminate Plymouth Boot Screen.
Oct 04 17:32:04 CarlosEDP-Win podman[1354]: time="2025-10-04T17:32:04-03:00" level=info msg="Setting parallel job count to 49"
Oct 04 17:32:04 CarlosEDP-Win systemd-logind[277]: New session c2 of user carlosedp.
Oct 04 17:32:04 CarlosEDP-Win podman[1354]: time="2025-10-04T17:32:04-03:00" level=info msg="Received shutdown.Stop(), terminating!" PID=1354
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: var-lib-containers-storage-overlay.mount: Deactivated successfully.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Finished setvtrgb.service - Set console scheme.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Finished podman-restart.service - Podman Start All Containers With Restart Policy Set To Always.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Created slice system-getty.slice - Slice /system/getty.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Started getty@tty1.service - Getty on tty1.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Reached target getty.target - Login Prompts.
Oct 04 17:32:04 CarlosEDP-Win sshd[1384]: Server listening on 0.0.0.0 port 22.
Oct 04 17:32:04 CarlosEDP-Win (sd-exec-strv)[1409]: '/run/systemd/user-generators/wsl-user-generator' is marked world-writable, which is a security risk as it is executed with privileges. Please remove world writability permission bits. Proceeding anyway.
Oct 04 17:32:04 CarlosEDP-Win sshd[1384]: Server listening on :: port 22.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Started ssh.service - OpenBSD Secure Shell server.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: var-lib-containers-storage-overlay.mount: Deactivated successfully.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: podman-auto-update.service: Deactivated successfully.
Oct 04 17:32:04 CarlosEDP-Win systemd[1]: Finished podman-auto-update.service - Podman auto-update service.
Oct 04 17:32:04 CarlosEDP-Win systemd[1380]: Queued start job for default target default.target.
Oct 04 17:32:04 CarlosEDP-Win systemd[1380]: Created slice app.slice - User Application Slice.
Oct 04 17:32:04 CarlosEDP-Win systemd[1380]: Started launchpadlib-cache-clean.timer - Clean up old files in the Launchpadlib cache.
Oct 04 17:32:04 CarlosEDP-Win systemd[1380]: Started nix-gc.timer - Nix Garbage Collector.
Oct 04 17:32:04 CarlosEDP-Win systemd[1380]: Started podman-auto-update.timer - Podman auto-update timer.
Oct 04 17:32:04 CarlosEDP-Win systemd[1380]: Reached target paths.target - Paths.
Oct 04 17:32:04 CarlosEDP-Win systemd[1380]: Reached target timers.target - Timers.
Oct 04 17:32:04 CarlosEDP-Win systemd[1380]: Starting dbus.socket - D-Bus User Message Bus Socket...
Oct 04 17:32:04 CarlosEDP-Win systemd[1380]: Listening on dirmngr.socket - GnuPG network certificate management daemon.
Oct 04 17:32:04 CarlosEDP-Win systemd[1380]: Listening on gpg-agent-browser.socket - GnuPG cryptographic agent and passphrase cache (access for web browsers).
Oct 04 17:32:04 CarlosEDP-Win systemd[1380]: Listening on gpg-agent-extra.socket - GnuPG cryptographic agent and passphrase cache (restricted).
Oct 04 17:32:04 CarlosEDP-Win systemd[1380]: Starting gpg-agent-ssh.socket - GnuPG cryptographic agent (ssh-agent emulation)...
Oct 04 17:32:04 CarlosEDP-Win systemd[1380]: Listening on gpg-agent.socket - GnuPG cryptographic agent and passphrase cache.
Oct 04 17:32:04 CarlosEDP-Win systemd[1380]: Listening on keyboxd.socket - GnuPG public key management service.
Oct 04 17:32:04 CarlosEDP-Win systemd[1380]: Listening on pk-debconf-helper.socket - debconf communication socket.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Listening on podman.socket - Podman API Socket.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Starting wslg-session.service - WSLg user service...
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Listening on dbus.socket - D-Bus User Message Bus Socket.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Listening on gpg-agent-ssh.socket - GnuPG cryptographic agent (ssh-agent emulation).
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Reached target sockets.target - Sockets.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Reached target basic.target - Basic System.
Oct 04 17:32:05 CarlosEDP-Win systemd[1]: Started user@1000.service - User Manager for UID 1000.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Starting podman-auto-update.service - Podman auto-update service...
Oct 04 17:32:05 CarlosEDP-Win systemd[1]: session-c1.scope: PID 641 vanished before we could move it to target cgroup '/user.slice/user-1000.slice/session-c1.scope', skipping: No such process
Oct 04 17:32:05 CarlosEDP-Win systemd[1]: session-c1.scope: No PIDs left to attach to the scope's control group, refusing.
Oct 04 17:32:05 CarlosEDP-Win systemd[1]: session-c1.scope: Failed with result 'resources'.
Oct 04 17:32:05 CarlosEDP-Win systemd[1]: Failed to start session-c1.scope - Session c1 of User carlosedp.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Starting podman-restart.service - Podman Start All Containers With Restart Policy Set To Always...
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Starting podman.service - Podman API Service...
Oct 04 17:32:05 CarlosEDP-Win systemd[1]: Stopping user@1000.service - User Manager for UID 1000...
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Activating special unit exit.target...
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: podman-auto-update.service: Main process exited, code=killed, status=15/TERM
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: podman-auto-update.service: Failed with result 'signal'.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Stopped podman-auto-update.service - Podman auto-update service.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: podman-restart.service: Main process exited, code=killed, status=15/TERM
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: podman-restart.service: Failed with result 'signal'.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Stopped podman-restart.service - Podman Start All Containers With Restart Policy Set To Always.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: wslg-session.service: Main process exited, code=killed, status=15/TERM
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: wslg-session.service: Failed with result 'signal'.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Stopped wslg-session.service - WSLg user service.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Stopped podman.service - Podman API Service.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Stopped target basic.target - Basic System.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Stopped target paths.target - Paths.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Stopped target sockets.target - Sockets.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Stopped target timers.target - Timers.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Stopped launchpadlib-cache-clean.timer - Clean up old files in the Launchpadlib cache.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Stopped nix-gc.timer - Nix Garbage Collector.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Stopped podman-auto-update.timer - Podman auto-update timer.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Closed dbus.socket - D-Bus User Message Bus Socket.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Closed dirmngr.socket - GnuPG network certificate management daemon.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Closed gpg-agent-browser.socket - GnuPG cryptographic agent and passphrase cache (access for web browsers).
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Closed gpg-agent-extra.socket - GnuPG cryptographic agent and passphrase cache (restricted).
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Stopping gpg-agent-ssh.socket - GnuPG cryptographic agent (ssh-agent emulation)...
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Closed gpg-agent.socket - GnuPG cryptographic agent and passphrase cache.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Closed keyboxd.socket - GnuPG public key management service.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Closed pk-debconf-helper.socket - debconf communication socket.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Closed podman.socket - Podman API Socket.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Closed gpg-agent-ssh.socket - GnuPG cryptographic agent (ssh-agent emulation).
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Removed slice app.slice - User Application Slice.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Reached target shutdown.target - Shutdown.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Finished systemd-exit.service - Exit the Session.
Oct 04 17:32:05 CarlosEDP-Win systemd[1380]: Reached target exit.target - Exit the Session.
Oct 04 17:32:05 CarlosEDP-Win landscape-config[1351]: Registered:    False
Oct 04 17:32:05 CarlosEDP-Win landscape-config[1351]: Config Path:   /etc/landscape/client.conf
Oct 04 17:32:05 CarlosEDP-Win landscape-config[1351]: Data Path      /var/lib/landscape/client
Oct 04 17:32:05 CarlosEDP-Win (sd-pam)[1396]: pam_unix(systemd-user:session): session closed for user carlosedp
Oct 04 17:32:05 CarlosEDP-Win systemd-logind[277]: Removed session c2.
Oct 04 17:32:05 CarlosEDP-Win systemd[1]: user@1000.service: Deactivated successfully.
Oct 04 17:32:05 CarlosEDP-Win systemd[1]: Stopped user@1000.service - User Manager for UID 1000.
Oct 04 17:32:05 CarlosEDP-Win systemd[1]: Stopping user-runtime-dir@1000.service - User Runtime Directory /run/user/1000...
Oct 04 17:32:05 CarlosEDP-Win systemd[1]: landscape-client.service: Skipped due to 'exec-condition'.
Oct 04 17:32:05 CarlosEDP-Win systemd[1]: Condition check resulted in landscape-client.service - Landscape client daemons being skipped.
Oct 04 17:32:05 CarlosEDP-Win systemd[1]: Reached target multi-user.target - Multi-User System.
Oct 04 17:32:05 CarlosEDP-Win systemd[1]: Reached target graphical.target - Graphical Interface.
Oct 04 17:32:05 CarlosEDP-Win systemd[1]: user-runtime-dir@1000.service: Deactivated successfully.
Oct 04 17:32:05 CarlosEDP-Win systemd[1]: Stopped user-runtime-dir@1000.service - User Runtime Directory /run/user/1000.
Oct 04 17:32:05 CarlosEDP-Win systemd[1]: Startup finished in 2min 2.031s.
Oct 04 17:32:05 CarlosEDP-Win systemd[1]: Removed slice user-1000.slice - User Slice of UID 1000.
Oct 04 17:32:05 CarlosEDP-Win systemd[1]: mnt-wslg-run-user-1000.mount: Deactivated successfully.
Oct 04 17:32:05 CarlosEDP-Win systemd[1]: run-user-1000.mount: Deactivated successfully.
Oct 04 17:32:07 CarlosEDP-Win wsl-pro-service[278]: WARNING Daemon: could not connect to Windows Agent: could not get address: could not read agent port file "/mnt/c/Users/carlosedp/.ubuntupro/.address": open /mnt/c/Users/carlosedp/.ubuntupro/.address: no such file or directory
```

inotify:

```
❯ sudo inotifywait --monitor --timefmt '%F %T' --format '%T %w%f %e' /run/user/1000
Setting up watches.
Watches established.
2025-10-04 17:32:04 /run/user/1000/systemd CREATE,ISDIR
2025-10-04 17:32:04 /run/user/1000/bus CREATE
2025-10-04 17:32:04 /run/user/1000/bus ATTRIB
2025-10-04 17:32:04 /run/user/1000/gnupg CREATE,ISDIR
2025-10-04 17:32:04 /run/user/1000/pk-debconf-socket CREATE
2025-10-04 17:32:04 /run/user/1000/pk-debconf-socket ATTRIB
2025-10-04 17:32:04 /run/user/1000/podman CREATE,ISDIR
2025-10-04 17:32:05 /run/user/1000/pulse CREATE,ISDIR
2025-10-04 17:32:05 /run/user/1000/pulse OPEN,ISDIR
2025-10-04 17:32:05 /run/user/1000/pulse CLOSE_NOWRITE,CLOSE,ISDIR
2025-10-04 17:32:05 /run/user/1000/wayland-0 CREATE
2025-10-04 17:32:05 /run/user/1000/wayland-0.lock CREATE
2025-10-04 17:32:05 /run/user/1000/ OPEN,ISDIR
2025-10-04 17:32:05 /run/user/1000/ ACCESS,ISDIR
2025-10-04 17:32:05 /run/user/1000/wayland-0.lock DELETE
2025-10-04 17:32:05 /run/user/1000/wayland-0 DELETE
2025-10-04 17:32:05 /run/user/1000/pulse OPEN,ISDIR
2025-10-04 17:32:05 /run/user/1000/pulse ACCESS,ISDIR
2025-10-04 17:32:05 /run/user/1000/pulse CLOSE_NOWRITE,CLOSE,ISDIR
2025-10-04 17:32:05 /run/user/1000/pulse DELETE,ISDIR
2025-10-04 17:32:05 /run/user/1000/podman OPEN,ISDIR
2025-10-04 17:32:05 /run/user/1000/podman ACCESS,ISDIR
2025-10-04 17:32:05 /run/user/1000/podman CLOSE_NOWRITE,CLOSE,ISDIR
2025-10-04 17:32:05 /run/user/1000/podman DELETE,ISDIR
2025-10-04 17:32:05 /run/user/1000/pk-debconf-socket DELETE
2025-10-04 17:32:05 /run/user/1000/gnupg OPEN,ISDIR
2025-10-04 17:32:05 /run/user/1000/gnupg ACCESS,ISDIR
2025-10-04 17:32:05 /run/user/1000/gnupg CLOSE_NOWRITE,CLOSE,ISDIR
2025-10-04 17:32:05 /run/user/1000/gnupg DELETE,ISDIR
2025-10-04 17:32:05 /run/user/1000/bus DELETE
2025-10-04 17:32:05 /run/user/1000/systemd OPEN,ISDIR
2025-10-04 17:32:05 /run/user/1000/systemd ACCESS,ISDIR
2025-10-04 17:32:05 /run/user/1000/systemd ACCESS,ISDIR
2025-10-04 17:32:05 /run/user/1000/systemd CLOSE_NOWRITE,CLOSE,ISDIR
2025-10-04 17:32:05 /run/user/1000/systemd DELETE,ISDIR
2025-10-04 17:32:05 /run/user/1000/containers OPEN,ISDIR
2025-10-04 17:32:05 /run/user/1000/containers ACCESS,ISDIR
2025-10-04 17:32:05 /run/user/1000/containers CLOSE_NOWRITE,CLOSE,ISDIR
2025-10-04 17:32:05 /run/user/1000/containers DELETE,ISDIR
2025-10-04 17:32:05 /run/user/1000/libpod OPEN,ISDIR
2025-10-04 17:32:05 /run/user/1000/libpod ACCESS,ISDIR
2025-10-04 17:32:05 /run/user/1000/libpod CLOSE_NOWRITE,CLOSE,ISDIR
2025-10-04 17:32:05 /run/user/1000/libpod DELETE,ISDIR
2025-10-04 17:32:05 /run/user/1000/ ACCESS,ISDIR
2025-10-04 17:32:05 /run/user/1000/ CLOSE_NOWRITE,CLOSE,ISDIR
```

**Comment by OneBlue** [comment]
Hmm looking journalctl, it's looking like `systemd-user-sessions.service` is starting pretty late, most likely because systemd is too slow to start, and WSL gives up waiting: 

```
Oct 04 17:30:14 CarlosEDP-Win unknown: WSL (2 - init-systemd(Ubuntu)) ERROR: WaitForBootProcess:3393: /sbin/init failed to start within 10000ms
```

Looking through's the boot sequence, I'm guessing that the problem is that `systemd-networkd-wait-online.service` times out, delaying everything else. 

Does running `systemctl mask systemd-networkd-wait-online.service` and restarting the distro solve the issue ?

**Comment by carlosedp** [comment]
Apparently masking networkd-wait-online service made the WSL VM boot way faster and the /run/user/1000/ now is not deleted.

**Comment by OneBlue** [comment]
Ok that makes sense. We already have [logic to today to discourage that unit from being enabled in WSL distros](https://github.com/microsoft/WSL/blob/c7aad6161166d330099cc48ceab7ee158b8225a2/distributions/validate-modern.py#L29) but if this is causing systemd boot timeout, we might need to always mask it during boot in WSL, since that unit seems to never "see" networking. 

I'll leave this issue open to track that

**Comment by vblazhkun** [comment]
@OneBlue The issue is probably related to `Docker` (or any other service, initializing an interface on boot, but not activating it hence breaking the `systemd-networkd-wait-online.service`).

``` bash
$ ip l
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1280 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 00:15:5d:4f:f1:19 brd ff:ff:ff:ff:ff:ff
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default
    link/ether fa:84:14:0a:01:15 brd ff:ff:ff:ff:ff:ff
```

The actual fix would be pointing the `systemd-networkd-wait-online.service` to the primary network interface of WSL2 (e.g. `eth0`) or letting it start with any active network interface (`--any` option should be passed to the given service):

``` bash
$ cat /etc/systemd/system/systemd-networkd-wait-online.service.d/wsl.conf
[Service]
# [vblazhkun]: required to zeroize the default options passed.
ExecStart=
ExecStart=/usr/lib/systemd/systemd-networkd-wait-online --interface='eth0'
```

N.B. I have had the exact same issue and that is fixed with the changes proposed without masking the given service.

**Comment by carlosedp** [comment]
I don't have Docker installed on WSL2, only Podman which doesn't create a network interface.

```
❯ ip l
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 60:cf:84:cf:cd:af brd ff:ff:ff:ff:ff:ff
    altname enx60cf84cfcdaf
3: loopback0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 00:15:5d:78:04:47 brd ff:ff:ff:ff:ff:ff
    altname enx00155d780447
4: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:15:5d:64:43:8a brd ff:ff:ff:ff:ff:ff
    altname enx00155d64438a
5: eth2: <BROADCAST,MULTICAST> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:15:5d:0f:b7:d5 brd ff:ff:ff:ff:ff:ff
    altname enx00155d0fb7d5

```

**Comment by vblazhkun** [comment]
@carlosedp Did you read my comment? it says:

> or any other service, initializing an interface on boot, but not activating it hence breaking the `systemd-networkd-wait-online.service`

In your setup you definitely have an interface in `DOWN` state at the time the `systemd-networkd-wait-online.service` fires. Which interface and what creates it you have to figure yourself.

**Comment by trianglesis** [comment]
The issue is still there, latest WSL version, OL9.5 distro.

```
WSL version: 2.7.3.0
Kernel version: 6.6.114.1-1
WSLg version: 1.0.73
MSRDC version: 1.2.6676
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26200.8457
```

For example ESPHome in virtual env is affected:

```shell
Traceback (most recent call last):
  File "/home/user/ESPHome/venv/lib/python3.14/site-packages/platformio/project/helpers.py", line 74, in get_default_projects_dir
    assert IS_WINDOWS
           ^^^^^^^^^^
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.14/runpy.py", line 203, in _run_module_as_main
    return _run_code(code, main_globals, None,
                     "__main__", mod_spec)
  File "/usr/local/lib/python3.14/runpy.py", line 88, in _run_code
    exec(code, run_globals)
    ~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/user/ESPHome/venv/lib/python3.14/site-packages/esphome/platformio_runner.py", line 144, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/user/ESPHome/venv/lib/python3.14/site-packages/esphome/platformio_runner.py", line 105, in main
    patch_structhash()
    ~~~~~~~~~~~~~~~~^^
  File "/home/user/ESPHome/venv/lib/python3.14/site-packages/esphome/platformio_runner.py", line 28, in patch_structhash
    from platformio.run import cli, helpers
  File "/home/user/ESPHome/venv/lib/python3.14/site-packages/platformio/run/cli.py", line 24, in <module>
    from platformio import app, exception, fs, util
  File "/home/user/ESPHome/venv/lib/python3.14/site-packages/platformio/app.py", line 59, in <module>
    "value": get_default_projects_dir(),
             ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/user/ESPHome/venv/lib/python3.14/site-packages/platformio/project/helpers.py", line 84, in get_default_projects_dir
    subprocess.check_output(["xdg-user-dir", "DOCUMENTS"])
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/subprocess.py", line 473, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
               **kwargs).stdout
               ^^^^^^^^^
  File "/usr/local/lib/python3.14/subprocess.py", line 555, in run
    with Popen(*popenargs, **kwargs) as process:
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/subprocess.py", line 1039, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        pass_fds, cwd, env,
                        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
                        gid, gids, uid, umask,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        start_new_session, process_group)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/subprocess.py", line 1990, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'xdg-user-dir'
```
