### ISSUE TITLE
Scrolling doesn't work properly in latest insider beta

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/WSL#1984]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.16179
* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I ran npm installed which produced lots of output text and wanted to scroll up to read the text I missed.
* What's wrong / what should be happening instead:
Instead of seeing the output from the command I just typed, I saw output from a command I ran hours ago.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

**Comment by zadjii-msft** [comment]
Gonna go out on a limb and say this has to do with the scroll margins, again.

MSFT:11647773 currently tracks what I think is this issue, though I'll add this to that bug to make sure they're the same. 

@warpdesign any chance that before you ran `npm install ...`, you had run `apt install ...`? I'm pretty sure that `apt` is a reliable repro for this behavior, but I don't know if `npm` is yet.

**Comment by Po-wei** [comment]
I have the same scrolling problem, too. What's more, when I encounter this issue, typing "clear" would let me cannot scroll up( The buffer was set to the size of the height, implicitly)

**Comment by zadjii-msft** [comment]
Wadda ya know, I fixed this issue this morning. On it's way out to Insider's now :)

**Comment by Po-wei** [comment]
@zadjii-msft When can i get this update from regular Windows Update?

**Comment by zadjii-msft** [comment]
If you're not on Insiders, then I think the best I can tell you is Soon<sup>TM</sup>. It'll  come out with the Fall Creator's Update, but I don't know when that will officially be released.

**Comment by MerkaST** [comment]
This appears to still happen with the Fall Creator's Update. I'm on build 16299.64 and running an `apt install` (or remove or autoremove, I'd assume all commands that use the progress bar) command that produces output longer than one window right after opening WSL will exhibit this behaviour, ie. have missing scrollback content.

**Comment by zadjii-msft** [comment]
Hmmm. Okay so i think I get what's happening. Basically, the "scroll margins" that apt sets are at a fixed point in the buffer. So anything that would scrollback off of it, is just lost instead. 

The right way to do this is to probably instead shift the whole viewport down a line (including the buffer-relative margin settings), then scroll the contents of the margins up a line, so that the top line is off of the viewport, in the "scrollback".

Filing a new bug to take a look at this later this release cycle.

**Comment by bitcrazed** [comment]
This issue was moved to Microsoft/console#111
