### ISSUE TITLE
Trying to install napalm

### ISSUE THREAD

**Issue by LongBeachHXC** [microsoft/WSL#2509]
Windows 10 Ver 10.0.14393
Pip: 9.0.1

I am attempting to install Napalm but every time I get an error message when it comes to the specific package relating to 'napalm-ros'. Every other package downloads and installs with no issues. Any assistance would be greatly appreciated.

Thanks

Collecting librouteros>1.0.0 (from napalm-ros->napalm)
  Downloading librouteros-1.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    error in librouteros setup command: 'extras_require' must be a dictionary whose values are strings or lists of strin
gs containing valid project/version requirement specifiers.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qST_7J/librouteros/

**Comment by LongBeachHXC** [comment]
I am utilizing the 'pip install napalm' command where it should just download napalm with no issues. I spun up an Ubuntu VM on my machine and went through the same procedures and napalm was able to download with no issues.

**Comment by benhillis** [comment]
Is upgrading to creators update an option for you? We have fixed a lot of bugs since the build you are running.

**Comment by LongBeachHXC** [comment]
hmmmm...unfortunately it appears that my company is blocking the install to the creators update. When attempting to upgrade my windows it says to contact systems administrator.

**Comment by LongBeachHXC** [comment]
Hey, so it turns out that I am able to download the creators update. I am doing that now and will report back after it is complete and I do some testing. THANKS!

**Comment by LongBeachHXC** [comment]
Hey so I was able to install the Windows Creator's Update (Version 1703 OS Build 15063.483). However, I am still having issues downloading that last module for Napalm. I found out that you can download the specific modules that you want (I.E. IOS) so I was able to download the one that I wanted with no issues.

**Comment by porkstoners** [comment]
I had the same issue and the same work around any update on this ?

**Comment by porkstoners** [comment]
Collecting librouteros>1.0.0 (from napalm-ros->napalm)
  Using cached librouteros-1.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    error in librouteros setup command: 'extras_require' must be a dictionary whose values are strings or lists of strin
gs containing valid project/version requirement specifiers.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\dbarke~1.hrl\appdata\local\temp\pip-build-crcaw7
\librouteros\

**Comment by benhillis** [comment]
Closing out old issues, if you're still having issues on newer versions of Windows please open a new issue.
