### ISSUE TITLE
Uptime becomes negative after Windows machine has been on for several days.

### ISSUE THREAD

**Issue by PetterS** [Microsoft/WSL#3514]
I am using Windows 1803 build 171134.228.

After my machine has been powered on for several days (in sleep mode during the nights), the following happens in WSL: 

    $ uptime
     11:23:19 up -24855 days, -3:-14,  0 users,  load average: 0.52, 0.58, 0.59

I get other problems as well that seem releated, like:

    $ python3 --version
    Python 3.7.0b3
    $ python3
    Fatal Python error: _Py_InitializeMainInterpreter: can't initialize time
    OverflowError: timestamp too large to convert to C _PyTime_t

    Current thread 0x00007f0232c21080 (most recent call first):
    Aborted (core dumped)

Restarting the computer fixes all of these issues.

**Comment by 0xbadfca11** [comment]
#3252
Fixed in Insider Preview.

**Comment by PetterS** [comment]
Thanks, I suppose we can close this then?

**Comment by drone-ah** [comment]
As a quicker workaround (than restarting windows), you can just restart the LxssManager service

**Comment by leoseccia** [comment]
This is still broken... @drone-ah suggestion helped me. Thank you.

**Comment by Chematronix** [comment]
To restart WSL / LxssManager quickly:

`Win + X, Windows PowerShell (Admin), Get-Service LxssManager | Restart-Service`
