### ISSUE TITLE
Zombie zsh processes left behind that consume 8 % CPU each

### ISSUE THREAD

**Issue by mnylen** [Microsoft/WSL#3940]
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17763.379]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

Sometimes after using Ubuntu 18.04 distribution on WSL with zsh set as the default shell for extended times, there are "zombie" background zsh processes left behind that seem to be in some kind of busy loop, consuming 8 % CPU each. It's possible to kill these processes via the Task Manager manually without affecting any running terminal windows.

I know this isn't a lot to go on, but I would appreciate if anyone could instruct what more information I could provide / how to provide it?

**Comment by Brian-Perkins** [comment]
Can you see these zsh processes from within wsl? If you run top or htop do you see zsh processes consuming cpu when taskmgr is showing this state? If you can see them from within wsl, you should also be able to attach [strace](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#6-strace-of-the-failing-command) to them by adding the -p <pid> flag to get an idea of what operations are consuming CPU. Attaching strace may require sudo in this scenario.

**Comment by mnylen** [comment]
Still trying to replicate this to get the strace... It seems to happen so inconsistently. Sometimes it happens many times a day when I have some long running processes open, but it's been behaving correctly for the last few days now with no problems.

**Comment by mnylen** [comment]
It finally happened again. I managed to get a strace of the process. See here https://gist.github.com/mnylen/a1fafaaf5fdf3d56215fe7e825af31c4

It seems it's in some kind of infinite loop trying to kill process 8744, which `ps axu` lists as `[awk] <defunct>`

**Comment by Brian-Perkins** [comment]
This is likely #3741.

**Comment by suhsteve** [comment]
I am also experiencing the same issue.

Microsoft Windows [Version 10.0.17763.437]

```shell
❯ cat /proc/version
Linux version 4.4.0-17763-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #379-Microsoft Wed Mar 06 19:16:00 PST 2019
❯ cat /proc/version_signature
Microsoft 4.4.0-17763.379-Microsoft 4.4.35
```

zsh strace:
https://gist.github.com/suhsteve/a3d577cd983b48deb906f7011a74b562

**Comment by kiranmr** [comment]
I am also experiencing the same issue from couple of months.
Window 10 Pro version 1809
```
$ cat /proc/version
Linux version 4.4.0-17763-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #379-Microsoft Wed Mar 06 19:16:00 PST 2019

$ cat /proc/version_signature
Microsoft 4.4.0-17763.379-Microsoft 4.4.35
```

Below is output of ps
```
$ ps -eaf
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  2 01:24 ?        00:00:00 /init ro
root         2     1  0 01:24 tty1     00:00:00 /init ro
kiran        3     2 19 01:24 tty1     00:00:01 -zsh
kiran       38     1 99 01:24 tty1     00:00:06 -zsh
kiran       44    38  0 01:24 tty1     00:00:00 [awk] <defunct>
kiran      105     3  0 01:24 tty1     00:00:00 ps -eaf
```
PID 44 is defunct and PID 38 zsh is utilizing 100% CPU

Output from top
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
   38 abcde     20   0   21876   1004    932 R 100.0  0.0   4:12.52 zsh
    1 root      20   0    8324    152    128 S   0.0  0.0   0:00.20 init
    2 root      20   0    8336    164    120 S   0.0  0.0   0:00.03 init
    3 abcde     20   0   21844   6824   6768 S   0.0  0.0   0:01.71 zsh
   44 abcde     20   0       0      0      0 Z   0.0  0.0   0:00.01 awk
```

here is the strace [gist](https://gist.github.com/kiranmr/430e508711584fbebcb787152c791913)

**Comment by mscraigloewen** [comment]
Hi @kiranmr , 

From @Brian-Perkins  it seems to be related to issue #3741 which is marked as fixed in an insiders build. 

I see you're running Windows version 17763, and from the other thread it's indicated that this bug is fixed in Version 18344. 

So a fix seems to be coming, and if you'd like to try it out right away and see if it resolves your issue you can do that through the Windows insider program!

Let me know if that helps!

**Comment by kiranmr** [comment]
Thanks for the update @mscraigloewen will evaluate if I can switch to insiders program and try the fix.

**Comment by suhsteve** [comment]
Windows updated to
```powershell
>ver

Microsoft Windows [Version 10.0.18362.30]
```

And the issue looks like it's fixed.

**Comment by therealkenc** [comment]
Thanks. Let's call it a dupe until proven otherwise.

**Comment by misadrik** [comment]
my windows is
Microsoft Windows [Version 10.0.18363.719]
Still have the same problem  it consume about 30%, each zsh consume 12% CPU. Sometimes one consume 30%.

**Comment by tkonya** [comment]
Microsoft Windows [Version 10.0.18362.720]
I have sometimes seen multiple zsh processes running in the background, consuming ~10% each. I can't use zsh because of this.

**Comment by therealkenc** [comment]
^--- landing zones for that are #3914 #5016 (tmux and sshd being academic).

**Comment by TeoTN** [comment]
Please re-open, the issue is not resolved:
```
Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #476-Microsoft Fri Nov 01 16:5
3:00 PST 2019

UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 16:38 ?        00:00:00 /init
piotr     4146     1  0 19:18 ?        00:00:42 /c/Users/piotr/.nvm/versions/node/v13.3.0/bin/node ...
piotr     4307  4146  0 19:18 ?        00:00:00 [node] <defunct>
piotr     4314  4146  0 19:18 ?        00:00:00 [node] <defunct>
piotr     4321  4146  0 19:18 ?        00:00:00 [node] <defunct>
piotr     4328  4146  0 19:18 ?        00:00:00 [node] <defunct>
piotr     4335  4146  0 19:18 ?        00:00:00 [node] <defunct>
piotr     4342  4146  0 19:18 ?        00:00:00 [node] <defunct>
root      6933     1  0 20:49 tty1     00:00:00 /init
piotr     6934  6933  0 20:49 tty1     00:00:00 -zsh
piotr     7374  6934  0 20:50 tty1     00:00:00 ps -ef
```

**Comment by mieber** [comment]
This was bugging me for a few weeks and I tried all kinds of things. In the end I uninstalled zsh and oh my zsh completely from my ubuntu@WSL and reinstalled it. The problem is gone for now. When syncing my old and new installation I saw that I had z installed as plugin and that was about 4 - 5 weeks ago. Maybe that introduced the issue. So maybe you want to check which plugins you have installed and if you still need them.
