### ISSUE TITLE
WSL2 localhost access is intermittent with stuck connections

### ISSUE THREAD

**Issue by benc-uk** [microsoft/WSL#4340]
**Please fill out the below information:**
* Your Windows build number: 10.0.18945.1001 (I am using WSL 2 mode)

* What you're doing and what's happening:  

Opening a URL served via a Node.js app using localhost, from a Windows browser results in page/URL never loading. It will spin indefinitely trying to load, rather than getting an error that site/page can not be found

Hitting stop and then refresh in browser will result in page loading OK
Page will continue to load OK, if you send requests to it quickly, if you wait a few seconds the problem will return and the URL and site will never load

I have verified the following:
    - It **only happens with Node.js**, I've tried Python, .NET Core and Golang web apps with out problem
    - **Problem only happens with localhost**, if I use the IP of `eth0` and access the app that way, I get no issues
    - It affects Node.js 8.x and 10.x, presumably other versions too
    - I've tried with Debian 9.7 and Ubuntu 18.04 distros and both have the same problem
    - It makes no difference what port I use
    - It makes no difference what browser is used (Edge, Chrome, Firefox)
    - It makes no difference if I use Node Express or the base http server package
    - Issue doesn't happen inside WSL when accessing the app with localhost using curl or wget

This seems to be a TCP socket issue with the way WSL 2 handles the new localhost bridging out to Windows

It is trivial to reproduce. Install Node.js and run the following simple server
```js
const http = require('http')
const requestHandler = (request, response) => {
  console.log(`### Request for ${request.url}`)
  response.end('<h1>Hello Node.js Server!</h1>')
}
const server = http.createServer(requestHandler)
server.listen(3000, '0.0.0.0', (err) => {
  if (err) return console.log('### Something bad happened', err)
  console.log(`### Server is listening on 3000`)
})
```

* What's wrong / what should be happening instead:
HTTP request /page should instantly load

* Strace of the failing command, if applicable:  
NA

* For WSL launch issues, please [collect detailed logs]
NA

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by benc-uk** [comment]
Here is a short screen capture illustrating what I am seeing

![](https://i.imgur.com/hjM9zvI.gif)

**Comment by benc-uk** [comment]
Confirmation this is a TCP keep alive issue

Setting the following
```
server.keepAliveTimeout = 0
```
As [described here](https://nodejs.org/api/http.html#http_server_timeout) resolves the issue

But this shouldn't be necessary

**Comment by mdragosv** [comment]
10.0.18945.1001 (I am using WSL 2 mode)
Same here

**Comment by benc-uk** [comment]
Phew thought I was going crazy! It's such a specific narrow problem...

I'm sure it's WSL 2 at fault here, as accessing over the WSL eth0 IP the problem goes away, so it's somehow related to whatever network trickery they use to get localhost working

**Comment by stkdev-ch** [comment]
Facing the same issue with apache.

Windows build : 10.0.18945.1001 with Ubuntu on WSL2 fresh install.

Accessing a website on localhost works only once in two. Like benc-uk with nodejs.

Turning off KeepAlive in apache conf resolve the issue.

**Comment by benc-uk** [comment]
Thanks  
I can also reproduce this, got the same problem with Apache/httpd. Good to know it's not just Node.js at fault here

Seeing the same "one request in every two" weird behavior

**Comment by benhillis** [comment]
Thanks for posting. I will dig into this.

**Comment by velosodigital** [comment]
I'm facing a similar issue, using NodeJs (v12.4.0) it only works once after that I get ERR_CONNECTION_REFUSED, the same in my Elixir(1.9.1)-Phoenix project.
Direct connection using the ip works just fine.

**Comment by benc-uk** [comment]
Just confirms it happens with Java Tomcat too

**Comment by karthikv** [comment]
I've been experiencing this issue with node.js servers as well. Thanks @benc-uk for mentioning the stopgap solution with `keepAliveTimeout`.

For those using `webpack-dev-server` who may find this issue, you can set the `keepAliveTimeout` in your webpack.config.js using the `devServer.before` hook, as shown below. Then your assets should be served without issue.

```ts
devServer: {
  before: function(app, server) {
    // We override the listen() function to set keepAliveTimeout.
    // See: https://github.com/microsoft/WSL/issues/4340
    // Original listen(): https://github.com/webpack/webpack-dev-server/blob/f80e2ae101e25985f0d7e3e9af36c307bfc163d2/lib/Server.js#L744
    const { listen } = server
    server.listen = function(...args) {
      const server = listen.call(this, ...args)
      server.keepAliveTimeout = 0
      return server
    }
  }
}
```

**Comment by velosodigital** [comment]
I'm not sure, but my problem has been softened with this:
sudo -i &&
 echo 200000 > /proc/sys/net/ipv4/tcp_keepalive_time &&
 echo 100 > /proc/sys/net/ipv4/tcp_keepalive_intvl &&
 echo 20 > /proc/sys/net/ipv4/tcp_keepalive_probes
In Elixir everything is working until react-apolo crash the connection somehow.

**Comment by benc-uk** [comment]
Thanks @karthikv 
I've used a similar workaround when serving directly in Express
```js
var server = require('http').createServer(app);
server.keepAliveTimeout = 0; // This is a workaround for WSL v2 issues
server.listen(port);
```
Which I'm using rather than the more normal `app.listen(port);`

I'd rather not have to workaround this in all my code, and I'm sure it has performance implications

**Comment by krushi123** [comment]
I am facing the same problem with rails application. Reloading problem. This keepaliveTimeOut is node specific. Anything that needs to be done for a rails app? I did try persistent_timeout 0 for puma configuration but not working.

**Comment by tomfakes** [comment]
> 
> I am facing the same problem with rails application. Reloading problem. This keepaliveTimeOut is node specific. Anything that needs to be done for a rails app? I did try persistent_timeout 0 for puma configuration but not working.

For Rails with Puma, I'm using the eth0 IP address without problem.  Localhost works for a few requests and then stops.  The IP address works pretty well so far.

**Comment by velosodigital** [comment]
@tomfakes, try this: https://github.com/shayne/wsl2-hacks
This one, install a service to update hosts file automatically: https://github.com/shayne/go-wsl2-host

**Comment by villasv** [comment]
@karthikv's suggestion did not work for me, though. Maybe there's something else related to the fact I'm using a named host.

test.dev -> 127.0.0.1 (on Windows etc/hosts) -> WSL IP (magic?) -> ??? WSL etc/hosts also contains test.dev mapping to 127.0.0.1

**Comment by velosodigital** [comment]
Any news on this thread?

**Comment by tomfakes** [comment]
I just upgraded to 18956 and my 'localhost' access from Windows to Ubuntu seems to be much more reliable so far

**Comment by xylinq** [comment]
I also updated to 18956, but didn't see any changes, this problem still exists.

**Comment by gaiadas** [comment]
Confirming the same issue using flask and docker-compose. Sporadic connection from localhost and interestingly no connection at all when I try 127.0.0.1. Both domains work fine on docker desktop.

**Comment by tomfakes** [comment]
I've mostly switched to using named hosts in the Windows hosts file.  This week I'm working on multiple cross-domain apps, so having a broken localhost actually works to my advantage.

But for short tests, localhost is more reliable this version than it was in 18950.

**Comment by montymole** [comment]
still breaks in 18956

**Comment by kabascolby** [comment]
same Issue with phpmyadmin weird when you manipulating data.

**Comment by coffenbacher** [comment]
This defeats the purpose of the localhost feature for me; in fact, it's even worse than not having it, since I wasted a lot of time reloading and then experimenting before finding this issue. So hopefully this gets a high priority, fixing it is **more** important than adding the initial feature was, at least for my use-case!

That said, `localhost` access is crucial overall, so I really hope this gets fixed rather than removed. Thanks to the WSL team for noting the need in the first place 😄

**Comment by dbroadhurst** [comment]
This is a critical issue. I can't even connect Studio3T to my docker MongoDB on localhost. Frustratingly my App ran for a while and then stopped. Using the VM IP works so I guess I could update my host's file but the IP can change so that's going leave me needing to keep updating the host's file. 

Got to say the overall developer experience when using VSCode is awesome, really can't wait until everything is working.

**Comment by jordaofranca** [comment]
It is happening to me with both webpack-dev-server and apache, after I updated to build 18956.

**Comment by benhillis** [comment]
I believe I have a fix for this.  Does somebody have a test app that I could use to validate this?  I've tried running nodejs servers and clicking refresh and that seems to be working great with my fix.

**Comment by benc-uk** [comment]
@benhillis Venerable old Apache httpd exhibits the behavior and is easy to test in Docker
```
docker run --rm -d -p 8080:80 -v "$PWD":/usr/local/apache2/htdocs/ httpd
```

**Comment by benhillis** [comment]
Thanks @benc-uk, my change seems to be working very well with httpd.  I'm hopeful this will resolve any issues... ETA for Insider build a few weeks.

**Comment by coffenbacher** [comment]
Awesome news @benhillis ! Thanks for working on this one. Beggars can't be choosers over here, but if there's any option for a expedited release, you can say at least one user is clamoring for it 😄 This is super annoying for my team on a daily basis. A few weeks is infinitely better than languishing forever though, so great work already.

**Comment by leofabri** [comment]
I'm facing the same problem as well. I didn't have much time to dig into it but always having to use the local machine IP is really annoying. 
##### I'm trying to serve Angular 8 apps through WSL2.
`$ ng serve`
##### The app is successfully compiled and I get this:
```** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **```

Unfortunately, if I visit _localhost:4200_ I just get a message telling me that the page is unreachable.
 I also tried to compile with a different `--host` (127.0.0.1, etc.) but the only one that's working is the address of **eth0**. 

I don't really understand why this happens with ng client. When I serve Docker containers or Go applications, localhost works great. 
Is there any known solution?

**Comment by jaspekang** [comment]
> Awesome news @benhillis ! Thanks for working on this one. Beggars can't be choosers over here, but if there's any option for a expedited release, you can say at least one user is clamoring for it 😄 This is super annoying for my team on a daily basis. A few weeks is infinitely better than languishing forever though, so great work already.

Count me in for clamoring :-D

**Comment by andresclari** [comment]
On 18963, the connection using direct vm IP on app.test address seems worse and slower.
Testing without that hack still doesn't work either.

**Comment by dbroadhurst** [comment]
@benhillis is it possible to send a message with the version number when the fix is released?

**Comment by leofabri** [comment]
Is my problem with Angular a common issue? Or did you guys get localhost up and running with ng-cli?

**Comment by benc-uk** [comment]
@leofabri It's a common issue with a many different services that serve HTTP requests, you basically won't get it working (well) with localhost until it's fixed. Using the eth0 IP is a workaround, e.g.
```
alias wsl-ip="ip addr show eth0 | grep \"inet 1\" | awk '{print \$2}' | cut -d/ -f1"
ng serve --host $(wsl-ip)
```
Hopefully in the next couple of Insiders builds this will be fixed and closed

**Comment by benc-uk** [comment]
Just updated to 18970 hoping it would be fixed. I spotted the WSL kernel version number got a bump to 4.19.59 so I was optimistic, however the problem is still happening
😢

**Comment by benhillis** [comment]
@benc-uk - A fix is on the way.

**Comment by dbroadhurst** [comment]
I get mixed results with most services but connecting to a MongoDB with localhost never works. Tried docker and installing on the host. VM IP works

mongodb://localhost:27017/my-db

**Comment by dsmaher** [comment]
I was having the same issue with `kubectl port-forward` ... sometimes it works, other times it doesn't.   Seems like it works until the port forward times out, and the next run of `kubectl port forward` doesn't work.  I found a workaround that will keep me going until the fix makes it's way to an Insider build... you can run:
```
wsl.exe --shutdown
```
and that will kill off the wsl kernel (and all shell instances attached to it).  When you restart your shell, everything works again.  It's annoying if you have several shell instances running and Docker Desktop WSL2 mode doesn't recover well, but it's workable until a fix lands.

**Comment by mmoskal** [comment]
Same thing here with 18970 and a node server. I set the keep alive timeout and also the /proc writes mentioned above. It works for a couple minutes, and then it stops. `wsl.exe --shutdown` helps for another couple minutes. This is with https://github.com/microsoft/pxt-arcade. @benhillis if you need someone internal to test let me know (`mimoskal@ms`).

**Comment by benhillis** [comment]
Build 18975 should improve this experience greatly.

**Comment by benc-uk** [comment]
Just tested on 18975 and my Node app is back to normal, removed my workaround code and all is good. Tried a Java Spring Boot app (Tomcat) and also no problems. Also repeated my Apache 2 test

All good! 😍

Thanks for fixing!

**Comment by tuananh** [comment]
I tested with Node and ruby. All works now. Thanks

**Comment by benc-uk** [comment]
I've checked localhost access on build 18980, and I'm not seeing any issues, still seems fixed to me 😃

**Comment by benhillis** [comment]
If you are still experiencing this on 18980 or later, please let us know some repro steps.

**Comment by tuananh** [comment]
> If you are still experiencing this on 18980 or later, please let us know some repro steps.

weird. i check again today and it's fine now. no code change whatsoever in my project.

**Comment by onomatopellan** [comment]
I think it's more about the number of entries in the Hosts file instead of the content.

This is a Windows hosts file for ad blocking: (more than 4000 entries)
https://pastebin.com/NmaBBmMa
output when launching WSL2: **"An existing connection was forcibly closed by the remote host."**

And this is same hosts file with 1000 entries instead:
https://pastebin.com/SvpjgTZP
output when launching WSL2:**"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."**

**Comment by thomasaull** [comment]
I checked again with a fresh installed distribution of Ubuntu 18.04 on WSL2. To reproduce:

Create a folder with an `index.php` with the following contents:
```
<?php echo "hello world"; ?>
```
install php with the following command:
```
sudo apt update
sudo apt install php7.2-cli
```
use the PHP Dev server like so to serve the index.php (inside the just created folder):
```
php -S 127.0.0.1:8000
```
Open Browser on `localhost:8000`. The site loads but the request never actually resolves (loading indicator keeps spinning forever). Interestingly though, if you open `http://localhost:8000/not-there.php` the php error page shows up, and the site loads normally.

**Comment by thomasaull** [comment]
Updated to 18985, issues is still there for me…

**Comment by stijnherreman** [comment]
I'm also seeing this issue on build 18985.1

Testing with `php -S 127.0.0.1:8000` and `<?php phpinfo(); ?>`, the entire page loads in my browser but the request never completes. Running `curl 127.0.0.1:8000/info.php` in wsl seems to work fine.

No issue when running with eth0, e.g. `php -S 172.30.112.116:8000`.

**Comment by stijnherreman** [comment]
@benhillis if you want, I can send Wireshark captures by email.

**Comment by jaykilleen** [comment]
Build 18985.1 been wrestling with rails becoming unresponsive via localhost. Found this thread. Glad it's not me! I have a windows update icon flashing at me so I'll try the next build and report back.

**Comment by jaykilleen** [comment]
18990.1 is still broken for rails development :( will double check to make sure it's not something I'm doing wrong. Also finding webpacker iis unable to create a `manifest.json` on a fresh install.

**Comment by FlipperPA** [comment]
I was having this issue at work with Django and localhost with `runserver`, but I am not having it at home. At home I'm on 18999.1. I'm going to check what version I'm on at work on Monday, but hopefully it is an early version and an upgrade fixes it.

Just in case, here's a minimal solid repro for a Django starter site:

```bash
sudo apt -y install python3-pip python3-venv git
python -m venv django_venv
. django_venv/bin/activate
pip install Django
django-admin startproject django_project
cd django_project
python manage.py runserver 0:8000
```

Then bring up http://localhost:8000/ in your browser and refresh a bunch of times over a few minutes.

**Comment by vasekboch** [comment]
This is still issue on build 18999. It causes various issues. For example Jetbrains PHPStorm has trouble with receiving data from Docker.

The issue seems to be related to the way how WSL2 (wslhost.exe) handles closed connections. Seems that when the connection in Linux is closed, the connection with wslhost.exe is stucks in Established state. 

The connections in Ubuntu (there is no active one)
![image](https://user-images.githubusercontent.com/1482932/66724151-bd13c900-ee22-11e9-942c-af6ae4f0c1de.png)

There is the established connection with Docker in Windows:
![image](https://user-images.githubusercontent.com/1482932/66724164-ea607700-ee22-11e9-988e-aeb419f18d4e.png)
Now the application is still waiting for some data, but the data never arrive, because the connection should be closed.

When i manually close the connection via TCPView, the application finished like it should at the begining.

**Comment by craigloewen-msft** [comment]
@FlipperPA I tried to repro your scenario by following your steps. I created the site and was able to connect to it. I tried refreshing about 50 times and each connection was successful. Could you try the update and see if that resolves your issue?

**Comment by vasekboch** [comment]
@craigloewen-msft I was able to reproduce it somehow with ```python -m SimpleHTTPServer 8000``` I tried two browsers old Edge and new chromium Edge.
- loaded page in old Edge.
- loaded page in new Edge
- refreshed page in old Edge
- spinner in old Edge stops spinning after the new Edge is refreshed.

**Comment by craigloewen-msft** [comment]
@vasekboch I was able to repro it with that workflow, thanks for sharing it! We'll dive into why this is happening.

**Comment by vasekboch** [comment]
@craigloewen-msft Cool, happy to help. I think, that its related to the way how wslhost.exe handles the connection. Seems that the connection stays in established state even after the connection in WSL is already closed. And when you make the second request the first established connection is closed and that is causing the spinner to stop spining. Or something similar to that. 
And some apps, that are sensitive to the fact, that the connection needs to be closed are broken. Aka the spinning spinner or my issue with PHPStorm, that I mentioned earlier.

**Comment by benc-uk** [comment]
Issue has definitely returned on 18999
It's the same flip / flop between the request working and failing, and if you make your requests quick enough (less than 5 secs apart) then the requests will work

The pattern is identical as it was before

**Comment by benhillis** [comment]
@benc-uk - I'm having a very hard time debugging this internally, i just cannot seem to get a repro.  "Refresh your web browser" is a difficult repro with a lot of variables.  Is there a targeted test that could be written so I can try to debug this further?

**Comment by vasekboch** [comment]
@benc-uk I was researching it a little bit more today. And I still don't have way how to reproduce it better. And now I think that the way that I described earlier is not correct. Because the python server is single threaded, and the chromium keeps the connection open. So that way the  And also the steps to reproduce are missing one key component. And that it works on direct IPv4 IP, and freezes on localhost. And I couldn't reproduce that. I tried switching python for (https://www.npmjs.com/package/http-server) and issue is not present.

I know that the bug still persists. Because PHPStorm's remote docker executor is broken and when I change the host from localhost to direct IP it works as expected. So there is something happening but I don't know what is it exacly. I think that it worked on 18970 or 18975, but I'm not sure which one. I will let you know, if I find something more.

**Comment by vasekboch** [comment]
@benhillis @craigloewen-msft Hey. I finally managed to replicate the bug in more controlled way (aka without browser). Actually it happened to me by a "happy" accident, but seems consistent. I have installed Docker on Ubuntu from the official repository. 

1) Run in WSL2 ```docker run --rm -it -p8080:8080 adminer:standalone```
2) In Windows ```curl 172.27.188.175:8080``` (use IP from WSL2 eth0 adapter)
3) In Windows ```curl localhost:8080```

The behaviour on my PC is following. 2) finishes without problem. 3) hangs and the end. Seems that the connection is not closed, but the data are returned correctly.

Hoping that this will finally help to nail this bug.

**Comment by benhillis** [comment]
@vasekboch - Thanks, I will give this a try today.

**Comment by vasekboch** [comment]
@benhillis For me It hangs on first request. See. https://1drv.ms/v/s!An2NRObJbs8nvYVtoVWv-wwyuh0FFA?e=kZco7j

**Comment by benhillis** [comment]
@vasekboch - thanks for the video, that's exactly what I'm doing locally and it is not hanging for me.  I did make a couple changes in this path recently, I will try on 19002 and see if I can get a repro there.

**Comment by vasekboch** [comment]
That seems promising. I've tested clean install of Fedora and the curl still hangs. My colleague has a same issue. So its not related only to my machine.

**Comment by benhillis** [comment]
@vasekboch - I have some great news.  I installed 19002 and was able to repro the issue, I then applied my fix to the build, and the issue goes away.  The fix should be in an insider build in a week or two.

**Comment by benhillis** [comment]
@vasekboch - Thank you very much for the targeted repro, that made things much easier.

**Comment by vasekboch** [comment]
@benhillis No problem. Happy to help. I'm glad that this one is fixed. It was pain to fill out every time new IP adress. 

Thank you for the fix. I check it a soon as it will go live. :)

**Comment by benhillis** [comment]
[19018](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-19018) should have the final fixes for this.

**Comment by FlipperPA** [comment]
@benhillis I've just upgraded to `19023` and this seems to be happening again. I run Django's `runserver` on port 8000 on Ubuntu 18. I had the intermittent problem, then it worked fine for a while, now it isn't working at all. I've tried several Windows reboots / restarts of Ubuntu.

If I go directly to the IP of the guest, `172.20.15.250`, it comes up.

A picture is worth a thousand words:

![image](https://user-images.githubusercontent.com/68164/68788879-47ae3a80-0612-11ea-9985-fb946721dc99.png)

**Comment by benhillis** [comment]
@FlipperPA - Could you give me a set of command line repro steps I could try?  Also would you mind taking a trace?

https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs

**Comment by stefankummer** [comment]
Well something weird for me on 19018.1.
Every first start of windows (after computer turned off), I am unable to access to http port (apache server started) via localhost, only via the IP of WSL2.
After restarting computer, I can access without restriction to localhost webserver.

**Comment by FlipperPA** [comment]
@benhillis @stefankummer I'll see if I can come up with a solid repro, but it is now working... which is especially weird, because I had tried restarting Ubuntu 18 and restarting all of Windows before posting above. I'll report back if I can get it to happen again!

**Comment by laem** [comment]
Serving files for me (express or http.server, doesn't matter) on 19030 is extremely slow on localhost (you can see images charging like with old 56k modems). 
When I use the eth0 ip, it's super fast.

**Comment by benc-uk** [comment]
Just updated to 19536 and this seems broken again
localhost simply not working, but using the WSL IP I get a connection

I thought we had this one nailed! :(

**Comment by benc-uk** [comment]
I think my latest issue is actually this https://github.com/microsoft/WSL/issues/4769

If I "reboot" WSL then then first connection/service binding works, all other services after the first don't work

**Comment by benhillis** [comment]
@benc-uk - fix is inbound.

**Comment by GameBurrow** [comment]
Seems like I have similar issue with apache docker on build 19041.21
When I had `127.0.0.1` on windows hosts only first response from server was gotten (index file, nothing else (js and css) got through). 

When I replaced that with the WSL IP, everything started working again.

**Comment by khuongduybui** [comment]
Port forwarding on build 19541.1000 (slow insider channel) is also broken.

**Comment by benc-uk** [comment]
Closing for now as #4769 has been closed

**Comment by Himakar-PV** [comment]
Hi,
I downloaded Microsoft Windows [Version 10.0.19592.1001] through insider (Fast)

It has vhost issue as explained below :

I have two projects

Laravel (var/www/html/laravel/..)
Pimcore (var/www/html/pimcore/..)
I have two configs under /etc/apache2/sites-available

laravel.dev.config
pimcore.dev.config
NOTE : Both are not enabled yet

In hosts file (/etc/hosts) I added below lines :
127.0.0.1 laravel.dev
127.0.0.1 pimcore.dev
::1 pimcore.dev
::1 laravel.dev

Now in browser when I type "localhost", it loads default Apache page.

Scenario 1 :
Run below commands
sudo a2ensite laravel.dev.config
sudo service apache2 restart
Type localhost in browser it loads Laravel project
Type laravel.dev in browser, loads nothing

Scenario 2 :
Run below commands
sudo a2dissite laravel.dev.config
sudo a2ensite pimcore.dev.config
sudo service apache2 restart
Type localhost in browser it loads pimcore project
Type pimcore.dev in browser, loads nothing

Scenario 3 :
Run below commands
sudo a2ensite pimcore.dev.config
sudo a2ensite laravel.dev.config
sudo service apavhe2 restart
Type localhost in browser it loads Laravel project
Type laravel.dev in browser, loads nothing
Type pimcore.dev in browser, loads nothing.
I wonder how localhost is loading one of the projects by default !!?
In scenario 3 if I enable pimcore.dev.config after laravel.dev.config then localhost is loading Laravel project instead of pimcore by default !!!

I am ready to screen share if anyone is ready to help.
Thank you.

**Comment by firrae** [comment]
I am also having this issue still. I tried stopping and restarting WSL like @khuongduybui mentioned and now it works with Rails. This always seems to happen after I shut down the computer and come back to it.

**Comment by GiancaDIFI** [comment]
I've been having this issue since I installed docker-desktop

**Comment by vasekboch** [comment]
@Himakar-PV Its not related to this issue. You need to setup your hosts in Windows `c:\Windows\System32\drivers\etc\hosts` Then it will work. AFAIK Apache select one active project as default. So thats why it loads something.

**Comment by fsoikin** [comment]
I see this issue too. 
Started happening since the last update to 22538. 
Rolling back to 22533 seems to have fixed it for now.

**Comment by fmiqbal** [comment]
> I see this issue too. Started happening since the last update to 22538. Rolling back to 22533 seems to have fixed it for now.

Same here on same version, happening on PHP (73, 74, 80) vanilla built-in webserver, bound to 127.0.0.1 or 0.0.0.0 port 8000 (or anything)

accessed via `127.0.0.1:8000`, the request will never finish, it load until it should be (I can load laravel project just fine) but the browser still show loading animation
accessed via WSL eth0 ip and it doesn't have this problem

**Comment by fsoikin** [comment]
@clovis1122 I have determined this is a bug in the latest version of WSL, the one available via the Microsoft Store.

But the good news is, an older version is available - the one bundled with Windows, - and it does not have this issue.

To install the bundled (aka "in-box") version, you need to (1) explicitly uninstall the Microsoft Store version, and then (2) `wsl --install --inbox`. 

You'll know you got the right version if it doesn't have a `--version` command:

```
>  wsl --version
Invalid command line option: --version
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]
...
```

**Comment by illepic** [comment]
Just noting that this is still an issue. 

```powershell
PS C:\WINDOWS\system32> wsl --version
WSL version: 1.1.0.0
Kernel version: 5.15.83.1
WSLg version: 1.0.48
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1194```

**Comment by khuongduybui** [comment]
Yes it just came back in the latest Windows update on Dev channel for me.

**Comment by illepic** [comment]
That's exactly what happened: the Dev channel Windows update this morning (January 30, 2023). I'm going to see if I can roll back that specific update until this resolves.

**Comment by pmartincic** [comment]
@illepic, @khuongduybui:
If you're experiencing problems on 1.1.0 please see issue #9508. This issue covers 1.0.3 and before.
