### ISSUE TITLE
HRM not working on WSL 2

### ISSUE THREAD

**Issue by marioidival** [microsoft/WSL#4417]
**Please fill out the below information:**
* Microsoft Windows [version 10.0.18956.1000]

* What you're doing and what's happening:  Development frontend technologies with HRM (Hot Reload Module)

* What's wrong / what should be happening instead: HRM not working on WSL 2  using `localhost`, but with `network ip` works.

This [issues](https://github.com/Microsoft/WSL/issues/2709) says that works.

**Comment by timmyd87** [comment]
+1 - Tried this with Vue and getting exactly the same result

**Comment by Biswa96** [comment]
Can you provide the steps to reproduce your issue?

**Comment by marioidival** [comment]
@Biswa96 
- I've tested with `vue`, but I belive that any HRM framework can reproduce this error
- create a app with these framework
- `npm run serve` and wait the server up
- open the browser with port that framework says
- edit the file page to the HRM can try reload the page.
- on localhost not works, but with `network ip` works.

**Comment by naeluh** [comment]
I am also experiencing this issue +1

**Comment by way-zer** [comment]
Maybe you can try this:
Access localhost ports from Windows(on https://github.com/shayne/wsl2-hacks)

**Comment by naeluh** [comment]
@way-zer I don't think its a port issue more so webpack-dev-server does not seem to be watching the files when I make a change the frontend does not rebuild. But the initial build works I can see it on port 3000. Its the rebuilding that does not happen but those hacks are pretty awesome.

**Comment by naeluh** [comment]
@way-zer although this looks like it might work

> **Increase `max_user_watches`**
> 
> If devtools are watching for file changes, the default is too low.
> 
> ```
> # /etc/rc.local runs as root by default
> # if you run these yourself add 'sudo' to the beginning of each command
> 
> sysctl -w fs.inotify.max_user_watches=524288
> ```
> 

I think I may try this tonight and I will report back here.

Thanks!

**Comment by swawrzyn** [comment]
> @way-zer although this looks like it might work
> 
> > **Increase `max_user_watches`**
> > If devtools are watching for file changes, the default is too low.
> > ```
> > # /etc/rc.local runs as root by default
> > # if you run these yourself add 'sudo' to the beginning of each command
> > 
> > sysctl -w fs.inotify.max_user_watches=524288
> > ```
> 
> I think I may try this tonight and I will report back here.
> 
> Thanks!

Thank you, this worked for me.

**Comment by naeluh** [comment]
@swawrzyn cool thanks for the update I have not had a chance to test this!
Ok I will try soon ! Thanks!

**Comment by naeluh** [comment]
@swawrzyn This only partially worked for me. Did your browser reload ? Mine did not ? Also what did you test it with ? I was testing a custom implementation of Webpack 4 and Hugo Static site generator. Thanks!

**Comment by craigloewen-msft** [comment]
Hi @marioidival I tried to reproduce this today and was able to see dynamic reloading on `localhost`. 

For clarity, here's what I did:
- Git cloned a [sample project](https://github.com/samuelayo/vue-spapt1) into my WSL distro
- Ran these commands to start it up:
``` 
npm install
npm run dev
```
- Loaded the page on localhost:8080
- Made changes to ./vue-spapt1/src/components/About.vue with vim and saw the changes load on the website without refreshing the page. 

So it seems like this has been fixed since build 18956 as there have been many improvements to localhost since then. Please try again and let us know if you run into the issue :) !

**Comment by mithunshanbhag** [comment]
I'm on WSL2 (build 18990) and still regularly encounter this issue with my angular projects (the `ng serve` command stops reacting to file changes). Unfortunately I don't have deterministic repro. 

I've tried increasing the max number of file watchers ([per VSCode's troubleshooting docs](https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc)) but that too hasn't helped.

FWIW, I have never encountered this issue on WSL1.

![image](https://user-images.githubusercontent.com/2327905/65823258-79409180-e270-11e9-98b0-1f8830a2ddd0.png)

**Comment by Tatamethues** [comment]
After increasing the max_user_watches,  HRM still not working. I need to refresh the page manually

**Comment by craigloewen-msft** [comment]
@Tatamethues can you share a project or detailed repro steps for us to reproduce this issue? I'm not able to reproduce it on any of the vue apps I'm running.

**Comment by Tatamethues** [comment]
@craigloewen-msft I tried both angular,that created by angular cli, and react next.js projects.

**Comment by naeluh** [comment]
@craigloewen-msft I have build 18990 installed I will test my apps tonight. But one question are you suggesting that increasing `max_user_watches`  would *not* be needed in build 18990 or greater or we need that also ? Thanks for your help!

**Comment by craigloewen-msft** [comment]
I tried to repro this again using [this sample calculator React project](https://github.com/ahfarmer/calculator) but was unable to do so. It was able to reload live without any issues.

If you're experiencing this issue please make sure that you are running inside of your Linux root file system. If you still find that your page is not auto updating then please post a sample solution that we can try and repro the problem on, thank you!

**Comment by naeluh** [comment]
@craigloewen-msft so If I run anything inside of /mnt/ it wont work ? thanks!

**Comment by naeluh** [comment]
Ok thank you! @craigloewen-msft I can see now that the idea is separating the operating systems completely. If I am using the vscode following the steps here =>https://code.visualstudio.com/blogs/2019/09/03/wsl2

I am able to edit and reloading works. I think the key item I did not understand is that I am not able to really use my files in /mnt in the same way.

I don't know if that was totally clear that was the case. Anyways I moved everything into /var/www and it all started working again. Thanks everyone for the help!

**Comment by naeluh** [comment]
@craigloewen-msft sorry one other question is there documentation that talks about this somewhere ? Where once cannot use the windows file system anymore or at least not in the same way ? Thanks again!!

**Comment by craigloewen-msft** [comment]
Yes we have this documentation page: [UX Changes between WSL 1 and WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes) with the exact goal of documenting these changes. I'll add in a note there about the fact that inotify events (which power live reloading) are not tracked in WSL 2 in your Windows drive file system. :)

**Comment by naeluh** [comment]
Awesome @craigloewen-msft thank you!

**Comment by craigloewen-msft** [comment]
I'll close this issue out, as it's contingent on the feature ask to add file watching to the Plan9 server which we are tracking here: https://github.com/microsoft/WSL/issues/4064. I'll also take it as an action item to add a quick note to the WSL2 docs about the UX change between WSL 1 and WSL 2 on this.

If you're experiencing this issue please place your files in the Linux root file system and run from there, if you are still experiencing this issue after that then please feel free to comment here or reopen. Thank you! :)

**Comment by dzegarra** [comment]
Nothing I tried worked. Finally, I decided to move my project files away from the windows file system into my Linux home directory. Wow, what a difference. Not only the file watchers started to work. The compilation speed was increased drastically (we are talking about from 1m to 5sec for `npm start`).

**Comment by nake89** [comment]
@dzegarra How are you modifying the files if they are in the linux directory?

**Comment by dzegarra** [comment]
@nake89 manually from the bash terminal or using VSCode with the [Remote Development](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) extension.

**Comment by nake89** [comment]
@dzegarra The Remote Development extension worked perfectly! I hope other people see this thread and see this solution!

**Comment by jinxmcg** [comment]
I encountered this issue when editing files which are located in the mounted folders /mnt/c/... regardless from where I edit the files (wls or windows). It does not detect the file change.

When working in /home or local folder if I edit the file it works.

**Comment by zenojunior** [comment]
I solved my problem when I moved the project into linux directory!

**Comment by djma777** [comment]
I cloned my repo into my linux directory, but hrm still isn't working...

**Comment by shogs** [comment]
Why is this issue closed?

The only thing that solved it for me too was to move the project into a linux path and not sitting in my windows home path. I did also set the max_user_watches but that didn't have any affect with HMR, moving to linux ~ (home) directory and running from there fixed it.

This is not a good solution given the benefits of WSL2, defeats the point of it all, for me anyways.

Ideally i should be able to store my project folders in my windows home folder and use linux for development and running of my services. I can then upgrade my linux distro, change distro even and not have to worry about losing my project files or re-cloning.

**Comment by shogs** [comment]
Upon further digging through issues I found the following two open issues that are related, I'll be looking at them more thoroughly later when I get time but thought I'll link them here incase others get to this issue regarding HRM not working on WSL2.

#4739 [WSL2] File changes made by Windows apps on Windows filesystem don't trigger notifications for Linux apps
#4064 File contents differs on mounted Windows drive between Windows and WSL

**Comment by pimjansen** [comment]
Why is this issue closed? Over here it is also not working. Just a basic react app running on `/mnt/d/my-repo`

When start `npm start` auto-reload is not working by a file changed trigger

**Comment by therealkenc** [comment]
> Why is this issue closed?

Here [we're](https://github.com/microsoft/WSL/issues/4417#issuecomment-540676694) speculating the issue is /dupe #4064 (or better #4739). [This one never actually made it out of need-repro.]

**Comment by viltiki813196** [comment]
The [Create-React-App HRM troubleshooting documentation](https://github.com/facebook/create-react-app/issues/659) needs to be updated to cover the problem with the current state of WSL 2.
I spent hours across a week trying to figure out what was wrong based on the current React documentations to finally discover just now that it is an issue that isn't mentioned in the react repos. It was a problem with WSL2 app / WIN10 filesystem integration all along.

**Comment by ronald-hristov** [comment]
Using the [linux filesystem](https://docs.microsoft.com/en-us/windows/wsl/compare-versions#use-the-linux-file-system-for-faster-performance) and developing through the wsl network location - \\wsl$ works best for me.

**Comment by philippeaellig** [comment]
if you are using webpack-dev-server and wsl2, changes in windows do not trigger the dev-server. but you can use the --watch-poll option.
"--watch-poll makes sure that webpack can detect changes in your files. By default, webpack listens to events triggered by the filesystem, but VirtualBox has many problems with this." see https://webpack.js.org/guides/development-vagrant/
the webpack guide is about vagrant with virtualbox. but this option work for the wsl2-problem too.

**Comment by lizy0329** [comment]
> @nake89 manually from the bash terminal or using VSCode with the [Remote Development](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) extension. The 2nd option is my preferred.

But you can't use some three-part tools like: GetKraken

**Comment by fandok** [comment]
Hi, i also happened to come across with this issue but with create-next-app.
The solution that i take is to change the wsl to wsl 1 version using commands from https://docs.microsoft.com/en-us/windows/wsl/install-win10#set-your-distribution-version-to-wsl-1-or-wsl-2

Hope this helps in case anyone come across this same issues

**Comment by lizy0329** [comment]
> if you are using webpack-dev-server and wsl2, changes in windows do not trigger the dev-server. but you can use the --watch-poll option.
> "--watch-poll makes sure that webpack can detect changes in your files. By default, webpack listens to events triggered by the filesystem, but VirtualBox has many problems with this." see https://webpack.js.org/guides/development-vagrant/
> the webpack guide is about vagrant with virtualbox. but this option work for the wsl2-problem too.

This issus will be fix?

**Comment by philippeaellig** [comment]
> > if you are using webpack-dev-server and wsl2, changes in windows do not trigger the dev-server. but you can use the --watch-poll option.
> > "--watch-poll makes sure that webpack can detect changes in your files. By default, webpack listens to events triggered by the filesystem, but VirtualBox has many problems with this." see https://webpack.js.org/guides/development-vagrant/
> > the webpack guide is about vagrant with virtualbox. but this option work for the wsl2-problem too.
> 
> This issus will be fix?

No. This is just a workaround.

**Comment by lizy0329** [comment]
> > > if you are using webpack-dev-server and wsl2, changes in windows do not trigger the dev-server. but you can use the --watch-poll option.
> > > "--watch-poll makes sure that webpack can detect changes in your files. By default, webpack listens to events triggered by the filesystem, but VirtualBox has many problems with this." see https://webpack.js.org/guides/development-vagrant/
> > > the webpack guide is about vagrant with virtualbox. but this option work for the wsl2-problem too.
> > 
> > 
> > This issus will be fix?
> 
> No. This is just a workaround.

For now，Is the WSL team aware of this problem and starting to fix it?

**Comment by filippzaripov** [comment]
Facing the same issue with React using docker on WSL engine. Just switched back to nonWSL engine and it works fine now.
Quick workaround if WSL is not so important for your docker app

**Comment by chloesun** [comment]
Experienced the same issue, and [this](https://github.com/facebook/create-react-app/issues/10253#issuecomment-747970009) works for me. 
just change your start script in the `package.json` to
`{ ... "start": "CHOKIDAR_USEPOLLING=true react-scripts start" ... }`

**Comment by wintercounter** [comment]
That's a workaround only. It's falling back to polling instead of using native file system events, causing 80% constant CPU usage.

**Comment by akhar** [comment]
> causing 80% constant CPU usage.
Try to reduce polling interval by `CHOKIDAR_INTERVAL=1000`

**Comment by AhmadAbualkhail** [comment]
I moved my repos to WSL path and all working fine 
\\wsl$\Ubuntu-20.04\home\Username\test

**Comment by matiaslauriti** [comment]
Only @chloesun shared the solution that worked for me... so I am going to write it more straightforward:

Try adding a `.env` with `CHOKIDAR_USEPOLLING=true` on it, this fixed it for me, because I am not storing the files inside `WSL` but in a different disk on Windows (`/mnt/d/`)...

**Comment by wintercounter** [comment]
Using polling is not a solution, just a workaround as I previously
mentioned. Without WSL Docker already solves this by forwarding native
events (it was dixed not so long ago after years of waiting). The same
should be done here.

**Comment by harisraharjo** [comment]
not working if you want to use https=true yarn start

**Comment by winzaa123** [comment]
> Only @chloesun shared the solution that worked for me... so I am going to write it more straightforward:
> 
> Try adding a `.env` with `CHOKIDAR_USEPOLLING=true` on it, this fixed it for me, because I am not storing the files inside `WSL` but in a different disk on Windows (`/mnt/d/`)...

this great 👍

**Comment by rajjeet** [comment]
> I moved my repos to WSL path and all working fine
> \wsl$\Ubuntu-20.04\home\Username\test

This has other issues.  Syncing and indexing will be very slow of intellij products.

**Comment by mdirshaddev** [comment]
> I moved my repos to WSL path and all working fine
> \wsl$\Ubuntu-20.04\home\Username\test

I was facing the same issue but now I am free from all these problems.

**Comment by paganjoshua** [comment]
none of these options work for me, I always see people suggesting moving the repo to the wsl path, but even projects made from scratch in my linux home dont work. Love wsl2 but man this sucks

**Comment by mdirshaddev** [comment]
> none of these options work for me, I always see people suggesting moving the repo to the wsl path, but even projects made from scratch in my linux home dont work. Love wsl2 but man this sucks

That's weird but I was facing the same issue for more than 2 months. Then I tried to move my files to wsl filesystem folder I.e., now my project resides in */home* of wsl directory and there seems to be working fine. I have heard about this issue why happening because we are trying to use multiple filesystem what I mean is that using windows filesystem in Linux. We should use Linux filesystem if we are working in our project.

**Comment by matiaslauriti** [comment]
What if I want an instant backup of it ? (disregard GIT or any other VCS). I use other hard drive and though `/mnt` I use that hard drive... This should be seamlessly and it is not...

**Comment by craigloewen-msft** [comment]
@paganjoshua please try the sample project that I listed in this comment and see if it works for you: https://github.com/microsoft/WSL/issues/4417#issuecomment-536131575 

We have verified on the team that when projects are in the Linux file system that hot refresh will work. If it doesn't work for you I would recommend you update to the latest Windows version and if it still doesn't work please could you file a bug on this repo? Thanks!

**Comment by paganjoshua** [comment]
@craigloewen-msft thanks for the sample, tested it out and worked perfectly which left me stumped for a couple days. Turns out the problem was with the version of the module bundler I was using, which had a recently documented bug I'd never encountered so after I tried my usual tricks with the bundler I jumped to conclusions about it being WSL, my apologies!

Really excited this is working as expected and that I ended up being at fault, this is a really cool project!

**Comment by dejayc** [comment]
I'm able to still reproduce this issue in build 19041 using the example Vue repro above.

**Comment by Tofandel** [comment]
@craigloewen-msft Yes but is there a way to get it to work on the Windows file system? Kinda sucks to have to downgrade to WSL1 which then prevents WSL git from working.. I'm gonna start pulling my hair out..

**Comment by wintercounter** [comment]
This is incredibly annoying, and forces many of us to use Docker with legacy Hyper-V base... There are multiple reasons not to store our files in the Linux mount, but that makes environments with file watchers completely unusable.

**Comment by itsjerryho** [comment]
Using WSL2 and faced the same issue of Hot Reloading not working for Create React App. Tried all sorts of methods and the only way that worked for me was to shift the app folder into the WSL path.

Honestly quite disappointed with WSL2...

**Comment by zmbq** [comment]
Faced the same issue with `webpack --watch`. I do not want to move the sources to a WSL only path. My workaround was to run webpack from Windows instead of WSL.

**Comment by chaderenyore** [comment]
Mine is not working at all, used vue cli and it was extremely slow to even start the server. when server even started, I will make a change but it won't reload. I reloaded manually without seeing the change.

**Comment by 7flash** [comment]
> Mine is not working at all, used vue cli and it was extremely slow to even start the server. when server even started, I will make a change but it won't reload. I reloaded manually without seeing the change.

same here https://github.com/withastro/astro/issues/2728

**Comment by rboddy** [comment]
2023 and I hate to necro this, but WSL2 on windows 11 is currently unable to HMR with Sveltekit. Any possibility of a long term fix on this?

**Comment by wintercounter** [comment]
I while ago I had enough and decided to just keep my files inside WSL to make watchers work. Since then I don't have any issues. I've also set up automated syncing of my files back to Windows, just in case the VHD image gets corrupted for whatever reason (happened before), I keep everything in Git also, so whatever, staying redundant as much as possible :D

**Comment by shallow-beach** [comment]
just to reiterate, using --watch-options-poll in my 'webpack serve' line fixed this for me.
