### ISSUE TITLE
WSL --import returns Unspecified error

### ISSUE THREAD

**Issue by yphillip** [microsoft/WSL#4735]
I had to get my computer replaced because of a hardware problem, and I backed up my wsl distro in preparation for moving it to the new computer. When I copy the tar file over to the new computer and try wsl --import, I get an Unspecified error.

**Windows version / build number**

Both computers: Windows [Version 10.0.18362.476]

**Steps required to reproduce**

On the old computer:
`wsl --export Ubuntu ubuntu_backup_2019_12_04.tar`

On the new computer:
Enable WSL (Enable developer mode, turn on WSL in Windows Features)
`wsl --import Ubuntu C:\Users\yphillip\AppData\Local\Packages\Ubuntu C:\Users\yphillip\wsl_backup\2019_12_04\ubuntu_backup_2019_12_04.tar`
The only output I get from this is `Unspecified error.`

The tar file is about 16 GB, and I have no problems sharing it if it might help someone debug my problem. Just let me know. Hoping I can salvage my old setup so I don't have to re-setup everything from scratch on the new computer.

**Comment by therealkenc** [comment]
Not a fan of the `unspecified error` myself.

Practical suggestion is to install a fresh distro on your new box. Unpack your tarball there. Cherry pick the stuff you care about, notably your `/home`. Then `apt install` your favorite stuff.

**Comment by yphillip** [comment]
Yeah makes sense, thanks. I've given up on trying to get `wsl --import` to work (tried Powershell vs cmd, admin vs without admin, all with the same result).

**Comment by dleslie** [comment]
Please re-open; the underlying issue persists.

How to reproduce:

1. Have a distribution installed
2. Export said distribution
3. Unregister said distribution
4. Import the exported tar with the same name and destination as the original distribution
5. Witness the _Unspecified Error_

**Comment by dleslie** [comment]
Enabling/Disabling the WSL feature doesn't even fix it. Some state is corrupted that doesn't get reset on removal of WSL.

**Comment by Congee** [comment]
if --import is not supposed to work reliably, what's the point of using it? I have a 56GB tar ball. sigh

**Comment by yuis-ice** [comment]
same issue here.

**Comment by antonymarion** [comment]
same error.

Could you please re-open the issue ?

Thks

**Comment by jbdamiano** [comment]
Same issue here. 
The import failed

**Comment by 4iter4life** [comment]
same issue here!
I understand that wsl2 is in preview.. but why is it so difficult to export just the vhd for wsl2 to make it migratable to new hardware?

**Comment by realKennyStrawn93** [comment]
Same issue. There was absolutely no reason to close this.

**Comment by jozefizso** [comment]
`wsl --import` does not work for me on Windows 10 (release 10.0.19041.207)

**Comment by torvnen** [comment]
Had this same issue after exporting/importing a fairly new Ubuntu 18.04, with a Windows reset in between. 

**Fixed the issue** by importing(installing) the distribution with [LxRunOffline](https://github.com/DDoSolitary/LxRunOffline).

**Comment by Ron2014** [comment]
Same error.

I'v tried many versions of backups. 
If the size of imported file ---- `ext4.vhdx` is under 8G (mine is 7,829,504KB) can work.

Check this out.

Ron

**Comment by hbhbts** [comment]
Same issue.
Is there some update about the bug?

**Comment by therealkenc** [comment]
Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here.

**Comment by nijave** [comment]
You may be able to solve this yourself... Follow the instructions here to start logging
https://github.com/microsoft/WSL/blob/2cb110aba644d0bb3ff8d6445448d4e08e11df78/CONTRIBUTING.md#8-detailed-logs

While logman is running, try the import and wait for it to fail
Stop logman and open the .etl files. I had Windows Performance Analyzer already installed https://docs.microsoft.com/en-us/windows-hardware/test/wpt/windows-performance-analyzer
I opened `lxcore_service.etl` since it was the biggest--figured there might be something useful

I doubled-clicked the tile in the top left where it says "Generic Events" and was able to get a trace that seems to indicate my particular issue
![image](https://user-images.githubusercontent.com/384474/95923920-86012c00-0d84-11eb-84cb-6ef948ef3bdb.png)

This rootfs I generated from the Fedora Live CD rootfs.img using guestfish with xattrs:true so I suppose that did it. Afaik Fedora uses xfs and WSL appears to use ext4 so that may also be related

**Comment by nijave** [comment]
Actually to reproduce this shouldn't be too terribly difficult...

I downloaded the Fedora Workstation iso and extracted the squashfs. From that, I extract rootfs.img. I opened that with guestfish and did `tar-out-opts / rootfs.tar xattrs:true selinux:true acls:true`

**Comment by jbarrella** [comment]
Had the same issue. I exported 2 WSL2 distros and then did a clean install of my Windows OS. "Unspecified error" came up when I tried to import them.

I fixed it by downloading the Linux kernel update package referred to at https://docs.microsoft.com/en-us/windows/wsl/install-win10 and then running the command `wsl --set-default-version 2`.

After this, my 2 distros imported without error.

**Comment by RSpliet** [comment]
@jbarrella Thanks for those hints, this did the trick for me too.

It must be something in the air (perhaps COVID), but I strongly feel like trying to make a point. 16 years ago I abandoned Windows XP in favour of Red Hat 9. My primary motivation back then was that I found it impossible to debug all the random problems that you can encounter: poor error messages, obscure logs, condescending "please contact your administrator" dialogues. Don't get me wrong, Linux back then had many many flaws and shortcomings, but it treated me maturely with log files and descriptive error messages in predictable places. 16 years later and situations like these make me feel like little has improved in Windows-land. I appreciate that errors happen everywhere, but please give me the necessary information and tools to solve them on my own rather than leaving me guessing and trying 20 random seemingly-unrelated things I find off the internet.

**Comment by nijave** [comment]
> @jbarrella Thanks for those hints, this did the trick for me too.
> 
> It must be something in the air (perhaps COVID), but I strongly feel like trying to make a point. 16 years ago I abandoned Windows XP in favour of Red Hat 9. My primary motivation back then was that I found it impossible to debug all the random problems that you can encounter: poor error messages, obscure logs, condescending "please contact your administrator" dialogues. Don't get me wrong, Linux back then had many many flaws and shortcomings, but it treated me maturely with log files and descriptive error messages in predictable places. 16 years later and situations like these make me feel like little has improved in Windows-land. "Unspecified error" is next-to-useless.
> Obviously this is not all the WSL devs' fault (so don't take it personal!), but it is something that genuinely puts me off from trying to use software. I appreciate that errors happen everywhere, but please give me the necessary information and tools to solve them on my own rather than leaving me guessing and trying one after the other random seemingly-unrelated thing I find off the internet.

See my comment above--you can use Windows Performance Analyzer https://github.com/microsoft/WSL/issues/4735#issuecomment-708050588

Usually the hex looking `0x00000000` error messages can be looked up in the DLL concerning the functionality although I don't remember off the top of my head

**Comment by mslinn** [comment]
Very unhappy with this problem. I tried @jbarrella's workaround but "Unspecified error" came back. Seriously, Microsoft, you need to do better than this lame error message!

**Comment by timkscripts** [comment]
After creating the wslconfig file in my $HOME directory and also checking '/etc/wsl.conf.' inside the TAR file to be sure of no conflicts, setting my RAM etc did not resolve the 'unspecified error' issue.
Using logman.exe as noted above didn't populate my etl files either.
I have tried every solution in this thread and a few other threads.
It turns out I opened my .tar file with 7-zip and it said it was corrupted with no end-of-file.
I extracted the TAR and it extracted with 1 error.
Data error in ".\version-pack-data\...\docker\...\diff\binaries\crictl" File is broken.

Unfortunately, re-taring my broken .tar does import after doing wsl --import again, however it does not boot when calling WSL. so its broken.
I already unregistered the image after exporting it thinking it was backed up. And I do not see it anymore under the /local/ folders.
So, I think I lost my image. I guess its good to learn this lesson early on that if something zips or tars, check it somehow.

**Comment by teenphly** [comment]
> Had this same issue after exporting/importing a fairly new Ubuntu 18.04, with a Windows reset in between.
> 
> **Fixed the issue** by importing(installing) the distribution with [LxRunOffline](https://github.com/DDoSolitary/LxRunOffline).

Thank you so much! This is the only fix in my case.
running `LxRunOffline.exe install -n <distro name> -d <installation directory> -f <full path to the tarball>` in powershell did the magic.

Afterwards, `Ubuntu1804.exe(your distro) config --default-user <user name>` sets the right user.

**Comment by jiceorange** [comment]
> Not a fan of the `unspecified error` myself.
> 
> Practical suggestion is to install a fresh distro on your new box. Unpack your tarball there. Cherry pick the stuff you care about, notably your `/home`. Then `apt install` your favorite stuff.

I'm also seeing "unspecified". Can you be a bit more detailed about the cherry pick process? Do you mean to hand copy the files into the newly installed distro? What's a safe way to do that that preserves ownership and permissions?

**Comment by jiceorange** [comment]
> > Not a fan of the `unspecified error` myself.
> > Practical suggestion is to install a fresh distro on your new box. Unpack your tarball there. Cherry pick the stuff you care about, notably your `/home`. Then `apt install` your favorite stuff.

Oh, you mean unpack it inside of the the newly created distro.  Got it.

**Comment by JackHunt** [comment]
I can confirm that the issue shows with a Gentoo stage3 tarball.

**Comment by Yogurt4** [comment]
Having the same problem. Tried all tips, including the ones at the similar [issue #4835](https://github.com/microsoft/WSL/issues/4835).

When I did a logging session, WPA showed me that the import failed at one of the ./isocache/...iso files. "Truncated tar archive". However, I could untar the file perfectly.

It seems the problem lays somewhere at the 8 GB working memory limit. My .tar is 7.7 GB, the total file size is 8.4 GB.
wsl --import starts to eat memory then suddenly releases all when ~8 GB is reached, and prints the error message.

So I've removed one file from the .tar (to decrease the total file size under 8 GB). Voila! Now it worked. And I added the removed file manually to the new data root.

**Comment by Kif11** [comment]
My 25GB tar fails with this error aprox. after unpacking 29GB.

**Comment by DepressedDoomer** [comment]
Hi there
So I have no idea if my contribution will help anyone but it worked for me.

### Solution 1:
The easiest way do get your wsl installed is to use wsldl.
It's really cool and easy to install.
They have many distros which you can choose from.

**Link:**
https://wsldl-pg.github.io/docs/Using-wsldl/

### Solution 2:
If your distro isn't included in the wsldl collection you have to do it the hard way.

**Step 1.**
Follow the ubuntu wsl tutorial to get ready for the next step.
(You have to scroll down to find the tutorial)

**Link:**
https://ubuntu.com/wsl

**Step 2.**
After that you have to install docker desktop.
Check if the "Install required Windows components for WSL 2" is enabled.

<img width="527" alt="Screenshot 2021-08-15 191943" src="https://user-images.githubusercontent.com/78982032/129486819-686403da-c9f1-448e-93fb-967315c47bb9.png">

Press "OK" and wait until the installation is finished.
After that press "Close".

**Link:**
https://www.docker.com/products/docker-desktop

**Step 3.**
Lets open "Docker Desktop" and skip the tutorial.
After that check if ubuntu is the default wsl.
To do that open a powershell terminal and paste the following command.

> wsl -l

If ubuntu is not the default wsl change that with the following command.

> wsl --set-default ubuntu

Now restart your pc to get ready for the next step.

**Step 4.**
So lets check if everything worked well.
Paste  the following command into a ubuntu terminal.

> docker --help

Now a list with commands should be appeared.

**Step 5.**
Now you are ready to obtain a tar file of a distro.
In this tutorial you try it with alpine linux.

To achieve that past the following command into a ubuntu terminal.

> docker run -t alpine bash ls /

Then open "Docker Desktop" and go to "Containers / Apps".
Try to run the container.

<img width="947" alt="Screenshot 2021-08-15 195639" src="https://user-images.githubusercontent.com/78982032/129487845-1870bf35-a5b8-4639-8871-a54fb534f3b5.png">

If no error appears you can skip this part.

<img width="949" alt="Screenshot 2021-08-15 195846" src="https://user-images.githubusercontent.com/78982032/129487891-509190fe-8693-48f7-a192-3ab9e37b65a4.png">

So in a case of an error delete the container.

<img width="950" alt="Screenshot 2021-08-15 200110" src="https://user-images.githubusercontent.com/78982032/129487939-ed308b3f-8985-4793-90e8-2c03b62e8272.png">

And now go to "Images" and try to run that.

<img width="947" alt="Screenshot 2021-08-15 200300" src="https://user-images.githubusercontent.com/78982032/129487982-6916e93c-3ba5-4178-b33d-bc089aced40d.png">

If the icon of the container is green you can stop the process.

<img width="949" alt="Screenshot 2021-08-15 200501" src="https://user-images.githubusercontent.com/78982032/129488062-59980fc7-c3c7-4f17-a03d-9d73bceb692b.png">

Now lets go back to the ubuntu terminal and paste the following command.

> dockerContainerID=$(docker container ls -a | grep -i alpine | awk '{print $1}')

After that create a folder with the name "temp" on your c drive.
When you are finished pasted the following command into the ubuntu terminal.

> docker export $dockerContainerID > /mnt/c/temp/alpine.tar

If everything worked a new "alpine.tar" file should be appeared in your "temp" folder.

**Step 6.**
Now lets add the tar file to wsl.
To do that open a powershell terminal and move to the "temp" folder.

> cd C:\temp

After that we use the following command to add our tar file to wsl.

> wsl --import Alpine ./ ./alpine.tar

If no error appears you have successfully added the distro to wsl.
To check that paste following command into the powershell terminal.

> wsl -l

To start the distro paste following command.

> wsl -d Alpine

I hope this tutorial will help.

**Comment by haosmos** [comment]
Exactly the same error: My .tar file weighs 12.7 gb. When the unpacking reaches 13.8gb, the following error occurs: [Unspecified error](url)

I applied different memory limit values in .wslconfig: 8gb, 10gb, 16gb, 22gb - nothing works. I have 32gb of RAM and there is a lot of free RAM left when unpacking the archive. But every time unpacking reaches about 13.8gb an [Unspecified error](url) is thrown.

**Comment by MiloDC** [comment]
Note that exporting the container to an archive (i.e. `docker export`) has to be done from a regular command prompt, **NOT** a Powershell prompt.  Performing that step from a Powershell prompt will result in the corruption of the archive file.

**Comment by ricardoboss** [comment]
I got the same error. To get my WSL back somehow, I used [DDoSolitary/LxRunOffline](https://github.com/DDoSolitary/LxRunOffline) to install it. I didn't specify a version and it actually managed to restore the file system in version 1 (so no `.vdhx` yet). Then I was able to get WSL to update this WSL instance to version 2. This time, I got a specific error message about some hard links not being available. After I went into the `rootfs` of the version 1 WSL and deleted said files and folders manually from the Explorer, I tried it again; and voilà! My WSL successfully updated to version two and instead of the rootfs living on NTFS I now got my `ext4.vdhx` on the correct drive.

**Comment by MiloDC** [comment]
In case anyone cares, I see this problem of a corrupted .TAR file only when I export a container (`docker export`) from Powershell.

When I export from a regular command prompt, it's fine.

**Comment by hluengas** [comment]
> In case anyone cares, I see this problem of a corrupted .TAR file only when I export a container (`docker export`) from PowerShell.
> 
> When I export from a regular command prompt, it's fine.

This fixed it for me! 

Importing WSL in powershell... getting unspecified error...
tried doing the docker export with CMD instead of powershell, now the import works perfectly!

**Comment by ruby-rust-perl** [comment]
I have the same problem while trying to use Gentoo Stage 3 Tarball 

Change all the extensions to `.etl`
I started logging and ran the command 
```
wsl --import Gentoo C:\Users\quant\AppData\Local\WSL\Gentoo\ .\stage3-amd64-openrc-20220130T170547Z.tar.xz --version 2
```

[lxcore_service.txt](https://github.com/microsoft/WSL/files/8000661/lxcore_service.txt)
[lxcore_user.txt](https://github.com/microsoft/WSL/files/8000662/lxcore_user.txt)

[lxcore_kernel.txt](https://github.com/microsoft/WSL/files/8000660/lxcore_kernel.txt)
l

**Comment by moyans** [comment]
**wsl --import Ubuntu-20.04 D:\wsl2_ubuntu\wsl2tar\Ubuntu-20.04.tar --version 2 failed**

Please run in the current directory
cd D:\wsl2_ubuntu\wsl2tar\ 
wsl --import Ubuntu-20.04 ./ .\Ubuntu-20.04.tar

**Comment by ruby-rust-perl** [comment]
@moyans This didn't work either. The issue still exists

**Comment by moyans** [comment]
> @moyans This didn't work either. The issue still exists

add memory and swap in .wslconfig 
<img width="275" alt="image" src="https://user-images.githubusercontent.com/13639445/154000788-be394fff-f168-463f-8749-2ed6a17c68cb.png">

I tried these two schemes and finally succeeded.

**Comment by ruby-rust-perl** [comment]
I solved this problem by doing this (for Gentoo)
1. Extracted `.tar.xz` file to get the actual `.tar` file
2. Imported using `wsl --import Gentoo path\to\Gentoo\WSL\storage path\to\the\tar\file`

Now, no errors

**Comment by adrndev** [comment]
In my case it works while changing from:
`wsl --import Ubuntu "C:\Users\{userName}" fileName.tar`
to:
`wsl --import Ubuntu "C:\Users\{userName}" .\fileName.tar`

**Comment by hakumcentral** [comment]
**Unspecified error wins**
Nothing above worked for me, I think I lost everything I had configured in my wsl instance. I have the TAR, and it is not corrupted, I tried to get logs during the process but after following https://github.com/microsoft/WSL/blob/2cb110aba644d0bb3ff8d6445448d4e08e11df78/CONTRIBUTING.md#8-detailed-logs the files 
```
lxcore_kernel.etl
lxcore_service.etl
lxcore_user.etl
```
never been filled. 

Seems there is a problem with the vdhx size for WSL2, all the time the error came after the vdhx size reaches 256GB, mine is bigger than that. I unregistered the WSL instance after exporting it using the wsl command, I'm not able to compress or try to resize the vdhx to a smaller size. 

DON'T try to move your vdhx to another drive if your current one is bigger than 256GB, I tried everything, and looks like there is no solution and no one knows exactly how to solve it. I saw comments on many places that few were able to solve the problem when instances are less than 256Gb. 

Importing the instance as WSL1 completes the process but the Ubuntu system now is corrupted and nothing is working as expected, errors are everywhere on almost every command. Trying to set the WSL1 to WSL2 is not working, again fails when the vdhx reaches the 256GB. 

Just don't bother yourself trying to move your instance to another ssd/hdd.

**Comment by 0xbillw** [comment]
Same issue here.
The import failed: Unspecified error
Microsoft Windows [Version 10.0.19044.1706]
tar ball size: 175GB

**Comment by janschristensen** [comment]
I was playing around with making a script that download image and run command "wsl --import".

Some time after download was disabled in the script I started seeing "Unspecified error".

I redownloaded the image, and after that it worked again.

**Comment by soseki-angfa** [comment]
I am having exacty the same issue here.
But, I am not sure of the same issue or not.

What I did is that I export to my laptop and I import to different PC today.

Then, it gives me Unspecified error.

Are we not allowed to do this?

**Comment by flexchar** [comment]
I've had a `.wslconfig` with the following contents:

```toml
[wsl2]
memory=25GB
swap=0
localhostForwarding=true
```

after temporarily deleting the file, restarting PC, I was able to **successfully import** 19GB tar file of Ubuntu distro. Hope that saves someone a few hours!

**Comment by elhigu** [comment]
As a workaround I was able to do the import (moving system  to other location) by importing original vhdx file directly instead of .tar file:

```
wsl --import Ubuntu-20.04-d D:\WSL\Ubuntu-20.04\ C:\Users\user\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu20.04onWindows_79rhkp1fndgsc\LocalState\ext4.vhdx --vhd
```

**Comment by george-j-thomas** [comment]
> As a workaround I was able to do the import (moving system to other location) by importing original 135GB vhdx file directly instead of 95GB .tar file:
> 
> ```
> wsl --import Ubuntu-20.04-d D:\WSL\Ubuntu-20.04\ C:\Users\user\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu20.04onWindows_79rhkp1fndgsc\LocalState\ext4.vhdx --vhd
> ```

Which build version is the --vhd flag included in? On 19041 this throws an error

**Comment by buliaoyin** [comment]
> 

Exactly the same situation. A lot of my work in ubuntu lost. Hope feature version could restore my .tar.

**Comment by buliaoyin** [comment]
> **Unspecified error wins** Nothing above worked for me, I think I lost everything I had configured in my wsl instance. I have the TAR, and it is not corrupted, I tried to get logs during the process but after following https://github.com/microsoft/WSL/blob/2cb110aba644d0bb3ff8d6445448d4e08e11df78/CONTRIBUTING.md#8-detailed-logs the files
> 
> ```
> lxcore_kernel.etl
> lxcore_service.etl
> lxcore_user.etl
> ```
> 
> never been filled.
> 
> Seems there is a problem with the vdhx size for WSL2, all the time the error came after the vdhx size reaches 256GB, mine is bigger than that. I unregistered the WSL instance after exporting it using the wsl command, I'm not able to compress or try to resize the vdhx to a smaller size.
> 
> DON'T try to move your vdhx to another drive if your current one is bigger than 256GB, I tried everything, and looks like there is no solution and no one knows exactly how to solve it. I saw comments on many places that few were able to solve the problem when instances are less than 256Gb.
> 
> Importing the instance as WSL1 completes the process but the Ubuntu system now is corrupted and nothing is working as expected, errors are everywhere on almost every command. Trying to set the WSL1 to WSL2 is not working, again fails when the vdhx reaches the 256GB.
> 
> Just don't bother yourself trying to move your instance to another ssd/hdd.

Exactly the same situation. A lot of my work in ubuntu lost. Hope feature version could restore my .tar.

**Comment by buliaoyin** [comment]
> > **Unspecified error wins** Nothing above worked for me, I think I lost everything I had configured in my wsl instance. I have the TAR, and it is not corrupted, I tried to get logs during the process but after following https://github.com/microsoft/WSL/blob/2cb110aba644d0bb3ff8d6445448d4e08e11df78/CONTRIBUTING.md#8-detailed-logs the files
> > ```
> > lxcore_kernel.etl
> > lxcore_service.etl
> > lxcore_user.etl
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > never been filled.
> > Seems there is a problem with the vdhx size for WSL2, all the time the error came after the vdhx size reaches 256GB, mine is bigger than that. I unregistered the WSL instance after exporting it using the wsl command, I'm not able to compress or try to resize the vdhx to a smaller size.
> > DON'T try to move your vdhx to another drive if your current one is bigger than 256GB, I tried everything, and looks like there is no solution and no one knows exactly how to solve it. I saw comments on many places that few were able to solve the problem when instances are less than 256Gb.
> > Importing the instance as WSL1 completes the process but the Ubuntu system now is corrupted and nothing is working as expected, errors are everywhere on almost every command. Trying to set the WSL1 to WSL2 is not working, again fails when the vdhx reaches the 256GB.
> > Just don't bother yourself trying to move your instance to another ssd/hdd.
> 
> Exactly the same situation. A lot of my work in ubuntu lost. Hope feature version could restore my .tar.
> 
> I'm thinking make another basic ubuntu distro, then extract my .tar inside. Hope me have luck.

It seems worked, first make a new ubuntu distro, then migrate to new disk, enlarge to 1T, at last extract tar file in the new ubuntu distro to replace all of the files.

**Comment by SuperSandro2000** [comment]
bumo

**Comment by vbarrancos** [comment]
> As a workaround I was able to do the import (moving system to other location) by importing original 135GB vhdx file directly instead of 95GB .tar file:
> 
> ```
> wsl --import Ubuntu-20.04-d D:\WSL\Ubuntu-20.04\ C:\Users\user\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu20.04onWindows_79rhkp1fndgsc\LocalState\ext4.vhdx --vhd
> ```

I was experiencing this issue on a fresh Windows installation with the newest version of WSL/kernel -- imports failed randomly after about 18-22GB for a 26GB .tar, either because they would stall indefinitely (no disk activity) or they would return this E_FAIL unspecified error.

The suggestion above (importing the vhdx directly instead of using the .tar from the `--export` command) worked for me.

**Comment by SuperSandro2000** [comment]
> Thank you!

🖕🏼 

The bot settings are stupid and force you to post a spam comment every 7 days which just wastes everyone's time.

**Comment by duncanvsn** [comment]
I worked around this error following the instructions here: https://github.com/microsoft/WSL/issues/8787#issuecomment-1233609408

I hope this issue can be re-opened and we get a proper solution.

**Comment by myfeing** [comment]
> In my case it works while changing from: `wsl --import Ubuntu "C:\Users\{userName}" fileName.tar` to: `wsl --import Ubuntu "C:\Users\{userName}" .\fileName.tar`

yes, it does work, my tar file up to 10g

**Comment by girol** [comment]
Leaving my 2 cents:

I was experiencing the same issue and making sure all the instances of wsl were down did the trick.

Somehow, `wsl --shutdown` command was not stopping all my current distributions. I use my machine mainly for coding with VSCode and Docker Desktop. My VSCode was left opened in another workspace holding back a distro up. Closing it, then forcing shutdown and re-importing my `.tar` file worked.

**Comment by Mistic92** [comment]
I was trying to move my WSL to another drive and now I can't import it because of this error :/

**Comment by monadstack** [comment]
reproducible on fresh export.

**Comment by gabeklavans** [comment]
Just happened to me. I just did another import, exact same command, and it worked. Kinda weird.... please output a more descriptive error.

**Comment by lockedtang** [comment]
Try executing "wsl --import" as an administrator, it works for me

**Comment by monadstack** [comment]
> Unspecified error

The error itself is just "Unspecified error", no other descriptive means, turns out my problem was my wsl vhd is corrupt, hence. if it was fresh from store, then it is fine.

**Comment by YAmikep** [comment]
> Leaving my 2 cents:
> 
> I was experiencing the same issue and making sure all the instances of wsl were down did the trick.
> 
> Somehow, `wsl --shutdown` command was not stopping all my current distributions. I use my machine mainly for coding with VSCode and Docker Desktop. My VSCode was left opened in another workspace holding back a distro up. Closing it, then forcing shutdown and re-importing my `.tar` file worked.

Same worked for me. Phew! Thank you for the tip.

**Comment by rjoomen** [comment]
Same issue here, but changing:
`wsl --import Ubuntu-22.04 D:\WSL\Ubuntu-22.04 D:\WSL\Ubuntu-22.04.tar`
to:
`wsl --import Ubuntu-22.04 .\Ubuntu-22.04 .\Ubuntu-22.04.tar`
did the trick, wth?

**Comment by sonnguyenmaxava** [comment]
> Same issue here, but changing: `wsl --import Ubuntu-22.04 D:\WSL\Ubuntu-22.04 D:\WSL\Ubuntu-22.04.tar` to: `wsl --import Ubuntu-22.04 .\Ubuntu-22.04 .\Ubuntu-22.04.tar` did the trick, wth?

worked for me when moving distro to another drive
Thanks @rjoomen

**Comment by eiz** [comment]
I followed the above instructions to capture an event log (sorry, I will not publicly upload the entire log here) and this is clearly the problem for me (tar file is 370GB):

![image](https://user-images.githubusercontent.com/405658/223341978-1f8f347c-765f-44b0-8e2e-72fd09f7b916.png)

not sure why tar is running in a cgroup that allows 64MB of memory on a box with 128GB... 🤣

**Comment by fractalzombie** [comment]
Have same issue as guys. And yes it is already for 3 years, how did you do this?)

**Comment by MiloDC** [comment]
> Have same issue as guys. And yes it is already for 3 years, how did you do this?)

https://github.com/microsoft/WSL/issues/4735#issuecomment-986051266

**Comment by fractalzombie** [comment]
> > Have same issue as guys. And yes it is already for 3 years, how did you do this?)
> 
> [#4735 (comment)](https://github.com/microsoft/WSL/issues/4735#issuecomment-986051266)

this works `wsl --import Ubuntu-22.04 "C:\Users\fract\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu_79rhkp1fndgsc" D:\Ubuntu.tar`

**Comment by ken-cdit** [comment]
> Had the same issue. I exported two WSL 2 distros and then did a clean install of my Windows OS. "Unspecified error" came up when I tried to import them.
> 
> I fixed it by downloading the Linux kernel update package referred to at https://docs.microsoft.com/en-us/windows/wsl/install-win10 and then running the command `wsl --set-default-version 2`.
> 
> After this, my two distros imported without error.

This worked for me.  I had the whole thing still in the console so here is a screencap...

![image](https://user-images.githubusercontent.com/37189364/227820102-da5ded57-ef4e-4c00-94fb-ba8f9e6fd590.png)

**Comment by armanexplorer** [comment]
I finally resolved this amiss during the following steps (Windows 10.0.19045 Build 19045):

1. Running `wsl.exe --import Ubuntu A:\wsl\Ubuntu A:\wsl\Ubuntu.tar`  = > `Unspecified error`
2. Running `LxRunOffline.exe install -n Ubuntu -d A:\wsl\Ubuntu -f A:\wsl\Ubuntu.tar` => `[ERROR] Couldn't get the value "DistributionName" of the registry key "Software\Microsoft\Windows\CurrentVersion\Lxss\AppxInstallerCache"`
3. Removing the `Software\Microsoft\Windows\CurrentVersion\Lxss\AppxInstallerCache` registry key 
4. Running `LxRunOffline.exe install -n Ubuntu -d A:\wsl\Ubuntu -f A:\wsl\Ubuntu.tar` => `[ERROR] Couldn't get the value "DistributionName" of the registry key "Software\Microsoft\Windows\CurrentVersion\Lxss\TryStoreWSL"`
5. Removing the `Software\Microsoft\Windows\CurrentVersion\Lxss\TryStoreWSL` registry key 
6. Running `LxRunOffline.exe install -n Ubuntu -d A:\wsl\Ubuntu -f A:\wsl\Ubuntu.tar` => ✔
7. Running `ubuntu.exe config --default-user arman` => ✔
8. done 🎉

**Comment by mslinn** [comment]
I will document that on https://www.mslinn.com/blog/2022/01/10/wsl-backup.html later this week.

**Comment by jcrben** [comment]
I was originally trying to do this from msys2

Changing to powershell and running the command with a `.\` as suggested here fixed it for me:

`wsl --import wsl-vpnkit-2 ../bin/wsl-distros .\wsl-vpnkit-3.8.tar.gz --version 2`

**Comment by taljacob2** [comment]
> I was originally trying to do this from an msys2 shell
> 
> Changing to powershell and running the command with a `.\` as suggested here fixed it for me:
> 
> `wsl --import wsl-vpnkit-2 ../bin/wsl-distros .\wsl-vpnkit-3.8.tar.gz --version 2`

Thanks!
Stating the `--version 2` solved this for me!

**Comment by carpe1** [comment]
I also had this problem, later I found out that the reason was **just because of lack of space**, I solved this problem simply by freeing up more disk space.

**Comment by carpe1** [comment]
I also had this issue, later I found out that the reason was **just because of lack of space**, I solved this problem simply by freeing up more disk space.

**Comment by syhesyh** [comment]
I meet the same problem ,the configuration of my PC is : win11, wsl2. My .tar is about 150G. I solve this problem by updating my wsl with `wsl --update`, then I import it again , it works

**Comment by crazyhouse33** [comment]
> 
> ![image](https://user-images.githubusercontent.com/405658/223341978-1f8f347c-765f-44b0-8e2e-72fd09f7b916.png)
> 


Please can someone explain how to obtain thoses logs. @eiz ?
