### ISSUE TITLE
wsl.exe fails with "Access is denied"

### ISSUE THREAD

**Issue by john-vaudin** [microsoft/WSL#4920]
After uninstalling an re-installing Windows Subsystem for Linux I can't install any distro - they all fail with "Access is denied". Even running wsl.exe now fails with "Access is denied".  

Your Windows build number: (Type ver at a Windows Command Prompt)

`Microsoft Windows [Version 10.0.18362.657]`

Steps to reproduce

`> wsl.exe`
`Access is denied`

Strace and logs attached.

[wsl_strace.txt](https://github.com/microsoft/WSL/files/4239982/wsl_strace.txt)

[logs.zip](https://github.com/microsoft/WSL/files/4239983/logs.zip)

**Comment by willemdh** [comment]
I seem to ahve the same issue... Although I can start ubuntu when I open it from the store, executing wsl always results in " Access is denied".

**Comment by hv1pr0** [comment]
Same over here.

Switched from WSL 1 to WSL 2. After rebooting I got an 
Access is denied. Later I found that I didn't have Windows 
Version 2004, Build 19041 install but only 1909 Build 18363.720. 

So I removed WSL from Windows Features, reboot, and activated 
WSL again with the effect that I get an "Access is denied" in PS being 
Admin but runs without Admin. However, I'm stuck now since I 
can no longer use wsl.exe being Admin nor revert to any previous 
state.

**Comment by AllanOricil** [comment]
I have the same problem.
I followed these steps https://docs.microsoft.com/pt-br/windows/wsl/install-win10
And got stucked in the part I had to switch to version 2.
I can't simply run `wsl` because windwos always say Access Denied

**Comment by juanBcn** [comment]
Same problem, any update or fix?

**Comment by juanBcn** [comment]
Fixed, modify permisions on WindowsApps folder work for me.

**Comment by zhangxd6** [comment]
> Fixed, modify permisions on WindowsApps folder work for me.

I have the same problem. I am curious what permissions you modified

**Comment by gujx2017** [comment]
> Fixed, modify permisions on WindowsApps folder work for me.

I have the same problem, and have't fix it yet.
Could you please to describe in detail of your operation?

**Comment by cforce** [comment]
same here. please provide a fix

**Comment by amstas** [comment]
Had the same issue when running as admin, when running without it WSL works fine. try it.

**Comment by codemonkey33** [comment]
Also got past this with WindowsApps folder permissions. You need to change the owner of this folder so you can get access to it.
Try this link (ignoring the stupid download an app version 1 of course :)
https://www.maketecheasier.com/access-windowsapps-folder-windows-10/

**Comment by richardso21** [comment]
@codemonkey33 has the solution that worked just fine for me. I still had the problem even when I had imported my ubuntu outside of the `WindowsApps` folder, weird...

**Comment by nimamahmoudi** [comment]
I have the same issue here. Is there any way we can do something similar to what @codemonkey33 is suggesting, but without the registry tweaking and only for WSL (not the whole windows apps folder)?

**Comment by nimamahmoudi** [comment]
Weird thing, I just launched Ubuntu from Windows Store, then ran wsl from cmd (running as administrator), and all of a sudden it seems like everything is working fine. Even in cmd without administrator privileges, or from Windows Terminal (which is where my issue started).

**Comment by rosea-tf** [comment]
I have the same issue on an Ubuntu installation imported from a TAR file to a custom location. I already have access to the WindowsApps folder; this doesn't help.

Running as a regular user: I get the "Access Denied" message when trying to start wsl.exe. 
Running as Administrator": wsl.exe works to .start the distro running. I can _then_ use it either as admin or as a regular user (via wsl.exe, Windows Terminal, VS Code...)
However, if the distro shuts down (e.g. via `wsl.exe --shutdown`), then I lose my ability to connect as a regular user, and have to run wsl.exe as admin again.

Problem seems to have appeared with Windows Update KB4565503 earlier this week.

**Comment by richardso21** [comment]
Can confirm the specific update (KB4565503) was the issue. `wsl` now works perfectly and doesn't say access denied.

**Comment by nimamahmoudi** [comment]
Same here, uninstalling `KB4565503` fixed the issue. Everything is back to normal.

**Comment by ojacques** [comment]
Issue #5605 has a possible ["permanent" fix](https://github.com/microsoft/WSL/issues/5605#issue-659146504) for the issue triggered by `KB4565503`.

**Comment by aslamdoctor** [comment]
Same here. Just updated Win 10 yesterday and now my WSL2 throws "Access denied" but if you run terminal as administrator and then go to wsl, it works.

**Comment by dacarey** [comment]
Just to +1  to comments by other about KB4565503 as a root cause for this

i.e.  I had the same issue, with "access is denied" being returned on wsl commands.  Having now uninstalled KB4565503 the problem is resolved.

**Comment by nimamahmoudi** [comment]
After uninstalling `KB4565503`, updates automatically install it again. Is there a permanent fix for this issue?

**Comment by rosea-tf** [comment]
> After uninstalling `KB4565503`, updates automatically install it again. Is there a permanent fix for this issue?

Yes - grant your user account full control over the .vhdx file. See https://answers.microsoft.com/en-us/windows/forum/all/kb4565503-installed-then-wsl-2-failed-to-start/25794c4f-0b20-465e-bbdb-a8af3d9e0e88

**Comment by mroma82** [comment]
> > After uninstalling `KB4565503`, updates automatically install it again. Is there a permanent fix for this issue?
> 
> Yes - grant your user account full control over the .vhdx file. See https://answers.microsoft.com/en-us/windows/forum/all/kb4565503-installed-then-wsl-2-failed-to-start/25794c4f-0b20-465e-bbdb-a8af3d9e0e88

Thank you - this worked for me!

**Comment by jwsinner** [comment]
I experienced this issue when Docker stopped unexpectedly.

PowerShell would either return that I didn't have permission (when run outside Administrator) or Access Denied (when run as Administrator. In a command prompt I was getting Access Denied when trying to run wsl, but was still able to run wsl --help.

If you are able to run wsl --help and get information back, you should be able to do the following:

1. Run `wsl --list --verbose` to get a list of distros
2. `wsl --shutdown`
3. `wsl --unregister [distro name listed from step 1]

Then I had located ext4.vhdx and deleted the folders in AppData that contained this file (Mine was Docker). If you can't delete it because it says it is open in System, restart and you should be able to delete it. After it's deleted, you should have access to wsl in PowerShell and cmd and be able to reinstall the distro you deleted.

**Comment by kashif-khan** [comment]
I too have this issue but in my case, **McAfee endpoint security** is installed on my machine and **it is blocking** me to run it. In the McAfee endpoint security, the below message was posted.

> <<MyUsername>> ran C:\Windows\System32\wsl.exe, which attempted to access the process LxssManagerProxyStub.dll, violating the rule "Executing Windows Subsystem for Linux", and was blocked. For information about how to respond to this event, see KB85494.

**Comment by Wolvverine** [comment]
Disable compress and encryption for this folder

%USERPROFILE%\AppData\Local\Packages{distribution_folder}

https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by kousu** [comment]
I had already installed Ubuntu on my machine a while ago. Today I found I could not start it:

i. Trying to click "Ubuntu" in the Start Menu would appear to not react,
ii. trying to start it from `cmd.exe` would exit immediately.

What did work, was to start `cmd.exe` or `powershell.exe` as Administrator and run `wsl` from there:

```
C:\Windows\system32> wsl
root@DESKTOP-XXXXX:~#
```

I tried to reinstall:

```
PS C:\Windows\system32> cd C:\Users\user
PS C:\Users\user> Invoke-WebRequest -Uri https://aka.ms/wsl-ubuntu-1804 -OutFile Ubuntu.appx -UseBasicParsing
PS C:\Users\user> Add-ProvisionedAppxPackage -PackagePath .\Ubuntu.appx -Online -SkipLicense
```

It appeared to install successfully, however I still had the same symptoms.

I tried reinstalling again, this time directly in my user account:

```
PS C:\Users\user> Get-AppxPackage -name CanonicalGroupLimited.Ubuntu18.04onWindows | Remove-AppxPackage
PS C:\Users\user> Add-AddxPackage .\Ubuntu1804.appx
```

It didn't solve it, but instead of Ubuntu crashing immediately, it told me:

```
PS C:\Users\user> ubuntu1804.exe
Access is denied.
```

(which is what brought me to this thread)

and of course it still works as Administrator:

```
PS C:\Windows\system32> ubuntu1804.exe
root@DESKTOP-XXXXX:~# logout
```

@jwsinner's fix in https://github.com/microsoft/WSL/issues/4920#issuecomment-746843348 seems to have actually fixed it fully! And done it without having to garble my system permissions or anything:

In my Administrator shell:

```
PS C:\Windows\system32> wsl --list --verbose
  NAME		STATE		VERSION
* Ubuntu-18.04	Running		1
PS C:\Windows\system32> wsl --shutdown
PS C:\Windows\system32> wsl --unregister Ubuntu-18.04
Unregistering...
PS C:\Windows\system32> 
```

Then, as my regular user, without reinstalling anything package:

```
PS C:\Users\user> ubuntu1804.exe
Installing, this may take a few minutes...
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username:
```


I'm -1 on **KB4565503** being the problem. I don't have it installed:

![2021-03-20-162400_896x645_scrot](https://user-images.githubusercontent.com/987487/111884553-c189cd00-8998-11eb-85da-2c318864a060.png)

I have Windows 10 Pro N-1909-18363.1440:

![2021-03-20-163231_457x280_scrot](https://user-images.githubusercontent.com/987487/111884755-ff3b2580-8999-11eb-9218-5fa772864aa1.png)

**Comment by Danon** [comment]
In my case, windows permission mixed up with linux permissions, and disabled the `x` attribute on my folders, so I couldn't read them.

I had to do
```
chmod +x folder
```

**Comment by cool-delete** [comment]
> > 卸载后`KB4565503`，更新会自动再次安装。是否有针对此问题的永久修复程序？
> 
> 是-授予您的用户帐户对.vhdx文件的完全控制权限。请参阅[https://answers.microsoft.com/zh-cn/windows/forum/all/kb4565503-installed-then-wsl-2-failed-to-start/25794c4f-0b20-465e-bbdb-a8af3d9e0e88](https://answers.microsoft.com/en-us/windows/forum/all/kb4565503-installed-then-wsl-2-failed-to-start/25794c4f-0b20-465e-bbdb-a8af3d9e0e88)

Yes, after I restored the system, vhdx permissions were messed up. Adding my own account access can solve the problem

**Comment by mooooonlight** [comment]
> > After uninstalling `KB4565503`, updates automatically install it again. Is there a permanent fix for this issue?
> 
> Yes - grant your user account full control over the .vhdx file. See https://answers.microsoft.com/en-us/windows/forum/all/kb4565503-installed-then-wsl-2-failed-to-start/25794c4f-0b20-465e-bbdb-a8af3d9e0e88

Thanks! It worked!

**Comment by Rohan-ult** [comment]
I have also encountered the same problem .
Any solution ?

**Comment by mariaanko** [comment]
I also have this issue...

**Comment by frschwab** [comment]
Same here, is there a possibility to see the error cause - where does wsl log more info?

**Comment by mariaanko** [comment]
actually I fixed this by running the powershell without the administrator access...only regular..now everything works fine :)

**Comment by frschwab** [comment]
I just fixed it.
`wsl --import Ub C:\Users\fs\wsl\Ub C:\Users\fs\backup\wsl\wsl.tar.gz --version 2`
worked, whereas
`wsl --import Ub C:\Users\fs\wsl\Ub C:\Users\fs\backup\wsl\wsl.tar --version 2`
failed. I don't know why I decided to unpack the gz file in the first attempt and tried to import from there.

**Comment by jzvi12** [comment]
all `wsl` commands works fine except the `wsl --update` command which always complaints about permissions

![image](https://user-images.githubusercontent.com/10729787/122694828-b307b780-d20c-11eb-9eb2-1e3b3fcec524.png)

without admin rights:
```
> wsl --update
Checking for updates...
Downloading updates...
The requested operation requires elevation.
```

with admin rights:
```
> wsl --update
Access is denied.
```

**Comment by JohnRDOrazio** [comment]
I started recently getting File permission errors when trying to edit anything under `\\wsl$\Ubuntu-20.04` from Windows Explorer, opening in VSCode. In the end I resorted to unregistering from Powershell (`wsl --shutdown` and `wsl --unregister Ubuntu-20.04`), and then re-installing (I just clicked on the Ubuntu icon which I had pinned in the taskbar, and it reinstalled). After reinstalling and creating the new user, now I can access and edit files using Windows Explorer and VSCode.

Unfortunately this has the downside of removing all data within the Ubuntu instance. It seems to me to be a pretty drastic approach. I had already checked permissions on the `ext4.vhdx` file (`C:\%USERPROFILE%\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu20.04onWindows_79rhkp1fndgsc\LocalState\ext4.vhdx`) and they were all correct as far as I could tell.

**Comment by zpyatt** [comment]
For anyone else who runs into this, it might be your antivirus. I'm using Bitdefender, ran into this problem, had time to find this post and search a few other pages, then Bitdefender (finally, after ~ 5-10 min.) popped up a message about it. I excluded it (wsl.exe), and things went back to normal.

I had clicked on a *.cpp file from a nautilus window (seeing if it would open gedit) and it crashed. After I excluded wsl.exe in BD, I was able to click on the *.cpp, but it tried to use windows  apps (i.e. no gedit). Anyway, maybe this will be useful to someone else. Good luck, WSL2 is awesome.

**Comment by garyo** [comment]
I'm still having this issue. Did everything in @CreativeWarlock 's post, but no joy. `wsl.exe` is owned by TrustedInstaller and can't be moved, deleted or anything (even when I uninstall wsl2). Just executing `wsl.exe` gives the "Access is denied" message. To be clear, wsl.exe does run -- you can see it in procmon. But then it prints that message and exits. Passing any args to it has no effect.

**Comment by sahendrickson** [comment]
This just happened to me. Seem the latest cumulative update caused it: KB5009566

**Comment by ValZapod** [comment]
Same problem when connecting through ssh.

**Comment by tbennett6421** [comment]
Recently ran out of disk space and had the same thing occur. Unable to resolve

**Comment by yszzu1** [comment]
I used wrong file path,   `wsl --import fedora C:\wsl  C:\Users\aa\Documents\fedora-33.20211125-x86_64.tar`   should be `wsl --import fedora C:\wsl  C:\Users\aa\Documents\fedora-33.20211125-x86_64.tar\fedora-33.20211125-x86_64.tar`

**Comment by sahendrickson** [comment]
This started working again after I did a full wipe and reinstall of the operating system. Disappointing to have to do that. But, I'm glad it's working again now.

**Comment by gabrieu-amaral** [comment]
> I experienced this issue when Docker stopped unexpectedly.
> 
> PowerShell would either return that I didn't have permission (when run outside Administrator) or Access Denied (when run as Administrator. In a command prompt I was getting Access Denied when trying to run wsl, but was still able to run wsl --help.
> 
> If you are able to run wsl --help and get information back, you should be able to do the following:
> 
> 1. Run `wsl --list --verbose` to get a list of distros
> 2. `wsl --shutdown`
> 3. `wsl --unregister [distro name listed from step 1]`
> 
> Then I had located ext4.vhdx and deleted the folders in AppData that contained this file (Mine was Docker). If you can't delete it because it says it is open in System, restart and you should be able to delete it. After it's deleted, you should have access to wsl in PowerShell and cmd and be able to reinstall the distro you deleted.

for me, it's only thing worked. But in new register I get new error, its like 'no permission' (don't remember exactly). Search for new error, I found this :

https://www.dell.com/support/kbdoc/en-ie/000195980/how-to-enable-or-disable-windows-virtualization-on-dell-systems

So maybe that's possible be the cause of no permission

**Comment by psztoch** [comment]
If you have WSL "Access is denied" problem, at first check where have you your WSL installed.
If you use WSL from Microsoft Store (it is good choice, because you have got fresh and current version) then WSL is installed in `C:\Program Files\WindowsApps\` folder. And this folder has very limited access. Local administrators can't access this folder.
I took over ownership of files in this directory to LOCAL-DOMAIN\Administrators. Then it was possible to add Read/Execute rights to LOCAL-DOMAIN\Administrators. After it WSL start working via SSH or other remote access.

**Comment by BibleChris** [comment]
I get the same mistake after a while but not at the beginning. I think this must be a bug in the App Windows Store. After I repair it by using Windowstools it seems to be work. 
(Settings ->Apps -> Reset to default.)
This bug has a long history but unfortunately without a solution until now.

**Comment by andersonn-roberto** [comment]
If anyone are facing this problem, check if you have an App called Windows Subsystem for Linux, if yes, uninstall it and you will get access to wsl2 again.

It get installed here after running `wsl --update` command.

![image](https://user-images.githubusercontent.com/6409097/223286321-23f75a57-e409-4afd-a671-889cf7130795.png)

**Comment by flaxes** [comment]
Had simillar problem. Running as administator won't help. (Access Denied)
After some manipulations, I've decided to turn off Windows Update Blocker (wub)

Now, WSL works

**Comment by FoliAGEQBS** [comment]
Use the WSL -List command to check whether the old version is completely uninstalled

**Comment by wicklander-bryant** [comment]
I ended up facing a similar issue where all I got was access denied when attempting to install any distro EXCEPT the default `Ubuntu` distro that is installed by default when installing `wsl` from the CLI. I tried every proposed solution in this thread and many others with a similar access denied error, none of them ended up working. The solution that ended up working for me was to perform a full factory reset on my PC. Obviously not the best solution, but you can always back up your data and copy it back over to your fresh install. This was a last resort as I've been facing this issue for over 3 weeks now and needed to get things working again 🤷

**Comment by Amarok24** [comment]
> If anyone are facing this problem, check if you have an App called Windows Subsystem for Linux, if yes, uninstall it and you will get access to wsl2 again.
> 
> It was installed here after running `wsl --update` command.
> 
> ![image](https://user-images.githubusercontent.com/6409097/223286321-23f75a57-e409-4afd-a671-889cf7130795.png)

Thank you!!! That's almost unbelievable, so Microsoft created a conflict between 2 different installations of WSL, one from the command line and the 2nd one from Microsoft Store which appeared automatically without my consent, and that new one was causing this error:
`Error code: Wsl/Service/CreateInstance/CreateVm/E_ACCESSDENIED`

**Comment by codeflorist** [comment]
> If anyone are facing this problem, check if you have an App called Windows Subsystem for Linux, if yes, uninstall it and you will get access to wsl2 again.
> 
> It was installed here after running `wsl --update` command.
> 
> ![image](https://user-images.githubusercontent.com/6409097/223286321-23f75a57-e409-4afd-a671-889cf7130795.png)

amazing. simply amazing. so `wsl --update` takes away the possibility to use `wsl.exe` command line. thus for example completely breaking Docker.

microsoft's idiocy, arrogance and and ignorance never fails to amaze me.

**Comment by makeitouthill** [comment]
> If anyone are facing this problem, check if you have an App called Windows Subsystem for Linux, if yes, uninstall it and you will get access to wsl2 again.
> 
> It was installed here after running `wsl --update` command.
> 
> ![image](https://user-images.githubusercontent.com/6409097/223286321-23f75a57-e409-4afd-a671-889cf7130795.png)

Specially when the option to uninstalled is not available from where the screenshot was taken(Assuming Microsoft store), it would be helpful to include the steps you took to uninstall.

**Comment by makeitouthill** [comment]
> If anyone are facing this problem, check if you have an App called Windows Subsystem for Linux, if yes, uninstall it and you will get access to wsl2 again.
> 
> It was installed here after running `wsl --update` command.
> 
> ![image](https://user-images.githubusercontent.com/6409097/223286321-23f75a57-e409-4afd-a671-889cf7130795.png)

Including the steps you taken to uninstall would be helpful. From searching the app to clicking the three dots in the library next to the app it does not provide the option to uninstall.

**Comment by ZackPlauche** [comment]
For anyone who might still be stuck here, [this solution](https://github.com/microsoft/WSL/issues/3815#issuecomment-575927068) worked for me: 

> >wsl --unregister ubuntu
> followed by
> >wsl --install
> fixes the problem for ubuntu atleast

**Comment by vncntk** [comment]
I suddenly had this problem. I have been working using an administered laptop and have been using WSL Ubuntu for work environment. Laptop went to sleep and when turned on VSCode and cmd couldn't access WSL.

![image](https://github.com/user-attachments/assets/321e7ef2-0f60-4971-bdd3-f852c27474b1)

![image](https://github.com/user-attachments/assets/42289d36-bd48-46e0-9f87-9f5a6228395f)

**Comment by ggcannard** [comment]
@vncntk Seconding this, the exact same thing happened to me today as well. Have not found a solution yet either.

**Comment by dylancarruthers** [comment]
Same here, seemed to happen after installing the latest Windows Updates:

- 2024-08 Cumulative Update for .NET Framework 3.5 and 4.8.1 for Windows 11, version 24H2 for x64 (KB5042098)
- 2024-08 Cumulative Update for Windows 11 Version 24H2 for x64-based Systems (KB5041571)

**Comment by koleh-tech** [comment]
I have the same problem, but the only update I installed was:

- 2024-08 Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.417.101.0)

**Comment by dylancarruthers** [comment]
Fixed after running the following in PowerShell as administrator

```
Add-MpPreference -AttackSurfaceReductionOnlyExclusions "C:\windows\system32\wsl.exe"

Add-MpPreference -AttackSurfaceReductionOnlyExclusions "C:\Program Files\WSL\wsl.exe"
```

**Comment by McRegt** [comment]
Same problem here, have the following updates installed recently:

- 2024-08 Cumulative Update for Windows 11 Version 24H2 for x64-based Systems (KB5041571)
- 2024-08 Cumulative Update for .NET Framework 3.5 and 4.8.1 for Windows 11, version 23H2 for x64 (KB5042099)

The Windows Store also results in an exception:
![image](https://github.com/user-attachments/assets/2c9f1c24-f543-46c1-9072-8d23056cfeaf)

**Comment by vjanssens** [comment]
Same for me, the solution provided by @dylancarruthers solved the issue when in Administrator mode. Docker Desktop also stopped working because of this and resolved that by:

1. Stopping Docker Desktop
2. Run `wsl --unregister docker-desktop`
3. Restart Docker Desktop

**Comment by JakeBroughton** [comment]
> I have the same problem, but the only update I installed was:
> 
>     * 2024-08 Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.417.101.0)

Defender was the cause for us too with this rule: **Block use of copied or impersonated system tools**. If you can check your protection history in Defender you might see all the blocked wsl.exe actions.

**Comment by nariman-zk** [comment]
Same issue here and @dylancarruthers's solution did not solve the issue for me!

**Comment by bharthijairaman** [comment]
Having the same issue not solved for me either

**Comment by ms08067** [comment]
my wsl is broken with "access denied" and it also looks like my traditional virtual machines also fail using vbox after the last windows update.  Running Windows 11 10.0.22631 N/A Build 22631

**Comment by mlcivilengineer** [comment]
Also having this issue and adding these rules to powershell in admin mode still gives me an access denied when trying to launch wsl. Any other alternatives?

**Comment by himanshu-gupta-ocl** [comment]
Facing this issue with docker desktop
![image](https://github.com/user-attachments/assets/b2514876-846f-4ab0-8f0a-ef8fa8c25367)

No wsl command works for me in powershell Or terminal in admin mode. I get Access is denied error. I've tried reinstalling docker desktop & installing WSL latest 2.3.17 version. Nothing seems to be working. Please help

**Comment by codeflorist** [comment]
So during not even a full year, Microsoft was able to completely break Docker via WSL two times via bodged updates - creating a massive amount of wasted working hours and annoyance.
👏🏼🤡

**Comment by mlcivilengineer** [comment]
The issue regarding the Microsoft Defender has been resolved on its own apparently. I would advise everyone that was having this issue because of the Defender to update to the latest Windows version.

**Comment by Muna-Lombe** [comment]
For anyone who encountered this issue after migrating the location of the distros and images, I found that the "accessDenied" was caused becaused the current user didn't have access to the new location I migrated to.  This command:
`icacls <dir> /grant "<user>:(OI)(CI)(F)"`
from this [article](https://medium.com/@patelnitish/lxrunoffline-windows-10-11-move-ubuntu-to-a-different-drive-wsl2-546fb6fa4646) definitely fixed it. Now I don't need elevated access to start wsl even after shutdown.

**Comment by gaetano-fichera** [comment]
> For anyone who encountered this issue after migrating the location of the distros and images, I found that the "accessDenied" was caused becaused the current user didn't have access to the new location I migrated to. This command: `icacls <dir> /grant "<user>:(OI)(CI)(F)"` from this [article](https://medium.com/@patelnitish/lxrunoffline-windows-10-11-move-ubuntu-to-a-different-drive-wsl2-546fb6fa4646) definitely fixed it. Now I don't need elevated access to start wsl even after shutdown.

Thanks, it worked for me. I had the issue after a windows reset and starting a distro from an imported .vhdx.

**Comment by miron42** [comment]
turn on virtualization in bios
