### ISSUE TITLE
WSL 2 requires an update / The update only applies to machines with WSL

### ISSUE THREAD

**Issue by nphmuller** [microsoft/WSL#5014]
* Your Windows build number:  `Microsoft Windows [Version 10.0.19041.153]`

* What you're doing and what's happening: 
I'm starting Ubuntu for Windows and I immediately receive the following message:
`WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel`.
This has happened before, so I simply go to the website mentioned and download the update. No big deal. But when I run the update this message pops up: `This update only applies to machines with the Windows Subsytem for Linux` (there's a small typo in the message, by the way).

What do I do now? Seems I'm stuck between updates...

**Comment by Jimbles** [comment]
I have the same problem with build `19041.172`, I have used WSL1 before switching to the insiders program without issue

**Comment by onomatopellan** [comment]
It seems some people have problems with the installer extracting the kernel.

You can always extract it manually with:
`msiexec /a "wsl_update_x64.msi" /qb TARGETDIR="C:\temp"`
and then copy the `kernel` file from C:\temp to C:\Windows\System32\lxss\tools

Final version shouldn't have this problem since the install comes from Windows Update.

**Comment by nphmuller** [comment]
@onomatopellan I had WSL2 working already, so I have both enabled. After an update it asked me to update WSL2 manually by downloading and executing the MSI file. On a previous update that worked perfectly and WSL2 worked again after updating. On this update however I receive the error message I described when executing the MSI file.

Thanks for the workaround! I'll try it out next week, when I have the system with this issue available again.

**Comment by sandys** [comment]
im having this exact same issue. im on release 2004 (19041.172)

I'm stuck between updates. and my dev system is down.

**Comment by sandys** [comment]
ok - i figured out the issue. the new update does not uninstall the old one (the slow insider ring one).

I right clicked the old msi - uninstalled it. now i can install the new one .

**Comment by Jimbles** [comment]
@sandys Thanks! That worked for me :)

**Comment by tasahi** [comment]
@onomatopellan , thanks. It worked for me just fine. It seems that some Win update erases the kernel file.

**Comment by friday963** [comment]
> 
> 
> ok - i figured out the issue. the new update does not uninstall the old one (the slow insider ring one).
> 
> I right clicked the old msi - uninstalled it. now i can install the new one .

Can you expand on this?  I'm not sure where you found the MSI to uninstall.  

I tried the recommended advice from @onomatopellan 
msiexec /a "wsl_update_x64.msi" /qb TARGETDIR="C:\temp"
and then copy the kernel file from C:\temp to C:\Windows\System32\lxss\tools

But I still cannot get it to work.  
I don't have a kernel file after executing those commands, its just an MSI file and when I click the file it says "The specified account already exists" and fails.

**Comment by onomatopellan** [comment]
@friday963 Something is broken in your install. Follow this and try again: https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed

**Comment by friday963** [comment]
> 
> 
> @friday963 Something is broken in your install. Follow this and try again: https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed
> 
> BTW the msi file you need is here https://aka.ms/wsl2kernel

You're right @onomatopellan , I needed to uninstall with that tool.  Thanks for the help!

**Comment by swaroop1** [comment]
@sandys Thanks that worked for me!!

We need to uninstall " Windows Subsystem for Linux Update " just as we would do for a regular windows application

**Comment by Alsushi** [comment]
> 
> 
> ok - i figured out the issue. the new update does not uninstall the old one (the slow insider ring one).
> 
> I right clicked the old msi - uninstalled it. now i can install the new one .

"Right clicked the downloaded msi" would have been correct.
Thanks!!!

**Comment by jakemitchellxyz** [comment]
> > ok - i figured out the issue. the new update does not uninstall the old one (the slow insider ring one).
> > I right clicked the old msi - uninstalled it. now i can install the new one .
> 
> "Right clicked the downloaded msi" would have been correct.
> Thanks!!!

This solved it for me!

**Comment by baoanhng** [comment]
Solved issue for me.

**Comment by skipper46** [comment]
Solved issue for me. The problem was the path "C:\Users\<UserName>\Downloads\wsl_update_x64.msi" to msi installation file.
I copied file to "C:\Temp\wsl_update_x64.msi", double-clicked and was installed OK.

**Comment by twocs** [comment]
I right clicked the new wsl_update_x64.msi file and selected "uninstall". It successfully uninstalled. Then I right clicked it again and selected install, and no longer saw "the update only applies to machines with the Windows Subsytem for Linux" error, and it installed successfully.

**Comment by drphrozen** [comment]
I solved my issue by elevating a command line and executing `wsl_update_x64.msi` from there.

**Comment by jtsalten** [comment]
I had the same issue. Last Windows 10 2004 up to date. Previously WSL1 installed and working. I tried uninstalling WSL several times with no luck. Finally I uninstalled Docker for Windows, WSL, Virtual Machine Platform Platform and Hyper-V... and reinstalled again Hyper-V, restart, WSL, restart, VMP, restart, install Ubuntu 20, install Docker for Windows with WSL2 enabled... Now it works... But not knowing what it fails it's a bit scary because seems like you never know when will happen again... 😰

**Comment by CaduceusInc** [comment]
> 
> 
> > ok - i figured out the issue. the new update does not uninstall the old one (the slow insider ring one).
> > I right clicked the old msi - uninstalled it. now i can install the new one .
> 
> "Right clicked the downloaded msi" would have been correct.
> Thanks!!!

Right! I only understood what he said after reading your comment. Works now, thanks!

**Comment by meizenga** [comment]
> I had the same issue. Last Windows 10 2004 up to date. Previously WSL1 installed and working. I tried uninstalling WSL several times with no luck. Finally I uninstalled Docker for Windows, WSL, Virtual Machine Platform Platform and Hyper-V... and reinstalled again Hyper-V, restart, WSL, restart, VMP, restart, install Ubuntu 20, install Docker for Windows with WSL2 enabled... Now it works... But not knowing what it fails it's a bit scary because seems like you never know when will happen again... 😰

I had the same issue and your solution fixed it, but.... I also had to run Docker Desktop installer as Adminitrator (even my account is already local admin). Thanks @CaduceusInc

**Comment by jramiresbrito** [comment]
I'm running on the same issue.
Here are the steps I did:

Power Shell:
- Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
- dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
- dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart

Microsoft Store: 
- Get the Ubuntu (Plain , not the 18 or 20 dist)

After install the Ubuntu and restart pc, on CMD:
- system32>wsl -l -v

It shows: 
NAME      STATE           VERSION
Ubuntu    Stopped         1

Then, update the WSL2 Kernel:

- Download and installed [wsl2 kernel](https://docs.microsoft.com/pt-br/windows/wsl/wsl2-kernel)

Back to CMD:

- wsl --set-version Ubuntu 2


The error prompts:

- WSL2 requires an update to you Kernel component. To get more info please go to [aka ms](https://aka.ms/wsl2kernel).

Checking the version and stays on Version 1:

- system32>wsl -l -v

NAME      STATE           VERSION
Ubuntu    Stopped         1

Tried to uninstall the manual update to WSL2 and installing it again, but the error keeps the same.

How can I solve this?

**Comment by benhillis** [comment]
@jramiresbrito - Did the MSI install correctly?  I assume you do not have a kernel under \windows\system32\lxss\tools?

**Comment by jramiresbrito** [comment]
> @jramiresbrito - Did the MSI install correctly? I assume you do not have a kernel under \windows\system32\lxss\tools?

Yes. It did not complain and successfully finish the installation.

**Comment by benhillis** [comment]
Do you have a %windir%\system32\lxss\tools file?

**Comment by jramiresbrito** [comment]
> Do you have a %windir%\system32\lxss\tools\kernel file?

No, only a kernel.rollback file. How to get the kernel?

**Comment by jramiresbrito** [comment]
I tough these guy was the one...
![image](https://user-images.githubusercontent.com/47673606/83907368-ad434f00-a73b-11ea-87d6-889130d07715.png)

**Comment by benhillis** [comment]
Just rename that file 'kernel'

**Comment by licanhua** [comment]
@jramiresbrito, Your windows already have linux kernel, so you don't need to download and install kernel manually.

**Comment by benhillis** [comment]
@licanhua - Then why did he see the error message?

**Comment by licanhua** [comment]
kernel MSI installer is designed to install to Windows which kernel is removed from os when WSL is enabled. 
When user install the MSI manually, it backup old kernel to kernel.rollback, then install the new kernel.
In his case, kernel is installed when he enables WSL, there are conflicts because both WSL and MSI installer are managing the same kernel. and finally caused kernel is removed. This is an known issue and we have no plan to fix it.
He see this message because kernel doesn't exist. it's removed when MSI is installed manually

**Comment by benhillis** [comment]
Ok, but why is the MSI removing the inbox kernel but not leaving the one from the MSI?

**Comment by jramiresbrito** [comment]
@licanhua So, what should I do in order to upgrade to WSL2?

**Comment by licanhua** [comment]
If you already installed the distro, https://docs.microsoft.com/en-us/windows/wsl/install-win10#set-your-distribution-version-to-wsl-1-or-wsl-2

otherwise you just need to `wsl --set-default-version 2`, then install the distro.

**Comment by jramiresbrito** [comment]
@licanhua running wsl` --set-default-version 2` is not working...

Also tried `wsl --set-version Ubuntu-20.04 2`

All prompt the same: `WSL2 requires an update to you Kernel component. To get more info please go to aka ms.`

Listing the installations I have `wsl -l -v`

  NAME                STATE           VERSION
  Ubuntu              Stopped         1
  Ubuntu-20.04    Stopped         1

**Comment by onomatopellan** [comment]
@jramiresbrito follow how to manually install the kernel [here](https://github.com/microsoft/WSL/issues/5014#issuecomment-605243281).

**Comment by licanhua** [comment]
@jramiresbrito, in you case, copy %windir%\system32\lxss\tools\kernel.rollback to %windir%\system32\lxss\tools\kernel

**Comment by jramiresbrito** [comment]
@onomatopellan Thank you. It worked!
@licanhua Idk why, the kernel.rollback has gone...

**Comment by 24githubs** [comment]
June 12, 2020
today! docker surprised me.
After I have updated to the latest version 2004 os build 19645.1  

![Capture2](https://user-images.githubusercontent.com/60570585/84465078-50e2b100-aca0-11ea-8e44-f02d6e9ffa7e.JPG)

**Comment by HongChongxi** [comment]
I also face the same issue. Tried to uninstall the msi (wsl_update_x64) and reinstall but still the same

**Comment by HongChongxi** [comment]
Can anybody advise how I can fix this? Thanks!

**Comment by 24githubs** [comment]
@HongChongxi 
1. download WSL 2 Linux kernel > https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel
2. copy file to C:\Temp\ and double-click  to  install.

**Comment by HongChongxi** [comment]
@24githubs:

Thanks, but I still get the same error. Essentially, I downloaded the WSL 2 Linux kernel but it gave me a message that the installation ended prematurely.
[WSL2 Linux Kernel Issue.docx](https://github.com/microsoft/WSL/files/4776685/WSL2.Linux.Kernel.Issue.docx)

**Comment by jramiresbrito** [comment]
The last insiders update broke everything here omg... Be careful you guys... Im reinstalling everything...

**Comment by licanhua** [comment]
@HongChongxi Are you using the latest mn_release? Two ways may workaround the problem:
1. extract MSI and put kernel to tools\ manually, see [here](https://github.com/microsoft/WSL/issues/5014#issuecomment-605243281)
2. uninstall the MSI and rerun it with admin
Please note that 'workaround' means you may hit the same problem next time because root cause is not identified.

@jramiresbrito what do you mean 'last insiders update broke everything here omg'? are you upgrading from old release? I can try to reproduce your problem next Monday

**Comment by HongChongxi** [comment]
@licanhu When I typed in msiexec /a "wsl_update_x64.msi" /qb TARGETDIR="C:\temp" to manually install the msi file, I got an error saying the installer package could not be opened.
![image](https://user-images.githubusercontent.com/52709640/84610576-a069ec80-aeed-11ea-80fe-8f9876296953.png)

**Comment by licanhua** [comment]
I guess you didn't in the correct directory and wsl_update_x64.msi doesn't exist. first download [wsl_update_x64](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi) to somewhere like %userprofile%\downloads, then goto that directory and execute the command.

**Comment by HongChongxi** [comment]
@licanhua Yes, now I downloaded the wsl_update_x64 to C;\Temp and moved it from C:\temp to C:\Windows\System32\lxss\tools. When I tried to uninstall the msi file, it gave:
![image](https://user-images.githubusercontent.com/52709640/84611893-a06beb80-aef1-11ea-856f-bcb766cbe97c.png)

After then running an installation from there, returned me the same errors again

**Comment by licanhua** [comment]
I mean: copy "C:\temp\System32\lxss\tools\kernel" to C:\Windows\System32\lxss\tools. then done

**Comment by markuszeller** [comment]
Issue fore me solved disabling via Apps & Features
- hyper V
- linux subsytem
- uninstall the old ubuntu wsl distribution (this was the main key).
- reboot

Afterwards just followed
- `dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart`
- `dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart`
- `wsl --set-default-version 2`

Install a Ubuntu distro from Store and it was auto installed as WSL2 and default.

**Comment by blc-gksl** [comment]
> ok - i figured out the issue. the new update does not uninstall the old one (the slow insider ring one).
> 
> I right clicked the old msi - uninstalled it. now i can install the new one .

Thanks bro, you are a lifesaver☻

**Comment by Akshayhackman** [comment]
**Download the Linux kernel update package**

Please download the latest [WSL2 Linux kernel update](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi) package for x64 machines.

_Note;
If you're using an ARM64 machine, please [download the ARM64 package](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_arm64.msi) instead._

**Comment by Vishnu05** [comment]
> * Your Windows build number:  `Microsoft Windows [Version 10.0.19041.153]`
> * What you're doing and what's happening:
>   I'm starting Ubuntu for Windows and I immediately receive the following message:
>   `WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel`.
>   This has happened before, so I simply go to the website mentioned and download the update. No big deal. But when I run the update this message pops up: `This update only applies to machines with the Windows Subsytem for Linux` (there's a small typo in the message, by the way).
> 
> What do I do now? Seems I'm stuck between updates...

How to get resolved this issue, I'm also facing a similar issue

**Comment by licanhua** [comment]
There are two possible reason for it:
1. You didn't enable WSL. Please follow the document to enable: Microsoft-Windows-Subsystem-Linux and VirtualMachinePlatform
2. After enable WSL, you didn't reboot the machine

You hit above message because pre-check failed. You have to enable WSL first, then install MSI. 
It's easy to verify if WSL enabled or not:
1. check if `HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\LxssManager\parameters` exists
2. or `dir %SystemRoot%\system32\lxss\LxssManager.dll`

**Comment by Vishnu05** [comment]
> There are two possible reason for it:
> 
> 1. You didn't enable WSL. Please follow the document to enable: Microsoft-Windows-Subsystem-Linux and VirtualMachinePlatform
> 2. After enable WSL, you didn't reboot the machine
> 
> You hit above message because pre-check failed. You have to enable WSL first, then install MSI.
> It's easy to verify if WSL enabled or not:
> 
> 1. check if `HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\LxssManager\parameters` exists
> 2. or `dir %SystemRoot%\system32\lxss\LxssManager.dll`

Hi, I'm using WSL for a long time it is working fine, when I try to change from WSL 1 to WSL 2 I'm facing issue 
and my virtualization is disabled and don't know how to enable it
2. or `dir %SystemRoot%\system32\lxss\LxssManager.dll` this exits in my machine

**Comment by licanhua** [comment]
What's your Windows version? WSL 2 is only available in Windows 10, Version 2004, Build 19041 or higher. 
You have LxssManager.dll but missing the regkey(MSI install error), so most likely you are using old OS which doesn't have WSL2 yet.

what do you mean `my virtualization is disabled`? You see error when run `dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart`

**Comment by Vishnu05** [comment]
![image](https://user-images.githubusercontent.com/32086222/85176857-6d7e7a80-b298-11ea-87b7-3e4639769a18.png)
![image](https://user-images.githubusercontent.com/32086222/85176956-a61e5400-b298-11ea-9dfd-a5dae683032c.png)
![image](https://user-images.githubusercontent.com/32086222/85176976-b3d3d980-b298-11ea-84fb-b57656ac9700.png)
![image](https://user-images.githubusercontent.com/32086222/85177238-54c29480-b299-11ea-94d9-5af982aee2d2.png)

I'm also updated the wsl 2, packages

**Comment by Vishnu05** [comment]
> What's your Windows version? WSL 2 is only available in Windows 10, Version 2004, Build 19041 or higher.
> You have LxssManager.dll but missing the regkey(MSI install error), so most likely you are using old OS which doesn't have WSL2 yet.
> 
> what do you mean `my virtualization is disabled`? You see error when run `dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart`

So I have tried some of the methods which are in docs, but still unable to switch, 
I don't know where I'm going wrong

**Comment by licanhua** [comment]
If you windows itself is a virtual machine, you have to have [nested virtualization enabled](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#can-i-run-wsl-2-in-a-virtual-machine) manually. Launch powershell with admin, and `Set-VMProcessor -VMName <VMName> -ExposeVirtualizationExtensions $true`

Otherwise it's very complex, and it depends on CPU module and what kind of physical machine you owns.  You can search keyword like 'microsoft how to enable virtualization in bios for HP x360'. I see a good articale https://mashtips.com/enable-virtualization-windows-10/

**Comment by Vishnu05** [comment]
> If you windows itself is a virtual machine, you have to have [nested virtualization enabled](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#can-i-run-wsl-2-in-a-virtual-machine) manually. Launch powershell with admin, and `Set-VMProcessor -VMName <VMName> -ExposeVirtualizationExtensions $true`
> 
> Otherwise it's very complex, and it depends on CPU module and what kind of physical machine you owns. You can search keyword like 'microsoft how to enable virtualization in bios for HP x360'. I see a good articale https://mashtips.com/enable-virtualization-windows-10/

I have enabled my virtualization by this article it is very help
Thanks a ton for the help, I almost struggled with this issue for more than 4 days it is resolved now,
I just have to enabled my virtualization, then everything works fine
Thanks again @licanhua  you have made my day!😊😊

**Comment by licanhua** [comment]
If you still hit `WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel`, please check this [Ship-WSL-2-Linux-Kernel wiki](https://github.com/microsoft/WSL/wiki/Ship-WSL-2-Linux-Kernel) first.

**Comment by mauroao** [comment]
> For WSL2 you will need 2 Windows components so make sure they are already enabled:
> `Microsoft-Windows-Subsystem-Linux`
> `VirtualMachinePlatform`
> 
> Also it seems some people have problems with the installer extracting the kernel.
> You can always extract it manually with:
> `msiexec /a "wsl_update_x64.msi" /qb TARGETDIR="C:\temp"`
> and then copy the `kernel` file from C:\temp to C:\Windows\System32\lxss\tools
> 
> Final version shouldn't have this problem since the install comes from Windows Update.

Thanks ! It worked fine to me

**Comment by frankiejgram** [comment]
@onomatopellan thanks for your solution! I had to click "Repair" on the file so it could generate a `license` file but after that, it worked.

**Comment by Sword-Smith** [comment]
> I solved my issue by elevating a command line and executing wsl_update_x64.msi from there.
This worked for me. Thank you @drphrozen

To be clear:
Open Windows Powershell with administrator rights and run the downloaded file `wsl_update_x64.msi`.

**Comment by OhhhZenix** [comment]
Can anyone help me?

Ive tried everything from every post i could find about how to fix it.

Im on the lastest window for wsl 2
i have both virtual and wsl on.
ive installed the wsl-update.msi and the kernel file is in the right location and installed properly
but whenever i go to change the version of the wsl to wsl 2 it would prompt me with that i need to install the wsl 2 update msi

any ideas how i can get wsl 2 to work?

**Comment by licanhua** [comment]
@OhhhZenix , What's your Windows version? Can you post the output of `dir %windir%\system32\lxss\tools\kernel`?
what's the error when you execute `wsl --set-default-version 2`?

**Comment by OhhhZenix** [comment]
> @OhhhZenix , What's your Windows version? Can you post the output of `dir %windir%\system32\lxss\tools\kernel`?
> what's the error when you execute `wsl --set-default-version 2`?

![image](https://user-images.githubusercontent.com/33815423/85487618-c8a6ba80-b581-11ea-94ad-c5493421670e.png)
![image](https://user-images.githubusercontent.com/33815423/85487673-e5db8900-b581-11ea-8bc5-5427baf42091.png)
![image](https://user-images.githubusercontent.com/33815423/85487699-f3910e80-b581-11ea-9606-7c686f54fb55.png)
![image](https://user-images.githubusercontent.com/33815423/85487720-ff7cd080-b581-11ea-8b4c-48d9e0865094.png)

**Comment by onomatopellan** [comment]
@OhhhZenix install any distro from the store and it should be version 2 already. Use `wsl.exe -l -v` to confirm the version of your distros.

**Comment by OhhhZenix** [comment]
> @OhhhZenix install any distro from the store and it should be version 2 already. Use `wsl.exe -l -v` to confirm the version of your distros.

lmao i didnt know welp thanks for the help it works <3

**Comment by stefanwendelmann** [comment]
We also discovered a permission problem, we needet to msiexec /i in admin console to install it

**Comment by licanhua** [comment]
yes. admin is required. May I ask why you installed it with msiexec other than double-click the msi?
As I know, the official document is double-click to install it which will ask you for elevated permission. If there are good reason to use msiexec, we should update that document too

**Comment by shortpoet** [comment]
I have been frustrated with this task all day.  Finally I came across this article. Apparently there's no way to enable the latest version of windows required for use with WSL2 and docker.  https://blogs.windows.com/windowsexperience/2020/05/27/how-to-get-the-windows-10-may-2020-update/  In docker settings you will see that latest windows build is required for WSL2.  For a reason unknown to me, my machine (despite running pro) is being throttled for the new release for now. Hopefully this helps save someone some frustration.

**Comment by UnusefulCoder** [comment]
Hello,

I'm using Windows 10, Build 20150.1000, enabled the features "Windows Subsystem for Linux" and "Virtual Machine Platform", the Task Manager and BIOS reports that Virtualization is enabled on my CPU and I've installed the kernel update (aka. wsl_update_x64.msi), but I can't change the version of a distro to wsl2; the message says: "Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.".

I guess what's missing on my CPU is Second Level Address Translation (SLAT), and this is something wsl2 needs... Is this true or is something else I forgot to do?

**Comment by onomatopellan** [comment]
@UnusefulCoder SLAT is a requirement for [anything Hyper-V related](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/system-requirements-for-hyper-v-on-windows#:~:text=on%20Windows%20Server.-,General%20requirements,the%20processor%20must%20have%20SLAT.). 
Because of a bug you are still able to enable WSL2 feature but it won't work. See #4709

**Comment by licanhua** [comment]
Did you install virtualbox or enable hyper-v or feature other than VirtualMachinePlatform on your machine before? Did you reboot the machine after VirtualMachinePlatform 

I may try disable VirtualMachinePlatform, reboot, then enable VirtualMachinePlatform again, and another reboot if needed. 
`
dism.exe /online /disable-feature /featurename:VirtualMachinePlatform
`

Do you want to restart the computer now? (Y/N) `y`

`
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
`

**Comment by py9mrg** [comment]
> > I solved my issue by elevating a command line and executing wsl_update_x64.msi from there.
> > This worked for me. Thank you @drphrozen
> 
> Running this program by double clicking on it did not work, only running it from PowerShell worked.
> 
> To be clear:
> Open Windows Powershell with administrator rights and run the downloaded file `wsl_update_x64.msi`.

Thank you, this is the only solution that worked for me. If I didn't do this then I would keep getting the same "...update only applies..." error no matter which of the troubleshooting methods I tried. The `msiexec /i "wsl_update_x64.msi"` command mentioned elsewhere didn't work either. I had to run only `.\wsl_update_x64.msi` in an elevated PS for it to work.

**Comment by licanhua** [comment]
@craigloewen-msft Please update the installation document, if user disabled UAC, there is no window popup and double click results failures. then user have to use elevated window to execute the msi

**Comment by asampal** [comment]
> For a reason unknown to me, my machine (despite running pro) is being throttled for the new release for now. Hopefully this helps save someone some frustration.

Have you tried to get it using the [Windows Update Assistant](https://support.microsoft.com/en-us/help/3159635/windows-10-update-assistant)?

**Comment by tgani** [comment]
I have Insider build 2004/19640.1. Here's what I see running identical commands via the Git MSYS based bash and via WSL2, running find on a /mnt drive:

Git Bash (MSYS based):

$ time find . -name '*~' >/dev/null

real    0m14.610s
user    0m4.296s
sys     0m10.203s

WSL2:

$ time find . -name '*~' >/dev/null

real    3m8.763s
user    0m3.894s
sys     0m40.197s

The WSL2 one is more than 12x slower.

**Comment by gobinda-tech** [comment]
> ok - i figured out the issue. the new update does not uninstall the old one (the slow insider ring one).
> 
> I right clicked the old msi - uninstalled it. now i can install the new one .

Thanks it works fine.

**Comment by tazyman** [comment]
@onomatopellan Thanks! That worked for me :)

**Comment by shortpoet** [comment]
> 
> 
> > For a reason unknown to me, my machine (despite running pro) is being throttled for the new release for now. Hopefully this helps save someone some frustration.
> 
> @shortpoet Have you tried to get it using the [Windows Update Assistant](https://support.microsoft.com/en-us/help/3159635/windows-10-update-assistant)?

@asampal thank you very much that seems to be working!! 😊

**Comment by sharshil98** [comment]
> * Your Windows build number:  `Microsoft Windows [Version 10.0.19041.153]`
> * What you're doing and what's happening:
>   I'm starting Ubuntu for Windows and I immediately receive the following message:
>   `WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel`.
>   This has happened before, so I simply go to the website mentioned and download the update. No big deal. But when I run the update this message pops up: `This update only applies to machines with the Windows Subsytem for Linux` (there's a small typo in the message, by the way).
> 
> What do I do now? Seems I'm stuck between updates...



> * Your Windows build number:  `Microsoft Windows [Version 10.0.19041.153]`
> * What you're doing and what's happening:
>   I'm starting Ubuntu for Windows and I immediately receive the following message:
>   `WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel`.
>   This has happened before, so I simply go to the website mentioned and download the update. No big deal. But when I run the update this message pops up: `This update only applies to machines with the Windows Subsytem for Linux` (there's a small typo in the message, by the way).
> 
> What do I do now? Seems I'm stuck between updates...



just don't try to install MSI. right click on install and select "repair" option.
after selecting option "nothing shows up", but wsl got repaired.
it worked for me, i hope it work for you also.

**Comment by RonGros** [comment]
I had the same issue with build 19041.388, luckily I had the old MSI so uninstalled it and installed the new one....

**Comment by AdminTurnedDevOps** [comment]
Figured this out if anyone else runs into the issue. You have to go into Programs and Features and uninstall the old WSL update. Apparently if the old update is still there, you can't install the new WSL2 kernel update.

**Comment by absyah** [comment]
I did these steps and worked just fine:

- Download **wsl_update_x64.msi** from https://aka.ms/wsl2kernel
- Right-click  **wsl_update_x64.msi** and select "uninstall", you will see a popup that says `This update only applies to ...`.  Ignore it / click "OK"
- Right-click **wsl_update_x64.msi** and select "install".

**Comment by Manvityagi** [comment]
> I saw the error "the update only applies to machines with the Windows Subsytem for Linux".
> 
> Reading this thread I saw advice to uninstall the old installer. I couldn't find any old installer, so I right clicked the newly downloaded wsl_update_x64.msi file and selected "uninstall". It successfully uninstalled. Then I right clicked it again and selected install, and no longer saw "the update only applies to machines with the Windows Subsytem for Linux" error. It installed successfully. @_@

This worked for me too!! Thanks

**Comment by ismailmamatov** [comment]
> Solved issue for me. The problem was the path "C:\Users<UserName>\Downloads\wsl_update_x64.msi" to msi installation file.
> I copied file to "C:\Temp\wsl_update_x64.msi", double-clicked and was installed OK.

thanks man! saved my time.

**Comment by Deepika-Sharma08** [comment]
I had same issue.. uninstalling and reinstalling helped me solve the issue.
In fact, I had two different WSL installed in my system which I previously installed.
I uninstalled previous versions and reinstalled wsl 2 followed by running wsl_update_x64.msi manually, which fixed the issue for me.

Hope this helps someone else who also installed WSL2 in order to run Alpinewsl.

**Comment by coolaj86** [comment]
# PowerScript Install

After much trial and error, I think I figured out a reliably way to install WSL, WSL2, and Ubuntu:

- https://webinstall.dev/wsl/
    - https://webinstall.dev/wsl1/
    - https://webinstall.dev/wsl2/

# Almost 100% CLI, Almost one-shot.

Unfortunately, I couldn't find out how to
- one-shot without a reboot between WSL 1 and WSL 2
- cause Ubuntu to complete its install process without asking the user to click on it in the Start Menu

If anyone has a solution to those, please let me know:
https://github.com/webinstall/packages/issues

I'd 
I'd love

**Comment by Key2Love** [comment]
> What's your Windows velirsion? WSL 2 is only available in Windows 10, Version 2004, Build 19041 or higher.
> You have LxssManager.dll but missing the regkey(MSI install error), so most likely you are using old OS which doesn't have WSL2 yet.
> 
> what do you mean `my virtualization is disabled`? You see error when run `dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart`

@licanhua 
![image](https://user-images.githubusercontent.com/33833308/98468288-cda89580-2214-11eb-9dbe-c008449bed38.png)
From the doc i see it requires version 1904 on x86 , is the doc out-of-date ? I run the msi file in version 1904 but it does not work.

**Comment by licanhua** [comment]
1909 should be also be 18383.1049 or high. Maybe the document didn't communicate this clear

![image](https://user-images.githubusercontent.com/6290692/98471963-969a9b80-21a4-11eb-8dab-7e3b68bf5d4b.png)

**Comment by feederaccount** [comment]
I am running 1909 with build number 18363.778 and was getting this error when it came to installing `wsl_update_x64.msi`.

The issue resolved when I rebooted my machine, during which Windows installed some updates.

**Comment by onomatopellan** [comment]
@feederaccount You are in 18363.**778** and you need at least 18363.**1049**. For that you need to install the latest KB update available. It should appear in Windows Update but also can be installed manually from https://www.catalog.update.microsoft.com/Search.aspx?q=KB4586786

**Comment by sonook** [comment]
Hope my below video can help in this regard.

https://youtu.be/4czn-4uu65c

**Comment by saruults** [comment]
After rebooting it worked for me

**Comment by gabrielgrant** [comment]
I was running into this issue during a fresh install of WSL (2) while following the instructions at: https://docs.microsoft.com/en-us/windows/wsl/install-win10

It turns out the issue was that I had missed the instruction to restart after enabling WSL and as part of enabling Virtualization ([step 3](https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-3---enable-virtual-machine-feature))

![image](https://user-images.githubusercontent.com/493968/114327495-4b940400-9b07-11eb-93ae-500d052f087f.png)


Certainly kinda my fault for moving too quickly and not reading thoroughly, but should really just be Step 4, or at least would be nice if [the bold text in step 1 telling you to not restart now](https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-1---enable-the-windows-subsystem-for-linux) instead said "wait to restart _until after step 3 (or until 4)_":

![image](https://user-images.githubusercontent.com/493968/114327583-aa597d80-9b07-11eb-9333-10abb9009961.png)

In addition, while trying @onomatopellan 's [advice above](https://github.com/microsoft/WSL/issues/5014#issuecomment-605243281) to extract the kernel manually, ran into the following error:

```
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2203.
```

It turns out the problem was that I had downloaded the MSI into the C:\Temp directory, and was also trying to extract it into that same folder. Apparently the folder in which the MSI is located gets locked during extraction, causing this failure. Creating a subdirectory and extracting into that instead worked. (thanks for [this Stack Overflow answer](https://stackoverflow.com/a/25166792) for pointing me in the right direction on this one)

**Comment by Joshfindit** [comment]
Would also like to add to the "we can all do it" pile:

![image](https://user-images.githubusercontent.com/1937155/118367082-4ea36980-b577-11eb-8b44-795427ce82cc.png)


This is at the bottom of the install page in the Troubleshooting section, and I _still_ got to this thread before rebooting.

**Comment by xumarcus** [comment]
The installer linked above does not work (This installation package could not be opened). Troubleshooter says it's incompatible and Orca cannot open it. (Version: 10.0.19043) WSL2 eventually works through Windows update -> Advanced Options -> Receive updates ... though.

**Comment by alexhaydock** [comment]
> I was running into this issue during a fresh install of WSL (2) while following the instructions at: https://docs.microsoft.com/en-us/windows/wsl/install-win10
> 
> It turns out the issue was that I had missed the instruction to restart after enabling WSL and as part of enabling Virtualization ([step 3](https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-3---enable-virtual-machine-feature))

I got bitten by this one just now, even though I was 100% certain I'd rebooted since enabling the features in Step 1 and 3. I'm not a frequent Windows user so what I apparently missed is that shutting down and then starting the machine back up later is **not** the same as a restart because it's more of a pseudo-hibernation these days. After a proper restart everything works fine.

Just putting this here in case anyone else is battling the same issue under the same circumstances.

**Comment by AliAlhajji** [comment]
I was having the same problem.  Uninstalling was not an option for me since I had not installed it previously.

Restarting the machine worked for me :)

**Comment by KorigamiK** [comment]
> For WSL2 you will need 2 Windows components so make sure they are already enabled:
> `Microsoft-Windows-Subsystem-Linux`
> `VirtualMachinePlatform`
> 
> Also it seems some people have problems with the installer extracting the kernel.
> You can always extract it manually with:
> `msiexec /a "wsl_update_x64.msi" /qb TARGETDIR="C:\temp"`
> and then copy the `kernel` file from C:\temp to C:\Windows\System32\lxss\tools
> 
> Final version shouldn't have this problem since the install comes from Windows Update.

God damn it! I had didn't realize that I had to install the update manually for wsl2. I'm glad that it's working now.

**Comment by ilayatshah** [comment]
I tried all of the above nothing worked for me. The only thing which worked for me was to manually type "feature" in the window search bar and click on the "Turn Windows features on or off". I unchecked both the "virtual machine platform" and "windows subsystem for Linux". Clicked ok and then restarted my computer. Again I followed the same procedure but this time I checked both the feature and again restarted my computer. Now I can install the downloaded MSI.

**Comment by Dev-Soumyaranjan** [comment]
> @friday963 Something is broken in your install. Follow this and try again: https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed
> 
> BTW the msi file you need is here https://aka.ms/wsl2kernel

Thanks It worked for me

**Comment by ZakhN** [comment]
i just removed 'Windows Subsystem For Windows' from Settings -> Apps
Than i installed wsl_update.msi again and it's worked well for me

**Comment by slonopotamus** [comment]
I just uninstalled Windows, installed Linux and everything worked fine for me since that day.

**Comment by junxian428** [comment]
wsl --update

**Comment by ilham76c** [comment]
> I'm running on the same issue.
> 
> **Running on** **Win version: 2004, Compilation: 19640.1**
> 
> Here are the steps I did:
> 
> Power Shell:
> 
> * Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
> * dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
> * dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
> 
> Microsoft Store:
> 
> * Get the Ubuntu (Plain , not the 18 or 20 dist)
> 
> After install the Ubuntu and restart pc, on CMD:
> 
> * system32>wsl -l -v
> 
> It shows: NAME STATE VERSION Ubuntu Stopped 1
> 
> Then, update the WSL2 Kernel:
> 
> * Download and installed [wsl2 kernel](https://docs.microsoft.com/pt-br/windows/wsl/wsl2-kernel)
> 
> Back to CMD:
> 
> * wsl --set-version Ubuntu 2
> 
> The error prompts:
> 
> * WSL2 requires an update to you Kernel component. To get more info please go to [aka ms](https://aka.ms/wsl2kernel).
> 
> Checking the version and stays on Version 1:
> 
> * system32>wsl -l -v
> 
> NAME STATE VERSION Ubuntu Stopped 1
> 
> Tried to uninstall the manual update to WSL2 and installing it again, but the error keeps the same.
> 
> How can I solve this?



> I'm running on the same issue.
> 
> **Running on** **Win version: 2004, Compilation: 19640.1**
> 
> Here are the steps I did:
> 
> Power Shell:
> 
> * Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
> * dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
> * dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
> 
> Microsoft Store:
> 
> * Get the Ubuntu (Plain , not the 18 or 20 dist)
> 
> After install the Ubuntu and restart pc, on CMD:
> 
> * system32>wsl -l -v
> 
> It shows: NAME STATE VERSION Ubuntu Stopped 1
> 
> Then, update the WSL2 Kernel:
> 
> * Download and installed [wsl2 kernel](https://docs.microsoft.com/pt-br/windows/wsl/wsl2-kernel)
> 
> Back to CMD:
> 
> * wsl --set-version Ubuntu 2
> 
> The error prompts:
> 
> * WSL2 requires an update to you Kernel component. To get more info please go to [aka ms](https://aka.ms/wsl2kernel).
> 
> Checking the version and stays on Version 1:
> 
> * system32>wsl -l -v
> 
> NAME STATE VERSION Ubuntu Stopped 1
> 
> Tried to uninstall the manual update to WSL2 and installing it again, but the error keeps the same.
> 
> How can I solve this?

thanks, I just downloaded the [wsl2 kernel](https://docs.microsoft.com/pt-br/windows/wsl/wsl2-kernel) then installed it, and all problems solved.

**Comment by schuberng** [comment]
> @friday963 Something is broken in your install. Follow this and try again: https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed
> 
> BTW the msi file you need is here https://aka.ms/wsl2kernel

I should say thank you for posting a tool that help fixing issues for program improperly uninstalled. Long story for short, back in days when I first touched cli and tried to remove program files with cli. After applied cli to adobe pdf reader directory, I found out pdf reader could not either be installed and uninstalled, because of my false operation. 

So, this problem sits for years, until finally I came across your answer and my pdf reader come back to life again. I know this sounds really stupid to most of you, but at least I got lesson learned by mistakes.

**Comment by neilwang0913** [comment]
I think you might also need to run in admin for the 1st time.

**Comment by mobentu** [comment]
it's very simple
after install and check all requirement
type `wsl --update` then `wsl --install`
done

**Comment by drakem58** [comment]
I am running Windows 11 not 10 and ran into the same display after installing Ubuntu, "WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel."  Went to the website, downloaded the fix, reran ubuntu and it works now.

**Comment by kangarooo** [comment]
Removed Ubuntu, WSL update, WSL in Add windows features deselected WSL
Restart
Installed in Features WSL
Restart
Did https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package
Installed update
Restart
Opened WSL
Didnt open
In store opened Ubuntu 22.04.3
Installed
WORKS

It should fix it all automatically instead of manually guessing and removing all

**Comment by Lakshan-Madushanka** [comment]
Open the power shell and run the command `wsl.exe --install` worked for me.

**Comment by goyaoyuanchun** [comment]
> > @friday963 Something is broken in your install. Follow this and try again: https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed
> > BTW the msi file you need is here https://aka.ms/wsl2kernel
> 
> You're right @onomatopellan , I needed to uninstall with that tool. Thanks for the help!

this works for me : https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package

**Comment by itsmejyv** [comment]
This error happens to me also in Windows 11, this is [Manual Installation](https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package ) will fix it, just make sure you enabled WSL on windows feature configuration. There's also included command there to enable virtual machine feature if ever you forgot to enable it.

**Comment by Harsh-1Byte** [comment]
Hey Folks!

**Comment by Harsh-1Byte** [comment]
Hey Folks 
I found my solution to my problem at this wonderful article below do check it out:
https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package

**Comment by wesandradealves** [comment]
> [@friday963](https://github.com/friday963) Something is broken in your install. Follow this and try again: https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed
> 
> BTW the msi file you need is here https://aka.ms/wsl2kernel

Nice approach. I've tried a bunch of other solutions but no success at all. I just ran this troubleshooter, selected the subsystem and it uninstalled properly so I could run the wsl command again with success.
