### ISSUE TITLE
X apps running in WSL randomly stop displaying on X Server in Windows host

### ISSUE THREAD

**Issue by gitbls** [microsoft/WSL#5339]
# Environment

```
Windows build number: Version 10.0.19041.264
Your Distribution version: Debian from the Windows Store with apt update/upgrade done
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

1) Start an Xserver on the Windows system. I've reproduced this with both Xming and the Cygwin Xserver and with 3 or 4 different X apps (xterm, xclock, xcolors, for instance)

2) Start the Debian WSL app using the icon created when Debian installed

3) `ping hostip` (192.168.xx.32 in my case) to confirm. It works.

4) `DISPLAY=192.168.xx.32:0 xterm &`

#  Expected behavior

The X app displays on the host through the Xserver. X app continues to run until I kill the Xserver or the app.  Happiness throughout the kingdom.

# Actual behavior

At some random point later, the xterm window simply disppears, with no action on my part. This seems to take a few hours sometimes. 

A `ps aux` in Debian still shows the xterm process as active.

I have tried doing some logging to capture the exact timing, but since the xterm and bash processes are still running, it's difficult to determine exactly when the app stopped displaying.

**Comment by gitbls** [comment]
I should add that xterms displaying on the same Xserver continue to work correctly and do not disconnect when the Debian xterm does.

**Comment by therealkenc** [comment]
![image](https://user-images.githubusercontent.com/7049700/83909587-ec62a780-a71d-11ea-8df5-cf926b308a2f.png)

**Comment by gitbls** [comment]
Thanks for the response. So, it's something I'm doing, but I can't imagine what.

I set up a new desktop system since I wrote this issue 2 days ago, and the new system has the same behavior! Here are some screen shots that I hope help demonstrate it.

I'd definitely appreciate assistance or suggestions to chase this down!

![image](https://user-images.githubusercontent.com/10481163/83957032-d7b70a00-a818-11ea-8f3a-559cba46b275.png)

![image](https://user-images.githubusercontent.com/10481163/83957034-de458180-a818-11ea-96fd-503597af1670.png)

![image](https://user-images.githubusercontent.com/10481163/83957036-e43b6280-a818-11ea-9dac-a6354396353a.png)

**Comment by therealkenc** [comment]
> So, it's something I'm doing, but I can't imagine what.

Not necessarily. I just don't have a repro (which is, counterintuitively, unfortunate).

Okay so if I am following, the two xterms (PID 88 and 122) were alive at 3:30, but one disappeared by 4:47. But the xterms are still running. That is good context, thank you.

Do a fav and re-run the same test as I did: which was, start a `xterm &` from a command prompt and go to bed. Whatever a '`doit`' is, don't. Before and after starting `xterm`, run `netstat` on both sides to see what those TCP connections are up to, like this:

![image](https://user-images.githubusercontent.com/7049700/83957950-3a140880-a821-11ea-83b1-4beaa0c3fcb1.png)

My run was with with VcXsrv. You can try that too, although I don't seriously think that's the variable.

If it survives the night maybe we can start identifying the variable. If it doesn't survive, and you didn't take any action (for real) on either the Windows side or the WSL side before looking at the screen to see if it was still alive, this gets more forlorn to track down.

**Comment by gitbls** [comment]
Thx! I was going to script something in doit, but didn't, so doit didn't do it ;)

I installed the latest vcxsrv and fired off a test with 2 xterms and a starting netstat. Will see how it does in the morning and update.

**Comment by gitbls** [comment]
As I mentioned, I started 2 xterms. After 12 hours, one of the xterms had disappeared from the screen, and the other one was still alive and working.

bls@MS-scout~> date
Sat 06 Jun 2020 06:36:32 PM PDT
bls@MS-scout~> netstat > netstat-start.log
bls@MS-scout~> date
Sun 07 Jun 2020 07:37:51 AM PDT
bls@MS-scout~> netstat > netstat-end.log
bls@MS-scout~> jobs
[1]-  Running                 xterm &
[2]+  Running                 xterm &
bls@MS-scout~> cat netstat-start.log
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 172.21.137.111:50756    scout.starwhite.net:x11 ESTABLISHED
tcp        0      0 172.21.137.111:50754    scout.starwhite.net:x11 ESTABLISHED
Active UNIX domain sockets (w/o servers)
Proto RefCnt Flags       Type       State         I-Node   Path
bls@MS-scout~> cat netstat-end.log
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 172.21.137.111:50756    scout.starwhite.net:x11 ESTABLISHED
tcp        0      0 172.21.137.111:50754    scout.starwhite.net:x11 ESTABLISHED
Active UNIX domain sockets (w/o servers)
Proto RefCnt Flags       Type       State         I-Node   Path
bls@MS-scout~>

**Comment by gitbls** [comment]
Re-opening since I hit the wrong button. Sigh!

**Comment by gitbls** [comment]
From the Windows side:

c:\bls> netstat /an | grep 6000
  TCP    0.0.0.0:6000           0.0.0.0:0              LISTENING
  TCP    127.0.0.1:6000         127.0.0.1:64630        ESTABLISHED
  TCP    127.0.0.1:6000         127.0.0.1:64631        ESTABLISHED
  TCP    127.0.0.1:6000         127.0.0.1:64632        ESTABLISHED
  TCP    127.0.0.1:64630        127.0.0.1:6000         ESTABLISHED
  TCP    127.0.0.1:64631        127.0.0.1:6000         ESTABLISHED
  TCP    127.0.0.1:64632        127.0.0.1:6000         ESTABLISHED
  TCP    [::]:6000              [::]:0                 LISTENING

c:\bls>

**Comment by therealkenc** [comment]
Thanks. First, what the third thing you launched (not that it matters much). And what else do you have running. `pstree -p`. 

With VcXsrv at least (probably the other servers too) you get two stacked taskbar icons. Do you have two (or three) or did the icons go down with the missing xterm. You can also maybe look at the VcXsrv logs and see if they show anything interesting. Looks like this:

![image](https://user-images.githubusercontent.com/7049700/83973782-69685b00-a89d-11ea-877f-5e6af7b72838.png)

I'll do a run with more than one X11 client myself tonight (if I remember). Don't have high hopes, I forget to close X clients all the time (OTOH I probably wouldn't notice if one disapeared). But at least we'll be in sync.

**Comment by gitbls** [comment]
The only other thing running is another Debian console window (created from the Debian item in the menu). Here's pstree -A -p

bls@MS-scout/bls> pstree -A -p
init(1)-+-init(8)---init(9)-+-bash(10)
        |                    -ssh-agent(62)
        |-init(163)---init(164)---bash(165)---pstree(243)
         -{init}(7)
bls@MS-scout/bls>

There were 2 stacked taskbar icons for the xterms when I started them, but I didn't notice if there were one or two this morning. Guessing there was only one, since the window had disappeared.

The VcXsrv log doesn't have anything useful, just the usual X garp.

One interesting thing: the 2nd xterm window went away this morning while I was out of the office, and there were two actual 'xterm: fatal IO error 110 (connection timed out) error in the Debian console window, and as expected, the jobs no longer show up with a 'jobs' command.

I'll do a Windows reboot and restart the test later this morning...let me know if there's anything else you'd like me to do for this one,.

**Comment by therealkenc** [comment]
Well you've gotta have the two xterms at least (although I guess they are long gone).

We're going to need to start over. I only just clued in that `netstat.exe` has no connections to WSL, only three spurrious `127.0.0.1`. Your starting position should look like this:

![image](https://user-images.githubusercontent.com/7049700/83975191-607c8700-a8a7-11ea-8f77-bc2346232cfc.png)


That's two sockets on the WSL side, and matching two on the Windows side. The point is to get a before and after, and see if the Windows side is still established or went away.

**Comment by therealkenc** [comment]
> xterm: fatal IO error 110 (connection timed out) error in the Debian console

That's useful, but also complicates things. That isn't the same situation as yesterday; the xterms were both still running and did not error out. Normally with that error above I'd shrug and say "dunno ask the people who maintain your X server of choice". But that's not it. Frustratingly, it is also hard to finger-point WSL networking (which is the usual suspect and this thread would be shorter). If your whole network went down (because the box hibernated is popular) it would take down both clients not just one. And they wouldn't be running.

**Comment by gitbls** [comment]
I'm setting up to do a full end-to-end clean run test with plenty of netstats along the way. Will report back with details. I realize that this isn't super-easy to solve, and really appreciate your time on this. 

A couple of questions: I'm using DISPLAY set to the Windows LAN IP address (192.168.92.7 in my case). Is that the case for your test as well? Is 172.26.16.1 the LAN IP address of the Windows host? Also, it appears that you have VcXsrv listening on 0.0.0.0, while mine is on 127.0.0.1. What are you using as the Listen address for VcXsrv.

Finally, I have not added any port proxies in the Hyper-V network infrastructure. I assume you don't have any either?

As far as the xterm connection timed out error, I've seen that happen a couple of other times, not at the same time as the xterm window disappears. Very strange!

**Comment by therealkenc** [comment]
> Is that the case for your test as well? Is 172.26.16.1 the LAN IP

Yes that is the only way to do it. I would have added the `DISPLAY=` line in my screencap yesterday (almost stepped back and did) but I already new you made it that far.

> Also, it appears that you have VcXsrv listening on 0.0.0.0, while mine is on 127.0.0.1. 

No yours is listening on zeros also, unless you pasted incorrectly. I am not even sure if there is a way to get VcXsrv to do otherwise without extraordinary steps (additional commandline flags maybe) but there is no way you are doing that.

![image](https://user-images.githubusercontent.com/7049700/83979098-b7db2100-a8c0-11ea-93e9-f26b061fcc3c.png)

> Finally, I have not added any port proxies in the Hyper-V network infrastructure. I assume you don't have any either?

No nothing special (which is where you want to be too).

**Comment by gitbls** [comment]
Yes, you're correct, of course, that I'm listening on 0.0.0.0 as well, and I've not added any VcXsrv command-line switches.

I ran another test last night. netstats follow. I started the test just after 8pm, and both xterms had disappeared from the screen when I re-checked at 9:47pm, but the xterms were still running as previously. By the following morning, the xterms had actually exited with _fatal error 110 (connection timed out)_. At each step, in the Debian WSL I captured the output of:

    netstat -an | grep 6000
    netstat.exe /an | grep 6000 | grep -v "127.0.0.1"

**Stage starting - VcXsrv started, but no X apps started**
Sun 07 Jun 2020 08:04:01 PM PDT
_WSL_
(no connections)
_Windows_
TCP    0.0.0.0:6000           0.0.0.0:0              LISTENING
TCP    [::]:6000              [::]:0                 LISTENING

**Stage xt1-started - After starting the first xterm**
Sun 07 Jun 2020 08:04:50 PM PDT
_WSL_
tcp        0      0 172.22.242.165:48242    192.168.92.7:6000       ESTABLISHED
_Windows_
  TCP    0.0.0.0:6000           0.0.0.0:0              LISTENING
  TCP    192.168.92.7:6000      192.168.92.7:60852     ESTABLISHED
  TCP    [::]:6000              [::]:0                 LISTENING

**Stage xt2-started - After starting the second xterm**
Sun 07 Jun 2020 08:05:39 PM PDT
_WSL_
tcp        0      0 172.22.242.165:48242    192.168.92.7:6000       ESTABLISHED
tcp        0      0 172.22.242.165:48244    192.168.92.7:6000       ESTABLISHED
_Windows_
  TCP    0.0.0.0:6000           0.0.0.0:0              LISTENING
  TCP    192.168.92.7:6000      192.168.92.7:60852     ESTABLISHED
  TCP    192.168.92.7:6000      192.168.92.7:60854     ESTABLISHED
  TCP    [::]:6000              [::]:0                 LISTENING

**Stage xt-disconnected - Both xterms had disappeared from the screen**
Sun 07 Jun 2020 09:47:00 PM PDT
_WSL_
tcp        0      0 172.22.242.165:48242    192.168.92.7:6000       ESTABLISHED
tcp        0      0 172.22.242.165:48244    192.168.92.7:6000       ESTABLISHED
_Windows_
  TCP    0.0.0.0:6000           0.0.0.0:0              LISTENING
  TCP    [::]:6000              [::]:0                 LISTENING

**Stage xt-fataled-out - Boh xterms had exited with fatal error 110**
Mon 08 Jun 2020 07:07:57 AM PDT
_WSL_
(no connections)
_Windows_
  TCP    0.0.0.0:6000           0.0.0.0:0              LISTENING
  TCP    [::]:6000              [::]:0                 LISTENING

**Comment by therealkenc** [comment]
Thank-you for the detailed follow up. My two xterms have been up for ~24 hours now, but we both pretty much knew that would be the case going in.

Your results are what I suspected (but needed to see). It is about the worst-case scenario for tracking down your variable. The Windows end of the TCP connection went away, but didn't do a close handshake (that the WSL side received anyway). Analogy here is if you had the X server on one machine, the client `xterm` on another machine, and unplugged the ethernet cable. That's why I wanted to pursue this. It isn't (scare quote) "WSL" in the Linux kernel sense. It isn't your X server. It sure ain't `xterm`.

The question is how your rig got in such a state, and needless to say I can't guess and neither can you. End-game here is to confirm, which absolute metaphysical certainty, you aren't running anything third-party like AV software or VPN software or firewall software, or anything third-party that would install a Windows kernel driver. Then submit network logs following (9) in [contributing.md](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md). The "Recreate your problem in the 'Additional Details' section" phase, which for you seems to take a couple of hours, is doing the above again. That's tricky (and unusual) because more commonly a network problem manifests hard and fast. But collecting network logs is about the last chance saloon here. 

You could in principle try to collect [wireshark](https://www.wireshark.org/) logs on port 6000 on both sides, but frankly I don't think that would demonstrate anything we don't already know by deduction.

Your best hope, really, is to get some me2s that help identify the variable. I'll drop the need-repro tag since you've done all you can, short the network logs via feedback hub.

**Comment by gitbls** [comment]
Thanks! Will sort that out and get it done in the next couple of days.

**Comment by WSLUser** [comment]
The first thing I'd check for any WSL2 related issues is memory consumption. Even network bandwidth requires some memory to start with and WSL2 will by default use everything at it's disposal (which is everything Windows has). Try limiting your RAM by half using .wslconfig. Then see if it dies overnight or if it takes less time before being consumed.

**Comment by therealkenc** [comment]
Open or closed is pretty academic in this instance. Close if you want it off your books (are moving on). Leaving it open is fine to. If nothing comes of this (ie a total absence of me2s arrive that are plausibly the same problem as you) it will get closed at some interminate time in the future either way. Your pleasure.

**Comment by alexvorobiev** [comment]
I have similar issue but only when Windows goes  to sleep. I then found this FAQ for x410: https://x410.dev/cookbook/wsl/using-x410-with-wsl2 at the very end.

**Comment by therealkenc** [comment]
The LZ for sleep/standby is #5021.

**Comment by aspen** [comment]
I seem to be having a possibly similar issue on 19042.487 and WSL2 (Ubuntu) with VcXSrv.

Some windows (an xfce4-terminal and IntelliJ) seem to occasionally disappear. The first time this happened there was a system sleep involved, but just now it happened maybe only 10 minutes into using the applications. No notable errors in VcXSrv or WSL but I too will see what I can find.

**Comment by johan718** [comment]
> 3\. `ping hostip` (192.168.xx.32 in my case) to confirm. It works.

When I ping my host IP, nothing happens.

Ubuntu 20.04 with WSL2

**Comment by gkamendje** [comment]
I have the same problem. I am running Win 10 2004 Build 19041.508 with WSL2 Ubuntu 18.04. My X11 apps crash with ` Fatal IO error 110 (Connection timed out) on X server`. I noticed that it happens most of the time when I recover from hibernation. At the beginning I thought it was an issue with the X server (Mobaxterm) that I was using. I switched to VcXSrv and I had the same issue. 
Although quite rare, I noticed that the problem sometime happens when I do not put the machine in hibernation. 
I had never seen the issue while I was running with WSL1.

**Comment by alexvorobiev** [comment]
The current workaround seems to be to use [X2Go](https://wiki.x2go.org/doku.php). I haven't tried that yet.

**Comment by nbdd0121** [comment]
This and #4675 both seems to be Windows dropping non-loopback TCP connections when wake-up from hibernation or when network changes. Because WSL2 networking goes through the WSL bridge, it is not loopback so Windows will reset it. AFAIK there is no easy way to change this behaviour.

The obvious workaround is using xpra or x2go which will reconnect when connection goes out. However in my experience they have much higher latency, are not as stable as raw X11 server and I frequently run into issues and need to restart/reconnect.

I ended up writing my own workaround which uses AF_VSOCK https://github.com/nbdd0121/x11-over-vsock.

**Comment by gitbls** [comment]
> This and #4675 both seems to be Windows dropping non-loopback TCP connections when wake-up from hibernation or when network changes. Because WSL2 networking goes through the WSL bridge, it is not loopback so Windows will reset it. AFAIK there is no easy way to change this behaviour.
> 
> The obvious workaround is using xpra or x2go which will reconnect when connection goes out. However in my experience they have much higher latency, are not as stable as raw X11 server and I frequently run into issues and need to restart/reconnect.
> 
> I ended up writing my own workaround which uses AF_VSOCK https://github.com/nbdd0121/x11-over-vsock.

While this may be your problem, in my case (the base note) there is no hibernation or network change involved at all.

**Comment by nbdd0121** [comment]
> While this may be your problem, in my case (the base note) there is no hibernation or network change involved at all.

Based on the discussion above I thought your issue is also network related? Sometimes a network change might be difficult to notice (e.g. WiFi reassociation, IP change, etc). I previously also had seemingly random X connection drop (my PC is connected via WiFi), and with my workaround I haven't observe any drop so far.

**Comment by gitbls** [comment]
> > While this may be your problem, in my case (the base note) there is no hibernation or network change involved at all.
> 
> Based on the discussion above I thought your issue is also network related? Sometimes a network change might be difficult to notice (e.g. WiFi reassociation, IP change, etc). I previously also had seemingly random X connection drop (my PC is connected via WiFi), and with my workaround I haven't observe any drop so far.

It obviously IS network-related, but nothing to do with a network change since all the systems are hardwired on a reliable LAN. I have seen it on 3 different systems here, at different times. My not-very-educated guess is that it's something to do with the Hyper-V switch. Hopefully @therealkenc and the rest of the team will reveal the solution to this mystery someday. Keep those cards and letters coming!

**Comment by JBPlinn** [comment]
Same issue: terminal closes unexpectedly after a certain amount of time...

**Comment by vkopanja** [comment]
Happens to me as well, using WSL2 on Ubuntu. I run my IntelliJ IDEA, and sometimes it just randomly closes and I have no way to reopen it.

**Comment by kportertx** [comment]
Also same issue on WSL2 & ubuntu20, but I didn't start noticing it until I needed to connect to a VPN (OpenVPN) for work.

**Comment by kportertx** [comment]
Solved (I hope). Issue seems to be caused by X11 timeouts. I've added [`ForwardX11Timeout 14d`](https://www.man7.org/linux/man-pages/man5/ssh_config.5.html) to `~/.ssh/config` and my windows was survived for 7 hours (so far). 

Note, setting `ForwardX11Timeout` to `0` will disable the timeout functionality, which I'll likely change to later.

My `~/.ssh/config`:
```
cat ~/.ssh/config
ForwardAgent yes
ForwardX11Timeout 14d
```

**Comment by gitbls** [comment]
> Solved (I hope). Issue seems to be caused by X11 timeouts. I've added [`ForwardX11Timeout 14d`](https://www.man7.org/linux/man-pages/man5/ssh_config.5.html) to `~/.ssh/config` and my windows was survived for 7 hours (so far).
> 
> Note, setting `ForwardX11Timeout` to `0` will disable the timeout functionality, which I'll likely change to later.
> 
> My `~/.ssh/config`:
> 
> ```
> cat ~/.ssh/config
> ForwardAgent yes
> ForwardX11Timeout 14d
> ```

Great to hear this solves your problem, but my issue had no ssh involved. That said, I haven't tried to repro my problem in a while, so giving it another go. Will report back in a few days after I see how it does.

**Comment by kportertx** [comment]
Are you sure you aren't using ssh. I have little experience with remote x session, but according to [this semi-reliable source](https://unix.stackexchange.com/a/44824/36465) you have to do additional configuration to allow non-ssh connections.

Btw, just checked my machine after being afk for 2.5 hrs, still running.

**Comment by gitbls** [comment]
> Are you sure you aren't using ssh. I have little experience with remote x sessions, but according to [this semi-reliable source](https://unix.stackexchange.com/a/44824/36465) you have to do additional configuration to allow non-ssh connections.
> 
> Btw, just checked my machine after being afk for 2.5 hrs, still running.

Yes, 100% sure. I open a Debian window and from that command line I start an xterm that displays on my xming Xserver running on the Windows box. The xterm comes up fine. There is no ssh running anywhere in this process.

Unfortunately, after about 2 hours, the xterm windows disappeared. The xterm processes still show up in a 'ps ux' done in the Debian command window, though, just like they did before. So, in spite of my fervent hope that this magically got corrected, no joy.

**Comment by kportertx** [comment]
You are right, I'm basically doing the same as you describe and shh isn't involved (confirmed being clear text with wireshark). So the reason for this issue  why the issue for me is a bit of a mystery.

**Comment by kportertx** [comment]
Possibly related.

I noticed when I disconnect from WiFi that my X11 windows would close. This was because I was using the IP address assigned to this interface for the `DISPLAY` variable. Switching to the IP address assigned to the virtual interface labeled "WSL" resolves this particular issue.

**Comment by kportertx** [comment]
I'm now using my local equivalent to `vEthernet (WSL) 172.31.48.1`. Apparently my xserver is listening on that interface as well.

**Comment by kportertx** [comment]
I'm not sure where the interface the xserver is listening on is configured. I'm using [GWSL](https://opticos.github.io/gwsl/tutorials/download.html) which uses VCXSRV.

**Comment by vinodatpu** [comment]
Me2. I have Windows 10 Pro 20H2 (OS build 19042.746) with WSL2 and Ubuntu 20.04 guest. Windows host has a static IP=192.168.1.10 and WSL2-Ubuntu IP and subnet keeps changing every few days. I am running MobaXterm v20.6 and its builtin Xserver on Windows host. 

X apps (xterm, xfig, emacs) on WSL2-ubuntu having DISPLAY=192.168.1.10:0.0 randomly stop displaying on X server within a few hours. Ubuntu ps shows the client apps are still running. The same apps running on a physical machine CentOS 7 that is on the same subnet as Windows 10, connecting to the same X server, do not experience this problem. This is certainly related to WSL2.

**Comment by vkopanja** [comment]
I can confirm this happens to me 100% of the time, when my IP changes (i.e. network changes from ethernet to WiFi and vice versa).

**Comment by simoncrook** [comment]
This is what works for me:

1) create a bash script with following (call it sysctl.sh and place in $HOME):

`#!/bin/bash`
`sysctl -w net.ipv4.tcp_keepalive_intvl=60 net.ipv4.tcp_keepalive_probes=5 net.ipv4.tcp_keepalive_time=300`

2) Change permissions and ownership:

`sudo chown root:root sysctl.sh`
`sudo chmod 755 sysctl.sh`

3) Modify sudoers file to allow users to run this (use sudo visudo). Ensure it has following line, where <username> translates to your username:
`<username> ALL=(root) NOPASSWD:/home/<username>>/sysctl.sh`

4) Finally, update your ~/.bashrc file to include:

`sudo ./sysctl.sh`

Without these changes my bash login shell and terminal (ie terminator) will close after say 30 minutes of inactivity.
With these changes my bash login shell and terminal stays open until I close it. Currently its been open for days.

**Note**: My DISPLAY variable is set to 

`host.docker.internal:0.0`

and my vcxsrv runs using:

`vcxsrv.exe :0 -ac  -lesspointer -multimonitors  -multiwindow -clipboard -nowgl -dpi auto`

Hope this works for your wsl2 vm and windows vcxsrv.

**Comment by gitbls** [comment]
> This is what works for me:
> 
> 1. create a bash script with following (call it sysctl.sh and place in $HOME):
> 
> `#!/bin/bash`
> `sysctl -w net.ipv4.tcp_keepalive_intvl=60 net.ipv4.tcp_keepalive_probes=5 net.ipv4.tcp_keepalive_time=300`
> 
> 1. Change permissions and ownership:
> 
> `sudo chown root:root sysctl.sh`
> `sudo chmod 755 sysctl.sh`
> 
> 1. Modify sudoers file to allow users to run this (use sudo visudo). Ensure it has following line, where  translates to your username:
>    `<username> ALL=(root) NOPASSWD:/home/<username>>/sysctl.sh`
> 2. Finally, update your ~/.bashrc file to include:
> 
> `sudo ./sysctl.sh`
> 
> Without these changes my bash login shell and terminal (ie terminator) will close after say 30 minutes of inactivity.
> With these changes my bash login shell and terminal stays open until I close it. Currently its been open for days.
> 
> **Note**: My DISPLAY variable is set to
> 
> `host.docker.internal:0.0`
> 
> and my vcxsrv runs using:
> 
> `vcxsrv.exe :0 -ac -lesspointer -multimonitors -multiwindow -clipboard -nowgl -dpi auto`
> 
> Hope this works for your wsl2 vm and windows vcxsrv.

WOW!!! Thank you for this! After making this change, it ran overnight, which it has NEVER done before. I'll be cautiously optimistic for a bit longer, but I think this works. 

I did make a slight change to your guide, though. I created /etc/sysctl.d/fixX.conf with the contents
```
net.ipv4.tcp_keepalive_intvl=60
net.ipv4.tcp_keepalive_probes=5
net.ipv4.tcp_keepalive_time=300
```
This is loaded automatically by sysctl when WSL restarts (need to do a wsl --shutdown if it's already up and running). No need to make any additional scripts or modify ~/.bashrc.

Thanks again! This is spectacular.

**Comment by simoncrook** [comment]
Glad to help :-)

**Comment by vinodatpu** [comment]
# sudo sysctl -a | grep tcp_keepalive
net.ipv4.tcp_keepalive_intvl = 75
net.ipv4.tcp_keepalive_probes = 9
net.ipv4.tcp_keepalive_time = 7200
Looks like the default values of 75, 9, 7200 are not good for WSL2. Setting them to 60, 5, 300 seem to have done the trick. Thanks you @simoncrook and @gitbls Hope WSL2 Developers will take a note of your findings.

**Comment by gitbls** [comment]
Confirmed! I have NEVER had an xterm stay up for 24 hours with WSL2 and now going on a couple of days. I'd be ecstatic with either a fix to the defaults for keeplive sysctl settings, or having /etc/sysctl.d/*.conf files processed during "system" startup, but I have a solution in my .bashrc that works now, so I'm pretty happy at the moment 😊

**Comment by vinodatpu** [comment]
I created /etc/sysctl.d/fixX.conf with suggested 3 lines. It does not work for me. Tried even including those 3 lines in /etc/sysctl.conf file. Upon restarting WSL2, my WSL2-Ubuntu had the default values (75, 9, 7200) and the problem came back. Manually running the following command works though: 
sudo sysctl -w net.ipv4.tcp_keepalive_intvl=60 net.ipv4.tcp_keepalive_probes=5 net.ipv4.tcp_keepalive_time=300

**Comment by gitbls** [comment]
> I created /etc/sysctl.d/fixX.conf with suggested 3 lines. It does not work for me. Tried even including those 3 lines in /etc/sysctl.conf file. Upon restarting WSL2, my WSL2-Ubuntu had the default values (75, 9, 7200) and the problem came back. Manually running the following command works though:
> sudo sysctl -w net.ipv4.tcp_keepalive_intvl=60 net.ipv4.tcp_keepalive_probes=5 net.ipv4.tcp_keepalive_time=300

Correct, as I mentioned "EDIT: Well, darn, per #4232 sysctl values aren't processed. Apologies for the diversion on this. " This means you need to do it in your .bashrc, or manually once you start the Linux system. Hoping sysctl processing gets completed at some point in the future, but once the sysctl settings are updated, at least on my system, xterms stay running (as opposed to previously where they just disappeared).

**Comment by therealkenc** [comment]
> sysctl -w net.ipv4.tcp_keepalive_intvl=60 net.ipv4.tcp_keepalive_probes=5 net.ipv4.tcp_keepalive_time=300

Thank-you for finding a work-around Simon. What is left unexplained (and baffling) is (a) why the problem only manifests for a minority of users (zero likes on Benn's OP as of this writing) and (b) why TCP keepalive should matter in the first instance. I used the unplugged network cable analogy back last [June](https://github.com/microsoft/WSL/issues/5339#issuecomment-640802664), but... youknow... that analogy doesn't make sense in the context.

**Comment by vinodatpu** [comment]
I think it is really the value of net.ipv4.tcp_keepalive_time which has been causing the problem. The long period of 7200 seconds for first probe is long enough for WSL2 to do its destructive act. Any value of tcp_keepalive_intvl of 60 or 72 or probably 600 seconds should be enough to keep session alive. I don't know why tcp_keepalive_time even exists, it used only once. After which, tcp_keepalive_intvl takes over, which it could very well do for the initial probe too.

**Comment by wheresrobert** [comment]
I can't help with figuring out why the proposed setting changes work, but I can throw in that my GUI apps have been running for days now under X410 without any random closings. It's been a breath of fresh air not having to worry that my terminal is going to blink out of existence after a long test suite run.

**Comment by davidbeaulieu-cc** [comment]
> This is what works for me:
> 
> 1. create a bash script with following (call it sysctl.sh and place in $HOME):
> 
> `#!/bin/bash`
> `sysctl -w net.ipv4.tcp_keepalive_intvl=60 net.ipv4.tcp_keepalive_probes=5 net.ipv4.tcp_keepalive_time=300`
> 
> 1. Change permissions and ownership:
> 
> `sudo chown root:root sysctl.sh`
> `sudo chmod 755 sysctl.sh`
> 
> 1. Modify sudoers file to allow users to run this (use sudo visudo). Ensure it has following line, where  translates to your username:
>    `<username> ALL=(root) NOPASSWD:/home/<username>>/sysctl.sh`
> 2. Finally, update your ~/.bashrc file to include:
> 
> `sudo ./sysctl.sh`
> 
> Without these changes my bash login shell and terminal (ie terminator) will close after say 30 minutes of inactivity.
> With these changes my bash login shell and terminal stays open until I close it. Currently its been open for days.
> 
> **Note**: My DISPLAY variable is set to
> 
> `host.docker.internal:0.0`
> 
> and my vcxsrv runs using:
> 
> `vcxsrv.exe :0 -ac -lesspointer -multimonitors -multiwindow -clipboard -nowgl -dpi auto`
> 
> Hope this works for your wsl2 vm and windows vcxsrv.

@simoncrook Are you running this script in WSL2 or in your Docker Container? I have exactly the same problem but with X11 apps running in the docker container running in WSL2. X11 apps started straight in WSL2 stay up for what seem forever.

**Comment by simoncrook** [comment]
Yes I was experiencing the same issue in both. Therefore I set this in both
my wsl2 and my wsl2 docker containers.

**Comment by therealkenc** [comment]
If anyone in this thread who is experiencing X protocol connections getting dropped, and the problem is addressed with the `net.ipv4.tcp_keepalive_intvl=60`/`net.ipv4.tcp_keepalive_timenet.ipv4.tcp_keepalive_time` work-around, _and_ happens to have Windows Pro, can you please see if the problem also with [Hyper-V](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/about/). It isn't critical (WSL2 is not Hyper-V) but if someone happens to have a Linux instance on Hyper-V handy, it would be a useful data point to know if the connections disappearing happens there as well.

**Comment by gitbls** [comment]
@therealkenc I currently have WSL2 enabled on my system. Can I also enable Hyper-V (without breaking WSL)? 

If I can, I'll be happy to run this test.

Thx

**Comment by therealkenc** [comment]
> Can I also enable Hyper-V (without breaking WSL)?

Yes, I run Hyper-V and WSL2 side-by-side myself. I just can't reproduce the problem on my rig on WSL2, so it certainly won't manifest on Hyper-V for me either. Hyper-V requires Windows Pro as it does not ship with Home Edition. You'll need to set up your `DISPLAY` variable to point at Xming or VcXsrv on Windows using your Windows IP address. Linux on Hyper-V is (typically) installed with a full graphical interface (Ubuntu Desktop) so you'll need to point `DISPLAY` in the right direction and make sure firewall rule ducks are in line. Otherwise you'll just end up running `xterm` inside the Hyper-V Linux instance.

It would look like this. The xterm on the right there is VcXsrv.

![image](https://user-images.githubusercontent.com/7049700/112709460-251f6900-8e77-11eb-9d5a-12b7cb7db2c6.png)

**Comment by gitbls** [comment]
Perfect. I'll get a test set up in the next day or two. Should I create as Gen1 VM or Gen2?

**Comment by gitbls** [comment]
The VM with the unmodified keepalive sysctl settings dropped its xterm sometime in the last 6 hours. The xterm process has disappeared from the screen, but pgrep -a xterm still shows that it's running.

The xterm on the VM with the modified keepalive sysctl settings is still running. 

Not 100% conclusive but would seem to indicate that Hyper-V has the issue as well as WSL. HTH

**Comment by therealkenc** [comment]
> The VM with the unmodified keepalive sysctl settings dropped its xterm sometime in the last 6 hours. 

Thanks for trying it out. Though xposting is sort of in bad form, you might try your luck in the [hyper-v Q&A forum](https://docs.microsoft.com/en-us/answers/topics/windows-server-hyper-v.html) and see if you can get a rise.

**Comment by gitbls** [comment]
Thanks, Ken. Here's my post over there: [https://docs.microsoft.com/en-us/answers/questions/336442/xterm-from-linux-vm-disappears-repeatably.html](). Hopefully enough of a Hyper-V slant to it.

**Comment by wbkoetsier** [comment]
I have this issue 100% of the time, as in, every morning my X apps have disappeared. I restart my modem every night, so the keepalive settings have no effect (the restart simply takes 15mins+ due to the mechanical time switch I use).

My workaround could be to not restart the modem as often...

```
net.ipv4.tcp_keepalive_intvl = 60
net.ipv4.tcp_keepalive_probes = 5
net.ipv4.tcp_keepalive_time = 300
```

**Comment by tactlessfish** [comment]
I've had this issue as well. Windows 19042.928, Ubuntu 20.04 LTS, GWSL 1.3.7. What fixed the issue for me was turning off Fast Startup, per https://github.com/microsoft/WSL/issues/6244 and [this SO question](https://stackoverflow.com/questions/63872289/wsl2-why-do-i-have-to-shutdown-wsl-to-restart-wsl-after-restarting-pc).

**Comment by gitbls** [comment]
I was able to reproduce this on Insiders build 21364, displaying to an X server on the LAN (i.e., not using WSLg).

Setting the 3 keepalive parameters reliably fixes it. Not setting them reliably reproduces the problem.

**Comment by lucamartini** [comment]
Upgraded to gWSL, same issue with konsole on Debian: disappearing, but still there. In fact I can re-attach to the tmux session that was there. Note that if instead of running undex gWSL, I run konsole under a VcXsrv server, it runs without problems.

**Comment by bread22** [comment]
> This is what works for me:
> 
> 1. create a bash script with following (call it sysctl.sh and place in $HOME):
> 
> `#!/bin/bash`
> `sysctl -w net.ipv4.tcp_keepalive_intvl=60 net.ipv4.tcp_keepalive_probes=5 net.ipv4.tcp_keepalive_time=300`
> 
> 1. Change permissions and ownership:
> 
> `sudo chown root:root sysctl.sh`
> `sudo chmod 755 sysctl.sh`
> 
> 1. Modify sudoers file to allow users to run this (use sudo visudo). Ensure it has following line, where  translates to your username:
>    `<username> ALL=(root) NOPASSWD:/home/<username>>/sysctl.sh`
> 2. Finally, update your ~/.bashrc file to include:
> 
> `sudo ./sysctl.sh`
> 
> Without these changes my bash login shell and terminal (ie terminator) will close after say 30 minutes of inactivity.
> With these changes my bash login shell and terminal stays open until I close it. Currently its been open for days.
> 
> **Note**: My DISPLAY variable is set to
> 
> `host.docker.internal:0.0`
> 
> and my vcxsrv runs using:
> 
> `vcxsrv.exe :0 -ac -lesspointer -multimonitors -multiwindow -clipboard -nowgl -dpi auto`
> 
> Hope this works for your wsl2 vm and windows vcxsrv.

This fixed my exact same issue, which bugs me for months. Thank you so much

**Comment by matteoguglielmi** [comment]
Hello everyone,

the issue is back after one of the most recent windows updates.

The proposed workaround seems to not be working anymore.

Is anybody else having the same issue again?

Version:       21H1
OS build:     19043.1110
Experience:   Windows Feature Experience Pack 120.2212.3530.0

**Comment by gitbls** [comment]
> Hello everyone,
> 
> the issue is back after one of the most recent windows updates.
> 
> The proposed workaround seems to not be working anymore.
> 
> Is anybody else having the same issue again?
> 
> Version: 21H1
> OS build: 19043.1110
> Experience: Windows Feature Experience Pack 120.2212.3530.0

Still working just fine for me on the latest (21H1 and 19043.1110). I was disappointed that the fixit was still required with the latest linux kernel update (5.10.16), but since it's in place and working, definitely not complaining!

**Comment by matteoguglielmi** [comment]
> 
> 
> > Hello everyone,
> > the issue is back after one of the most recent windows updates.
> > The proposed workaround seems to not be working anymore.
> > Is anybody else having the same issue again?
> > Version: 21H1
> > OS build: 19043.1110
> > Experience: Windows Feature Experience Pack 120.2212.3530.0
> 
> Still working just fine for me on the latest (21H1 and 19043.1110). I was disappointed that the fixit was still required with the latest linux kernel update (5.10.16), but since it's in place and working, definitely not complaining!

I usually play music from youtube using mpv (text mode) in a  tmux session (detached) with WSL2... and that actually never stops... even when the X11 terminal windows suddenly disappear.

Can you please confirm that my setup looks fine?

```
$> tail -1 ~/.bashrc 

[ ! -f /usr/local/bin/sysctl-wsl2 ] || sudo /usr/local/bin/sysctl-wsl2

$> ls -liah /usr/local/bin/sysctl-wsl2

-rwxr-xr-x 1 root root 627 May 23 16:18 /usr/local/bin/sysctl-wsl2

$> cat /usr/local/bin/sysctl-wsl2

#!/bin/bash
sysctl -wq net.ipv4.tcp_keepalive_time=300 \
           net.ipv4.tcp_keepalive_intvl=60 \
           net.ipv4.tcp_keepalive_probes=5
```

Thank you.

**Comment by gitbls** [comment]
Do you get the expected values if you read them out with sysctl after you're logged in?

**Comment by matteoguglielmi** [comment]
> 
> 
> Do you get the expected values if you read them out with sysctl after you're logged in?

Yes.

```
$> sudo sysctl -a | grep ^net.ipv4.tcp_keepalive

net.ipv4.tcp_keepalive_intvl = 60
net.ipv4.tcp_keepalive_probes = 5
net.ipv4.tcp_keepalive_time = 300
```

**Comment by gitbls** [comment]
Don't know what to tell you. I'm WSL2 with a Debian VM on both my desktop (always up) and my laptop. Neither have exhibited the problem described here if I do the 3 keepalive sysctl settings. Without them, X11 apps disconnect at a random interval.

**Comment by vinodatpu** [comment]
I have Windows 10 Pro 21H1 (19043.1110) and Xserver distributed with Mobaxterm v20.6.  I do not see x-apps disconnecting from Xserver when the tcp kernel is configured with intvl=60, probes=5, time=300.

**Comment by matteoguglielmi** [comment]
On my system,

X11 terminal windows do now disappear (sometimes) as quickly as giving focus to any other window on the desktop.

WSL2 isn't dying though (before, without the keepalive trick, I also had to restart WSL2 most of the times)... yet X11 windows are now disappearing again.

**Comment by matteoguglielmi** [comment]
UPDATE:

Things seem back to normal after replacing Xming (7.7.0.69) with X410.

Anyone out there using Xming without problems?

**Comment by gunnernme** [comment]
Had this exact problem for weeks.   Fixed by putting these three lines in /etc/sysctl.conf:
net.ipv4.tcp_keepalive_intvl = 60
net.ipv4.tcp_keepalive_probes = 5
net.ipv4.tcp_keepalive_time = 300

**Comment by matteoguglielmi** [comment]
UPDATE:

it's been days now that X11 windows started to disappear again with X410.

**Comment by gitbls** [comment]
> XServer will try to close the connection to the XClient after some period of inactivity. You can observe this if you run wireshark or tcpdump on the client machine. You should also see a number of keepalive messages sent from the XClient to the XServer. At some point the XServer will send a FIN message to the client and close the connection. You need to set the OS sysctl options on the client machine to control how these keepalives are sent:
> 
> net.ipv4.tcp_keepalive_time // This is how long before the first keepalive is sent. If you set this too high, the connection will close before any keepalives are sent at all.
> 
> net.ipv4.tcp_keepalive_intvl // This is the gap between messages, again if you set this too high the connection will close before the next keepalive is sent.
> 
> net.ipv4.tcp_keepalive_probes // The number of messages that are unacknowledged before the connection is closed.
> 
> Set the first two properties to low values, and the last property to a higher value. Observe the changes again through wireshark/tcpdump
> 
> Note also if you're running a docker container on WSL, then you need to set these properties using the `docker run --sysctl` flag.

I'm not sure that your first statement is true. I run several XTerms on both RasPiOS and Ubuntu, displaying on an XMing server on Windows 10. They NEVER get closed by the Xserver. 

However, without the sysctl keepalive settings, XTerms in WSL DO get closed at arbitrary, unpredictable times.

**Comment by mlromramse** [comment]
SOLVED!
I have had the same problem  as most guys above and just recently found a viable solution for me. I had tried with both Vcxsrv and X410 when I noticed that x410 had a new release 3.1.0 which support vsock.
After downloading and setting up vsock all my problems was gone. Their solution for vsock might work for vcxsrv also but I have not tried that since x410 provides better details in the graphics and I prefer that.

> ### Why vsock ?
> Using vsock brings the independency from TCP and IP addresses that was a problem for me.
> With this solution I can switch network without loosing any linux app GUI. Happy days!

## This is what I did:

### Download X410 for windows and install - https://x410.dev/#download
1. Start_ X410: ``/mnt/c/Program\ Files/Choung\ Networks/X410/X410.exe &``
### Use option VSOCK OPTION 2 Modify XCB - https://x410.dev/cookbook/transparently-adding-native-support-for-vsock-in-x11-apps
1. Download pre-built library - https://gitlab.com/vsockfy/libxcb-1.14-vsock/-/releases/v1.14-vsock
2. Rename old libxcb.so: ``sudo mv /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0 /usr/lib/x86_64-linux-gnu/libxcb.backup.so.1.1.0``
3. Copy the downloaded file into place (move to your folder beforehand): ``sudo cp libxcb.se.1.1.0 /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0``
4. Verify functionality: ``export DISPLAY=vsock/:0; xset q``   (Should respond with 'Keyboard Control:......' if successful)
### Add aliases and functions to your .bashrc or similar:
1. Add alias to launch X410 
``````
alias xlaunch='/mnt/c/Program\ Files/Choung\ Networks/X410/X410.exe &'
``````
3. Add function: 
``````
function x_display {
  export DISPLAY="vsock/:0"
  export QT_SCALE_FACTOR=1
  export GDK_SCALE=1
  if ! timeout 1s xset q &>/dev/null; then
    taskkill.exe /IM X410.exe &> /dev/null && echo "Running X was killed!"
    echo "Starting X..."
    xlaunch
    sleep 2
  fi
  echo "X for WSL instantiated on $DISPLAY"
}
``````
4. Add alias to launch intellij (my reason for this endevour): 
``````
alias intellij='x_display; /opt/idea/bin/idea.sh &> /dev/null &'
``````
 5. Save your .bashrc
 2. Source your changed .bashrc: source ~/.bashrc
 3. Start Intellij: intellij

**Comment by alipi** [comment]
> SOLVED! I have had the same problem as most guys above and just recently found a viable solution for me. I had tried with both Vcxsrv and X410 when I noticed that x410 had a new release 3.1.0 which support vsock. After downloading and setting up vsock all my problems was gone.

Thanks, I also use X410 with vsock. but I wouldn't call it a solution, more a workaround? WSL2 should still handle this case.

**Comment by Lamarcke** [comment]
> SOLVED! I have had the same problem as most guys above and just recently found a viable solution for me. I had tried with both Vcxsrv and X410 when I noticed that x410 had a new release 3.1.0 which support vsock. After downloading and setting up vsock all my problems was gone. Their solution for vsock might work for vcxsrv also but I have not tried that since x410 provides better details in the graphics and I prefer that.
> 
> > ### Why vsock ?
> > Using vsock brings the independency from TCP and IP addresses that was a problem for me.
> > With this solution I can switch network without loosing any linux app GUI. Happy days!
> 
> ## This is what I did:
> ### Download X410 for windows and install - https://x410.dev/#download
> 1. Start_ X410: `/mnt/c/Program\ Files/Choung\ Networks/X410/X410.exe &`
> 
> ### Use option VSOCK OPTION 2 Modify XCB - https://x410.dev/cookbook/transparently-adding-native-support-for-vsock-in-x11-apps
> 1. Download pre-built library - https://gitlab.com/vsockfy/libxcb-1.14-vsock/-/releases/v1.14-vsock
> 2. Rename old libxcb.so: `sudo mv /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0 /usr/lib/x86_64-linux-gnu/libxcb.backup.so.1.1.0`
> 3. Copy the downloaded file into place (move to your folder beforehand): `sudo cp libxcb.se.1.1.0 /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0`
> 4. Verify functionality: `export DISPLAY=vsock/:0; xset q`   (Should respond with 'Keyboard Control:......' if successful)
> 
> ### Add aliases and functions to your .bashrc or similar:
> 1. Add alias to launch X410
> 
> ```
> alias xlaunch='/mnt/c/Program\ Files/Choung\ Networks/X410/X410.exe &'
> ```
> 
> 3. Add function:
> 
> ```
> function x_display {
>   export DISPLAY="vsock/:0"
>   export QT_SCALE_FACTOR=1
>   export GDK_SCALE=1
>   if ! timeout 1s xset q &>/dev/null; then
>     taskkill.exe /IM X410.exe &> /dev/null && echo "Running X was killed!"
>     echo "Starting X..."
>     xlaunch
>     sleep 2
>   fi
>   echo "X for WSL instantiated on $DISPLAY"
> }
> ```
> 
> 4. Add alias to launch intellij (my reason for this endevour):
> 
> ```
> alias intellij='x_display; /opt/idea/bin/idea.sh &> /dev/null &'
> ```
> 
> 5. Save your .bashrc
> 6. Source your changed .bashrc: source ~/.bashrc
> 7. Start Intellij: intellij

Can confirm this indeed works.
I just feel that it shouldn't be locked behind a paid third-party tool. 

A lot of people use X-Servers for WSL, and i don't really think this will ever be resolved because they probably want to push WSLg.

**Comment by cvjjm** [comment]
I am having the exact same issue described here with VcXsrv + WSL 2 + Docker. Very annoying...

**Comment by cvjjm** [comment]
> Another option I found was simply turning off the screensaver with xset x off.
I've left my xserver running for multiple days at a time without having the xserver go blank after I did this.
This is on VcXsrv + WSL 2 running Ubuntu 20.02.

You mean `set s off`?
