### ISSUE TITLE
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.

### ISSUE THREAD

**Issue by liudonghua123** [microsoft/WSL#5363]
# Environment
```
C:\Users\Liu.D.H>ver

Microsoft Windows [Version 10.0.19041.264]

C:\Users\Liu.D.H>bcdedit

Windows Boot Manager
--------------------
identifier              {bootmgr}
device                  partition=\Device\HarddiskVolume1
description             Windows Boot Manager
locale                  en-US
inherit                 {globalsettings}
default                 {current}
resumeobject            {8c132511-806f-11e9-8860-f798d1b7a8f1}
displayorder            {current}
                        {89f269f4-cc9f-11e6-8727-64006a16df31}
                        {8c132516-806f-11e9-8860-f798d1b7a8f1}
toolsdisplayorder       {memdiag}
timeout                 5

Windows Boot Loader
-------------------
identifier              {current}
device                  partition=C:
path                    \WINDOWS\system32\winload.exe
description             Windows 10
locale                  en-US
inherit                 {bootloadersettings}
recoverysequence        {8c132514-806f-11e9-8860-f798d1b7a8f1}
displaymessageoverride  Recovery
recoveryenabled         Yes
allowedinmemorysettings 0x15000075
osdevice                partition=C:
systemroot              \WINDOWS
resumeobject            {8c132511-806f-11e9-8860-f798d1b7a8f1}
nx                      OptIn
bootmenupolicy          Legacy
hypervisorlaunchtype    Off

Windows Boot Loader
-------------------
identifier              {89f269f4-cc9f-11e6-8727-64006a16df31}
device                  partition=\Device\HarddiskVolume1
path                    \Windows\system32\winload.exe
description             Windows 7
locale                  zh-CN
inherit                 {bootloadersettings}
osdevice                partition=\Device\HarddiskVolume1
systemroot              \Windows
resumeobject            {89f269f3-cc9f-11e6-8727-64006a16df31}
nx                      OptIn
detecthal               Yes

Windows Boot Loader
-------------------
identifier              {8c132516-806f-11e9-8860-f798d1b7a8f1}
device                  partition=C:
path                    \WINDOWS\system32\winload.exe
description             Windows10 with Hyper-V
locale                  en-US
inherit                 {bootloadersettings}
recoverysequence        {8c132514-806f-11e9-8860-f798d1b7a8f1}
displaymessageoverride  Recovery
recoveryenabled         Yes
allowedinmemorysettings 0x15000075
osdevice                partition=C:
systemroot              \WINDOWS
resumeobject            {8c132511-806f-11e9-8860-f798d1b7a8f1}
nx                      OptIn
bootmenupolicy          Legacy
hypervisorlaunchtype    Auto

C:\Users\Liu.D.H>systeminfo

Host Name:                 DESKTOP-LDH
OS Name:                   Microsoft Windows 10 Education
OS Version:                10.0.19041 N/A Build 19041
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Windows User
Registered Organization:
Product ID:                00328-10000-00001-AA635
Original Install Date:     2020-05-11, 22:13:14
System Boot Time:          2020-06-08, 10:12:11
System Manufacturer:       Dell Inc.
System Model:              Vostro 3900
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 60 Stepping 3 GenuineIntel ~3601 Mhz
BIOS Version:              Dell Inc. A10, 2015-07-30
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             zh-cn;Chinese (China)
Input Locale:              zh-cn;Chinese (China)
Time Zone:                 (UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi
Total Physical Memory:     16,301 MB
Available Physical Memory: 9,703 MB
Virtual Memory: Max Size:  33,709 MB
Virtual Memory: Available: 26,300 MB
Virtual Memory: In Use:    7,409 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-LDH
Hotfix(s):                 6 Hotfix(s) Installed.
                           [01]: KB4552925
                           [02]: KB4534170
                           [03]: KB4537759
                           [04]: KB4545706
                           [05]: KB4557968
                           [06]: KB4556803
Network Card(s):           4 NIC(s) Installed.
                           [01]: TAP-Windows Adapter V9
                                 Connection Name: 以太网
                                 Status:          Media disconnected
                           [02]: Realtek PCIe GBE Family Controller
                                 Connection Name: Ethernet_Realtek
                                 DHCP Enabled:    Yes
                                 DHCP Server:     113.55.112.1
                                 IP address(es)
                                 [01]: 113.55.127.140
                                 [02]: fe80::3d0a:ecde:2178:d77c
                                 [03]: 2001:250:2800:cc09:6600:6aff:fe16:df31
                           [03]: Realtek RTL8188CU Wireless LAN 802.11n USB 2.0 Network Adapter
                                 Connection Name: Wi-Fi 2
                                 Status:          Media disconnected
                           [04]: Microsoft KM-TEST Loopback Adapter
                                 Connection Name: Npcap Loopback Adapter
                                 DHCP Enabled:    Yes
                                 DHCP Server:     255.255.255.255
                                 IP address(es)
                                 [01]: 169.254.104.11
                                 [02]: fe80::d8bf:11ab:7b05:680b
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

C:\Users\Liu.D.H>
```

![image](https://user-images.githubusercontent.com/2276718/83988171-106bf600-a975-11ea-9f2b-aaf2d59ff922.png)

# Steps to reproduce

Open Ubuntu 18.04 or 20.04.

#  Expected behavior

Works as expected.

# Actual behavior

![image](https://user-images.githubusercontent.com/2276718/83988122-e9adbf80-a974-11ea-97e4-d5415ab86a98.png)

I can confirm that I have enabled `Virtual Machine Platform` and `VT-x`. But the errors when I started Ubuntu is confused. 
And for some reasons I do not want to enable Hyper-V features. From the doc (https://docs.microsoft.com/en-us/windows/wsl/), it is not a requirement for WSL2.

**Comment by liudonghua123** [comment]
From the doc https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq, It seems that hyper-v is a requirement when running wsl2.

So I have to enable hyper-v? I will test it and report later.

**Comment by liudonghua123** [comment]
Hope to document enable Hyper-V in https://docs.microsoft.com/en-us/windows/wsl/install-win10 when install and run wsl2.

- `DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V`
- `bcdedit /set hypervisorlaunchtype auto`

**Comment by benhillis** [comment]
@liudonghua123 - The Hyper-V feature is not required, but Virtual Machine Platform (which includes the Hyper-V hypervisor) is required.

**Comment by MrFoxPro** [comment]
I get same error after clean install, Win 10 Home. Tried many times to enable/reenable features and rebooting pc. Virtualization is enabled in bios and shown as active in task manager. With clean install of ubuntu i get error `WslRegisterDistribution failed with error: 0x80370102`. Really disappointed as it works on laptop but not on desktop....

**Comment by MrFoxPro** [comment]
![image](https://user-images.githubusercontent.com/17229619/84186366-df411200-aaa9-11ea-8cb0-ea3af5b2d859.png)
I suspect that hyper-v is somehow enabled on my pc, but i can disable it scince im running with home edition. I can check it if I disable virtualization in bios.

**Comment by MrFoxPro** [comment]
suddenly resolved it by resetting bios.

**Comment by liudonghua123** [comment]
@benhillis From the doc https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq, It seems that hyper-v is a requirement when running wsl2. If I disabled it, then I got `Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.` error message. I have tried many times.

**Comment by therealkenc** [comment]
The faq says (quoth) "...WSL uses Hyper-V architecture to enable its virtualization. This architecture will be available in the 'Virtual Machine Platform' optional component". That is the checkbox you want, and you look good:

![image](https://user-images.githubusercontent.com/7049700/84450145-2e02bf00-ac04-11ea-8fe0-6e6486fa91e0.png)

You also seem okay as far as Hyper-V requirements go, notably your BIOS, per your `systeminfo` output in the OP.

Collect [detailed logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs). 

@benhillis there is probably some semi-actionable here, at least in terms of user feedback in the error path. The upcoming `wsl --setup` feature might mitigate some fails for people "doing it wrong", but there is at least some evidence of folks who seem to have their prerequisite ducks in line, and yet `wsl.exe` still tells them to "Please enable the Virtual Machine Platform". Which is unreasonably confusing when they already have VMP enabled. The WSL stack knows (or can at least determine) whether VMP is enabled and whether Windows thinks the BIOS is okay.

**Comment by HoshiYamazaki** [comment]
Seems that NX Pages protection can be issue, enable it if the WSL2 fails to launch.

**Comment by worlvlhole** [comment]
I'm having the same issue. i updated my windows system, restarted and keep getting this message.  

I have been running wsl2 with no issues and all of a sudden this is not occurring.

**Comment by kubichris** [comment]
Same problem:
After restart my computer for an update, i can not start my wsl2 Ubuntu with same error message.

**Comment by worlvlhole** [comment]
> I'm having the same issue. i updated my windows system, restarted and keep getting this message.
> 
> I have been running wsl2 with no issues and all of a sudden this is now occurring.

I figured out my issue. It broke to do installing CS:GO ESEA client. In order to fix, i had to uninstall and disable and re-enable WSL  featurs.

**Comment by SoutheastCXF** [comment]
when i  took your advice, I fixed unexpectedly. thanks ！

> > I'm having the same issue. i updated my windows system, restarted and keep getting this message.
> > I have been running wsl2 with no issues and all of a sudden this is now occurring.
> 
> I figured out my issue. It broke to do installing CS:GO ESEA client. In order to fix, i had to uninstall and disable and re-enable WSL features.
when i  took your advice, I fixed unexpectedly. thanks ！

**Comment by LucaBernstein** [comment]
I was just glad to see that by enabling the following modules in `Turn Windows features on or off`, followed by a restart, I was able to convert wsl from v1 to v2 via `wsl --set-version Ubuntu 2`:

* [x] Containers
* [x] Hyper-V
* [x] Virtual Machine Platform
* [x] Windows Hypervisor Platform
* [x] Windows Sandbox
* [x] Windows Subsystem for Linux

Seems to be kind of like brute force, but at least it works now 😃

**Comment by 0x04** [comment]
After the update to WSL2 and some reboots later, I had the same issue. Disabling and re-enabling WSL fixed the problem for me.

@spennymac Thanks for figuring that out! 👍

**Comment by Delta456** [comment]
When I try to update to WSL 2 I get this as well. Of course I followed all the steps listed here https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2

```
PS C:\Users\admin> wsl --set-version Ubuntu-20.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/wsl2-install
PS C:\Users\admin>
```

**Comment by zhangqijia** [comment]
suffer this problem and still cannot fix it,  even though I reinstall WSL and enable the virtualization in BIOS

**Comment by zhangqijia** [comment]
> Hope to document enable Hyper-V in https://docs.microsoft.com/en-us/windows/wsl/install-win10 when install and run wsl2.
> 
> * `DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V`
> * `bcdedit /set hypervisorlaunchtype auto`

`bcdedit /set hypervisorlaunchtype auto`
this command saved my life, thank you

**Comment by V1NAY8** [comment]
I reset my BIOS and 
```bash
bcdedit /set hypervisorlaunchtype auto
```
Really worked!

**Comment by udithishara** [comment]
If anyone else come across this trying to upgrade to WSL2 from 1

- If you come across Kernel issues [read this](https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel)
- If you're getting virtualization bios error, look into updating bios for your motherboard
- Run `DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V` & `bcdedit /set hypervisorlaunchtype auto` (Credit: @liudonghua123)
- Everything should be working fine at this point

**Comment by Xyverz** [comment]
I'm keeping Hyper-V turned off because I use VMware Workstation Pro on my PC, but your command below fixed the problem for me. Thank you very much!

> * `bcdedit /set hypervisorlaunchtype auto`

**Comment by Karlheinzniebuhr** [comment]
> 
> 
> I'm keeping Hyper-V turned off because I use VMware Workstation Pro on my PC, but your command below fixed the problem for me. Thank you very much!
> 
> > * `bcdedit /set hypervisorlaunchtype auto`

I have the same situation. Hyper-V off due to VMware but after running this command, rebooting and running again 
`wsl --set-version Ubuntu-20.04 2`
solved my issue

**Comment by nakedlookuk** [comment]
I solved this issue in simpler way. Went BIOS setup, disabled Virtualization in BIOS. Booted Windows. Once properly booted, shutdown and restart in BIOS setup. Enable Virtualization in BIOS et voilà. It works in WSL 2. I had reinstall Ubuntu though which was still in WSL 1 version. But because it was fresh install, did not have to worry about legacy baggage.

**Comment by VIIIHenryVIII** [comment]
> Hope to document enable Hyper-V in https://docs.microsoft.com/en-us/windows/wsl/install-win10 when install and run wsl2.
> 
> * `DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V`
> * `bcdedit /set hypervisorlaunchtype auto`

This last bit did it for me after restart.

**Comment by michaeldrawe** [comment]
I solved my issue the same way that TradianIndian solved his. Disable Virtualization in the bios, rebooted to windows, enabled virtualization and now WSL works for me.

**Comment by marstrong** [comment]
Similar to @TradingIndian and @michaeldrawe, my issue was that virtualization was disabled on my machine. 
Microsoft's [WSL Installation Guide for Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10) DOES specify that "Virtual Machine Platform" must be enabled, but I didn't get any sort of error message when I ran the provided PowerShell command, so it took me a while to realize my issue. 

You can check whether virtualization is enabled or not by opening the "Turn Windows features on or off" menu -- if virtualization is disabled, the check box next to "Virtual Machine Platform" will be grayed out, and a pop-up will confirm that virtualization is not enabled. 

To fix the problem, I followed [these instructions](https://mashtips.com/enable-virtualization-windows-10/) to enable virtualization in my UEFI firmware.
Once my machine rebooted, I was able to check the box for "Virtual Machine Platform," then rebooted again. 
Opened PowerShell as an Administrator, then ran all the commands listed in the WSL Installation Guide:
`dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart`
`dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart`
`wsl --set-version Ubuntu 2`
Once conversion completed (took several minutes), I used the following to confirm:
`wsl --list --verbose`

**Comment by alikhamesy** [comment]
>I solved this issue in simpler way. Went to BIOS setup, disabled Virtualization in BIOS. Booted Windows. Once properly booted, shutdown and restart in BIOS setup. Enable Virtualization in BIOS et voilà. It works in WSL 2. I had to reinstall Ubuntu though, which was still showing WSL 1 version. But because it was fresh install, I did not have to worry about legacy baggage.

That worked for me... Gotta love the good ol' turn it off and on again.

**Comment by dafuloth** [comment]
> I solved this issue in simpler way. Went to BIOS setup, disabled Virtualization in BIOS. Booted Windows. Once properly booted, shutdown and restart in BIOS setup. Enable Virtualization in BIOS et voilà.

As absurd as this solution sounds, I too can confirm that turning it off and on again does indeed work.

IIRC I already had WSL2 and everything all set up and working - but today it was giving this silly message `Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.`

Maybe some recent Windows update screwed something up.

**Comment by ben-wing** [comment]
My solution today was to turn Hyper-V feature on, perform
`wsl --set-version Ubuntu 2`
`wsl --set-default-version 2`
`bcdedit /set hypervisorlaunchtype auto`

Have since rebooted, and turned off Hypber-V feature, and WSL2 versioned Ubuntu install continues to function just fine. so another version of turn it on and then back off...

**Comment by Tomiprase3270** [comment]
i have some issue problem today and i'm solved this problem very simple.
i just  go to BIOS setting and disable virtualization, then reboot into windows 10. after thet i go to BIOS again and i enable virtualization again. Taraaaaaa, wsl2 ubuntu lts 20.04 woking normally.

**Comment by rajan-31** [comment]
Simple restart did the job for me.

**Comment by DjoleLepi** [comment]
My problem was that I didn't fully enable virtualization in BIOS.
I only checked the **IOMMU** to be enabled.
After digging some more I also found the **SVM** setting.

This is the documented way to enable virtualization, I just wanted to mention it here in case someone made the same mistake as me.

**Comment by Wyverns010** [comment]
> I solved this issue in simpler way. Went to BIOS setup, disabled Virtualization in BIOS. Booted Windows. Once properly booted, shutdown and restart in BIOS setup. Enable Virtualization in BIOS et voilà. It works in WSL 2. I had to reinstall Ubuntu though, which was still showing WSL 1 version. But because it was fresh install, I did not have to worry about legacy baggage.

The solution @TradingIndian mentioned worked for me, but partially. When I uninstalled the older ubuntu distro(`wsl --unregister <DistributionName>`) to install a new one, wsl stopped working again, showing  `server execution failed`

I  unchecked Windows Subsystem for Linux in `Turn Windows features on or off`(control panel->Programs->Turn Windows features on or off), rebooted, checked it back again, rebooted, wsl started working! 

Before installing a new distro, I [manually enabled wsl 2](https://docs.microsoft.com/en-us/windows/wsl/install-win10), finally installed the new distro through [powerShell](https://stackoverflow.com/questions/52512026/is-it-possible-install-ubuntu-in-windows-10-wsl-without-microsoft-store). I checked the distro version(` wsl --list --verbose`) and it was 2!

**Comment by black2996** [comment]
It seems messed up, wsl2 works perfectly on my machine with "virtualization platform" feature turned off.

**Comment by untoreh** [comment]
> My problem was that I didn't fully enable virtualization in BIOS.
> I only checked the **IOMMU** to be enabled.
> After digging some more I also found the **SVM** setting.
> 
> This is the documented way to enable virtualization, I just wanted to mention it here in case someone made the same mistake as me.

`SVM` and `NX mode` both have to be enable on AMD platforms

**Comment by ShlomiRex** [comment]
> Hope to document enable Hyper-V in https://docs.microsoft.com/en-us/windows/wsl/install-win10 when install and run wsl2.
> 
> * `DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V`
> * `bcdedit /set hypervisorlaunchtype auto`

Can confirm it works after struggling using WSL for the first time!

**Comment by jadebujeya** [comment]
I resolved this issue by turning on HP Application Driver in BIOS.

**Comment by kensykora** [comment]
This happened to me after I installed Visual Studio 2019 with Xamarin and Android SDK. The simulator must mess with the virtualization settings

**Comment by shinayser** [comment]
My wsl2 stopped working right now on my Windows 11, out of nowhere!!!. And not only WSL2 but also Android's emulator.
Says that I need to turn on virtual machine and hipervisor resources on, but they are already on!!!
Everything was working fine the past month.

Someone got a clue?

**Comment by one0410** [comment]
I did everything above, but didn't work.
It is 2022-01-12 today. I run WINDOWS UPDATE today, I can do "wsl --set-verion ubuntu 2 " finally.

**Comment by EhsanKia** [comment]
The opposite for me, I've been using wsl 2 for a long time. Last week I ran windows update, installing 21H2. Also updated apps on Windows Store which may have updated Ubuntu image?

Not I get
```
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
```

and 
```
C:\WINDOWS\system32>wsl --list --verbose
  NAME      STATE           VERSION
* Legacy    Running         1
  Ubuntu    Stopped         2
```

I've tried all the commands in this thread:

```
C:\WINDOWS\system32>wsl --set-version Ubuntu 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The distribution is already the requested version.

C:\WINDOWS\system32>wsl --set-default-version 2
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
The operation completed successfully.
```

No dice.

**Comment by RshStone** [comment]
For me, I installed BlueStacks software which needs me disable  Hype-V. On the next morning. I start my ASUS computer. I found the warning that makes us meet here. I tried Turn Windows Features On and Not. Enable Hype-V, restart PC and not work. I open BIOS and found that the Virtualization Technology is enabled. So, I disable it and  restart it.  
Then I enable it. I found wsl worked!
PC: ASUS Processor: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
OS: Windows 10 Pro 20H2

**Comment by jeff-zone** [comment]
These steps worked for me:
1.  Disabling both virtualization options via the BIOS (Intel XPU)
2.  Reboot back into windows
3. run "wsl --list --verbose"
4. Reboot back into the BIOS and re-enable virtualization
5. Reboot back into windows
6. Was then able to convert my WSL1 Distro to WSL 2 with this command:  "wsl --set-version Ubuntu 2" (don't freak out, this takes a few minutes - definitely don't close the window while this conversion is in progress)
7. Subsequently ran this command: "wsl --set-default-version 2" with no err, just an informative message but it seems to have worked.
8. Was able to verify the changes with: "wsl --list -v"

**Comment by ruppke** [comment]
> I'm having the same issue. i updated my windows system, restarted and keep getting this message.
> 
> I have been running wsl2 with no issues and all of a sudden this is now occurring.

metoo

**Comment by paxperscientiam** [comment]
> I'm keeping Hyper-V turned off because I use VMware Workstation Pro on my PC, but your command below fixed the problem for me. Thank you very much!

I too am trying to get WSL2 (and docker) working with Hyper-V turned off. I can confirm that this command got my WSL (ubuntu) setup working again; I had been getting the same error message in terminal.

**Comment by danielhg1285** [comment]
I got this issue after executing following command:
bcdedit /set hypervisorlaunchtype off

After running following the following command and reboot was solved: 
bcdedit /set hypervisorlaunchtype auto

**Comment by xiangpeng2008** [comment]
is there any change to update wsl 1 to wsl 2 without "admin" ?

**Comment by Biswa96** [comment]
> is there any change to update wsl 1 to wsl 2 without "admin" ?

The conversion process from WSL1 to WSL2 itself does **not** require admin privilege. But enabling WSL2 features does require admin privilege.

**Comment by xiangpeng2008** [comment]
> > is there any change to update wsl 1 to wsl 2 without "admin" ?
> 
> The conversion process from WSL1 to WSL2 itself does **not** require admin privilege. But enabling WSL2 features does require admin privilege.

So I can't update to wsl2 without admin? It seems admin is needed for "Turn window features on and off"

**Comment by Biswa96** [comment]
> So I can't update to wsl2 without admin?

It depends if WSL2 feature is enabled or not.

**Comment by kreshna93** [comment]
> Hope to document enable Hyper-V in https://docs.microsoft.com/en-us/windows/wsl/install-win10 when install and run wsl2.
> 
> * `DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V`
> * `bcdedit /set hypervisorlaunchtype auto`

THANKS.. IT REALLY WORKED

**Comment by 1pavanb** [comment]
ran systeminfo
looked like this
```
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes
```
So the message it showed didn't make sense. Tried this that was mentioned by people above.
```
DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V
bcdedit /set hypervisorlaunchtype auto
```
Didn't change anything. Then tried resetting bios settings. Visibly nothing changed there as well since hyper-v was enabled there already. But it worked 🥴. What?!

Ubuntu terminal showed prompt and everthing seems normal again.

Checked systeminfo again to see any difference.
```
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```
🤷👍

**Comment by MSRhmn** [comment]
Two month's ago I had a conflict with wsl as ["catastrophic failure"](https://github.com/microsoft/WSL/issues/5092#issuecomment-1164419186). Solutions from the issue didn't solve my problem, so I had to make a clean install and end up losing wsl data. This time, it doesn't just work as solutions from up above, neither a clean install.

**Comment by 1pavanb** [comment]
> Two month's ago I had a conflict with wsl as ["catastrophic failure"](https://github.com/microsoft/WSL/issues/5092#issuecomment-1164419186). Solutions from the issue didn't solve my problem, so I had to make a clean install and end up losing wsl data. This time, it doesn't just work as solutions from up above, neither a clean install.

F

**Comment by kadekedwin** [comment]
> Hope to document enable Hyper-V in https://docs.microsoft.com/en-us/windows/wsl/install-win10 when install and run wsl2.
> 
> * `DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V`
> * `bcdedit /set hypervisorlaunchtype auto`

thanks

**Comment by kdomo** [comment]
Please enable Hyper-V Windows first
Then reboot and enter the BIOS.
Anyway, when this window appears, press F7.
The Advanced Mode will appear.
I'll go to Advanced
Change the SVM Mode to Enabled.

**Comment by Natemo6348** [comment]
After trying everything here, I still can't get WSL2 to work, any ideas as to what I can try and what I should look for?

**Comment by kdomo** [comment]
@Natemo6348
Please enable Hyper-V Windows first
Then reboot and enter the BIOS.
Change the SVM Mode to Enabled

**Comment by Natemo6348** [comment]
@kdomo did not work for me, any other ideas?

**Comment by irving-vale** [comment]
https://made4geek.com/error-0x80370102-the-virtual-machine-could-not-be-started-because-a-required-feature-is-not-installed-wsl-2-code-example/

**Comment by dkalog** [comment]
WSL 2 : This warning is a collective one it address many different causes of show stoppers. 
Although I had configure/ticked WSL and virtual machine platform from additional features, that was not ENOUGH
For my case was enough to 
**bcdedit /set hypervisorlaunchtype auto** or ON.  
( I haved picked AUTO because I used SL in conjunction with VBOX 6.1.34 and beyond..

**Comment by Ukriyte** [comment]
> # Environment
> ```
> C:\Users\Liu.D.H>ver
> 
> Microsoft Windows [Version 10.0.19041.264]
> 
> C:\Users\Liu.D.H>bcdedit
> 
> Windows Boot Manager
> --------------------
> identifier              {bootmgr}
> device                  partition=\Device\HarddiskVolume1
> description             Windows Boot Manager
> locale                  en-US
> inherit                 {globalsettings}
> default                 {current}
> resumeobject            {8c132511-806f-11e9-8860-f798d1b7a8f1}
> displayorder            {current}
>                         {89f269f4-cc9f-11e6-8727-64006a16df31}
>                         {8c132516-806f-11e9-8860-f798d1b7a8f1}
> toolsdisplayorder       {memdiag}
> timeout                 5
> 
> Windows Boot Loader
> -------------------
> identifier              {current}
> device                  partition=C:
> path                    \WINDOWS\system32\winload.exe
> description             Windows 10
> locale                  en-US
> inherit                 {bootloadersettings}
> recoverysequence        {8c132514-806f-11e9-8860-f798d1b7a8f1}
> displaymessageoverride  Recovery
> recoveryenabled         Yes
> allowedinmemorysettings 0x15000075
> osdevice                partition=C:
> systemroot              \WINDOWS
> resumeobject            {8c132511-806f-11e9-8860-f798d1b7a8f1}
> nx                      OptIn
> bootmenupolicy          Legacy
> hypervisorlaunchtype    Off
> 
> Windows Boot Loader
> -------------------
> identifier              {89f269f4-cc9f-11e6-8727-64006a16df31}
> device                  partition=\Device\HarddiskVolume1
> path                    \Windows\system32\winload.exe
> description             Windows 7
> locale                  zh-CN
> inherit                 {bootloadersettings}
> osdevice                partition=\Device\HarddiskVolume1
> systemroot              \Windows
> resumeobject            {89f269f3-cc9f-11e6-8727-64006a16df31}
> nx                      OptIn
> detecthal               Yes
> 
> Windows Boot Loader
> -------------------
> identifier              {8c132516-806f-11e9-8860-f798d1b7a8f1}
> device                  partition=C:
> path                    \WINDOWS\system32\winload.exe
> description             Windows10 with Hyper-V
> locale                  en-US
> inherit                 {bootloadersettings}
> recoverysequence        {8c132514-806f-11e9-8860-f798d1b7a8f1}
> displaymessageoverride  Recovery
> recoveryenabled         Yes
> allowedinmemorysettings 0x15000075
> osdevice                partition=C:
> systemroot              \WINDOWS
> resumeobject            {8c132511-806f-11e9-8860-f798d1b7a8f1}
> nx                      OptIn
> bootmenupolicy          Legacy
> hypervisorlaunchtype    Auto
> 
> C:\Users\Liu.D.H>systeminfo
> 
> Host Name:                 DESKTOP-LDH
> OS Name:                   Microsoft Windows 10 Education
> OS Version:                10.0.19041 N/A Build 19041
> OS Manufacturer:           Microsoft Corporation
> OS Configuration:          Standalone Workstation
> OS Build Type:             Multiprocessor Free
> Registered Owner:          Windows User
> Registered Organization:
> Product ID:                00328-10000-00001-AA635
> Original Install Date:     2020-05-11, 22:13:14
> System Boot Time:          2020-06-08, 10:12:11
> System Manufacturer:       Dell Inc.
> System Model:              Vostro 3900
> System Type:               x64-based PC
> Processor(s):              1 Processor(s) Installed.
>                            [01]: Intel64 Family 6 Model 60 Stepping 3 GenuineIntel ~3601 Mhz
> BIOS Version:              Dell Inc. A10, 2015-07-30
> Windows Directory:         C:\WINDOWS
> System Directory:          C:\WINDOWS\system32
> Boot Device:               \Device\HarddiskVolume1
> System Locale:             zh-cn;Chinese (China)
> Input Locale:              zh-cn;Chinese (China)
> Time Zone:                 (UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi
> Total Physical Memory:     16,301 MB
> Available Physical Memory: 9,703 MB
> Virtual Memory: Max Size:  33,709 MB
> Virtual Memory: Available: 26,300 MB
> Virtual Memory: In Use:    7,409 MB
> Page File Location(s):     C:\pagefile.sys
> Domain:                    WORKGROUP
> Logon Server:              \\DESKTOP-LDH
> Hotfix(s):                 6 Hotfix(s) Installed.
>                            [01]: KB4552925
>                            [02]: KB4534170
>                            [03]: KB4537759
>                            [04]: KB4545706
>                            [05]: KB4557968
>                            [06]: KB4556803
> Network Card(s):           4 NIC(s) Installed.
>                            [01]: TAP-Windows Adapter V9
>                                  Connection Name: 以太网
>                                  Status:          Media disconnected
>                            [02]: Realtek PCIe GBE Family Controller
>                                  Connection Name: Ethernet_Realtek
>                                  DHCP Enabled:    Yes
>                                  DHCP Server:     113.55.112.1
>                                  IP address(es)
>                                  [01]: 113.55.127.140
>                                  [02]: fe80::3d0a:ecde:2178:d77c
>                                  [03]: 2001:250:2800:cc09:6600:6aff:fe16:df31
>                            [03]: Realtek RTL8188CU Wireless LAN 802.11n USB 2.0 Network Adapter
>                                  Connection Name: Wi-Fi 2
>                                  Status:          Media disconnected
>                            [04]: Microsoft KM-TEST Loopback Adapter
>                                  Connection Name: Npcap Loopback Adapter
>                                  DHCP Enabled:    Yes
>                                  DHCP Server:     255.255.255.255
>                                  IP address(es)
>                                  [01]: 169.254.104.11
>                                  [02]: fe80::d8bf:11ab:7b05:680b
> Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
>                            Virtualization Enabled In Firmware: Yes
>                            Second Level Address Translation: Yes
>                            Data Execution Prevention Available: Yes
> 
> C:\Users\Liu.D.H>
> ```
> 
> ![image](https://user-images.githubusercontent.com/2276718/83988171-106bf600-a975-11ea-9f2b-aaf2d59ff922.png)
> 
> # Steps to reproduce
> Open Ubuntu 18.04 or 20.04.
> 
> # Expected behavior
> Works as expected.
> 
> # Actual behavior
> ![image](https://user-images.githubusercontent.com/2276718/83988122-e9adbf80-a974-11ea-97e4-d5415ab86a98.png)
> 
> I can confirm that I have enabled `Virtual Machine Platform` and `VT-x`. But the errors when I started Ubuntu is confused. And for some reasons I do not want to enable Hyper-V features. From the doc (https://docs.microsoft.com/en-us/windows/wsl/), it is not a requirement for WSL2.



> # Environment
> ```
> C:\Users\Liu.D.H>ver
> 
> Microsoft Windows [Version 10.0.19041.264]
> 
> C:\Users\Liu.D.H>bcdedit
> 
> Windows Boot Manager
> --------------------
> identifier              {bootmgr}
> device                  partition=\Device\HarddiskVolume1
> description             Windows Boot Manager
> locale                  en-US
> inherit                 {globalsettings}
> default                 {current}
> resumeobject            {8c132511-806f-11e9-8860-f798d1b7a8f1}
> displayorder            {current}
>                         {89f269f4-cc9f-11e6-8727-64006a16df31}
>                         {8c132516-806f-11e9-8860-f798d1b7a8f1}
> toolsdisplayorder       {memdiag}
> timeout                 5
> 
> Windows Boot Loader
> -------------------
> identifier              {current}
> device                  partition=C:
> path                    \WINDOWS\system32\winload.exe
> description             Windows 10
> locale                  en-US
> inherit                 {bootloadersettings}
> recoverysequence        {8c132514-806f-11e9-8860-f798d1b7a8f1}
> displaymessageoverride  Recovery
> recoveryenabled         Yes
> allowedinmemorysettings 0x15000075
> osdevice                partition=C:
> systemroot              \WINDOWS
> resumeobject            {8c132511-806f-11e9-8860-f798d1b7a8f1}
> nx                      OptIn
> bootmenupolicy          Legacy
> hypervisorlaunchtype    Off
> 
> Windows Boot Loader
> -------------------
> identifier              {89f269f4-cc9f-11e6-8727-64006a16df31}
> device                  partition=\Device\HarddiskVolume1
> path                    \Windows\system32\winload.exe
> description             Windows 7
> locale                  zh-CN
> inherit                 {bootloadersettings}
> osdevice                partition=\Device\HarddiskVolume1
> systemroot              \Windows
> resumeobject            {89f269f3-cc9f-11e6-8727-64006a16df31}
> nx                      OptIn
> detecthal               Yes
> 
> Windows Boot Loader
> -------------------
> identifier              {8c132516-806f-11e9-8860-f798d1b7a8f1}
> device                  partition=C:
> path                    \WINDOWS\system32\winload.exe
> description             Windows10 with Hyper-V
> locale                  en-US
> inherit                 {bootloadersettings}
> recoverysequence        {8c132514-806f-11e9-8860-f798d1b7a8f1}
> displaymessageoverride  Recovery
> recoveryenabled         Yes
> allowedinmemorysettings 0x15000075
> osdevice                partition=C:
> systemroot              \WINDOWS
> resumeobject            {8c132511-806f-11e9-8860-f798d1b7a8f1}
> nx                      OptIn
> bootmenupolicy          Legacy
> hypervisorlaunchtype    Auto
> 
> C:\Users\Liu.D.H>systeminfo
> 
> Host Name:                 DESKTOP-LDH
> OS Name:                   Microsoft Windows 10 Education
> OS Version:                10.0.19041 N/A Build 19041
> OS Manufacturer:           Microsoft Corporation
> OS Configuration:          Standalone Workstation
> OS Build Type:             Multiprocessor Free
> Registered Owner:          Windows User
> Registered Organization:
> Product ID:                00328-10000-00001-AA635
> Original Install Date:     2020-05-11, 22:13:14
> System Boot Time:          2020-06-08, 10:12:11
> System Manufacturer:       Dell Inc.
> System Model:              Vostro 3900
> System Type:               x64-based PC
> Processor(s):              1 Processor(s) Installed.
>                            [01]: Intel64 Family 6 Model 60 Stepping 3 GenuineIntel ~3601 Mhz
> BIOS Version:              Dell Inc. A10, 2015-07-30
> Windows Directory:         C:\WINDOWS
> System Directory:          C:\WINDOWS\system32
> Boot Device:               \Device\HarddiskVolume1
> System Locale:             zh-cn;Chinese (China)
> Input Locale:              zh-cn;Chinese (China)
> Time Zone:                 (UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi
> Total Physical Memory:     16,301 MB
> Available Physical Memory: 9,703 MB
> Virtual Memory: Max Size:  33,709 MB
> Virtual Memory: Available: 26,300 MB
> Virtual Memory: In Use:    7,409 MB
> Page File Location(s):     C:\pagefile.sys
> Domain:                    WORKGROUP
> Logon Server:              \\DESKTOP-LDH
> Hotfix(s):                 6 Hotfix(s) Installed.
>                            [01]: KB4552925
>                            [02]: KB4534170
>                            [03]: KB4537759
>                            [04]: KB4545706
>                            [05]: KB4557968
>                            [06]: KB4556803
> Network Card(s):           4 NIC(s) Installed.
>                            [01]: TAP-Windows Adapter V9
>                                  Connection Name: 以太网
>                                  Status:          Media disconnected
>                            [02]: Realtek PCIe GBE Family Controller
>                                  Connection Name: Ethernet_Realtek
>                                  DHCP Enabled:    Yes
>                                  DHCP Server:     113.55.112.1
>                                  IP address(es)
>                                  [01]: 113.55.127.140
>                                  [02]: fe80::3d0a:ecde:2178:d77c
>                                  [03]: 2001:250:2800:cc09:6600:6aff:fe16:df31
>                            [03]: Realtek RTL8188CU Wireless LAN 802.11n USB 2.0 Network Adapter
>                                  Connection Name: Wi-Fi 2
>                                  Status:          Media disconnected
>                            [04]: Microsoft KM-TEST Loopback Adapter
>                                  Connection Name: Npcap Loopback Adapter
>                                  DHCP Enabled:    Yes
>                                  DHCP Server:     255.255.255.255
>                                  IP address(es)
>                                  [01]: 169.254.104.11
>                                  [02]: fe80::d8bf:11ab:7b05:680b
> Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
>                            Virtualization Enabled In Firmware: Yes
>                            Second Level Address Translation: Yes
>                            Data Execution Prevention Available: Yes
> 
> C:\Users\Liu.D.H>
> ```
> 
> ![image](https://user-images.githubusercontent.com/2276718/83988171-106bf600-a975-11ea-9f2b-aaf2d59ff922.png)
> 
> # Steps to reproduce
> Open Ubuntu 18.04 or 20.04.
> 
> # Expected behavior
> Works as expected.
> 
> # Actual behavior
> ![image](https://user-images.githubusercontent.com/2276718/83988122-e9adbf80-a974-11ea-97e4-d5415ab86a98.png)
> 
> I can confirm that I have enabled `Virtual Machine Platform` and `VT-x`. But the errors when I started Ubuntu is confused. And for some reasons I do not want to enable Hyper-V features. From the doc (https://docs.microsoft.com/en-us/windows/wsl/), it is not a requirement for WSL2.

How did you get all the environment info of your machine?

**Comment by S-Osman4** [comment]
@Ukriyte systeminfo in your terminal should work

**Comment by MHKhan18** [comment]
I was having the same error on a Windows-10 machine despite having the Virtual Machine Platform and Windows Subsystem for Linux features turned on. Got around it by enabling Intel Software Guards Extension in Bios settings (it was set to software controlled).

**Comment by NikolozCh** [comment]
> Hope to document enable Hyper-V in https://docs.microsoft.com/en-us/windows/wsl/install-win10 when install and run wsl2.
> 
> * `DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V`
> * `bcdedit /set hypervisorlaunchtype auto`

Thanks for the help. It worked like a charm!

Note: Before running the commands, open Powershell with admin rights.

**Comment by MattMcL4475** [comment]
This is still an issue in Azure as of 3/31/2023 when creating a new VM with Windows 11

**Comment by wabass** [comment]
Have you tried 

```
$wsl --update
```

**Comment by mym4y4** [comment]
Just enable the optional component 'Windows Hypervisor Platform'

**Comment by jay-jjwu** [comment]
if you are using a virtualized windows, enable this CPU setting in your virtual platform...
![image](https://github.com/microsoft/WSL/assets/78014320/f545124a-1b57-409f-8846-d4b90f92e77b)

**Comment by DanKaplanSES** [comment]
What's left in this feature? Is it to update the documentation in [the FAQ](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq)?

> WSL 2 is available on all Desktop SKUs where WSL is available, including Windows 10 Home and Windows 11 Home.
> 
> The newest version of WSL uses Hyper-V architecture to enable its virtualization. This architecture will be available in the 'Virtual Machine Platform' optional component. This optional component will be available on all SKUs. You can expect to see more details about this experience soon as we get closer to the WSL 2 release.

This second paragraph seems like it was written before WSL2 or maybe before the 'Virtual Machine Platform' checkbox existed? If I'm wrong about that, IMHO, the wording gives this impression.

I'd add how to get to the "Turn Windows Features On or Off" dialog to change that 'Virtual Machine Platform' checkbox (Press Win + Q then search for "Turn Windows Features On or Off"). I tried to find out how I could submit a PR with a doc update, but after a few minutes I couldn't find where it's committed. I'm assuming only MS employees can edit that page.

**Comment by Stan-Green** [comment]
I still cannot run VMWare Player 5.5.7 with Virtualization enabled (I need this to run Docker in the VM) and WSL2 on the same desktop computer. This works on my Lenovo T480 laptop; I don't know why the laptop is different, as all the Windows features are the same as the desktop. Both are on Windows 10. As others have noted, I have the "Virtual Machine Platform" feature enabled and the "Hyper-V" feature disabled due to the VMWare requirement. The command "bcdedit /set hypervisorlaunchtype auto" does not work as the VMWare VM will not run due to the Virtualization being turned on in the Gust OS. I know this is an ancient issue, but are there any updates on running WSL2 and VMWare on the same desktop computer?

**Comment by borguuh** [comment]
Found a solution for coexisting VMware Workstation Pro and Hyper-V on the same system. Although they can't run simultaneously, you can switch between them using the following commands:

To use VMware Workstation Pro:
```bash
Bcdedit /set hypervisorlaunchtype off
```
Restart your system after executing the command.

To use Hyper-V:
```bash
Bcdedit /set hypervisorlaunchtype auto
```
Again, restart your system after executing the command.

This allows you to use either VMware Workstation Pro 15 or Hyper-V on the same machine, one at a time. Hope this helps!

**Comment by Stan-Green** [comment]
Yes, @borguuh if you are OK with restarting all the time, that would work. I don't what to have to restart just to run a quick WSL command. I only restart when Windows makes me! Again, I can run both at the same time on my laptop, but not my desktop. They both have the same settings. I would like to run both WSL2 and VMWare Player (BTW: Not Pro) at the same time.

**Comment by annehanako** [comment]
![image](https://github.com/microsoft/WSL/assets/117386596/74064f2c-d12b-438d-9466-dd4018bf9270)
I am having the following issue, I need WSL for Docker, trying to fix it. I already enabled my VM in BIOS and followed all the steps I could find, still nothing working. In my other computer tho I had no issues with this. I will be updating if I find a way to fix it.

**Comment by AshleyHelen808** [comment]
Just resolved this issue by updating my bios to include virtualization. It's quite hidden in UEFI, the search did nothing for me. Windows doesn't even pick it up in windows features. Good luck!

**Comment by bravemaster3** [comment]
I also did everything, until the suggestions of some above, to deactivate and reactivate WSL (in windows features), worked for me as well.

**Comment by AionZones** [comment]
> # Environment
> ```
> C:\Users\Liu.D.H>ver
> 
> Microsoft Windows [Version 10.0.19041.264]
> 
> C:\Users\Liu.D.H>bcdedit
> 
> Windows Boot Manager
> --------------------
> identifier              {bootmgr}
> device                  partition=\Device\HarddiskVolume1
> description             Windows Boot Manager
> locale                  en-US
> inherit                 {globalsettings}
> default                 {current}
> resumeobject            {8c132511-806f-11e9-8860-f798d1b7a8f1}
> displayorder            {current}
>                         {89f269f4-cc9f-11e6-8727-64006a16df31}
>                         {8c132516-806f-11e9-8860-f798d1b7a8f1}
> toolsdisplayorder       {memdiag}
> timeout                 5
> 
> Windows Boot Loader
> -------------------
> identifier              {current}
> device                  partition=C:
> path                    \WINDOWS\system32\winload.exe
> description             Windows 10
> locale                  en-US
> inherit                 {bootloadersettings}
> recoverysequence        {8c132514-806f-11e9-8860-f798d1b7a8f1}
> displaymessageoverride  Recovery
> recoveryenabled         Yes
> allowedinmemorysettings 0x15000075
> osdevice                partition=C:
> systemroot              \WINDOWS
> resumeobject            {8c132511-806f-11e9-8860-f798d1b7a8f1}
> nx                      OptIn
> bootmenupolicy          Legacy
> hypervisorlaunchtype    Off
> 
> Windows Boot Loader
> -------------------
> identifier              {89f269f4-cc9f-11e6-8727-64006a16df31}
> device                  partition=\Device\HarddiskVolume1
> path                    \Windows\system32\winload.exe
> description             Windows 7
> locale                  zh-CN
> inherit                 {bootloadersettings}
> osdevice                partition=\Device\HarddiskVolume1
> systemroot              \Windows
> resumeobject            {89f269f3-cc9f-11e6-8727-64006a16df31}
> nx                      OptIn
> detecthal               Yes
> 
> Windows Boot Loader
> -------------------
> identifier              {8c132516-806f-11e9-8860-f798d1b7a8f1}
> device                  partition=C:
> path                    \WINDOWS\system32\winload.exe
> description             Windows10 with Hyper-V
> locale                  en-US
> inherit                 {bootloadersettings}
> recoverysequence        {8c132514-806f-11e9-8860-f798d1b7a8f1}
> displaymessageoverride  Recovery
> recoveryenabled         Yes
> allowedinmemorysettings 0x15000075
> osdevice                partition=C:
> systemroot              \WINDOWS
> resumeobject            {8c132511-806f-11e9-8860-f798d1b7a8f1}
> nx                      OptIn
> bootmenupolicy          Legacy
> hypervisorlaunchtype    Auto
> 
> C:\Users\Liu.D.H>systeminfo
> 
> Host Name:                 DESKTOP-LDH
> OS Name:                   Microsoft Windows 10 Education
> OS Version:                10.0.19041 N/A Build 19041
> OS Manufacturer:           Microsoft Corporation
> OS Configuration:          Standalone Workstation
> OS Build Type:             Multiprocessor Free
> Registered Owner:          Windows User
> Registered Organization:
> Product ID:                00328-10000-00001-AA635
> Original Install Date:     2020-05-11, 22:13:14
> System Boot Time:          2020-06-08, 10:12:11
> System Manufacturer:       Dell Inc.
> System Model:              Vostro 3900
> System Type:               x64-based PC
> Processor(s):              1 Processor(s) Installed.
>                            [01]: Intel64 Family 6 Model 60 Stepping 3 GenuineIntel ~3601 Mhz
> BIOS Version:              Dell Inc. A10, 2015-07-30
> Windows Directory:         C:\WINDOWS
> System Directory:          C:\WINDOWS\system32
> Boot Device:               \Device\HarddiskVolume1
> System Locale:             zh-cn;Chinese (China)
> Input Locale:              zh-cn;Chinese (China)
> Time Zone:                 (UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi
> Total Physical Memory:     16,301 MB
> Available Physical Memory: 9,703 MB
> Virtual Memory: Max Size:  33,709 MB
> Virtual Memory: Available: 26,300 MB
> Virtual Memory: In Use:    7,409 MB
> Page File Location(s):     C:\pagefile.sys
> Domain:                    WORKGROUP
> Logon Server:              \\DESKTOP-LDH
> Hotfix(s):                 6 Hotfix(s) Installed.
>                            [01]: KB4552925
>                            [02]: KB4534170
>                            [03]: KB4537759
>                            [04]: KB4545706
>                            [05]: KB4557968
>                            [06]: KB4556803
> Network Card(s):           4 NIC(s) Installed.
>                            [01]: TAP-Windows Adapter V9
>                                  Connection Name: 以太网
>                                  Status:          Media disconnected
>                            [02]: Realtek PCIe GBE Family Controller
>                                  Connection Name: Ethernet_Realtek
>                                  DHCP Enabled:    Yes
>                                  DHCP Server:     113.55.112.1
>                                  IP address(es)
>                                  [01]: 113.55.127.140
>                                  [02]: fe80::3d0a:ecde:2178:d77c
>                                  [03]: 2001:250:2800:cc09:6600:6aff:fe16:df31
>                            [03]: Realtek RTL8188CU Wireless LAN 802.11n USB 2.0 Network Adapter
>                                  Connection Name: Wi-Fi 2
>                                  Status:          Media disconnected
>                            [04]: Microsoft KM-TEST Loopback Adapter
>                                  Connection Name: Npcap Loopback Adapter
>                                  DHCP Enabled:    Yes
>                                  DHCP Server:     255.255.255.255
>                                  IP address(es)
>                                  [01]: 169.254.104.11
>                                  [02]: fe80::d8bf:11ab:7b05:680b
> Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
>                            Virtualization Enabled In Firmware: Yes
>                            Second Level Address Translation: Yes
>                            Data Execution Prevention Available: Yes
> 
> C:\Users\Liu.D.H>
> ```
> 
> ![image](https://user-images.githubusercontent.com/2276718/83988171-106bf600-a975-11ea-9f2b-aaf2d59ff922.png)
> 
> # Steps to reproduce
> Open Ubuntu 18.04 or 20.04.
> 
> # Expected behavior
> Works as expected.
> 
> # Actual behavior
> ![image](https://user-images.githubusercontent.com/2276718/83988122-e9adbf80-a974-11ea-97e4-d5415ab86a98.png)
> 
> I can confirm that I have enabled `Virtual Machine Platform` and `VT-x`. But the errors when I started Ubuntu is confused. And for some reasons I do not want to enable Hyper-V features. From the doc (https://docs.microsoft.com/en-us/windows/wsl/), it is not a requirement for WSL2.

hi sir

**Comment by AionZones** [comment]
![image](https://github.com/microsoft/WSL/assets/174421710/49947bbf-11eb-4ed7-9600-1361846ad144)
Can you help me how to disable in command prompt the four hyper v pls? Im playing a game called aion and i cant run the game because it still detecting the hyper v error.. Pls let me know how you can disable it tru command prompt or any settings in windows 11 Home. Thank u so much in advance for helping

**Comment by VladasZ** [comment]
@TradingIndian this worked for me too. Thanks!

**Comment by rtmreza** [comment]
for solve this problem : 
see this video

https://www.youtube.com/watch?v=myouQBBDhXQ

**Comment by leotorol** [comment]
This command saved my life

bcdedit /set hypervisorlaunchtype auto
