### ISSUE TITLE
KB4566782 (OS Build 19041.450) breaks WSL 2

### ISSUE THREAD

**Issue by sajithneyo** [microsoft/WSL#5760]
# Environment

```none
Windows build number: 10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Your Distribution version: Ubuntu 18.04 LTS
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

Update the Windows. Especially for me KB4566782. After that, WSL 2 stops working.

#  Expected behavior

WSL2 related services to work normally.

# Actual behavior

Docker with WSL2 backend crashes.
Linux installations with WSL 2 stops working.

# How this bug occurred me

I use Ubuntu 20.04 WSL2 and Docker WSL2 backend. An automatic update was applied on 2020-08-14. The update is **August 11, 2020—KB4566782 (OS Build 19041.450)**. After that Docker started to crash always. Then I tried Windows Terminal. It also started to crash (Coz it's using Ubuntu 20.04 WSL2 by default)

# Workaround I found

I had to uninstall both my WSL2 related Docker and Ubuntu. Then I changed WSL to version 1. Then installed Ubuntu 20.04 and Docker. Docker somehow uses WSL2 even I opt-out from that feature when installing. It takes some time for docker to crash. So in between, I accessed the docker-desktop dashboard and disabled the WSL2 feature. Now both are working fine in WSL1.

# Conclusion

Anything related to WSL 2 does not work. Linux distros cannot be installed by changing to WSL 2. Trying to install Ubuntu 18.04 LTS on WSL 2 throws 
```
WslRegisterDistribution failed with error: 0x80041002
Error: 0x80041002 (null)
Press any key to continue...
```

Please fix this

**Comment by benhillis** [comment]
Could you please take a trace?

**Comment by sajithneyo** [comment]
@benhillis of what and how?

**Comment by benhillis** [comment]
https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs

**Comment by bminahan73** [comment]
for me after the update WSL command just hangs. Uninstalling the update resolved the issue (but I'd like to keep up to date)

**Comment by sajithneyo** [comment]
@benhillis https://aka.ms/AA99z5m

**Comment by bmmuller** [comment]
I had exactly the same problem reported by @sajithneyo:
- Docker with WSL2 backend crashes.
- Linux installations with WSL 2 stops working (Ubuntu 20.04 in my case too)

This happened right after an automatic update of two KBs: KB4569745 and KB4566782

**Comment by takizo** [comment]
I further found out uninstall Virtual Machine Platform will resolve BSOD, but WSL2 cannot run, need to downgrade to WSL1. 

It's either 
1. Uninstall KB4566782 
2. Uninstall VMP and downgrade to WSL1. 

Hope the info helps.

**Comment by niallnsec** [comment]
I'm having the same issue. I was using WSL2 to support docker and after Windows installed updates KB4569745 and KB4566782 my system entered a boot loop.

The crash was reliable and would trigger a short time after startup, usually before the "Installing Updates" page was done. A couple of times I could log in but the system never lasts more than a minuet after boot.

The BSOD was an un-handled exception in a system thread (`SYSTEM THREAD EXCEPTION NOT HANDLED`), always occurring in `SparkIO.sys`. Unfortunately Windows would not write a minidump otherwise I could provide more information.

I couldn't find any info on SparkIO.sys and notice that without the VMP feature and WSL enabled it is not present on my system, so I assume it must be related to one of these features.

The only way to fix the problem for me was to disable the Virtual Machine Platform feature. Unfortunately, by the time I saw it (Windows rebooted my machine while I was asleep) the boot loop and recovery process had destroyed my OS, forcing me to re-install windows from an install disk (completely clean reinstall).

On the fresh install, fully updated, if I try to enable Virtual Machine Platform the system will begin crashing again until the feature is removed.

My CPU is an AMD Ryzen 7 4800H.

**Comment by takizo** [comment]
> I'm having the same issue. I was using WSL2 to support docker and after Windows installed updates KB4569745 and KB4566782 my system entered a boot loop.
> 
> The crash was reliable and would trigger a short time after startup, usually before the "Installing Updates" page was done. A couple of times I could log in but the system never lasts more than a minuet after boot.
> 
> The BSOD was an un-handled exception in a system thread (`SYSTEM THREAD EXCEPTION NOT HANDLED`), always occurring in `SparkIO.sys`. Unfortunately Windows would not write a minidump otherwise I could provide more information.
> 
> I couldn't find any info on SparkIO.sys and notice that without the VMP feature and WSL enabled it is not present on my system, so I assume it must be related to one of these features.
> 
> The only way to fix the problem for me was to disable the Virtual Machine Platform feature. Unfortunately, by the time I saw it (Windows rebooted my machine while I was asleep) the boot loop and recovery process had destroyed my OS, forcing me to re-install windows from an install disk (completely clean reinstall).
> 
> On the fresh install, fully updated, if I try to enable Virtual Machine Platform the system will begin crashing again until the feature is removed.
> 
> My CPU is an AMD Ryzen 7 4800H.

I also did clean install. But after disabled Intel VT on BIOS, I was able to boot into Windows 10. Lucky enough I have 2 machines, one machine able to patched to latest and I realize only different is the other machine without boot loop is running WSL1, thinkpad I am using getting Bootloop is WSL2.

After uninstall Virtual Machine Platform, then only I was able to identified the main issue is Virtual machine platform.

**Comment by ruftas** [comment]
> # Environment
> ```
> Windows build number: 10.0.19041.0 Microsoft Windows NT 10.0.19041.0
> Your Distribution version: Ubuntu 18.04 LTS
> Whether the issue is on WSL 2 and/or WSL 1: WSL 2
> ```
> 
> # Steps to reproduce
> Update the Windows. Especially for me KB4566782. After that, WSL 2 stops working.
> 
> # Expected behavior
> WSL2 related services to work normally.
> 
> # Actual behavior
> Docker with WSL2 backend crashes.
> Linux installations with WSL 2 stops working.
> 
> # How this bug occurred me
> I use Ubuntu 20.04 WSL2 and Docker WSL2 backend. An automatic update was applied on 2020-08-14. The update is **August 11, 2020—KB4566782 (OS Build 19041.450)**. After that Docker started to crash always. Then I tried Windows Terminal. It also started to crash (Coz it's using Ubuntu 20.04 WSL2 by default)
> 
> # Workaround I found
> I had to uninstall both my WSL2 related Docker and Ubuntu. Then I changed WSL to version 1. Then installed Ubuntu 20.04 and Docker. Docker somehow uses WSL2 even I opt-out from that feature when installing. It takes some time for docker to crash. So in between, I accessed the docker-desktop dashboard and disabled the WSL2 feature. Now both are working fine in WSL1.
> 
> # Conclusion
> Anything related to WSL 2 does not work. Linux distros cannot be installed by changing to WSL 2. Trying to install Ubuntu 18.04 LTS on WSL 2 throws
> 
> ```
> WslRegisterDistribution failed with error: 0x80041002
> Error: 0x80041002 (null)
> Press any key to continue...
> ```
> 
> Please fix this


**The problem is with the Windows update..**

**Comment by wintertee** [comment]
Same problem. My laptop is MECHREVO code01 with Ryzen 4800H. After having updated to OS Build 19041.450, enabling Hyper-v cause BSOD before entering the system, showing `SYSTEM THREAD EXCEPTION NOT HANDLED` , but no driver issue is found.

**Comment by ManuDoni** [comment]
I have the same issue with XMG core 17 AMD. I have a clean installation of windows 10 (with XMG control center) and after installing Docker Windows cannot start.
Which one is to blame? WSL2 or the control center?

**Comment by 19188** [comment]
> Same problem. My laptop is MECHREVO code01 with Ryzen 4800H. After having updated to OS 
Same problem. Mine MECHREVO Jiaolong Series with 4600h. After enabling VMP, I can login, but within seconds I got bsod referring SparkIO.sys

**Comment by nickgreensgithub** [comment]
> > Same problem. My laptop is MECHREVO code01 with Ryzen 4800H. After having updated to OS
> 
> Same problem. Mine MECHREVO Jiaolong Series with 4600h. After enabling VMP, I can login, but within seconds I got bsod referring SparkIO.sys
> 
> Maybe romoving OEM software like GamingCenterU will work? it has the same file SparkIOsys. I havent tried though.
> ![capture](https://user-images.githubusercontent.com/22554102/91735123-6a7c0080-ebde-11ea-9434-b6d318475caf.png)

For me uninstalling Control Centre worked, I've been using wsl and docker again for over a week now with no crashes. I guess GamingCenterU is just Control Centre with another name.

**Comment by cyberdude** [comment]
> Same situation here, after an update this morning I got stuck in a boot loop and had to disable Hyper-v, WSL, and Virtual Machine Platform to get past the windows login screen.
> 
> Everytime the error on the bsod mentioned SparkIO.sys.
> 
> I can't get docker working with just Hyper-V anymore like I used to have, it also wants me to enable Virtual Machine Platform which seems to the the cause of the bsod.
> 
> My cpu is also an AMD Ryzen 7 4800h, I hope that's just a conicidence.
> 
> Overall I've had an exceptionally unproductive Friday.

@nickgreensgithub SparkIO.sys is part of the control center.  Reboot in safe mode and delete the control center that your XMG has installed in order to control the light of your keyboard and other display configuration.  Please open a ticket too with them.  I have one open

**Comment by sajithneyo** [comment]
@benhillis any update on this?

**Comment by sajithneyo** [comment]
I guess the error already exists in OS Build 19041.450 as I did a fresh install today and still the problem of WSL2 not working existed. Then I updated to the latest (OS Build 19041.508) and now it works perfectly. In my previous install, I did not have Virtual Switch 'WSL'. So I guess this can be the root cause. But there is no way for me to confirm this as I have a fresh windows. The reason I noticed this is, I have a 'WSL' virtual switch in the latest build thatI have now.

![image](https://user-images.githubusercontent.com/27737837/92611261-3c7d7700-f2d6-11ea-94c2-2fd5332ec52a.png)

A lot of you guys are talking about ControlCenter and about an AMD processor. But it wasn't my case as I have a Intel. As this issue is solved, I'm closing this. Thank you!

**Comment by XMG-gg** [comment]
This is currently a known issue and it has also been reported to our ODM from various customers in other regions. Although the Bluescreen points at Control Center, the current assumption is that this is a issue unique on Windows v2004 (May 2020 Update). Our ODM is in touch with Microsoft to find a solution.

When Control Center is uninstalled, you still have some access to different performance profiles with the mode switch button, next to the power button. It has 3 stati:
- Off
- Half
- Full

You'll see some difference in CPU and GPU clock between these modes, although the difference is not as strong as when having Control Center installed. If this is the only way for you to use WSL2 right now, it's worth a try.

// Tom

**Comment by wintertee** [comment]
> Same problem. My laptop is MECHREVO code01 with Ryzen 4800H. After having updated to OS Build 19041.450, enabling Hyper-v cause BSOD before entering the system, showing `SYSTEM THREAD EXCEPTION NOT HANDLED` , but no driver issue is found.

update: I made a clean installation of Windows 10 (19041.388) and everything works right.
**NOTE:** Disable Windows update!!! Do not update to 19041.450!!!

**Comment by brisexton** [comment]
I thought this issue had something to do with my laptop hardware so I've been in touch with Lenovo. After that August 14th update I blue screen and no crash dump is generated. Intel i7-8665U CPU.

`SYSTEM TREAD EXCEPTION NOT HANDLED`
`Faulting module: acpi.sys`

The only thing I found, which is an old post on MSDN forums, was [Enabled Hyper-V causes "System thread exception not handled" BSOD](https://social.technet.microsoft.com/Forums/en-US/17c2bbb3-a167-48b0-87bb-c6c0bc4e337a/enabled-hyperv-causes-quotsystem-thread-exception-not-handledquot-bsod-in-builds-10041-and?forum=WinPreview2014Feedback)

I have Visual Studio 2019 Professional installed and run Hyper-V. Other Windows components regarding virtualization include Containers and Windows Hypervisor Platform. Virtual Machine Platform is not installed because I run full-blown Hyper-V. 

I came across this post on VMware's forums: [Windows 10 2004 (May 2020 Update) VM upgrade/boot fails with BSOD Stop Code: SYSTEM THREAD EXCEPTION NOT HANDLED](https://communities.vmware.com/thread/639655). My Intel CPU has 4 cores. 

@benhillis , Do you know if anything was reported regarding this? Windows OS with 4 cores (or 4 vCPU's) being exposed from an Intel CPU causing `SYSTEM THREAD EXCEPTION NOT HANDLED` to occur. And should this be posted under the [hcsshim](https://github.com/microsoft/hcsshim) repo?

My workstation (tower), which is running an AMD Ryzen 5 2600 with 6 cores and has Visual Studio 2019 as well as Docker Installed. On the Windows Features side, the following are installed:

- Hyper-V
- Containers
- Windows Subsystem for Linux (with Ubuntu 18.04 LTS)
- WSL 2

My workstation has had _**NO**_ issues with any of the updates. 

Coming across this issue, I uninstalled Docker and Windows System for Linux as well as the 4.19.128 update. 

@takizo , I don't know if I have the enhanced Biometric feature on so I'm going to check that right now, but I do have a ThinkPad P43s.

**Comment by takizo** [comment]
> I thought this issue had something to do with my laptop hardware so I've been in touch with Lenovo. After that August 14th update I blue screen and no crash dump is generated. Intel i7-8665U CPU.
> 
> `SYSTEM TREAD EXCEPTION NOT HANDLED`
> `Faulting module: acpi.sys`
> 
> The only thing I found, which is an old post on MSDN forums, was [Enabled Hyper-V causes "System thread exception not handled" BSOD](https://social.technet.microsoft.com/Forums/en-US/17c2bbb3-a167-48b0-87bb-c6c0bc4e337a/enabled-hyperv-causes-quotsystem-thread-exception-not-handledquot-bsod-in-builds-10041-and?forum=WinPreview2014Feedback)
> 
> I have Visual Studio 2019 Professional installed and run Hyper-V. Other Windows components regarding virtualization include Containers and Windows Hypervisor Platform. Virtual Machine Platform is not installed because I run full-blown Hyper-V.
> 
> I came across this post on VMware's forums: [Windows 10 2004 (May 2020 Update) VM upgrade/boot fails with BSOD Stop Code: SYSTEM THREAD EXCEPTION NOT HANDLED](https://communities.vmware.com/thread/639655). My Intel CPU has 4 cores.
> 
> @benhillis , Do you know if anything was reported regarding this? Windows OS with 4 cores (or 4 vCPU's) being exposed from an Intel CPU causing `SYSTEM THREAD EXCEPTION NOT HANDLED` to occur. And should this be posted under the [hcsshim](https://github.com/microsoft/hcsshim) repo?
> 
> My workstation (tower), which is running an AMD Ryzen 5 2600 with 6 cores and has Visual Studio 2019 as well as Docker Installed. On the Windows Features side, the following are installed:
> 
> * Hyper-V
> * Containers
> * Windows Subsystem for Linux (with Ubuntu 18.04 LTS)
> * WSL 2
> 
> My workstation has had _**NO**_ issues with any of the updates.
> 
> Coming across this issue, I uninstalled Docker and Windows System for Linux as well as the 4.19.128 update.
> 
> @takizo , I don't know if I have the enhanced Biometric feature on so I'm going to check that right now, but I do have a ThinkPad P43s.

Hopefully it's the biometric, mine root cause is confirmed the Biometric function in BIOS. Once that disable, I can upgrade to the latest KB and enable Virtual Machine Platform 

![image](https://user-images.githubusercontent.com/582304/93730394-fb9d3080-fbfa-11ea-9341-6d738d22ae67.png)

**Comment by brisexton** [comment]
I wonder what that Enhanced Windows Biometric actually enables/provides to the system. I turned it off and was able to successfully: 

1. Enable Hyper-V
2. Enable Windows Hyper-V Platform
3. Install Windows System for Linux
4. Install Docker
4a. Docker the enabled the Containers feature
4b. And enabled the Virtual Machine Platform feature
5. Install Ubuntu 18.04 from the Windows store and get through setup
6. Enable WSL2 support via docker and install the WSL2 msi. 

All without issue. I also noticed on my AMD workstation that acpi.sys in C:\Windows\system32\drivers directory was last updated on 9/9/2020. I guess Microsoft did release something this month. However the issue still persisted until I changed that BIOS setting. 

![image](https://user-images.githubusercontent.com/37346284/93731063-46c62d80-fb80-11ea-9e99-b86473dae892.png)

I paused Windows Updates, but it only let's you do it for a month or so. Tomorrow they were going to start back up again and then I would of been stuck at a blue screen. Thank you @takizo .

**Comment by takizo** [comment]
> I wonder what that Enhanced Windows Biometric actually enables/provides to the system. I turned it off and was able to successfully:
> 
> 1. Enable Hyper-V
> 2. Enable Windows Hyper-V Platform
> 3. Install Windows System for Linux
> 4. Install Docker
>    4a. Docker the enabled the Containers feature
>    4b. And enabled the Virtual Machine Platform feature
> 5. Install Ubuntu 18.04 from the Windows store and get through setup
> 6. Enable WSL2 support via docker and install the WSL2 msi.
> 
> All without issue. I also noticed on my AMD workstation that acpi.sys in C:\Windows\system32\drivers directory was last updated on 9/9/2020. I guess Microsoft did release something this month. However the issue still persisted until I changed that BIOS setting.
> 
> ![image](https://user-images.githubusercontent.com/37346284/93731063-46c62d80-fb80-11ea-9e99-b86473dae892.png)
> 
> I paused Windows Updates, but it only let's you do it for a month or so. Tomorrow they were going to start back up again and then I would of been stuck at a blue screen. Thank you @takizo .

I think the biometric has something to do with Virtulization environment, because that option is available in Virtualization Technology. I forgot where I read, it mentioned Windows 10 no longer support hence it will cause BSOD. It's might well turn it off :) At least it will not affect our work.

**Comment by brisexton** [comment]
> > I wonder what that Enhanced Windows Biometric actually enables/provides to the system. I turned it off and was able to successfully:
> > 
> > 1. Enable Hyper-V
> > 2. Enable Windows Hyper-V Platform
> > 3. Install Windows System for Linux
> > 4. Install Docker
> >    4a. Docker the enabled the Containers feature
> >    4b. And enabled the Virtual Machine Platform feature
> > 5. Install Ubuntu 18.04 from the Windows store and get through setup
> > 6. Enable WSL2 support via docker and install the WSL2 msi.
> > 
> > All without issue. I also noticed on my AMD workstation that acpi.sys in C:\Windows\system32\drivers directory was last updated on 9/9/2020. I guess Microsoft did release something this month. However the issue still persisted until I changed that BIOS setting.
> > ![image](https://user-images.githubusercontent.com/37346284/93731063-46c62d80-fb80-11ea-9e99-b86473dae892.png)
> > I paused Windows Updates, but it only let's you do it for a month or so. Tomorrow they were going to start back up again and then I would of been stuck at a blue screen. Thank you @takizo .
> 
> I think the biometric has something to do with Virtulization environment, because that option is available in Virtualization Technology. I forgot where I read, it mentioned Windows 10 no longer support hence it will cause BSOD. It's might well turn it off :) At least it will not affect our work.

That's good to know. Thanks a million!

**Comment by XMG-gg** [comment]
For anyone who is using TongFang models with AMD Ryzen, we have posted a BIOS update with a solution in this thread:

https://www.reddit.com/r/XMG_gg/comments/kb1p9i/solution_for_hyperv_and_wsl2_issues_on_various/

This applies to the following TongFang models: PF5NU1G, PF4NU1F, GK5NP5O, GK5NPFO, GK5NR0O, GK7NP5R, GK7NPFR, GK7NR0R.

If you're not sure which model you have, check the rating label on the bottom of your laptop and follow the instruction in the linked thread.

**Comment by MU-Software** [comment]
Hansung TFX5470H laptop that uses AMD Ryzen 4800H (that's OEM version of XMG's) posted a new BIOS update(1.07) that says "solved problem related to virtualization", I tested it, and IT FINALLY WORKS!!! I can boot without any BSOD after enabling Virtual Machine Platform and WSL2!!!!!!! Thank you for doing a great job, @XMG-gg !
