### ISSUE TITLE
Persist /mnt/wsl mountpoints

### ISSUE THREAD

**Issue by giggio** [microsoft/WSL#5851]
**Is your feature request related to a problem? Please describe.**

In WSL2, I'd like to be able to share my home directory between distros. So when Ubuntu (my main distro) comes up, it adds a symlink from `/mnt/wsl/homeuser/` to `/home/user`, and when OpenSuse comes up, it also mounts from `/mnt/wsl/homeuser/` to `/home/user`.

**Describe the solution you'd like**

I understand `/mnt/wsl` enables the sharing between distros but unfortunately `/mnt/wsl` uses tmpfs, so when wsl shutsdown you lose everything that was there.

**Describe alternatives you've considered**

I could host the files on my main distro (Ubuntu) and share from Ubuntu to `/mnt/wsl/homeuser/`, and when OpenSuse comes up, it does the opposite. Unfortunately, for that to occur, Ubuntu must come up first, and must stay up, consuming memory and cpu cycles.

**Additional context**

Initial request started at #5177. Also related to #689 and to a possible `wsl --mount` described in https://github.com/MicrosoftDocs/WSL/pull/824.

**Comment by stefanloerwald** [comment]
Is there a workaround for this? I need to be able to persist a folder in `/mnt/wsl` for kubernetes/docker-for-win. Actual folder can be elsewhere, but I at least need a way to persistently mount bind in `/mnt/wsl`.

**Comment by stefanloerwald** [comment]
Maybe you have an idea for a workaround, @therealkenc ?

**Comment by therealkenc** [comment]
Use `.bashrc` and `/etc/suders` tricks, same as always for what-would-be normally a `systemd` thing. Analogous firing up (say) `sshd` et cetera at first launch.

**Comment by TBBle** [comment]
`/mnt/wsl` should really only be used for mounts, both bind-mounts across WSL2 distros (the original use-case per https://github.com/microsoft/WSL/issues/4577#issuecomment-545192865), and [`wsl --mount`](https://devblogs.microsoft.com/commandline/access-linux-filesystems-in-windows-and-wsl-2/), not for actually storing data. Persistent data storage outside a distro falls under #689 (per https://github.com/microsoft/WSL/issues/5177#issuecomment-685211096), but the _mount points_ also need to be recreated on startup, for use-cases like Docker Desktop kubernetes hostPath mounts that reference other distros, see https://github.com/docker/for-win/issues/7023#issuecomment-774891325.

This introduces a minor ordering issue, as all the mounts need to be up before any distribution starts (the k8s `hostPath` PV use-case from https://github.com/microsoft/WSL/issues/5177), but of course the mount has no real way to know which distribution is the source of the mount (it's just a bind-mount between two mnt namespaces); it can't rely on running distribution startup scripts, as it wouldn't know that it needs to start docker-desktop _last_ so that its mounts into other distros function correctly.

**Comment by TBBle** [comment]
> Another issue here is where do we create said data/home partition? Seems to be we would have to deal with that inside wsl. So maybe like using docker we can create a persistent drive with the wsl command and then copy HOME to it, then tell wsl to mount it to HOME?

This is a use-case for #689, per https://github.com/microsoft/WSL/issues/5177#issuecomment-685211096: A way/place to store data inside WSL but outside any particular distro's storage, so that it can be shared with all distros without needing to start a particular distro first.

Then you would just need what was originally described in this ticket: When a distro starts, before you access $HOME, you replace with with a symlink/bind-mount to wherever that block device is mounted. (Which could be `/mnt/wsl`, but that will depend on the way #689 is addressed, and if necessary any follow-on work to auto-mount such block devices).

**Comment by b-hayes** [comment]
if you just want to share small files such as  .bashrc and other config files just store them on /mnt/c/.
I use /mnt/c/devtools (c:\devtools) for my bash profile special configs and my entire collection of bash scripts.
My distros just source /mnt/c/devtools...../.bashrc and this is also git repository I sync across multiple machines all using multiple wsl distros.

All my custom scripts reside in NTFS and are accessible by all distros and git bash and PowerShell simply because I added the bin folder to the windows env path.

I have found no performance impact at all, my distros still start and run my scripts instantly.

PS: another trick I do is make all distros use git credential helper from windows and windows composer.phar so they never need to ask for git authentication once windows has triggered a browser sign in.

**Comment by guba-launikda** [comment]
@giggio Did you ever find a solution to this? I can't believe I'm asking about this years later haha

**Comment by giggio** [comment]
> @giggio Did you ever find a solution to this? I can't believe I'm asking about this years later haha

It's been a while since I requested this, and since I haven't tried it again. I don't know if any of the new features would enable it, but AFAIK this is still not possible.

**Comment by wnunezc** [comment]
I am adding a current cross-component use case that shows why persistent `/mnt/wsl` mount coordination is still needed, especially for consumers such as Docker Desktop.

## Environment

- Windows 11 Pro, build 26200
- WSL 2.7.8.0
- WSL kernel 6.18.33.1
- Docker Desktop engine 29.5.3
- A dedicated WSL2 distribution stores Linux-native project trees under `/home/developer/projects`

## Scenario

A consumer outside the source distribution needs stable access to a Linux-native directory. Docker Desktop accepts the directory and internally exposes it through a path similar to:

```text
/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/<distribution>/<hash>
```

The source data remains intact in the original WSL distribution after Windows, WSL, or Docker Desktop restarts. However, the cross-distribution mountpoint/relay is not persistent and may not be recreated before the consumer attempts to use it. The consumer retains a reference to the old path and fails with:

```text
flags: 0x1000: no such file or directory
```

This is represented on the Docker Desktop side by:

- docker/for-win#14924
- docker/for-win#12406
- docker/for-win#10060

## Missing contract

The problem is not persistence of the source files. It is persistence or deterministic rehydration of the mount relationship between WSL distributions and external WSL-based consumers.

A stable contract could take one of these forms:

1. A declarative mechanism for persistent cross-distribution bind mounts that WSL restores before dependent distributions start.
2. A stable namespace/path that consumers can resolve again after the WSL VM restarts.
3. Lifecycle notifications plus dependency ordering so a consumer can wait until the source distribution and shared mount are ready.
4. A supported API to register and rehydrate cross-distribution mount relationships.

## Workaround currently required

The consumer must implement its own recovery service:

1. Detect that the source distribution and directory still exist.
2. Wait for the dependent service to become ready.
3. Detect that the retained relay path is stale.
4. Remove and recreate the consumer-side mount metadata.
5. Recreate the dependent container/process.
6. Limit retries to avoid destructive recovery loops.

This workaround repairs derived mount metadata; it does not repair or restore source data. It indicates that the missing piece is lifecycle coordination rather than storage persistence.

This issue appears to be the appropriate WSL-side feature request. Docker Desktop still owns its generated relay and should rehydrate it, but WSL currently provides no documented persistent cross-distribution mount contract on which such consumers can rely.
