### ISSUE TITLE
wsl --install will say 'Downloading GUI app support' and encounter an error when installing

### ISSUE THREAD

**Issue by craigloewen-msft** [microsoft/WSL#6715]
# Environment

```none
Windows build number: 21337
WSL 2
```

# Steps to reproduce

- As an administrator run `wsl --install`. 

#  Expected behavior

WSL is fully installed and displays no errors. 

# Actual behavior

An error message surrounding GUI app support is displayed.

![image](https://user-images.githubusercontent.com/42221804/112227325-b4fdb280-8bec-11eb-95f7-704d659b2c3c.png)

**Comment by craigloewen-msft** [comment]
This is a known issue that we are working on resolving! An internal setting got flipped and we are working on fixing it. This error does not affect your ability to use the `wsl --install` feature, and will just show this error. Thank you all for your patience!

**Comment by yume-chan** [comment]
Two days ago I found someone on Twitter said he managed to install the GUI app support package (on 21337, before you pulled the file off) and it worked (except GPU acceleration).

Does it mean the GUI support will land to Insider Preview (officially) soon?

**Comment by Biswa96** [comment]
If you see wslg.exe in System32 or WinSxS folder then it's already there but disabled.

**Comment by benhillis** [comment]
@yume-chan - yes we hoping to release soon, once we wrap up a few remaining work items.

**Comment by PavelSosin-320** [comment]
I'm running the Windows Insider preview build 21343.100 and it is already here.

**Comment by wusuowei60** [comment]
By the way, the error code is 0x80190194. I suppose this will be useful for future issue searching.

Besides, looking forward to the final GUI feature on WSL2. :D

**Comment by ati46** [comment]
Does wsl support wayland? I very much hope that sway can be used in wsl.

**Comment by Biswa96** [comment]
> Does wsl support wayland?

It will be. https://www.youtube.com/watch?v=EkNBsBx501Q

**Comment by craigloewen-msft** [comment]
This has now been fixed in [the latest insiders build](https://blogs.windows.com/windows-insider/2021/04/14/announcing-windows-10-insider-preview-build-21359/).

**Comment by bloomyhood** [comment]
**Microsoft Windows [Version 10.0.21354.1]**
(c) Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>wsl --install
Installing: Virtual Machine Platform
Virtual Machine Platform has been installed.
Installing: Windows Subsystem for Linux
Windows Subsystem for Linux has been installed.
Downloading: WSL Kernel
Installing: WSL Kernel
WSL Kernel has been installed.
Downloading: GUI App Support
A error was encountered during installation, but installation may continue. Component: 'GUI App Support' Error Code: 0x80072eff
Downloading: Ubuntu
The requested operation is successful. Changes will not be effective until the system is rebooted.

**Comment by jamikaroque** [comment]
Windows Insider previer build 21382.1000

C:\WINDOWS\system32>wsl --install -d Ubuntu-20.04
Installing: Virtual Machine Platform
Virtual Machine Platform has been installed.
Installing: Windows Subsystem for Linux
Windows Subsystem for Linux has been installed.
Downloading: WSL Kernel
Installing: WSL Kernel
WSL Kernel has been installed.
Downloading: GUI App Support
[==========================97.5%=========================  ]

mine is stuck at 97.5% download.

**Comment by ffleader1** [comment]
![image](https://user-images.githubusercontent.com/15016720/126313677-8456542e-6040-4756-aaa1-cb48cffc2784.png)
It seems this error persist.
Windows 11 21996.1
Not sure it's the same thing but I just could not install it.

**Comment by halilintar8** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/15016720/126313677-8456542e-6040-4756-aaa1-cb48cffc2784.png)
> It seems this error persist.
> Windows 11 21996.1
> Not sure it's the same thing but I just could not install it.

you must run these 2 dism command : 

- Enable Windows Subsystem for Linux
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart

- Enable Virtual Machine for Linux
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart


https://www.tecmint.com/install-windows-subsystem-for-linux/amp/

**Comment by utkarsh92** [comment]
> > ![image](https://user-images.githubusercontent.com/15016720/126313677-8456542e-6040-4756-aaa1-cb48cffc2784.png)
> > It seems this error persist.
> > Windows 11 21996.1
> > Not sure it's the same thing but I just could not install it.
> 
> you must run these 2 dism command :
> 
> * Enable Windows Subsystem for Linux
>   dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
> * Enable Virtual Machine for Linux
>   dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
> 
> https://www.tecmint.com/install-windows-subsystem-for-linux/amp/

I ran these 2 commands. But I already had done "wsl --install" and GUI app support failed as it did for others. How do I re-install specifically GUI app support? doing "wsl --install" again does nothing....

**Comment by OgulcanCelik** [comment]
FYI: If you do not install the GPU driver before running `wsl --instal`, you will get error. Fixed after installing the Nvidia Preview Driver mentioned here:
https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps

**Comment by Varini** [comment]
I am experiencing this error on Windows 11 Pro [Version 21H2 - Build 10.0.22000.527]. I tried everything mentioned above, but I still get the error "Component: 'GUI App Support' Error Code: 0x80072eff".

**Comment by Danila-hub** [comment]
> Windows Insider previer build 21382.1000
> 
> C:\WINDOWS\system32>wsl --install -d Ubuntu-20.04 Installing: Virtual Machine Platform Virtual Machine Platform has been installed. Installing: Windows Subsystem for Linux Windows Subsystem for Linux has been installed. Downloading: WSL Kernel Installing: WSL Kernel WSL Kernel has been installed. Downloading: GUI App Support [==========================97.5%========================= ]
> 
> mine is stuck at 97.5% download.

Hi. I have this problem too. Do you fix it?

**Comment by ChelsyMena** [comment]
> Windows Insider previer build 21382.1000
> 
> C:\WINDOWS\system32>wsl --install -d Ubuntu-20.04 Installing: Virtual Machine Platform Virtual Machine Platform has been installed. Installing: Windows Subsystem for Linux Windows Subsystem for Linux has been installed. Downloading: WSL Kernel Installing: WSL Kernel WSL Kernel has been installed. Downloading: GUI App Support [==========================97.5%========================= ]
> 
> mine is stuck at 97.5% download.

Mine has been stuck at 53.7% for at least a half hour now

**Comment by prajwalingole** [comment]
> > Windows Insider previer build 21382.1000
> > C:\WINDOWS\system32>wsl --install -d Ubuntu-20.04 Installing: Virtual Machine Platform Virtual Machine Platform has been installed. Installing: Windows Subsystem for Linux Windows Subsystem for Linux has been installed. Downloading: WSL Kernel Installing: WSL Kernel WSL Kernel has been installed. Downloading: GUI App Support [==========================97.5%========================= ]
> > mine is stuck at 97.5% download.
> 
> Mine has been stuck at 53.7% for at least a half hour now

Mine has been stuck at 77.4% , what should I do?

**Comment by chasays** [comment]
phenomenon: "wsl install 0x80072f78"
I remove Ubuntu xxx, and reinstall package offline,

you can download package from[ here](https://docs.microsoft.com/zh-cn/windows/wsl/install-manual#downloading-distributions)

**Comment by angeloboustany** [comment]
![image](https://user-images.githubusercontent.com/48178030/174252113-7cdde699-ece5-4e87-8941-2bdc4b6d8ee7.png)
I am still having that Error Code: 0x80072f78, I am on Windows 11 fresh installed, did anyone found a fix?

**Comment by MaximusR9** [comment]
> This error does not affect your ability to use the `wsl --install` feature, and will just show this error.

they said 
>This error does not affect your ability to use the wsl --install feature, and will just show this error.
so you still should be able to use WSL just fine

**Comment by ucefkh** [comment]
2023 still not solved

![image](https://user-images.githubusercontent.com/1968135/233790075-a6913b17-3e9a-4b29-9cbe-cd624d6fe042.png)


So which decade is it going to be solved @craigloewen-msft ? 2030 maybe?
