### ISSUE TITLE
Missing kernel feature - debugging processes

### ISSUE THREAD

**Issue by jhoareau** [Microsoft/WSL#688]
Hi,
- The _[Apple Swift](http://github.com/apple/swift)_ REPL cannot run on BashOnWindows because of a missing kernel feature - I believe the missing feature is the one associated with debugging processes.
- Expected results:

``` bash
$ swift
  >
```
- Actual results: 

``` bash
$ swift
  error: failed to launch REPL process: process launch failed: 'A' packet returned an error: 8
```
- Windows Build number: 14393.0
- How to reproduce: Install the latest _swift_ snapshot for Ubuntu 14.04 on [https://swift.org](https://swift.org) with required dependencies (clang and libicu-dev), add swift to path, then try to run _swift_. Compiling a file does work correctly though, but not the REPL.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  Can you please collect an strace of the failing process so we can see why the application is failing?

**Comment by therealkenc** [comment]
#555 dup

**Comment by jhoareau** [comment]
@therealkenc Indeed, I believe it is the same issue. You can mark it as duplicate.

**Comment by CeruleanSky** [comment]
@stehufntdev providing an strace and a couple very verbose lldb logs, since lldb produces the same error.

Hopefully this will help determine if this is the same problem as what is occurring in #555 or is something different. As a side note gdb does work for the same circumstances.

If you need anything else, let me know. I'm on windows build14393.82

-----

>lldb -- jsc testscript1.js
(lldb) target create "jsc"
Current executable set to 'jsc' (x86_64).
(lldb) settings set -- target.run-args  "testscript1.js"
(lldb) log enable -vtgT -f lldb_log.txt lldb all
(lldb) log enable -vtgT -f lldb_gdb_remote_log.txt gdb-remote all
(lldb) process launch
error: process launch failed: 'A' packet returned an error: 8
(lldb) quit

------

Here are the logs it generated:  

[lldb_gdb_remote_log.txt](https://github.com/Microsoft/BashOnWindows/files/440299/lldb_gdb_remote_log.txt)
[lldb_log.txt](https://github.com/Microsoft/BashOnWindows/files/440300/lldb_log.txt)


Excerpt from lldb_gdb-remote_log:  

```
1472252855.132365000 GDBRemoteCommunication::CheckForPacket adding 7 bytes: $E08#ad
1472252855.132365000 <   7> read packet: $E08#ad
1472252855.132365000 failed to connect to debugserver: 'A' packet returned an error: 8
1472252855.134366000 ProcessGDBRemote::MonitorDebugserverProcess (baton=0xc79720, pid=8327, signo=2 (0x2), exit_status=-1)
```

----

Strace (similiar workflow, sans lldb logging)

>strace -o strace.log lldb -- jsc testscript1.js
(lldb) target create "jsc"
Current executable set to 'jsc' (x86_64).
(lldb) settings set -- target.run-args  "testscript1.js"
>(lldb) process launch
error: process launch failed: 'A' packet returned an error: 8
>(lldb) quit

-------

Here is the strace log:

[strace_log.txt](https://github.com/Microsoft/BashOnWindows/files/440273/strace_log.txt)

-----

Strace(lldb-server loging)

strace -o lldb-server-log.txt lldb-server platform --listen *:1234

>lldb
(lldb) platform select linux-remote
error: unable to find a plug-in for the platform named "linux-remote"
(lldb) platform select remote-linux
  Platform: remote-linux
 Connected: no
(lldb) target create jsc
Current executable set to 'jsc' (x86_64).
(lldb) process launch testscript1.js
error: process launch failed: Lost debug server connection
(lldb) platform connect connect://127.0.0.1:1234
  Platform: remote-linux
    Triple: x86_64-*-linux
OS Version: 3.4.0 (3.4.0+)
    Kernel: #1 PREEMPT Thu Aug 1 17:06:05 CST 2013
  Hostname: MACBOOKAIR
 Connected: yes
WorkingDir: /home/gl/remote-debug-logs
(lldb) target create jsc
Current executable set to 'jsc' (x86_64).
(lldb) process launch testscript1.js
error: process launch failed: 'A' packet returned an error: 8
(lldb) quit

-------

Strace log for lldb-server http://s000.tinyupload.com/index.php?file_id=56190828631857628254 (tinyupload links since github didn't let me upload zip file of it)

**Comment by therealkenc** [comment]
The failing syscall appears to be:

`ptrace(PTRACE_TRACEME, 0, 0, 0) = -1 EPERM (Operation not permitted)`

**Comment by sunitjoshi** [comment]
I've the same issue on Windows 10, with Ubuntu 14.04.5 LTS

**Comment by sunilmut** [comment]
Marking it duplicate as per the above comments.

**Comment by therealkenc** [comment]
Note this issue is `PTRACE_TRACEME` which is still outstanding (unless something changed). #1692 is `PTRACE_OLDSETOPTIONS`. The #1692 application (UML) will _also_ eventually fail on `PTRACE_TRACEME`, but it is marked as fixinbound because the other (easier) `ptrace()` option was fixed.

**Comment by yanite** [comment]
I've the same issue on Windows 10, with Ubuntu 18.04 swift 5.0.1

**Comment by PseudonymPatel** [comment]
Still having this issue, it would be nice to see if something could be done about it

**Comment by viegasfh** [comment]
Any update on this?

**Comment by jhoareau** [comment]
This was fixed with WSL2 using a virtual machine instead of rewriting system calls.

**Comment by viegasfh** [comment]
Hi, @jhoareau !

Do you have a link I can follow to update this? O native Windows it does nothing. It runs and returns to the command prompt. On Ubuntu 20.04 on WSL2 it hangs.
