### ISSUE TITLE
/etc/resolv.conf gets removed on shutdown/startup of WSLg container

### ISSUE THREAD

**Issue by TotiTolvukall** [microsoft/WSL#6977]
# Environment

```none
Windows build number: 21387.co_release.210518-1436 / 10.0.21387.1
Your Distribution version: Ubuntu 20.04
Your WSLg version: [Open 'Apps and Features' and check the version of 'Windows Subsystem for Linux GUI app support', e.g: 0.2.3.13]
```

# Steps to reproduce

Create the /etc/wsl.conf containing the two magic lines:
user@host:/etc$ cat wsl.conf
[network]
generateResolvConf = false
user@host:/etc$

Make sure you have your own resolv.conf:
user@host:/etc$ sudo rm -f resolv.conf && sudo cat > resolv.conf << EOT
nameserver 1.1.1.1
nameserver 8.8.8.8
domain mydomain.com
search mydomain.com
EOT
Password:
user@host:/etc$

In CMD, do a wsl --shutdown

Start WSL Ubuntu 20.04 session again, and check for the /etc/resolv.conf.

It will be gone.

**WSL logs**: 

The wsl logs reveal nothing about resolv.conf

#  Expected behavior

Expected is that MY resolv.conf is left alone. As it did in the WSL (pre-g release) version. 

# Actual behavior

Actually my resolv.conf is being forcefully removed - which IS making WSLg unusable until a new one has been put in place.

**Comment by 0xbadfca11** [comment]
```sh
sudo cat > resolv.conf << EOT
```
Suspicious command line.
Isn't this command line unsuccessful anyway?

**Comment by TotiTolvukall** [comment]
@0xbadfca11 how about at least making an attempt at understanding what's being done before commenting like that?

No, it's not unsuccessful. It's perfectly successful.

try it on a different file.

sudo rm -f filethatdidntexist && sudo cat > filethatdidntexist << EOT
I should have tried this myself before making me look smart on github
EOT

You will be asked for a password - type it in correctly and the SECOND sudo will run without a password.

But THIS is a digression. The original problem is that of resolv.conf being deleted at boot/shutdown and that is what this ticket should address, not script semantics (regardless if you do understand them or not).

**Comment by SheepReaper** [comment]
Check out https://github.com/microsoft/WSL/issues/5420#issuecomment-804422879 See if that sequence helps

**Comment by TotiTolvukall** [comment]
@SheepReaper the problem isn't the shutdown itself (and I wouldn't have reported it unless I'd tried all kinds of WSL shutdowns - including full computer reboots). The problem is the procedure running (I suspect at start-up, not shutdown as you normally want your autogenerated resolv.conf to be generated from the current settings, not the settings when you last turned off your computer) at start-up. Without having dug into it, my gut feeling tells me;
It should be like this:
* if /etc/wsl.conf exists
*  - if it contains "generateResolvConf" and it's set to "false"
*     : don't do anything
*  - else 
*     : delete /etc/resolv.conf
*     : symlink to /run/resolvconfsomething

But is more like this
* delete /etc/resolv.conf
* if /etc/wsl.conf exists
*   - if it contains "generateResolvConf" and it's set to "false"
*      : don't do anything
*  .
*  .
*  .

Just a gut feeling, but it matches up to what I'm seeing.


For now, I have a /etc/resolv.conf.real which is my actual resolv.conf file, and then at EVERY reboot of my computer or fresh startup of WSL, I do "sudo ln -s /etc/resolv.conf.real /etc/resolv.conf"

**Comment by therealkenc** [comment]
![image](https://user-images.githubusercontent.com/7049700/119420935-5f0fbe80-bcb2-11eb-99e3-0e4286a3ed05.png)

**Comment by clodbrasilino** [comment]
Same issue here.
|      |      |
| --- | --- |
| Edition | Windows 10 Pro |
| Version | Dev |
| Installed on | ‎5/‎23/‎2021 |
| OS build | 21387.1 |
| Experience | Windows 10 Feature Experience Pack 321.13101.0.3 |

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\WINDOWS\system32> wsl
clod@DESKTOP-9QBVQDR:/mnt/c/WINDOWS/system32$ sudo su
[sudo] password for clod:
root@DESKTOP-9QBVQDR:/mnt/c/WINDOWS/system32# cat /etc/resolv.conf
cat: /etc/resolv.conf: No such file or directory
root@DESKTOP-9QBVQDR:/mnt/c/WINDOWS/system32# touch /etc/resolv.conf
root@DESKTOP-9QBVQDR:/mnt/c/WINDOWS/system32# echo 'nameserver 1.1.1.1' > /etc/resolv.conf
root@DESKTOP-9QBVQDR:/mnt/c/WINDOWS/system32# cat /etc/resolv.conf
nameserver 1.1.1.1
root@DESKTOP-9QBVQDR:/mnt/c/WINDOWS/system32# cat /etc/wsl.conf
[network]
generateResolvConf = false
root@DESKTOP-9QBVQDR:/mnt/c/WINDOWS/system32# exit
exit
clod@DESKTOP-9QBVQDR:/mnt/c/WINDOWS/system32$ exit
logout
PS C:\WINDOWS\system32> wsl --shutdown
PS C:\WINDOWS\system32> wsl
clod@DESKTOP-9QBVQDR:/mnt/c/WINDOWS/system32$ sudo cat /etc/resolv.conf
[sudo] password for clod:
cat: /etc/resolv.conf: No such file or directory
clod@DESKTOP-9QBVQDR:/mnt/c/WINDOWS/system32$
```

**Comment by wjzhou** [comment]
I got the same result.

a working workaround for now:
`sudo chattr +i /etc/resolv.conf`

Full configuration:

```
# add config to /etc/wsl.conf
# or manually edit if you have other config in wsl.conf
sudo tee /etc/wsl.conf << EOF
[network]
generateResolvConf = false
EOF
# some document says need restart the wsl once for the configure to work
# for me, it works without it, keep it here for reference
# run in windows command
# wsl --shutdown

# /etc/resolv.conf is a symbol link, delete it to create a regular file
sudo rm /etc/resolv.conf
sudo tee /etc/resolv.conf << EOF
nameserver 8.8.8.8
nameserver 8.8.4.4
# search local
EOF

# this is the real bug in wsl GUI version reported here
# for some reason it always delete the /etc/resolv.conf when generateResolvConf = false
# this +i will prevent delete of the file
# to edit the file again please use
# sudo chattr -i /etc/resolv.conf
sudo chattr +i /etc/resolv.conf
```

The real bug here is that the `/etc/resolv.conf` file got deleted when `generateResolvConf = false`. (without creating new file)
So I guess that there is a delete statement that delete blinding without checking the  `generateResolvConf = false` option.

But despite the current bug, I still think this whole process needs some design, at least more clear document in /etc/resolv.conf
1. need to /etc/wsl.conf, the document is clear, so it's ok
2. some document says need to `wsl --shutdown` for the option to take effect
3. need to `rm /etc/wsl.conf` to remove the symbol link, this step is very easy to forget

**Comment by ajfpay** [comment]
> I got the same result.
> 
> a working workaround for now:
> `sudo chattr +i /etc/resolv.conf`
> 
> Full configuration:
> 
> ```
> # add config to /etc/wsl.conf
> # or manually edit if you have other config in wsl.conf
> sudo tee /etc/wsl.conf << EOF
> [network]
> generateResolvConf = false
> EOF
> # some document says need restart the wsl once for the configure to work
> # for me, it works without it, keep it here for reference
> # run in windows command
> # wsl --shutdown
> 
> # /etc/resolv.conf is a symbol link, delete it to create a regular file
> sudo rm /etc/resolv.conf
> sudo tee /etc/resolv.conf << EOF
> nameserver 8.8.8.8
> nameserver 8.8.4.4
> # search local
> EOF
> 
> # this is the real bug in wsl GUI version reported here
> # for some reason it always delete the /etc/resolv.conf when generateResolvConf = false
> # this +i will prevent delete of the file
> # to edit the file again please use
> # sudo chattr -i /etc/resolv.conf
> sudo chattr +i /etc/resolv.conf
> ```
> 
> The real bug here is that the `/etc/resolv.conf` file got deleted when `generateResolvConf = false`. (without creating new file)
> So (my guess), there is a delete statement that deletes blinding without checking the `generateResolvConf = false` option.
> 
> But despite the current bug, I still think this whole process needs some design, at least more clear document in /etc/resolv.conf
> 
> 1. need to /etc/wsl.conf, the document is clear, so it's ok
> 2. some document says need to `wsl --shutdown` for the option to take effect
> 3. need to `rm /etc/resolv.conf` to remove the symbol link, this step is very easy to forget

Omg, this script worked, thank you very very much

**Comment by benhillis** [comment]
Typically this is happening because /etc/resolv.conf is a symlink to tmpfs.  If you want to take ownership of this file, set the /etc/wsl.conf setting, and replace the /etc/resolv.conf symlink with a regular file.

**Comment by TotiTolvukall** [comment]
It would be respectful to ALL the people in this thread @benhillis to at least glance over the discussion so far before replying with an entry that has zero weight.

It has already been concluded that by disabling WSL from messing with the resolver, it removes all traces of resolv.conf - symbolic links as well as regular files. And does so repeatedly (i.e. on every startup/restart.)

Thus the issue.

**Comment by benhillis** [comment]
@TotiTolvukall - I appreciate you taking the time to file this issue, turns out there was some refactoring that introduced this issue. I'll get this sorted out.

This issue has a very common signature of a common pitfall people often run into, I apologize I got this conflated with that one.

**Comment by bjolivot** [comment]
hi!
Any news on that bug ?

**Comment by trexmaster** [comment]
@benhillis any news on this ? I'm also having this issue on Windows 11 build 22000.318

**Comment by Mr-EmPee** [comment]
Same problem, Windows 11 build 22000.318

**Comment by withinboredom** [comment]
```
sudo chattr +i /etc/resolv.conf
```
keeps the file after a reboot for me. It's not great, but serious kudos for suggesting that!

**Comment by azilber** [comment]
This bug is damn annoying, and open since May, and now has wheedled itself into Windows 11.

**Comment by nwestra** [comment]
> 

I don't recall seeing this behavior in Win10, but definitely confirm this behavior in Win11

**Comment by SheepReaper** [comment]
Not that there aren't valid use cases for specifying /etc/resolv.conf, but the examples above seem to want to use google dns.
Can you not use the default behavior (sets nameserver to hyper-v host network interface) and set your computer's DNS instead? (As a temp workaround, I mean)

**Comment by nwestra** [comment]
For me at some point last year whatever value WSL came up (within the linked resolv.conf) stopped working, so I ended up manually configuring /etc/resolv.conf (telling WSL to leave resolv.conf alone through /etc/wsl.conf). 
This worked fine until I made the switch to Windows 11

**Comment by SheepReaper** [comment]
So 2 questions then:
1. Were you on an insiders build on Win 10 with WSL2?
2. Did you run wsl --install or wsl --update after upgrading to Win 11?

**Comment by nwestra** [comment]
1. Nope, regular Win 10 builds from 1909 all the way to 21H2 before upgrading to Win11, at some point upgraded WSL to WSL2, not sure when
2. Didn't use either, is that required?

**Comment by SheepReaper** [comment]
Well, I'm not positive about this, but if you didn't take windows insider on Win 10, then you didn't have access to the latest and greatest WSL2. I don't know exactly on which version or problems began, but I suspect the version of WSL2 you had is different than the one you get with Win 11. I suspect since WSL (and the dependency Virtual Machine Platform) is a windows component, It's probably reinstalled during the Win 11 upgrade.

I think wsl --install only works on Win 11 if either the VMP or WSL system components are not installed or the update is missing:
<img width="800" alt="image" src="https://user-images.githubusercontent.com/5705509/145115093-5f422f66-78ba-4bc6-b240-140dd11c769c.png">

wsl --update should work if either of the above updates are missing/out of date

So I'm concerned that either you might not be on the latest version of WSL and consequently don't have the newest kernel. Second, your linux vm should also have the version set to 2 if it's not already.

![image](https://user-images.githubusercontent.com/5705509/145115675-b77341da-351a-45c7-9d2e-f33153e9be11.png)

**Comment by withinboredom** [comment]
> Not that there aren't valid use cases for specifying /etc/resolv.conf, but the examples above seem to want to use google dns.

Isn't that the definition of an example? No one probably wants to share their real setup and 8.8.8.8 is easy to remember. 

> Can you not use the default behavior (sets nameserver to hyper-v host network interface) and set your computer's DNS instead? (As a temp workaround, I mean)

I'm using a DNS server behind a VPN, in my case. The VPN is configured on the host and the host isn't (nor do I want it to be) configured to use the same DNS.

**Comment by nwestra** [comment]
WSL is up to date and my linux vm is version 2

**Comment by SheepReaper** [comment]
Insert shrug emoji?

I hate these inconsistent problems. I use WSL2 with the g update for work, use the default behavior, no customization and It's fine.
But on occasion, I have random problems that I don't think are related to WSL2. Like if the system goes to sleep/hibernate sometimes my remote vscodes disconnect (the wsl$ share goes offline) but not always, and usually comes back within a minute (but not always)
I think I had one time Hyper-V decided to change the ip range on the vm network and I was chasing my tail with why a netsh port forward wasn't working. <- restarting WSL and re-doing the port forwards was the fix.
Since then I stopped using netsh port forwards to WSLsince it seems like now it's implicit? (I dunno, I can run a service on WSL as long as that port doesn't collide with something on Windows, and the firewall port is open, my network can use it without me doing the forward.
Some of the magic is really useful, but since I'm used to managing virtual networks, I kinda expect a NATed network to actually behave like one and not a bridged one.

**Comment by trexmaster** [comment]
> > Not that there aren't valid use cases for specifying /etc/resolv.conf, but the examples above seem to want to use google dns.
> 
> Isn't that the definition of an example? No one probably wants to share their real setup and 8.8.8.8 is easy to remember.
> 
> > Can you not use the default behavior (sets nameserver to hyper-v host network interface) and set your computer's DNS instead? (As a temp workaround, I mean)
> 
> I'm using a DNS server behind a VPN, in my case. The VPN is configured on the host and the host isn't (nor do I want it to be) configured to use the same DNS.

I'm almost in the same case, except the DNS (my company's) is set in WSL so that I can SSH/ansible/terraform into my servers, while my host's DNS are just good old Coudflare's. 

I circumvented the issue by writing a small script that recreates a symlink to a resolv.conf file in my home dir if /etc/resolv.conf doesn't exist and having that script run at WSL startup, but still, I'd prefer the issue to be properly fixed.

**Comment by parsec** [comment]
any updates on this? the fixinbound tag was applied last August, and we haven't heard back from anyone. this issue is getting exceedingly frustrating for those of us who have to work over a VPN (read: a significant number of users of WSL2) who need to override DNS settings.

**Comment by StevenLiekens** [comment]
> In CMD, do a wsl --shutdown
> 
> Start WSL Ubuntu 20.04 session again, and check for the /etc/resolv.conf.
> 
> It will be gone.

I was having this problem. The workaround I found is to write-protect the file.

``` sh
sudo chattr +i /etc/resolv.conf
```

Hope this helps somebody.

**Comment by asampal** [comment]
Put me down for finding this very annoying bug.

Windows 11

**Comment by laingsc** [comment]
Use:
sudo chmod +t /etc/resolv.conf

if you get Inappropriate ioctl for device While reading flags on /etc/resolv.conf

**Comment by TotiTolvukall** [comment]
The chmod +t is a kluge at best and inherently unhelpful for those that work on umpteen networks and NEED to alter their resolv.conf manually on a regular basis.

 �

This should of course have been solved eons ago – it truly cannot be that hard.

 �

Question to the developers: Can the source for the WSL bootstrap be downloaded somewhere to be scrutinized?

 �

**Comment by NicolaiMogensen** [comment]
This is super annoying and needs to be fixed. My resolv.conf ends up in a state that looks like this: 

![image](https://user-images.githubusercontent.com/11227437/162172556-9f4fe6ec-b23f-42af-a27e-f9b58f4b8c00.png)

So the file doesnt "exist" and you or the WSL process can't write to it. If you forcefully remove it, and add it back in.. it works. But it's hardly a fix

**Comment by deviantony** [comment]
Went with another approach (and another one!):

````
# In my WSL2 Ubuntu instance
# Edit /etc/wsl.conf and append the following to disable resolvconf generation
[network]
generateResolvConf = false

# Install resolvconf
sudo apt install resolvconf

# Update /etc/resolvconf/resolv.conf.d/head and add the nameservers of your choice
nameserver 1.1.1.1

# Edit /etc/wsl.conf to automatically run the following commands at boot
[boot]
command="dpkg-reconfigure --frontend=noninteractive resolvconf && resolvconf -u"
````

Feels a bit dirty - I wish the network stack in WSL wasn't so flaky.

**Comment by withinboredom** [comment]
I feel like until someone working at Microsoft actually has to use WSL2 to do their job, the networking stuff won't ever be prioritized. No IPv6 (still), no working custom DNS, etc.

**Comment by saltsucker** [comment]
Using WSLg, `Microsoft Windows [Version 10.0.22000.675]`.
the sudo chattr command was the key for me. I set the wsl.conf value, rm'd the resolv.conf symlink (wasn't even there)

> I got the same result.
> 
> a working workaround for now: `sudo chattr +i /etc/resolv.conf`
> 
> Full configuration:
> 
> ```
> # add config to /etc/wsl.conf
> # or manually edit if you have other config in wsl.conf
> sudo tee /etc/wsl.conf << EOF
> [network]
> generateResolvConf = false
> EOF
> # some document says need restart the wsl once for the configure to work
> # for me, it works without it, keep it here for reference
> # run in windows command
> # wsl --shutdown
> 
> # /etc/resolv.conf is a symbol link, delete it to create a regular file
> sudo rm /etc/resolv.conf
> sudo tee /etc/resolv.conf << EOF
> nameserver 8.8.8.8
> nameserver 8.8.4.4
> # search local
> EOF
> 
> # this is the real bug in wsl GUI version reported here
> # for some reason it always delete the /etc/resolv.conf when generateResolvConf = false
> # this +i will prevent delete of the file
> # to edit the file again please use
> # sudo chattr -i /etc/resolv.conf
> sudo chattr +i /etc/resolv.conf
> ```
> 
> The real bug here is that the `/etc/resolv.conf` file got deleted when `generateResolvConf = false`. (without creating new file) So (my guess), there is a delete statement that deletes blinding without checking the `generateResolvConf = false` option.
> 
> But despite the current bug, I still think this whole process needs some design, at least more clear document in /etc/resolv.conf
> 
>     1. need to /etc/wsl.conf, the document is clear, so it's ok
> 
>     2. some document says need to `wsl --shutdown` for the option to take effect
> 
>     3. need to `rm /etc/resolv.conf` to remove the symbol link, this step is very easy to forget

The key for me was: `sudo chattr +i /etc/resolv.conf`

- Using WSLg, `Microsoft Windows [Version 10.0.22000.675]`. 
- I set the wsl.conf file with correct strings, rm'd the resolv.conf symlink (wasn't even there), rebooted WSL and resolv kept getting deleted. Using `chattr` command stopped it from getting deleted. Oddly WSL2, I didn't need to do that. So there is something new with WSLg and `resolv.conf`.

**Comment by wrgeorge1983** [comment]
I can confirm the following:  
Bug wasn't present in updated windows 10 a week ago when I checked.
On a separate windows 11 machine the bug is present and has been since purchase.  The windows 11 machine is brand new and never had 10, so we can rule out any further discussion about upgrade mechanics.
Neither machine uses any insider builds for anything


the built-in resolver breaks certain DNS queries (https://github.com/microsoft/WSL/issues/7642 etc... ) so the generated resolv.conf MUST be overridden for me to do work. 

after fresh boot resolv.conf is removed entirely, no symlink 
```
~
❯ ls -al /etc/resolv.conf
ls: cannot access '/etc/resolv.conf': No such file or directory
```

I'm assuming at this point the discussed workarounds work fine, but this really is absurd how long this issue's been around at this point.

**Comment by SheepReaper** [comment]
If you could, please upvote the OP. M$ may track heat via reactions. Or maybe I've been watching too much spiffing Brit...

**Comment by Wittionary** [comment]
I had the exact issue that @wrgeorge1983 mentioned. It stopped me from working for several days.

**Comment by nbrugger-tgm** [comment]
> If you could, please upvote the OP. M$ may track heat via reactions. Or maybe I've been watching too much spiffing Brit...

Ping pong, upvote whatever. The amount of network related issues I experienced in WSL is ... perfectly balanced

**Comment by nebelmeerwanderer1** [comment]
has this been resolved? 

I had the same issue today - no clue why it suddenly popped up. 

I followed @TotiTolvukall 's steps to reproduce, but my resolv.conf still existed after restart(!).  In fact, the problem appears to have been resolved for me - my WSL is working again

**Comment by Amondale** [comment]
I can confirm the problem is highly flakey (like most things networked in the subsys). Running W11, used the walkthrough [here](https://dev.to/felipecrs/simply-run-docker-on-wsl2-3o8) to get docker running without needing the desktop version, and *voila* -- the bug now pops up! I had generateResolvConf unassigned in wsl.conf, but when I added it and set it to (of course) google DNS, *presto* -- it got clobbered per the items in this thread.

So consider this one more factor in unraveling the plate of spag called WSL networking (2/g/whatever) -- docker does create and needs its *own* networking stack, and AFAIK, if it generates IPv6 bindings, they are ignored in WSL2/g because of no IPv6 stack except for the curious entries in /etc/hosts. Curiously, the /etc/hosts file isn't clobbered in a similar manner, and may or may not be a symlink referred to elsewhere in this thread.

**Comment by eulores** [comment]
Best tip so far is from deviantony (https://github.com/microsoft/WSL/issues/6977#issuecomment-1132234201)
```shell
# Install resolvconf
sudo apt install resolvconf
```
and then read the documentation in **detail**!
`less /usr/share/doc/resolvconf/README.gz`

you can (and should) then only patch the files in `/etc/resolvconf/resolv.conf.d` (head, base, tail, or your own) as required.

**Comment by udoyhasan** [comment]
### I was also facing this problem but I fixed it by following steps:

* I deleted my default ***`resolv.conf`*** file and created a new one with my custom configurations and after that, I stopped the auto-deleting of the file by giving it ***read-only permission***.
  ```bash
  sudo rm /etc/resolv.conf
  sudo echo "nameserver 1.1.1.1" >> /etc/resolv.conf
  sudo echo "nameserver 8.8.8.8" >> /etc/resolv.conf
  sudo chattr +i /etc/resolv.conf 
  ```
* Then I stop the auto **wsl resolv configuration** rewrite on startup.
  ```bash
  sudo rm /etc/wsl.conf
  sudo echo "[network]\ngenerateResolvConf = false" >> /etc/wsl.conf
  ```

### Hope this will also fix your issue :)

**Comment by NickFall** [comment]
Hi @benhillis I think you forgot about this one

**Comment by boner-cmd** [comment]
It's possible this is being ignored (frustratingly, because it should at least be _closed_ if they are going to ignore it...) because the documented solution looks like it works now.

```
> systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22621 N/A Build 22621

> wsl --version --verbose
WSL version: 1.0.0.0
Kernel version: 5.15.74.2
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.819

> wsl -l -v`
  NAME      STATE           VERSION
* Ubuntu    Running         2
```

Freshly installed and updated version of WSL2, running freshly-installed Ubuntu (the generic distro, not a specific version) from the Microsoft App Store. Installed WSL itself from Windows, _not_ the App Store.

Encountered the common problem where my distro could not connect to the internet. Searching led to #5420, which led to this issue. 

Opened the distro, then ran `wsl --shutdown` in PowerShell in the background, then manually created `/etc/wsl.conf` and added as suggested in the tip from resolv.conf: 

```
[network]
generateResolvConf = false
```

Purely to test, closed the distro and reopened it. Now no `resolv.conf` is created at all, as other users noted. 

Shutdown WSL again via PowerShell just in case. Manually created `resolv.conf` and added a DNS.

`nameserver 1.1.1.1`

Closed the distro and reopened it. My custom resolv.conf is still there, and WSL didn't overwrite it. My custom wsl.conf telling WSL not to overwrite resolv.conf is also still there.

Happy to provide any additional system info. Tried to start from as clean a setup as possible. 

Not endorsing the fact that Microsoft has let the community struggle with this bug for years, just suggesting that the bug may have been quietly fixed by restoring the intended (but still obtuse) behavior of requiring wsl to be shutdown to make sure changes stick.

I did not try a single other intended solution first to preserve integrity, and like many others refused to use the immutable file kludge. Hope this helps someone.

**Comment by luxzg** [comment]
As I mentioned about a month and a half ago, like @boner-cmd I have no issues with my custom `resolv.conf`, and `wsl.conf` option `generateResolvConf = false` works for me just fine. But just as described above, I've also started with fresh WSL2 install, on fresh OS, with fresh Ubuntu distro. If someone is still having issues perhaps their workarounds from yesteryear are now working against you. I'm now on `1.0.0` as well, and all works as expected.

**Comment by lucastheisen** [comment]
For me, i was able to get it working again by editing my `/etc/resolv.conf` then immediately `wsl.exe --shutdown`.  After that it did stick around for next wsl shutdown.  Also could be worth mentioning that _a `resolv.conf`_ is still getting generated at `/mnt/wsl/resolv.conf`, but it is not replacing mine.

**Comment by jimklimov** [comment]
Thanks for all the suggestions here. Just one pattern repeated by many seems fishy: `sudo CMD >> /etc/filename`: the redirection `>>` *should* be done by your user shell, so unprivileged and unable to write to a system-protected file. I do not know if distros for WSL handle it differently, but in all other OSes people jump through hoops to get such files opened and written by a privileged process - often via `cmd | sudo tee (-a) /etc/filename` pattern.

Hope this helps :)
Jim Klimov

**Comment by AnonDrew** [comment]
```
OS Name             : Microsoft Windows 11 Home
OS Version          : 10.0.22621 N/A Build 22621
OS Manufacturer     : Microsoft Corporation
OS Configuration    : Standalone Workstation
```
I encountered this issue after a fresh W11 install a few days ago.
I installed WSL through the "Windows Features" checkbox GUI, whatever that does to install WSL.
Note that `wsl --version` did not work and did not seem to show up in the `--help` list in this version of WSL I got.

I wanted to avoid `sudo chattr +i /etc/resolv.conf`.
I used `wsl --set-default-version 2` and reinstalled Ubuntu (latest) and still had the same problem.
The fresh install comments suggested to me that I should completely uninstall WSL; did so following this article:
https://pureinfotech.com/uninstall-wsl-windows-11/
I then reinstalled WSL using `wsl --install` in PowerShell.
Deleted Ubuntu (Default), then reinstalled Ubuntu with `wsl --install Ubuntu`.

At this point, I am in Ubuntu and manually created the `wsl.conf` with
```
[network]
generateResolvConf = false
```
Exited Ubuntu and did `wsl --shutdown`.
Went back in and created my custom `resolv.conf`.
Restarted WSL and `ls /etc/` and my `resolv.conf` was not overridden and still has not after more WSL restarts.
```
PS C:\Users\Anon> wsl --version
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1105
```

**Comment by luxzg** [comment]
@AnonDrew 
```
I encountered this issue after a fresh W11 install a few days ago.
I installed WSL through the "Windows Features" checkbox GUI, whatever that does to install WSL.
Note that wsl --version did not work and did not seem to show up in the --help list in this version of WSL I got.
```

For whatever reason, version installed from Microsoft Store is NEWER.

I'd suggest to uninstall WSL, reboot host PC, and install from MS Store.

Running `version` after that should work. That will also shiw version 1.x.x being installed confirming latest WSL2 version.

From there on just keep updating from Store.

I'm not sure why there's disparity between the installed versions, but several new features are absent as well from non-store versions.

**Comment by mb555444** [comment]
This bug still exists no matter what. resolv.conf gets deleted from /etc upon shutdown of WSL.

**Comment by leiflinse-trivector** [comment]
I still have the issue and I noticed that for me `wsl --version` says it doesn't support the --version parameter. I have checked for windows updates. 

PS C:\Users\anon> wsl --version
Invalid command line option: --version
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]
```

Reading in `wsl --help` of this version it seems there is a `wsl --update` command that updates the wsl engine.

**Comment by SheepReaper** [comment]
If `--version` is unsupported, you are using the in-box wsl. You need to
install wsl from the M$ Store.

**Comment by SheepReaper** [comment]
Windows Subsystem for Linux https://apps.microsoft.com/store/detail/windows-subsystem-for-linux/9P9TQF7MRM4R

**Comment by kdolgikh** [comment]
I have the same issue on Win 11 Enterprise, ```wsl --version``` below:

>WSL version: 1.2.5.0  
>Kernel version: 5.15.90.1  
>WSLg version: 1.0.51  
>MSRDC version: 1.2.3770  
>Direct3D version: 1.608.2-61064218  
>DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp  
>Windows version: 10.0.22621.2283

My workaround is to modify "/etc/wsl.conf" first, then do ```wsl --shutdown```, then modify "/etc/resolv.conf". I run a script to install and configure WSL Debian, this solution has worked reliably so far.

**Comment by joebaca** [comment]
This is really effing annoying BS.  Typical MS shit.

**Comment by CaspervdKerk** [comment]
https://github.com/microsoft/WSL/issues/6977#issuecomment-1743560564

> My workaround is to modify "/etc/wsl.conf" first, then do `wsl --shutdown`, then modify "/etc/resolv.conf". I run a script to install and configure WSL Debian, this solution has worked reliably so far.

This seems to be the solution for now. It would seem that on first wsl reboot after `generateResolvConf` has been set to false it removes `/etc/resolv.conf`, but after that it doesn't touch it anymore.

**Comment by ayushshukla7777** [comment]
Why isn't this getting fixed. Every now and then, I have to spend whole day fixing these issues on wsl. I guess thats why developers are using macbook. Simply- the OS shouldn't come in way of user.

**Comment by joebaca** [comment]
Ya, fix this BASIC functionality.  I know we all want to contribute to core kernel but this shit is important too!!

**Comment by aprescott706** [comment]
Also seeing this issue.

OS: Windows 11
WSL: ubuntu 20.04

/etc/wsl.conf contains
[network]
generateResolvConf = false

I manually create /etc/resolv.conf, shutdown the running instance, start back up and /etc/resolv.conf is gone.

Workaround I'm using is "sudo chattr +i /etc/resolv.conf"

**Comment by asampal** [comment]
@aprescott706 are you using the latest, 2.2.1 at the moment, version of WSL?

**Comment by aprescott706** [comment]
> @aprescott706 are you using the latest, 2.2.1 at the moment, version of WSL? 

I'm not sure to be honest. The command wsl --version/-v doesn't work. 

File version on wsl.exe is 10.0.22621.1

**Comment by SheepReaper** [comment]
That's because you have the 'in box' version of wsl. You must install wsl from the M$ Store.

easiest way to determine you have the wrong version installed.

when the M$ store version is installed the output is thus:
```shell
wsl --version
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3296
```

**Comment by asampal** [comment]
Sometimes, based on issues addressed, you might want to install the latest preview version here, https://github.com/microsoft/WSL/releases. You can find the binaries by expanding the "Assets" section.

**Comment by joebaca** [comment]
I have the version you show here an still had to use the posted workaround.  This should not require the suggested workaround.  (Taut is what you are suggesting,  the workaround was required because the user did not have the latest version?).

**Comment by AyushSehrawat** [comment]
> Also seeing this issue.
> 
> OS: Windows 11 WSL: ubuntu 20.04
> 
> /etc/wsl.conf contains [network] generateResolvConf = false
> 
> I manually create /etc/resolv.conf, shutdown the running instance, start back up and /etc/resolv.conf is gone.
> 
> Workaround I'm using is "sudo chattr +i /etc/resolv.conf"

Same issue, disabled the automatic generation and on restart the file is gone

```
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3296
```

**Comment by jrausch12** [comment]
Experiencing the issue as well

WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.22621.3958

**Comment by ragmel** [comment]
Same issue:

WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.4112

**Comment by SheepReaper** [comment]
Still don't know if it's a bug or not. But can confirm that disabling resolv.conf generation does in fact delete it, but only for the first `wsl --shutdown` for me. If I set generation to false, logout, and then call wsl --shutdown, on the next boot /etc/resolv.conf is missing. But then I can create it, and it persists for every other wsl reboot.

So maybe not bug, but very annoying behavior. Why not just leave the file there even if it was originally generated? (Asking MS here)
```shell
WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.22631.4112
```

**Comment by chuanqisun** [comment]
My `resolv.conf` just disappeared randomly. There was no shut-down or restart. I was using it just fine and suddenly I lost domain name resolution.

```txt
WSL version: 2.3.24.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2033
```

**Comment by DaddyBigFish** [comment]
As was said
```
sudo chattr -i /etc/resolv.conf; sudo nano /etc/resolve.conf; sudo chattr +i /etc/resolv.conf
```
