### ISSUE TITLE
wsl 2 - Getting “Failed to connect to the bus: Could not parse server address” error when launching google chrome or any electron app

### ISSUE THREAD

**Issue by mwoodpatrick** [microsoft/WSL#7915]
### Version

 Windows version: 10.0.22000.376

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.74.3

### Distro Version

20.04.3 LTS (Focal Fossa)

### Other Software

electron 16.0.6 or Google chrome Version 97.0.4692.71 (Official Build) (64-bit)

### Repro Steps

Install and start google chrome on wsl2 and start 

### Expected Behavior

browser should come up without error

### Actual Behavior

google-chrome
[8405:8442:0110/140553.266744:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[8405:8441:0110/140553.276538:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[8405:8441:0110/140553.277982:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[8405:8441:0110/140553.329491:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[8405:8441:0110/140553.329632:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[8405:8476:0110/140553.499766:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[8405:8476:0110/140553.499863:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[8405:8476:0110/140553.500048:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[8405:8476:0110/140553.500124:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[8405:8476:0110/140553.500170:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[8448:8448:0110/140555.058357:ERROR:sandbox_linux.cc(378)] InitializeSandbox() called with multiple threads in process gpu-process.
[8405:8441:0110/140636.457250:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[8405:8441:0110/140636.457371:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[8405:9002:0110/140641.065898:ERROR:chrome_browser_main_extra_parts_metrics.cc(227)] START: ReportBluetoothAvailability(

**Comment by mwoodpatrick** [comment]
Note chrome and electron apps do start but they give the above errors

**Comment by elsaco** [comment]
`dbus` service is not running. Start the service with `sudo service dbus start` before launching Chrome.

**Comment by benhillis** [comment]
@mwoodpatrick - are you using WSLg or a third party xserver on Windows?

**Comment by mwoodpatrick** [comment]
wslg, xdpyinfo shows

name of display:    :0
version number:    11.0
vendor string:    Microsoft Corporation
vendor release number:    12010000
maximum request size:  16777212 bytes
motion buffer size:  256
bitmap unit, bit order, padding:    32, LSBFirst, 32
image byte order:    LSBFirst

**Comment by mwoodpatrick** [comment]
starting dbus using

sudo service dbus start

did not help

**Comment by ssbarnea** [comment]
That error is making our GHA workflows hard to debug as there are tons of it. If anyone know a workaround for it it would be great.

**Comment by mbwhite** [comment]
Likewise I'm seeing a lot of these errors, when running test on our Electron based app.

The cyrpress test tool makes reference to it in http://www.apimirror.com/cypress/guides/guides/debugging, 
And there is some hope offered here https://x410.dev/cookbook/wsl/setting-up-wsl-for-linux-gui-apps/

I would hope that the new WSLg will help here; or use multipass rather WSL.

**Comment by rajann44** [comment]
I am getting these error with Cypress + Github Actions. Any solution for this?

**Comment by OmarLomsadze** [comment]
any updates?

**Comment by RestOp** [comment]
also interesting

**Comment by PLopezD** [comment]
Would also appreciate some help with this - im running into the same issue

**Comment by elsaco** [comment]
Here are steps to get `dbus` functionality on Win10/WSL:

```
- set `DISPLAY` env variable
- start `dbus` service
- set `XDG_RUNTIME_DIR` env variable
- start `dbus` user session
```

This will fix `ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/user/1000/bus: No such file or directory`

Sample run on `Win10` and `vcxsrv` using current WSL endpoint IP address:
```
- export DISPLAY=172.19.48.1:0
- sudo service dbus start
- export XDG_RUNTIME_DIR=/run/user/$(id -u)
- sudo mkdir $XDG_RUNTIME_USER
- sudo chmod 700 $XDG_RUNTIME_DIR
- sudo chown $(id -un):$(id -gn) $XDG_RUNTIME_DIR
- export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus
- dbus-daemon --session --address=$DBUS_SESSION_BUS_ADDRESS --nofork --nopidfile --syslog-only &
```

This can be added to `.profile` or `.bashrc` however the IP changes with every WSL restart. Win11 users don't need to worry about setting `DISPLAY` it's done by `wslg`.

When lauching `google-chrome` there are no more `dbus` errors, just some power daemon related (ignore them) and some extension not being supported:

```
tux@RIPPER:~$ google-chrome
[1603:1687:0622/090500.809467:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1603:1687:0622/090500.809580:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1603:1687:0622/090500.809665:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1643:1643:0622/090501.718820:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

**Comment by ayushverma14** [comment]
I am trying to launch vs code installed on wsl ubuntu installed on windows machine .Getting the same error and vs code is unable to start
```
[18017:0708/124642.570768:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[18017:0708/124642.570908:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[18017:0708/124642.572659:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[18017:0708/124642.572681:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[18017:0708/124642.628617:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[main 2022-07-08T07:16:42.707Z] [File Watcher (node.js)] Request to start watching: /home/ayusver/.config/Code/User (excludes: <none>, includes: <all>),/home/ayusver/.config/Code/User/settings.json (excludes: <none>, includes: <all>)
[main 2022-07-08T07:16:42.719Z] Sending env to running instance...
[main 2022-07-08T07:16:42.720Z] [File Watcher (node.js)] Started watching: '/home/ayusver/.config/Code/User'
[main 2022-07-08T07:16:42.721Z] [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/home/ayusver/.config/Code/User/settings.json'
[main 2022-07-08T07:16:42.827Z] Sent env to running instance. Terminating...
[main 2022-07-08T07:16:42.828Z] Lifecycle#kill()
[main 2022-07-08T07:16:42.828Z] Lifecycle#onWillShutdown.fire()
```

**Comment by StephaneRavet** [comment]
I am trying to launch cypress from my wsl project :

> npx cypress open
[2069:0708/111639.476991:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[2069:0708/111639.477091:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[2069:0708/111639.480470:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2069:0708/111639.480516:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2069:0708/111639.575912:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[2241:0708/111639.606803:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[2241:0708/111639.609824:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
[2069:0708/111640.314047:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2069:0708/111640.441276:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

**Comment by ms0uto** [comment]
Launching chromium from void linux causes the same behaviour.

`[6769:6795:0926/204512.848653:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[6769:6795:0926/204512.848734:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[6769:6795:0926/204512.848775:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")`

**Comment by Jester3141** [comment]
I had this issue and it turned out that SELinux was causing chrome not to be able to access certain things through dbus.  (errors were seen in the dbus log noting the selinux/chrome connection)  Solutions are to either, add the appropriate selinux permissions to chrome or to disable selinux.

**Comment by desaijay315** [comment]
Is this issue resolved? After installing google-chrome , getting the below issue

![image](https://user-images.githubusercontent.com/9349985/197147479-a7a2ebab-4131-49d4-95d3-034fcf364132.png)

**Comment by desaijay315** [comment]
> I had this issue and it turned out that SELinux was causing chrome not to be able to access certain things through dbus. (errors were seen in the dbus log noting the selinux/chrome connection) Solutions are to either, add the appropriate selinux permissions to chrome or to disable selinux.

@Jester3141  - Ill give this a try

**Comment by StephaneRavet** [comment]
Cypress now launches correctly after migrating to Windows 11 (which adds WSLg).

**Comment by sam-mfb** [comment]
> Here are steps to get `dbus` functionality on Win10/WSL:
> 
> ```
> - set `DISPLAY` env variable
> - start `dbus` service
> - set `XDG_RUNTIME_DIR` env variable
> - start `dbus` user session
> ```
> 
> This will fix `ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/user/1000/bus: No such file or directory`
> 
> Sample run on `Win10` and `vcxsrv` using current WSL endpoint IP address:
> 
> ```
> - export DISPLAY=172.19.48.1:0
> - sudo service dbus start
> - export XDG_RUNTIME_DIR=/run/user/$(id -u)
> - sudo mkdir $XDG_RUNTIME_USER
> - sudo chmod 700 $XDG_RUNTIME_DIR
> - sudo chown $(id -un):$(id -gn) $XDG_RUNTIME_DIR
> - export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus
> - dbus-daemon --session --address=$DBUS_SESSION_BUS_ADDRESS --nofork --nopidfile --syslog-only &
> ```

Is line 4 a typo, i.e., should it be `sudo mkdir $XDG_RUNTIME_DIR`?

**Comment by mikaello** [comment]
> Here are steps to get `dbus` functionality on Win10/WSL:
> ...

This seems to help, but does not work completely, I now got errors like:

```
[5675:7:1110/161554.189115:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[1110/161556.373605:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[1110/161556.373667:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
```

... and the webpage crashes. Has someone solved this this?

I am running google-chrome in Docker in WSL trough xserver.

**Comment by joracine** [comment]
Tweak:
`
export DISPLAY=`hostname -I | xargs`:0
sudo service dbus start
export XDG_RUNTIME_DIR=/run/user/$(id -u)
sudo mkdir $XDG_RUNTIME_USER
sudo chmod 700 $XDG_RUNTIME_DIR
sudo chown $(id -un):$(id -gn) $XDG_RUNTIME_DIR
export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus
dbus-daemon --session --address=$DBUS_SESSION_BUS_ADDRESS --nofork --nopidfile --syslog-only &
`

**Comment by SirLouen** [comment]
```
$ sudo service dbus start
Redirecting to /bin/systemctl start dbus.service
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

How can you start dbus without systemd?

**Comment by elsaco** [comment]
@SirLouen if you type `systemctl cat dubs.service` there are the `ExecStart` and `ExecReload` commands. Also `dbus-daemon --help` will show the options for starting the daemon.

**Comment by SirLouen** [comment]
> @SirLouen if you type `systemctl cat dubs.service` there are the `ExecStart` and `ExecReload` commands. Also `dbus-daemon --help` will show the options for starting the daemon.

```
$ sudo systemctl cat dbus.service
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

**Comment by elsaco** [comment]
@SirLouen you could just look at the unit file in `/lib/systemd/system/dbus.service`:

```
elsaco@RIPPER:~$ cat /lib/systemd/system/dbus.service
[Unit]
Description=D-Bus System Message Bus
Documentation=man:dbus-daemon(1)
Requires=dbus.socket
# Do not stop on shutdown
DefaultDependencies=no
Wants=sysinit.target
After=sysinit.target basic.target

[Service]
ExecStart=@/usr/bin/dbus-daemon @dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
ExecReload=/usr/bin/dbus-send --print-reply --system --type=method_call --dest=org.freedesktop.DBus / org.freedesktop.DBus.ReloadConfig
OOMScoreAdjust=-900
```

**Comment by SirLouen** [comment]
> cat /lib/systemd/system/dbus.service

Not exactly there

```
$ cat /etc/systemd/system/dbus.service
[Unit]
Description=D-Bus System Message Bus
Documentation=man:dbus-broker-launch(1)
DefaultDependencies=false
After=dbus.socket
Before=basic.target shutdown.target
Requires=dbus.socket
Conflicts=shutdown.target

[Service]
Type=notify
Sockets=dbus.socket
OOMScoreAdjust=-900
LimitNOFILE=16384
ProtectSystem=full
PrivateTmp=true
PrivateDevices=true
ExecStart=/usr/bin/dbus-broker-launch --scope system --audit
ExecReload=/usr/bin/busctl call org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus ReloadConfig

[Install]
Alias=dbus.service
```

```
$ /usr/bin/dbus-broker-launch --scope system --audit
No listener socket inherited
```

**Comment by wwjll** [comment]
I tried

```
export LIBGL_ALWAYS_INDIRECT=1
export DISPLAY=:0
```

then I can launch chrome window in my win11. And using xrdp and xfce4 seems a reliable solution if you want a full desktop of your wsl2 .

**Comment by Creeki** [comment]
> I tried
> 
> ```
> export LIBGL_ALWAYS_INDIRECT=1
> export DISPLAY=:0
> ```
> 
> then I can launch chrome window in my win11. And using xrdp and xfce4 seems a reliable solution if you want a full desktop of your wsl2 .

Thanks you so much @wwjll !!,  it also makes the microsoft-edge works in my win11!

**Comment by 3xploiton3** [comment]
open vs code, or oss code using kali linux give us this error

> [4081:0825/183951.012712:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[4081:0825/183951.015442:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[4081:0825/183958.526565:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[4081:0825/183958.528552:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[4081:0825/184002.551679:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[4081:0825/184002.555458:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[4081:0825/184024.138150:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[4081:0825/184024.141588:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

**Comment by Dari4sho** [comment]
I could get rid of the xdg related errors by reinstalling xdg-utils on Ubuntu-22.04 (wsl2) on win11 with wslg
```bash
sudo apt-get install --reinstall xdg-utils
```

**Comment by kevin-coppens** [comment]
I fixed it by following this : https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps

and then: sudo apt-get install dbus-x11

**Comment by boamorte666** [comment]
Windows 11 - Ubuntu - WSL 2 - Clean Install

wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb
sudo apt install --fix-broken -y
sudo dpkg -i google-chrome-stable_current_amd64.deb

I'm just do this:

sudo apt install upower
export XDG_RUNTIME_DIR=/run/user/$(id -u)
export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus
dbus-daemon --session --address=$DBUS_SESSION_BUS_ADDRESS --nofork --nopidfile --syslog-only &

![Captura de tela 2023-11-27 014618](https://github.com/microsoft/WSL/assets/149851917/f89662ce-4740-435f-a43b-8ae6326db820)
![Captura de tela 2023-11-27 014552](https://github.com/microsoft/WSL/assets/149851917/f5d1a09c-f715-4f94-8c33-c0e2fbe36e68)

**Comment by shrikantbmali** [comment]
Just restart your PC.

**Comment by Juulaps** [comment]
> Here are steps to get `dbus` functionality on Win10/WSL:
> 
> ```
> - set `DISPLAY` env variable
> - start `dbus` service
> - set `XDG_RUNTIME_DIR` env variable
> - start `dbus` user session
> ```
> 
> This will fix `ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/user/1000/bus: No such file or directory`
> 
> Sample run on `Win10` and `vcxsrv` using current WSL endpoint IP address:
> 
> ```
> - export DISPLAY=172.19.48.1:0
> - sudo service dbus start
> - export XDG_RUNTIME_DIR=/run/user/$(id -u)
> - sudo mkdir $XDG_RUNTIME_USER
> - sudo chmod 700 $XDG_RUNTIME_DIR
> - sudo chown $(id -un):$(id -gn) $XDG_RUNTIME_DIR
> - export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus
> - dbus-daemon --session --address=$DBUS_SESSION_BUS_ADDRESS --nofork --nopidfile --syslog-only &
> ```
> 
> This can be added to `.profile` or `.bashrc` however the IP changes with every WSL restart. Win11 users don't need to worry about setting `DISPLAY` it's done by `wslg`.
> 
> When lauching `google-chrome` there are no more `dbus` errors, just some power daemon related (ignore them) and some extension not being supported:
> 
> ```
> tux@RIPPER:~$ google-chrome
> [1603:1687:0622/090500.809467:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
> [1603:1687:0622/090500.809580:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
> [1603:1687:0622/090500.809665:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
> [1643:1643:0622/090501.718820:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
> ```
> 
> And if you install `upower` the only error when starting `google-chrome` is:
> 
> ```
> tux@RIPPER:~$ google-chrome
> [2313:2313:0622/092753.743901:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
> ```

On Windows 11 (OS Build 22631.2861) + Ubuntu 22.04.3 I only needed to start the dbus user session to resolve the errors. The environment variables are already set out of the box. And the dbus service was already started (checked with `systemctl status dbus`).

`dbus-daemon --session --address=$DBUS_SESSION_BUS_ADDRESS --nofork --nopidfile --syslog-only &`

I do still get 2 Vulkan errors but those seems to be ignorable.

![image](https://github.com/microsoft/WSL/assets/130138922/2d4c4b52-255f-43c8-b746-25e9a92d5995)

**Comment by fdciabdul** [comment]
![image](https://github.com/microsoft/WSL/assets/31664438/fc948a56-3d09-49b1-81ba-65c235574998)
same issue here

**Comment by xavier-fenton** [comment]
any solution to the problem?

**Comment by WuYeqi** [comment]
> Here are steps to get `dbus` functionality on Win10/WSL:以下是在 Win10/WSL 上获取 `dbus` 功能的步骤：
> 
> ```
> - set `DISPLAY` env variable
> - start `dbus` service
> - set `XDG_RUNTIME_DIR` env variable
> - start `dbus` user session
> ```
> 
> This will fix `ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/user/1000/bus: No such file or directory` 这将修复 `ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/user/1000/bus: No such file or directory`
> 
> Sample run on `Win10` and `vcxsrv` using current WSL endpoint IP address:示例运行 `Win10` 和 `vcxsrv` 使用当前 WSL 终结点 IP 地址：
> 
> ```
> - export DISPLAY=172.19.48.1:0
> - sudo service dbus start
> - export XDG_RUNTIME_DIR=/run/user/$(id -u)
> - sudo mkdir $XDG_RUNTIME_USER
> - sudo chmod 700 $XDG_RUNTIME_DIR
> - sudo chown $(id -un):$(id -gn) $XDG_RUNTIME_DIR
> - export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus
> - dbus-daemon --session --address=$DBUS_SESSION_BUS_ADDRESS --nofork --nopidfile --syslog-only &
> ```
> 
> This can be added to `.profile` or `.bashrc` however the IP changes with every WSL restart. Win11 users don't need to worry about setting `DISPLAY` it's done by `wslg`.这可以添加到 IP 中 `.profile` ，或者 `.bashrc` IP 会随着每次 WSL 重启而更改。Win11 用户无需担心将其设置为 `DISPLAY` 由 `wslg` 完成。
> 
> When lauching `google-chrome` there are no more `dbus` errors, just some power daemon related (ignore them) and some extension not being supported:启动 `google-chrome` 时，不再 `dbus` 有错误，只是一些与电源守护程序相关的错误（忽略它们）和一些不支持的扩展：
> 
> ```
> tux@RIPPER:~$ google-chrome
> [1603:1687:0622/090500.809467:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
> [1603:1687:0622/090500.809580:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
> [1603:1687:0622/090500.809665:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
> [1643:1643:0622/090501.718820:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
> ```
> 
> And if you install `upower` the only error when starting `google-chrome` is:
> 
> ```
> tux@RIPPER:~$ google-chrome
> [2313:2313:0622/092753.743901:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
> ```

There is a small error in the code here
![image](https://github.com/microsoft/WSL/assets/7300814/19455643-84d8-4bf3-8ce9-1a442a5832e2)
This will work。Thank you very much, I spent several days trying to find a way to solve this problem

**Comment by batata004** [comment]
Any news? I am still facing this same error message on Centos Stream 9.

**Comment by qingpu-y** [comment]
1. try <apt-get install dbus>
2. try <services dbus start>

 
	1.  Failed to connect to the bus: Failed to connect to socket /run/user/0/bus: No such file or directory
	> dbus-launch and export <output DBUS_SESSION_BUS_ADDRESS>

	2. [32374:32485:0815/162322.776073:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
	> apt install upower

![image](https://github.com/user-attachments/assets/818bae42-309f-436a-8e20-79f879b232b1)

**Comment by sshveta** [comment]
sudo service dbus start
- export XDG_RUNTIME_DIR=/run/user/$(id -u)
- sudo mkdir $XDG_RUNTIME_USER
- sudo chmod 700 $XDG_RUNTIME_DIR
- sudo chown $(id -un):$(id -gn) $XDG_RUNTIME_DIR
- export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus
- dbus-daemon --session --address=$DBUS_SESSION_BUS_ADDRESS --nofork --nopidfile --syslog-only &
 

This worked for me .

**Comment by alexanderilyin** [comment]
@Juulaps seems you had small typo:

```diff
 sudo service dbus start
 export XDG_RUNTIME_DIR=/run/user/$(id -u)
-sudo mkdir $XDG_RUNTIME_USER
+sudo mkdir $XDG_RUNTIME_DIR
 sudo chmod 700 $XDG_RUNTIME_DIR
 sudo chown $(id -un):$(id -gn) $XDG_RUNTIME_DIR
 export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus
 dbus-daemon --session --address=$DBUS_SESSION_BUS_ADDRESS --nofork --nopidfile --syslog-only &
```

but it solved by errors. Thanks!
