### ISSUE TITLE
DNS issues in WSL2

### ISSUE THREAD

**Issue by OneBlue** [microsoft/WSL#8365]
### Version

Multiple Windows builds are affected

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

This issue is here to merge DNS related issues in WSL2.

Symptoms include:

- DNS resolution failing with `Temporary failure in name resolution`
- DNS resolution timing out

This issue does not cover scenario where /etc/resolv.conf is manually edited.

If you're hitting this, please upvote / comment and [upload logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs-recommended-method) 

### Expected Behavior

N / A

### Actual Behavior

N / A

**Comment by stijnherreman** [comment]
@OneBlue I've posted repro steps in #8236 for one of the causes.

**Comment by lbarbaglia** [comment]
Hi,
I'm having the exact same issue so I've collected some logs in case it can help:
[WslLogs-2022-05-10_16-27-14.zip](https://github.com/microsoft/WSL/files/8662436/WslLogs-2022-05-10_16-27-14.zip)

Even modifying the /etc/resolv.conf is not working anymore.

**Comment by CraigHutchinson** [comment]
I am getting this issue on fresh installation of Windows 11 with WSL2 Ubuntu image, really annoying issue!

[WSL] `sudo apt update` = `... Temporary failure resolving 'archive.ubuntu.com' ...`
[WSL] `resolv.conf` = `... nameserver 172.23.48.1`
[WSL] `ping 172.23.48.1` = `From 172.23.62.236 icmp_seq=3 Destination Host Unreachable`
[Windows] `ping 172.23.48.1` = `Reply from 172.23.48.1: bytes=32 time<1ms TTL=128`

**Comment by CraigHutchinson** [comment]
Logs captured from steps above
[WslLogs-2022-05-17_10-05-59.zip](https://github.com/microsoft/WSL/files/8706870/WslLogs-2022-05-17_10-05-59.zip)

NOTE: The script reported an error on Windows 11 but did capture lots of data still but possible incomplete?
![image](https://user-images.githubusercontent.com/54269136/168774664-05dbb4ae-bfd7-4ba9-ba69-3970a21070e6.png)

**Comment by CraigHutchinson** [comment]
I am getting this issue on fresh installation of Windows 11 with WSL2 Ubuntu image, really annoying issue!

[WSL] sudo apt update = ... Temporary failure resolving 'archive.ubuntu.com' ...
[WSL] resolv.conf = ... nameserver 172.23.48.1
[WSL] ping 172.23.48.1 = From 172.23.62.236 icmp_seq=3 Destination Host Unreachable
[Windows] ping 172.23.48.1 = Reply from 172.23.48.1: bytes=32 time<1ms TTL=128

Attached are the logs.
[WslLogs-2022-05-17_10-17-13.zip](https://github.com/microsoft/WSL/files/8706980/WslLogs-2022-05-17_10-17-13.zip)

NOTE: ON Windows 11 I got this error when running the capture so they may be incomplete?
![image](https://user-images.githubusercontent.com/54269136/168777262-7a419799-3f0b-4de6-a0b6-0b80fddf74a3.png)

**Comment by r2evans** [comment]
@CraigHutchinson , your comment appears to mimic what I'm seeing, where the problem is somehow in the *routing* and not just the name resolution. Have you found any workarounds?

**Comment by MikaelUmaN** [comment]
#4285 was already tracking this. I consider this issue the /dupe #4285

**Comment by BtbN** [comment]
There were multiple open issues, all about the functionally same issue. Hence, as the initial description says, this exists to merge and declutter them.

**Comment by dlaudams** [comment]
> There were multiple open issues, all about the functionally same issue. Hence, as the initial description says, this exists to merge and declutter them.

If this leads to a fix, this is a great outcome.

However the way it was handled may alienate the community. i.e., closing all the related issues without discussion or a clear reason provided in those issues.

**Comment by unowiz** [comment]
It might be to do with Windows Defender settings. resolv.conf and wsl.conf based approach didn't work for me. 
sudo apt update && sudo apt upgrade worked immediately after I turned off the Private network firewall. Once the update completed, I've put the firewall for private network back on.

On Windows 11, Go to Windows Security (from system tray, right click on Windows Security icon and select "View security dashboard" or simply search for "Firewall and network protection" after you press the windows key). Within the Firewall and network protection page, you should see Domain network (if domain connected), Private network, Public network. Go for the private network an turn it off temporarily as a workaround. Hope this helps.

**Comment by Glitterinn** [comment]
I may have found another way to fix this. Originally I had this problem after using a proxy software. I just edited resolv.conf. It worked well until I realized that I also couldn't ping to Windows from WSL.

For some reason, the vEthernet (WSL) adapter on my PC was treated as a public network. Disabling public firewall or turning off the option "block all incoming connections, including those in the list of allowed applications" in Control Panel fixed everything. I also attempted to change its connection profile to private using PowerShell, but `Get-NetConnectionProfile` can't even find it while both `ipconfig` and `Get-NetIPconfiguration` can display some limited info about it.

**Comment by zugazagoitia** [comment]
> It might be to do with Windows Defender settings. resolv.conf and wsl.conf based approach didn't work for me. sudo apt update && sudo apt upgrade worked immediately after I turned off the Private network firewall. Once the update completed, I've put the firewall for private network back on.
> 
> On Windows 11, Go to Windows Security (from system tray, right click on Windows Security icon and select "View security dashboard" or simply search for "Firewall and network protection" after you press the windows key). Within the Firewall and network protection page, you should see Domain network (if domain connected), Private network, Public network. Go for the private network an turn it off temporarily as a workaround. Hope this helps.

This seems to be a fix for me too, Windows Firewall must be blocking DNS queries originating inside the WSL VM from reaching the DNS server at the host.

**Comment by Ray-Barker** [comment]
Tried to disable Windows Defender Firewall on Windows 10, doesn't help.
Tried manually editing /etc/resolv.conf in my Ubuntu 20.04 WSL2 by adding 8.8.8.8 and 1.1.1.1, it helps, but these servers don't work in our VPN.
What helped me as a workaround was adding my router's IP as a nameserver to resolv.conf since it has DNS server capability.
But I would like a more generalized solution.

**Comment by mbwhite** [comment]
Windows 10 with Ubuntu 20 in WSL2 : got some reproducible failures today for the first time; and it's confirmed something I've suspected but never been able to prove.. that there might be a connection with running the docker daemon.

Everything is working correctly (as fas as DNS goes), start the docker daemon (just a plain `sudo dockerd` ) afterwards, the 'temporary failure' error occurs. 

Logs attached.
[WslLogs-2022-06-08_16-56-39.zip](https://github.com/microsoft/WSL/files/8863290/WslLogs-2022-06-08_16-56-39.zip)

**Comment by jikuja** [comment]
For me https://github.com/microsoft/WSL/issues/7555 gave really good pointers for fixing the issue.

Fixes that works for me:
* Disabling defender for **public profile** fixes DNS issue
* or removal of vEthernet(WSL) network connection on public profile settings also fixes the DNS issue

I cannot recommend either of those to anyone because the first solution just breaks security and the second one might open some vulnerabilites.

**Comment by BtbN** [comment]
Can you change it via Set-NetConnectionProfile in an elevated PowerShell prompt?

**Comment by MatthewSkingley** [comment]
Turning off Bluetooth and Wi-Fi hotspot on my laptop worked this time, sometimes restarting LxssManager works

**Comment by Mithras** [comment]
I've decided to give Docker 4.x another try to see if WLS2 is still busted and tried to do what was suggested in https://github.com/microsoft/WSL/issues/4285#issuecomment-1180567785 Using it for a couple days already and everything seems to be fine for now. So for me the issue was not firewalls, VPNs, etc. It was because WLS2 doesn't like default Docker network bridge. See https://docs.docker.com/network/bridge/#configure-the-default-bridge-network

**Comment by BtbN** [comment]
If docker really uses the same subnet than WSL2 does, it's not surprising that breaks stuff.
Though for me that was never an issue, so maybe there's some randomness or auto-detection to the network WSL2 and/or Docker uses?

**Comment by mateusz91t** [comment]
run
`echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null`

**Comment by r2evans** [comment]
@mateusz91t, just curious ... why use `tee` there? You are explicitly dumping its sole purpose: send to both the output and a file, but you redirect output to `/dev/null`, so why do that when `echo "nameserver 8.8.8.8" > /etc/resolve.conf` would be far simpler and direct. (FYI, this hasn't worked for me when a wifi change caused WSL2 to stop working correctly. For me it is a routing problem, not a name-resolution problem. That is, name-resolution will report failing when routing doesn't work, but that doesn't mean that dns is the core problem.)

**Comment by mateusz91t** [comment]
@r2evans,
I've done some steps during googling and finally something helps me. My previous answer probably is not helpful. I think **disconnect a VPN** is a my solution.

**Comment by mateusz91t** [comment]
@r2evans, it is a workaround that helps me. If you use VPN too, try it please.
https://github.com/sakai135/wsl-vpnkit
Found in this issue:
https://github.com/microsoft/WSL/issues/5068

**Comment by isaac-infotrend** [comment]
My fix was to run the stock Windows 10 network reset feature from searching for that in the start menu. After that run wsl and it will reinitalize the virtual switch for you and work just fine.

Noteworthy:

-In the network reset prompt, Windows suggests it may need to reinstall VPN or virtual switches... Both WSL and things that use HyperV switches like Docker for Windows appear to create virtual switches. 
- After running reset, I ran Get-NetAdapter and the WSL vEthernet (WSL) entry did not show up.  After running `wsl` it did.  I believe the order in which the virtual network adapters are created may impact things.  Each software team should include a step to check for the existence of the network card and either prompt the user to use an existing one or allow them to define a new one with no overlapping DNS rules.  
- Windows does not support more than one virtual switch, even though WSL itself creates a new virtual switch when it first starts after running network reset. 
- I do not recommend the firewall fix because it may bypass domain name resolution checks, become its own man in the middle (?) attack vector. 
- I noticed that Docker has Powershell script MobyLinux.ps1 that creates then removes virtual switch named DockerNAT, attempting to bypass a bug, perhaps related to this one. 

Applying the nameserver 8.8.8.8 to /etc/resolve.conf seems wise enough, given that the virtual switch or your network cards' IP addresses may change.  It is not a good design to dynamically assign something that may get corrupted, so go ahead and do that.

**Comment by ecourtial** [comment]
Same issue.

WSL2 worked perfectly and on the first attempt on 2 of our 4 PCs running Windows 11.
For the two others : we have this DNS issue. We tried everything among the billion of various solutions described on the Web... No result.

**Comment by keith-horton** [comment]
A couple of comments for some of the issues being described here.

There's a known issue where the necessary Firewall Rules to all the DNS request to be proxied are incorrect, and thus block DNS requests from the WSL container. We have put a fix for this in this next WSL release: https://github.com/microsoft/WSL/releases/tag/0.70.5

Secondly, there's a known Firewall configuration which will always block proxied DNS requests from the WSL container: this is the "BlockAllInbound" setting on network profiles. You can see if this is set by opening "Windows Security" - clicking "Firewall & network protection" -- then clicking on one of the 3 Network Profiles which is being applied to your connected network adapters (Domain, Public, or Private). That page lists a setting, "Blocks all incoming connections, including those in the list of allowed apps." ---> if this is checked, then DNS requests will not be proxied from the WSL container.

**Comment by MarcoGorelli** [comment]
In my case, this was due to Norton's Smart Firewall - turning that off resolved the issue

**Comment by jikuja** [comment]
@keith-horton Did anyone investigate how much DNS problems have been caused by usage of Docker? There has been few reports that the issue is triggered as soon as docker daemon has been started:

* e.g. for me problem was fixed after multiple reboots/retries
  * the only change I saw was ` vEthernet (WSL)` having a new subnet that did not overlap with docker default bridge subnet.

Is it even sane use case to have overlapping subnets on  vEthernet (WSL) and docker default bridge?

**Comment by cr2007** [comment]
**Update:** Now the issue seems to have been resolved in the latest Windows update
under the 2022-10 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5018496)

I am now able to do `sudo apt-get update` and `code .` to open VS Code via the server.

**Comment by keith-horton** [comment]
> Is it even sane use case to have overlapping subnets on vEthernet (WSL) and docker default bridge?

I'm not super familiar with Docker. Having overlapping private NAT'd subnets that both need to get NAT'd (probably both by the WinNAT driver in Windows) is likely going to create issues. I'll need to follow up with folks on Docker.

**Comment by chrisjsmith** [comment]
After battling with this for over two years, I have dumped WSL entirely and gone back to VirtualBox + Debian + PuTTY.

We have no chance of getting Windows 11 and we don't really want it anyway so the fix target is a joke.

I'm not sure why I even bothered at this point. It's just been pain and friction, for what?!?

**Comment by jordansissel** [comment]
From https://github.com/microsoft/WSL/issues/8365#issuecomment-1298001836, 
> seems to have been resolved in ... 2022-10 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5018496)

@cr2007 I wonder what changed on your system to make things work again. A [bug fix in the firewall rules ](https://github.com/microsoft/WSL/issues/8365#issuecomment-1295250969) hasn't been released yet. I just received this update  (KB5018496) and the problem is not yet resolved.

I see WSL 0.70.5 is not yet available, so I'll wait until then to try again.

**Comment by noraab** [comment]
Can anyone give me a hint how to check the WSL version currently installed?

**Comment by stijnherreman** [comment]
@noraab run `wsl --version` in PowerShell.

```
PS C:\Users\stijn> wsl --version
WSL version: 0.70.5.0
...
```

**Comment by noraab** [comment]
@stijnherreman thank you for your reply. Unfortunately, that prints the help-text on my system. Could it be, that `wsl --version` only works on Windows 11? I'm on Windows 10.

**Comment by BtbN** [comment]
I think you need the Windows Store version of WSL2.
Not sure if that's available on Windows 10.

**Comment by noraab** [comment]
> I think you need the Windows Store version of WSL2. Not sure if that's available on Windows 10.

Thanks, @BtbN. You're right, Windows Store version is required to run `wsl --version`.
It is only available on Windows 11, even though it first looks like one can install it on Windows 10, it fails when trying to run it after installation.

**Comment by jikuja** [comment]
> In my case, this was due to a network overlap between the WSL network and the Docker subnets.
> 
> Fixed it by editing /etc/docker/daemon.json

@keith-horton do you have information which IP address ranges are being allocated for WSL network by default? Would be easier to select docker's default address pool if WSL's random(?) address range is documented.

**Comment by keith-horton** [comment]
Hi there.

WSL IP allocations come from HNS - which finds an available IP prefix range from 172.17.* to 172.32.*, though can use 192.168.* if need be. (Basically, the "class b" and "class c" IP prefix ranges).

**Comment by domattioli** [comment]
None of the suggestions I've tried on this (or other Github threads) worked for me. I tried everything except disabling my firewall, as many suggested.

[This solution](https://www.ithands-on.com/2020/12/failed-to-fetch-httpdearchiveubuntucomu.html), however, did work:
```echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null```

I'm not sure how this is different than the other solutions that suggested something similar. But it worked nonetheless.

I'm using WSL2, Ubuntu 22.04.

**Comment by jikuja** [comment]
>> There's a known issue where the necessary Firewall Rules to all the DNS request to be proxied are incorrect, and thus block DNS requests from the WSL container. We have put a fix for this in this next WSL release: https://github.com/microsoft/WSL/releases/tag/0.70.5

> Will fixes like this and updates be released for WSL on Windows 10? Many enterprises will be using Windows 10 for a long time to come.

I'll mention this in here too: WSL 2 is now available on Microsoft Store for both Windows 10 and 11: https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-in-the-microsoft-store-is-now-generally-available-on-windows-10-and-11/ 

The article does not mention if Windows 10 and Windows 11 now has full feature-parity looks like some of the windows 11 -exclusive things are now available for Windows 10.

**Comment by tgross35** [comment]
Unfortunately it seems like there is a chance that the 2022-08 security update might break this, at least on Windows 11. have never had an issue but [KB5012170](https://support.microsoft.com/en-us/topic/kb5012170-security-update-for-secure-boot-dbx-august-9-2022-72ff5eed-25b4-47c7-be28-c42bd211bb15) was installed this morning, and now it doesn't work (nor does the `/etc/resolv.conf` workaround

Disabling the private network firewall (as mentioned [here](https://github.com/microsoft/WSL/issues/8365#issuecomment-1140416081)) allows internet connection, but updating (mentioned in the comment) didn't persist the fix when I re-enabled private firewall.

**Comment by jabbera** [comment]
I'm still getting blocks in my firewall log that I can't seem to get rid of. It's making me sad.

**Comment by slonopotamus** [comment]
Either configure your firewall so it no longer blocks WSL requests or contact your system administrator.

**Comment by jabbera** [comment]
@slonopotamus It seems unpossible. I put a wide open rule in both directions and they are still getting dropped.

**Comment by jabbera** [comment]
@slonopotamus I had to do this: Set-NetFirewallProfile -DisabledInterfaceAliases "vEthernet (WSL)"

**Comment by jikuja** [comment]
> Hi there.
> 
> WSL IP allocations come from HNS - which finds an available IP prefix range from 172.17.* to 172.32._, though can use 192.168._ if need be. (Basically, the "class b" and "class c" IP prefix ranges).

FYI: Related ticket has been opened: https://github.com/microsoft/WSL/issues/9251

Implementation of that should decrease possibility of getting issues by overlapping IP addresses in case of Docker Desktop is used.

**Comment by ryan-lake** [comment]
One fix we discovered is if the main network connection is in a public profile, it will also prevent DNS resolutions within WSL when on the VPN with similar symptoms. Moving the WIFI connection to Private fixed the issue.

**Comment by jmacdone** [comment]
One of the things I've had success with to get WSL2 and DNS playing nice is to use the Local Group Policy Editor to set enable local rule merging for the local firewall.
Computer Configuration > Windows Settings > Security Settings > Windows Defender ... > Windows Defender [...] Local Group Policy Object

Find "Windows Defender Firewall Properties", Then under each relevant profile:
   Settings > Customize... > Apply local firewall rules: Yes

**Comment by 0x4c6565** [comment]
Confirmed that the [policy change described](https://github.com/microsoft/WSL/issues/8365#issuecomment-1354130966) by @jmacdone above fixes the problem for me - the WSL created firewall rule (`HNS Container Networking ...`) works fine now

**Comment by joaov777** [comment]
As for me, a simple `wsl --shutdown` from the windows command prompt did it for me. Working like a charm now.

**Comment by matkozak** [comment]
I am unhappy to report that updating to the Store version on Windows 10 (v1.0.3.0 on build 19045.2486) by itself did not solve these issues for me. Previously the non-Store WSL installation had been working fine since May 2022 until October when the DNS stopped working, seemingly out of the blue. Currently, I am still using the manual DNS configuration in `/etc/resolv.conf` which generally works but is less then ideal (does not work with VPN; switching between Google's public DNS and corporate network DNS adds a delay when waiting for the wrong DNS to time out).

I am using Docker but not Docker Desktop, only apt-installed docker inside WSL. The problem persists regardless of whether the docker daemon is running.

**Comment by joaov777** [comment]
@matkozak Did you try `wsl --shutdown`?

**Comment by jasonjgw** [comment]
The group policy change recommended by @jmacdone solved this problem for me as well. I had installed the Windows Security Baseline policy, which I assume was the source of the original (stricter) setting.

**Comment by jmacdone** [comment]
Like @jasonjgw, we're also applying a (slightly modified) windows security baseline.  It's on my list of suspects too.

**Comment by ron-many** [comment]
This worked for me. It solved DNS to both public and VPN connections.
In admin PowerShell window I run the following to allow Inbound traffic to the virtual WSL ethernet connection.
`New-NetFirewallRule -DisplayName "WSL" -Direction Inbound -InterfaceAlias "vEthernet (WSL)" -Action Allow`

Hope this helps

**Comment by OrbitalCannon** [comment]
> One of the things I've had success with to get WSL2 and DNS playing nice is to use the Local Group Policy Editor to set enable local rule merging for the local firewall. Computer Configuration > Windows Settings > Security Settings > Windows Defender ... > Windows Defender [...] Local Group Policy Object
> 
> Find "Windows Defender Firewall Properties", Then under each relevant profile: Settings > Customize... > Apply local firewall rules: Yes

This was the solution for me.

Replying to the multiple comments saying to turn off the Windows Defender Firewall for vEthernet (WSL) interface, make sure you have the firewall configured on WSL before making that change. WSL by default does not have a firewall setup, or it didn't on mine.

**Comment by Ged-fi** [comment]
> One of the things I've had success with to get WSL2 and DNS playing nice is to use the Local Group Policy Editor to set enable local rule merging for the local firewall. Computer Configuration > Windows Settings > Security Settings > Windows Defender ... > Windows Defender [...] Local Group Policy Object
> 
> Find "Windows Defender Firewall Properties", Then under each relevant profile: Settings > Customize... > Apply local firewall rules: Yes

This fixed this long-standing problem for me, too!

**Comment by iambryancs** [comment]
> One of the things I've had success with to get WSL2 and DNS playing nice is to use the Local Group Policy Editor to set enable local rule merging for the local firewall. Computer Configuration > Windows Settings > Security Settings > Windows Defender ... > Windows Defender [...] Local Group Policy Object
> 
> Find "Windows Defender Firewall Properties", Then under each relevant profile: Settings > Customize... > Apply local firewall rules: Yes

This fixed my issue as well. Thank you!

**Comment by samueldc** [comment]
> See if this link helps. [#4285 (comment)](https://github.com/microsoft/WSL/issues/4285#issuecomment-1180567785)
> 
> Basically a change to `/etc/docker/daemon.json`:
> 
> ```
> {
>     "bip" : "10.10.0.1/16"
> }
> ```

Thanks!

That's the only solution that worked in my case.

Edição	Windows 10 Pro
Versão	22H2
Instalado em	‎09/‎03/‎2022
Compilação do SO	19045.2846
Experiência	Windows Feature Experience Pack 120.2212.4190.0

Versão do WSL: 1.2.5.0
Versão do kernel: 5.15.90.1
Versão do WSLg: 1.0.51
Versão do MSRDC: 1.2.3770
Versão do Direct3D: 1.608.2-61064218
Versão do DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Versão do Windows: 10.0.19045.2846

**Comment by ashoklathwal** [comment]
[Check this detailed article](https://wealthquint.com/fix-wsl-dns-not-working-62430/) with the proper steps . By following these comprehensive troubleshooting steps, you can effectively diagnose and resolve most WSL DNS issues, ensuring smooth operation and minimal downtime.

**Comment by tomthecarrot** [comment]
> > One of the things I've had success with to get WSL2 and DNS playing nice is to use the Local Group Policy Editor to set enable local rule merging for the local firewall. Computer Configuration > Windows Settings > Security Settings > Windows Defender ... > Windows Defender [...] Local Group Policy Object
> > Find "Windows Defender Firewall Properties", Then under each relevant profile: Settings > Customize... > Apply local firewall rules: Yes
> 
> This fixed my issue as well. Thank you!

Fixed here too, thanks!

**Comment by jeffrson** [comment]
For me it does not seem to be a firewall issue.

It always happens after starting a couple of nodejs applications all trying to access mongodb on the Windows host via hostname.local.

Then I cannot ping the host anymore by its name because of "Temporary failure in name resolution". Sometimes, after 1 or 2 minutes, it starts working again. Sometimes, however, I need to reboot the host.

Single services can be started separately without problems. Maybe this is some kind of DOS protection? Don't have any idea to have any influence on that.

**Comment by shubhamanand148** [comment]
The only thing which worked for me was to switch to version 1.

To switch to version 1:
1. Open Powershell
2. wsl --shutdown
3. wsl.exe --set-version Ubuntu 1
4. Now open Ubuntu and try to ping.

**Comment by pter1342** [comment]
I can't access the group policy manager as it's managed by the company, as expected, DNS works just fine in WSL 1

**Comment by Elphasmaluki** [comment]
> It might be to do with Windows Defender settings. resolv.conf and wsl.conf based approach didn't work for me. sudo apt update && sudo apt upgrade worked immediately after I turned off the Private network firewall. Once the update completed, I've put the firewall for private network back on.
> 
> On Windows 11, Go to Windows Security (from system tray, right click on Windows Security icon and select "View security dashboard" or simply search for "Firewall and network protection" after you press the windows key). Within the Firewall and network protection page, you should see Domain network (if domain connected), Private network, Public network. Go for the private network an turn it off temporarily as a workaround. Hope this helps.

This woked perfectly for me. Turned off the Private Network firewall, restarted my computer and ran sudo apt update. All updates installed with problems.

**Comment by Previesam** [comment]
So this may help someone. After trying all most of the above with no luck. All I had to do was remove the resolve.conf link and the original file itself. Then edit /etc/wsl.conf and input the key to disable auto generation of the config file.

```
sudo unlink /etc/resolv.conf
sudo rm -rf /mnt/wsl/resolv.conf
sudo nano /etc/wsl.conf

Enter the following and save.
#[network]
generateResolvConf = false
```

After all that Open terminal windows terminal and run the following to shutdown wsl and start it back

```
wsl --shutdown
wsl
```

After this you should have internet access.

**Comment by grrava** [comment]
None of all these so-called fixes work for me. I tried everything. I have two computers, on my desktop this all works fine, on my laptop it doesn't. 
The /etc/resolv.conf file is unchanged, and is the same on both computers, so changing that file should not be regarded as a fix.
The local group policy is also the same on both, so this is also not what is causing the issue for me.

The only thing that is different (afaik) is that the laptop is on the domain of my company, and the desktop is not. Is there a setting there that can be checked if it has an impact?

**Comment by slonopotamus** [comment]
> I tried everything.

No you didn't. As was discussed a million times already, the cause why DNS is not working inside WSL2 is that _something_ is blocking DNS traffic between WSL2 and host machine. This _something_ is a firewall. So, the only proper way to fix the issue is to allow this traffic.

**Comment by grrava** [comment]
> No you didn't. As was discussed a million times already, the cause why DNS is not working inside WSL2 is that _something_ is blocking DNS traffic between WSL2 and host machine. This _something_ is a firewall. So, the only proper way to fix the issue is to allow this traffic by changing firewall rules.

Sure, I'd be happy to try that! What rules should I change?

**Comment by slonopotamus** [comment]
I neither have any idea what firewall rules you _have_ nor what software is used as a firewall at all. There are multiple of them besides stock Windows Firewall. You can try temporarily disabling the whole firewall thing and check whether that fixes DNS for you. If yes, you need to dig deeper into firewall configuration.

**Comment by grrava** [comment]
I have a clean windows install, so no weird rules or firewalls, just standard windows config.

**Comment by sommer-gei** [comment]
Just my 5 cents: I (2 times) had *similar* experiences/problems. After switching from Debian (11) to Ubuntu with the official WSL2 instructions, everything works (like expected and written above).

**Comment by mwmix** [comment]
> slonopotamus

Just ran into this issue after I just finished a fresh install. I didn't want to do the hack fix of changing /etc/resolv.conf and am happy you pointed out I should check my FW. Apparently my eset antivirus's fw was at fault and once I disabled that things started working. Ty for the hint.

**Comment by slonopotamus** [comment]
> Apparently my eset antivirus's fw was at fault and once I disabled that things started working.

Note that you do not need to disable fw _completely_, you just need to set it up so it allows relevant traffic. Unfortunately I don't have enough expertise with set to tell you how exactly to do that.

**Comment by keith-horton** [comment]
If you want the NAT DNS Server to resolve name resolution requests from the container, you will need an Firewall rule to allow [inbound] access to [UDP port 53] to the SharedAccess service. Windows creates this rule in the Windows Firewall with the name "HNS Container Networking - DNS (UDP-In) *"

**Comment by jasonyang-ee** [comment]
Not sure if this is skill issue or what. This thread comments are correct. Host firewall setting is the cause (for my case), but I can't seems to figure out how to set it correctly to make it work.

So, I simply nuked the entire Windows defender setting.

Click Windows Defender -> Firewall & network protection -> Turn off any network firewall -> "Restore Settings" button will show up -> This button will nuke your entire firewall setting.

But hey, it worked now..

**Comment by slonopotamus** [comment]
@jasonyang-ee try this: https://github.com/microsoft/WSL/issues/8365#issuecomment-1638592894

**Comment by grrava** [comment]
I just reinstalled Ubuntu and now it works... Made no changes to anything else so I guess something got fixed?

**Comment by craigloewen-msft** [comment]
Hi folks, we have put out a new update that aims to address networking issues in WSL. In your `.wslconfig` file you can set `experimental.networkingMode=mirrored`, as well as some other key settings that should improve your network compatibility! Please try them out and let us know what you think.

More info on this release and the changes can be [found here in the blog post](https://devblogs.microsoft.com/commandline/windows-subsystem-for-linux-september-2023-update/).

Please note: You need to be on a Windows Insiders version to use the new networking settings (Any channel of Windows Insiders will do, including release preview). If you see the "These are not supported" messages it means that your current Windows version doesn't have support, and you will need to upgrade. These features will eventually be coming to Windows 11 22H2.

**Comment by matkozak** [comment]
Hi @craigloewen-msft,

This news is much appreciated. Will these features be eventually supported in Windows 10 as well?

**Comment by wtrewby** [comment]
> Hi folks, we have put out a new update that aims to address networking issues in WSL. In your `.wslconfig` file you can set `experimental.networkingMode=mirrored`, as well as some other key settings that should improve your network compatibility! Please try them out and let us know what you think.
> 
> More info on this release and the changes can be [found here in the blog post](https://devblogs.microsoft.com/commandline/windows-subsystem-for-linux-september-2023-update/).
> 
> Please note: You need to be on a Windows Insiders version to use the new networking settings (Any channel of Windows Insiders will do, including release preview). If you see the "These are not supported" messages it means that your current Windows version doesn't have support, and you will need to upgrade. These features will eventually be coming to Windows 11 22H2.

Upgrading to pre-release version and adding the experimental networking mode sorted this out for me - thanks!

**Comment by kochinc** [comment]
> Hi folks, we have put out a new update that aims to address networking issues in WSL. In your `.wslconfig` file you can set `experimental.networkingMode=mirrored`, as well as some other key settings that should improve your network compatibility! Please try them out and let us know what you think.
> 
> More info on this release and the changes can be [found here in the blog post](https://devblogs.microsoft.com/commandline/windows-subsystem-for-linux-september-2023-update/).
> 
> Please note: You need to be on a Windows Insiders version to use the new networking settings (Any channel of Windows Insiders will do, including release preview). If you see the "These are not supported" messages it means that your current Windows version doesn't have support, and you will need to upgrade. These features will eventually be coming to Windows 11 22H2.

Thank you. Now I don't have to turn off the firewall for WSL2 to resolve names. I recalled there were only lo and eth0 listed with 'ip addr' command. After the pre-release update, 'ip addr' command shows all network interfaces including Wi-Fi and VPNs.

**Comment by craigloewen-msft** [comment]
These new networking features are now available on the latest version of Win11 22H2!

@matkozak this work is currently not planned to go back to Win10.

Please make sure you're on the latest build to get these features, you can do that by clicking "Check for Updates" in Windows settings. You can check you have the right build by either ensuring you have [KB5031354](https://support.microsoft.com/en-us/topic/october-10-2023-kb5031354-os-build-22621-2428-ecc07685-218f-4ba9-b3c8-fe2e35059aec) installed, or run `cmd.exe /c ver` and ensure that your build number is 22621.2428 or higher (Including the minor build number which is after the `.` as this was a backport!)

**Comment by slonopotamus** [comment]
According to that page, KB5031354 has absolutely nothing to do with WSL2.

**Comment by hack3rman** [comment]
Confirmed [KB5031354](https://support.microsoft.com/en-us/topic/october-10-2023-kb5031354-os-build-22621-2428-ecc07685-218f-4ba9-b3c8-fe2e35059aec) fixed the WSL2 DNS issue for me.

**Comment by Kyle2142** [comment]
Just in case it helps anyone, I had previously used the `generateResolvConf = false` config and after backup/restore to a different windows installation, it seems like it broke. Disabling this re-created `/etc/resolv.conf` (why did I have `/wsl/resolv.conf`?) and made DNS work again. Win11 not having the adapter listed threw me off though

**Comment by amadeann** [comment]
This may be completely unrelated, but maybe it works for some people (worked for me). I am using NordVPN, and with the "Stay invisible on LAN" setting ON, I get "Temporary failure in name resolution" error. When I switch if off, things work as expected. So if other solutions don't work for you, and you're using a VPN (NordVPN or other), you may try and debug issues on that end.

![image](https://github.com/microsoft/WSL/assets/14104292/03033606-167b-4666-a20f-0b1ffdc7c917)

**Comment by slonopotamus** [comment]
> "Stay invisible on LAN"

This is just a fancy way to say "we'll inject random rules in your system firewall and break things". Absolutely identical to `block-outside-dns` OpenVPN option.

**Comment by keith-horton** [comment]
Sorry for the DNS issues. We have updated our troubleshooting documentation with Firewall configuration compatibility issues, and a workaround for an OS bug. https://github.com/MicrosoftDocs/WSL/blob/main/WSL/troubleshooting.md#troubleshooting-dns-in-wsl

It has suggestions for various VPNs as well.

**Comment by j0nimost** [comment]
@keith-horton I followed this example and it didn't work for me. I'm running Windows 11 version 23H2 and my trouble started with the update `KB5033375`

**Comment by bpohoriletz** [comment]
if none of above worked for you check if DNS resolution works with TCP with
`dig +tcp google.com`
if it does - follow [this answer](https://serverfault.com/questions/762003/how-to-configure-linux-to-use-tcp-for-dns-queries) to force DNS via TCP and see if it solved the issue with 
`ping google.com`. Use `ping` not `dig` since `dig` ignores options

**Comment by SupahFox** [comment]
I'm having the same issue
These are my logs [WslLogs-2024-01-31_12-05-41.zip](https://github.com/microsoft/WSL/files/14113419/WslLogs-2024-01-31_12-05-41.zip)

WSL version: 2.0.14.0
Kernel version: 5.15.133.1-1

**Comment by asunekants** [comment]
> These new networking features are now available on the latest version of Win11 22H2!
> 
> @matkozak this work is currently not planned to go back to Win10.
> 
> Please make sure you're on the latest build to get these features, you can do that by clicking "Check for Updates" in Windows settings. You can check you have the right build by either ensuring you have [KB5031354](https://support.microsoft.com/en-us/topic/october-10-2023-kb5031354-os-build-22621-2428-ecc07685-218f-4ba9-b3c8-fe2e35059aec) installed, or run `cmd.exe /c ver` and ensure that your build number is 22621.2428 or higher (Including the minor build number which is after the `.` as this was a backport!)

Is it at all possible to reconsider this decision?
I'm struggling with this issue in a corporate environment that at the moment is restricted to Windows 10 for a regulatory reason that I don't quite understand, and having this on Windows 10 would make my life a lot easier;
I'm certain that I'm not alone in that.

Thank you very much!

**Comment by gtedavid** [comment]
Hi, I don't know if this helps on this issue, because it seems to be happening to quite a few people and I wanted to avoid opening an issue just for this, as I have found a temporary workaround.

https://gist.github.com/coltenkrauter/608cfe02319ce60facd76373249b8ca6?permalink_comment_id=5017885#gistcomment-5017885
I unfortunately don't know what was the configuration of  `/etc/resolve.conf` before the issue appeared

I may have a VPN (paid licence), but it isn't used that often.

**Comment by TylerCHodges** [comment]
Do we yet know what exactly is causing this issue? Is it a specific version of WSL2 or is in ALL WSL2 versions? Why does WSL1 work and 2 does not?

**Comment by BtbN** [comment]
On 07/06/2024 15:35, TylerCHodges wrote:
> Do we yet know what exactly is causing this issue? Is it a specific 
> version of WSL2 or is in ALL WSL2 versions? Why does WSL1 work and 2 
> does not?

It's been explained in this issue countless times now.
WSL2 is a VM, with its own networking. So if you employ some kind of 
Firewall or "Security Solution" that blocks incoming network traffic, 
including the VMs DNS queries, it breaks.

WSL1 is not a VM, so it conceptually does not have the issue.

It's also long been solved with host mode networking and some of the 
other related new features that are graduating from experimental-mode now.
So there is no reason to use WSL1 (which on top of that, also does not 
work properly anymore with modern Distros).

**Comment by jabbera** [comment]
@TylerCHodges upgrading to 2.2.1 and making sure resolve.conf was automatically generated fixed my issues.

**Comment by hahearn73** [comment]
> downgrade your wsl to version 1 .. wsl --set-version 1

This solved my issue. Company firewall blocked wsl2 but not wsl1

**Comment by levzlotnik** [comment]
Hi, I'm having issues with connecting from WSL2 to a machine on my LAN. No VPN involved.

Things I've tried:
- Manually editing `/etc/resolv.conf`
- Editing `%USERPROFILE%\.wslconfig` and adding/removing iteratively all the following flags:
    * `wsl2.dnsTunneling=true` 
    * `experimental.networkingMode=mirrored`
    * `experimental.bestEffortDnsParsing=true`

Notes:
- My *Windows* SSH (or pinging) has no issues connecting to the same machine on LAN. 
- From within WSL2, I am able to connect to the same local machine via its LAN IP address. 

It's not a deal breaker for me since I still can connect to the local machine through something like VSCode but I'd still prefer being able to SSH to that machine from WSL2 as well.

**Comment by slonopotamus** [comment]
> This appeared suddenly today, last time I tried (a few weeks ago) it had no such issues.

So just undo any changes you did to your setup during these few weeks.

**Comment by levzlotnik** [comment]
> > This appeared suddenly today, last time I tried (a few weeks ago) it had no such issues.
> 
> So just undo any changes you did to your setup during these few weeks.

I hadn't made any changes myself, I assume the changes came from some automatic updates to Windows settings. So I don't really know what changed.
It's not really a big deal for me as I can still connect through Windows' SSH. I just reported that this was an issue for me that's related to this thread.

**Comment by danielfdickinson** [comment]
This is just an FYI, I have worked around the issues and have things working (latest Windows 11 normal--non-insiders--channel).

1. With `dnsTunneling=true` (or not set as this is the default) in both NAT and mirrored network modes, `nslookup github.com` only succeeds for the first of the three queries it makes.
   * I suspect this is due to having DoH enabled on all my networks in the Windows host networking.
2. In order to disable dnsTuneling for mirrored network mode, one has to first set
```ini
networkMode=NAT
dnsTunneling=false
```
   then do a `wsl --shutdown`, start wsl, and shut it down again, then set
```ini
networkMode=mirrored
dnsTunneling=false
```
   Then the next time you start wsl the `10.255.255.254` address on the loopback will no longer be there. If you just skip to the `dnsTunneling=false` and `networkMode=mirrored` in one step the dns tunneling remains active and the `10.255.255.254` address is still present.

HTH

**Comment by OscBacon** [comment]
Hey, I also run into issues when using mirrored mode (dnsTunneling set to true or false), and switch wifi connections.
So far, seems like the only fix is to stick to NAT mode?
@danielfdickinson tried switching off dnsTunneling in two steps, but no luck

**Comment by djordje47** [comment]
Hi everyone, I've read all the comments briefly, so don't hate me if I miss something. I had a DNS problem with the local projects not being able to be resolved with the fake domain name. 

So, in a nutshell, I have the following env. 

WSL2 & LAMP stack on it. Then on Windows, I modify the hosts file like so:
`::1             shipment.development localhost`

It was working until some update, but then it stopped.

My temporary solution is the following:

1. Get the IP address of the wsl when I start it with this command:  `ip addr show eth0 | grep inet`
2. Then I modify my hosts file on Windows like this: `<the_wsl_ip_address>	shipment.development`

This works for me now, but if you have some other solution, I am all ears. By the way strange thing the previous hosts file modification works with some VPN enabled, but why, I don't know.

I didn't have time to check it more thoroughly, but when I get the chance, I will. 

Hope this helps someone, cheers!

**Comment by anudeepx** [comment]
WSL2: Temporary failure in name resolution even after setting static DNS and disabling `generateResolvConf`

### What I’ve tried
- Set static DNS manually (`8.8.8.8` and Windows gateway)
- Disabled auto-generation of resolv.conf
- Flushed DNS and reset Winsock
- Rebooted multiple times

### Results
- `ping 8.8.8.8` → works
- `ping google.com` → fails
- `/etc/resolv.conf` is correct but ignored by WSL
- `.wslconfig` triggers: `Unknown key 'network.generateResolvConf' in C:\Users\avula\.wslconfig`

**Comment by onomatopellan** [comment]
@0x4nud33p beware generateResolvConf is something you add to `/etc/wsl.conf` in the distro and not in .wslconfig. Also [you shouldn't disable it](https://learn.microsoft.com/en-us/windows/wsl/troubleshooting#networking-considerations-with-dns-tunneling:~:text=In%20order%20for%20DNS%20tunneling%20to%20be%20succesfully%20enabled%2C%20the%20generateResolvConf%20option%20in%20the%20wsl.conf%20file%20should%20not%20be%20disabled.) if you are in Windows 11 and using DNS tunneling.

If you really need to configure `.wslconfig` I recommend the "WSL Settings" app that comes with latest version of WSL.

**Comment by anudeepx** [comment]
Fresh WSL install but can’t reach the internet, even though Windows networking works fine. I can ping from Windows successfully, but inside WSL all packets are lost.
```
PS C:\WINDOWS\system32> wsl --version
WSL version: 2.6.1.0
Kernel version: 6.6.87.2-1
WSLg version: 1.0.66
MSRDC version: 1.2.6353
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26200.6899

PS C:\WINDOWS\system32> wsl
anudeep@AsusVivobook16x:/mnt/c/WINDOWS/system32$ ping google.com
PING google.com (142.251.222.174) 56(84) bytes of data.
^C
--- google.com ping statistics ---
24 packets transmitted, 0 received, 100% packet loss, time 23548ms

anudeep@AsusVivobook16x:/mnt/c/WINDOWS/system32$ exit
logout

PS C:\WINDOWS\system32> ping google.com

Pinging google.com [2404:6800:4002:80e::200e] with 32 bytes of data:
Reply from 2404:6800:4002:80e::200e: time=75ms
Reply from 2404:6800:4002:80e::200e: time=75ms
Reply from 2404:6800:4002:80e::200e: time=78ms
Reply from 2404:6800:4002:80e::200e: time=84ms

Ping statistics for 2404:6800:4002:80e::200e:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 75ms, Maximum = 84ms, Average = 78ms
```

> [@0x4nud33p](https://github.com/0x4nud33p) beware generateResolvConf is something you add to `/etc/wsl.conf` in the distro and not in .wslconfig. Also [you shouldn't disable it](https://learn.microsoft.com/en-us/windows/wsl/troubleshooting#networking-considerations-with-dns-tunneling:~:text=In%20order%20for%20DNS%20tunneling%20to%20be%20succesfully%20enabled%2C%20the%20generateResolvConf%20option%20in%20the%20wsl.conf%20file%20should%20not%20be%20disabled.) if you are in Windows 11 and using DNS tunneling.
> 
> If you really need to configure `.wslconfig` I recommend the "WSL Settings" app that comes with latest version of WSL.

**Comment by onomatopellan** [comment]
@0x4nud33p I see you have prioritized IPv6 on Windows. Inside WSL, does something like `ping 142.251.222.174` work? What's the output for `ifconfig`?


I need you to go to Start menu and open the app "WSL Settings". In the Networking section make sure your networking mode is "Mirrored", you have enabled DNS tunneling and optionally DNS best effort parsing.
Remember to restart WSL with `wsl.exe --shutdown` to see the changes.

**Comment by anudeepx** [comment]
> ping 142.251.222.174

@onomatopellan 

- ping 142.251.222.174 hangs!
```bash
PS C:\Users\avula> wsl
anudeep@AsusVivobook16x:/mnt/c/Users/avula$ ping 142.251.222.174
PING 142.251.222.174 (142.251.222.174) 56(84) bytes of data.
```
- output of ipconfig:
```bash
PS C:\Users\avula> ipconfig

Windows IP Configuration


Unknown adapter McAfee VPN:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Wireless LAN adapter Local Area Connection* 1:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Wireless LAN adapter Local Area Connection* 2:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Wireless LAN adapter Wi-Fi:

   Connection-specific DNS Suffix  . :
   IPv6 Address. . . . . . . . . . . : 2409:40f0:dc:1ce6:b33c:17ec:4a8b:fe81
   Temporary IPv6 Address. . . . . . : 2409:40f0:dc:1ce6:4c20:b5ba:4082:6c75
   Link-local IPv6 Address . . . . . : fe80::c8da:3c9b:7a0c:160%8
   Autoconfiguration IPv4 Address. . : 169.254.120.29
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . . . . . : fe80::d82a:2aff:fe82:f462%8

Ethernet adapter vEthernet (WSL (Hyper-V firewall)):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::6cfd:c0f9:980a:a4f0%42
   IPv4 Address. . . . . . . . . . . : 172.22.128.1
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :
PS C:\Users\avula>
```
- edited /etc/wsl.conf to: 
```
[network]
generateResolvConf = false
```
- output: 
```bash
anudeep@AsusVivobook16x:/mnt/c/WINDOWS/SystemApps/MicrosoftWindows.Client.CBS_cw5n1h2txyewy$ sudo nano /etc/wsl.conf
[sudo] password for anudeep:
anudeep@AsusVivobook16x:/mnt/c/WINDOWS/SystemApps/MicrosoftWindows.Client.CBS_cw5n1h2txyewy$ sudo nano /etc/wsl.conf
anudeep@AsusVivobook16x:/mnt/c/WINDOWS/SystemApps/MicrosoftWindows.Client.CBS_cw5n1h2txyewy$ sudo rm /etc/resolv.conf
echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
nameserver 8.8.8.8
```
- even after trying all commands: 
```bash
PS C:\Users\avula> wsl.exe --shutdown
PS C:\Users\avula> ping google.com

Pinging google.com [2404:6800:4007:833::200e] with 32 bytes of data:
Reply from 2404:6800:4007:833::200e: time=40ms
Reply from 2404:6800:4007:833::200e: time=48ms
Reply from 2404:6800:4007:833::200e: time=39ms
Reply from 2404:6800:4007:833::200e: time=261ms

Ping statistics for 2404:6800:4007:833::200e:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 39ms, Maximum = 261ms, Average = 97ms
PS C:\Users\avula> wsl
wsl: Invalid boolean value 'fasle' for key 'network.generateResolvConf' in /etc/wsl.conf:2
anudeep@AsusVivobook16x:/mnt/c/Users/avula$ ping google.com
PING google.com (172.217.24.238) 56(84) bytes of data.
^X^C
--- google.com ping statistics ---
60 packets transmitted, 0 received, 100% packet loss, time 60420ms

anudeep@AsusVivobook16x:/mnt/c/Users/avula$
```
I do not have the “WSL Settings” app on my system I cannot access networking options through that app.

> [@0x4nud33p](https://github.com/0x4nud33p) I see you have prioritized IPv6 on Windows. Inside WSL, does something like `ping 142.251.222.174` work? What's the output for `ifconfig`?
> 
> I need you to go to Start menu and open the app "WSL Settings". In the Networking section make sure your networking mode is "Mirrored", you have enabled DNS tunneling and optionally DNS best effort parsing. Remember to restart WSL with `wsl.exe --shutdown` to see the changes.

**Comment by onomatopellan** [comment]
@0x4nud33p You can get the networking mode from inside WSL with `wslinfo --networking-mode`. Is it `mirrored`?

**Comment by anudeepx** [comment]
> [@0x4nud33p](https://github.com/0x4nud33p) You can get the networking mode from inside WSL with `wslinfo --networking-mode`. Is it `mirrored`?
@onomatopellan 
```bash
anudeep@AsusVivobook16x:/mnt/c/Users/avula$ wslinfo --networking-mode
nat
```
It shows my WSL instance is using the default NAT networking mode, not mirrored.  
I don’t have the “WSL Settings” app available on my system to change this mode through the UI.

**Comment by onomatopellan** [comment]
@0x4nud33p It's weird. it should be in `C:\Program Files\WSL\wslsettings\`

Anyway you need mirrored networking. In Windows 11 edit the `.wslconfig` file in the Users folder with this content:
```
[wsl2]
networkingMode=Mirrored
````

Then `wsl.exe --shutdown` and try again.

**Comment by anudeepx** [comment]
It worked. Appreciate the guidance @onomatopellan
