### ISSUE TITLE
WSL complete freeze

### ISSUE THREAD

**Issue by schiorean** [microsoft/WSL#8824]
### Version

Microsoft Windows [Version 10.0.22000.918]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.57.1

### Distro Version

Ubuntu 22.04

### Other Software

PhpStorm 2022.2.1

### Repro Steps

1. Open a large project in PhpStorm (starts indexing project fileds...)
2. Open another large project in PhpStorm (starts indexing project fileds...)
3. Keep switching between large projects and sooner or later WSL is completely frozen while PhpStorm is indexing files

### Expected Behavior

PhpStorm finishes files indexing and WSL is usable.

### Actual Behavior

WSL freezes completely including any `wsl.exe` command, so even `wsl.exe --shutdown` will hang forever. The only way to restart WSL is by doing a computer restart. 

### Diagnostic Logs

Uploading via Feedback Hub.

**Comment by schiorean** [comment]
Here is the Feedback Hub WLS logs https://aka.ms/AAi265d

**Comment by OneBlue** [comment]
Thanks for reporting this @schiorean. Unfortunately I'm not seeing any logs on Feedback Hub. Can you share logs here ?

**Comment by schiorean** [comment]
@OneBlue here's the log. Many thanks!

[WslLogs-2022-09-13_14-38-49.zip](https://github.com/microsoft/WSL/files/9559719/WslLogs-2022-09-13_14-38-49.zip)

**Comment by OneBlue** [comment]
Thank you @schiorean. I'm not seeing anything that jumps out in the logs.

This looks like 'freeze' issue we've been investigating for a while.

If you can reproduce this consistently, can you please: 

- First clear everything by running wsl --shutdown (make sure nothing is running). If this is unresponsive, kill wslservice.exe.
- Open a shell inside your the system distro (and leave it open) via: wsl --u root --system
- Install gdb in that shell via: Ashis Chatterjee <aschatterjee@microsoft.com>
- Run the steps you described to get WSL into that "frozen" state in your regular distro  (not inside the system distro)
- Once WSL is frozen, use the previously opened shell to dump all the 'init' processes via: `gcore -a $(pgrep init)`
- This will generate a few `core.*` files, please shares those on this issue
- Also please share a dump of wslservice.exe (you can do this via task manager, in the 'details' tab, right click on wslservice.exe, then 'Create dump file')
- Also please share the output of `dmesg` in the system shell


This should give us enough information to understand what's happening

**Comment by schiorean** [comment]
Hi @OneBlue,

I reproduced it again, but I don't have the gcore output because I can't figure out how to install gdb in the system shell (none of the usual commands are recognized e.g. trying `apt install gdb` I get `-bash: apt: command not found`). So until I can install gdb in the system shell (I sent an email to Ashis Chatterjee [aschatterjee@microsoft.com](mailto:aschatterjee@microsoft.com)) I am sharing here the output of `dmesg` and `wslservice` service dump.

Some extra notes, maybe it's helping:

1. Even though `wsl.exe` is frozen the currently open shells are still usable (btw, can't I install gdb in the normal, non-system, shell and provide the dump from there?)
2. The only way to restart WSL besides a full computer restart, is by opening a terminal as Administrator, then run `hcsdiag list` followed by `hcsdiag kill`.

I tried to upload the zip file containing the dumps here, but looks like File size is too big. I uploaded again in Feedback Hub https://aka.ms/AAi265d however when I open Details I can't see it... If you can't see it in Feedback Hub please tell me where to send the file?

**Comment by OneBlue** [comment]
Oh sorry @schiorean, that was a missed copy-paste from me.

What I meant was:
"Install gdb in that shell via `tdnf install gdb`"

But there was an unrelated email address in my clipboard (edited out). Sorry about that.

Can you try that and share the Linux dumps ? It should be possible to upload them directly on this issue.

**Comment by schiorean** [comment]
@OneBlue 
I uploaded `dmesg` output, wslservice.exe dump is too big (> 25MB) and can't upload it here.
[dmesg.txt](https://github.com/microsoft/WSL/files/9563497/dmesg.txt)

Later today I hope will provide the `dbg` dump too.

**Comment by OneBlue** [comment]
Thank you @schiorean. Sadly nothing jumps out from dmesg so we'll need the dumps to root cause this.

If the dumps are too big for Github, OneDrive / Google drive should work.
Given the symptoms I'm suspecting that the issue is on the Linux side, so the Linux dumps should be the most interesting files for this issue.

**Comment by sinetek** [comment]
Hi, I am also getting random freezes like that.

**Comment by sypaq-nexton** [comment]
We've hit a similar issue here. I can't reliably reproduce it, but I do have a workaround that fixes our specific problem. In our case:
* We have a CI build that is running inside WSL.
* If Windows Defender starts scanning the build folder, WSL will freeze (as per @schiorean's description).
* If we exclude the build folder from Windows Defender, we don't see this behaviour.

As I said, I can't reliably reproduce this issue, but it _seems_ to happen most often when a file is deleted in WSL (it seems to occur more frequently in the `clean` stage of our build).

**Comment by ZedG2** [comment]
There is another way to restore WSL usable.
1. win+s Search WSL 
2. right-click, "App Settings (应用设置 in my localized)"
3. then click "reset".

**Comment by schiorean** [comment]
> If we exclude the build folder from Windows Defender, we don't see this behaviour.
@sypaq-nexton Unofrtunately, I have the WSL home folder added in "Virus & threat protection" exclusions for many months already, so it's not a solution (for me at least).

**Comment by OneBlue** [comment]
Thanks a lot for the dumps @schiorean.

We've published [a new version of store wsl](https://github.com/microsoft/WSL/releases/tag/0.67.6), if you can still reproduce the issue with the latest version, can you please share the Windows and Linux dumps of the same repro? 

That would help us a lot

**Comment by schiorean** [comment]
@OneBlue `wsl --update` says I'm already at the latest version intalled (0.66.2.0).

**Comment by OneBlue** [comment]
If you're not enrolled in Windows insider, that makes sense since we haven't published that package everywhere yet. 

You can install it without an insider account by downloading [the package](https://github.com/microsoft/WSL/releases/download/0.67.6/Microsoft.WSL_0.67.6.0_x64_ARM64.msixbundle)  and running something like (elevated PowerShell) :

```
$installedPackage = Get-AppxPackage MicrosoftCorporationII.WindowsSubsystemforLinux -AllUsers
Remove-AppxPackage $installedPackage -AllUsers
Add-AppxPackage /path/to/msixbundle
```

**Comment by schiorean** [comment]
Actually here's the wslservice.exe dump as well https://drive.google.com/file/d/19nPGc6-NOpv_f0RSp8-5kgRwW1Y-1y5n

**Comment by OneBlue** [comment]
Thanks @schiorean.

After looking at all the dumps, I have a good idea of where the issue is, but I'll need a bit more info to root cause it.

I built a private version of the package with extra logging: https://1drv.ms/u/s!AiWXuqXSX5K2d45U1MHyOchps0k?e=w8SSjC 
To install it (elevated powershell):

```
# Remove the installed package
$installedPackage = Get-AppxPackage MicrosoftCorporationII.WindowsSubsystemforLinux -AllUsers
Remove-AppxPackage $installedPackage -AllUsers

# Trust the private package's certificate (since it's not an official build, it's not signed with the official Microsoft certificate)
(Get-AuthenticodeSignature "/path/to/msixbundle").SignerCertificate | Export-Certificate -FilePath private-wsl.cert
Import-Certificate -FilePath .\private-wsl.cert -CertStoreLocation Cert:\LocalMachine\Root

# Install the package
Add-AppxPackage /path/to/msixbundle
```

Once the package is installed:

- before doing anything please start the log collection with `collect-wsl-logs.ps1`
- Open a shell inside your the system distro (and leave it open) via: wsl --u root --system
- Reproduce the hang
- Inside the system distro shell, run: `ss -lap --vsock`, `ls -la /proc/*/fd`  and `dmesg` and share the output of the three commands
- Dump wslservice.exe

This should give us more information to identify what's happening.

**Comment by schiorean** [comment]
@OneBlue attached are the logs are per your latest instructions. wslservice.exe dump uploaded separately here https://drive.google.com/file/d/19nPGc6-NOpv_f0RSp8-5kgRwW1Y-1y5n/view?usp=sharing

[WslLogs-2022-09-26_11-09-22.zip](https://github.com/microsoft/WSL/files/9646057/WslLogs-2022-09-26_11-09-22.zip)
[dmesg.txt](https://github.com/microsoft/WSL/files/9646059/dmesg.txt)
[proc.txt](https://github.com/microsoft/WSL/files/9646060/proc.txt)
[vsoc.txt](https://github.com/microsoft/WSL/files/9646061/vsoc.txt)

**Comment by OneBlue** [comment]
Thank you @schiorean.

With this information, our current theory is that this issue was introduced by the latest Linux kernel upgrade.

To validate this, can you please:

- Download the previous 5.10 kernel: https://1drv.ms/u/s!AiWXuqXSX5K2eGpAFOyDE9DjUEI?e=Zbe8Lf 
- Force wsl to use this kernel by adding this entry in `%userprofile%/.wslconfig: `
```
[wsl2]
kernel=C:\\path\\to\\kernel-5-10
```

(Make sure that the '\\' are doubled)

- Then shutdown wsl via: `wsl.exe --shutdown`
- Run: `wsl uname -a` to make sure that the correct kernel is in use. It should say: `Linux [hostname] 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Then try to reproduce the issue (please share dmesg output if you can reproduce again with this kernel)

**Comment by schiorean** [comment]
@OneBlue sorry but it happened again with the 5.10 kernel as well. Attached is the dmesg, I didn't have the system console started but was able to get it from normal console.
Let me know if I can do anything else to help you guys. This is really frustrating and I really don't want to leave Windows, it's perfect for my development besides this thing. 

[dmesg.log](https://github.com/microsoft/WSL/files/9654287/dmesg.log)

**Comment by michaelarnauts** [comment]
I have the same problem as OP. Same usecase (Phpstorm that causes WSL to hang during indexing, or probably, anything that does high IO). It happens multiple times a day, and I can reproduce this quite easily.

A faster way to get a fresh WSL env without rebooting (since the `wsl --shutdown` indeed hangs forever) is to kill `wslservice.exe` from the task manager.

The output of `collect-wsl-logs.ps1` is here:
[WslLogs-2022-09-28_14-05-40.zip](https://github.com/microsoft/WSL/files/9664743/WslLogs-2022-09-28_14-05-40.zip)


`wsl --version`:
```
WSL version: 0.66.2.0
Kernel version: 5.15.57.1
WSLg version: 1.0.42
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.1042
```

I'll try the "unpublished" package above and retry.

**Comment by michaelarnauts** [comment]
@OneBlue I've managed to reproduce it again. I've used your build of wsl.

```
wsl --version
WSL version: 0.67.7.9
Kernel version: 5.15.62.1
WSLg version: 1.0.44
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.1042
MSBuild version: 1929
Commit: 6732c637
Build time: 22:50:36 Sep 23 2022
```

collect-wsl-logs.ps1 output:
[WslLogs-2022-09-28_14-45-44.zip](https://github.com/microsoft/WSL/files/9665181/WslLogs-2022-09-28_14-45-44.zip)

the 3 commands from the system distro shell:
[logs.txt](https://github.com/microsoft/WSL/files/9665182/logs.txt) 

And the wslservice.exe coredump:
https://1drv.ms/u/s!ArytPhqDXQ94lAIJ85S-_XFeCtJ-?e=VL5rb9

**Comment by michaelarnauts** [comment]
@OneBlue This still crashes daily here. Anything else I can do to help troubleshoot this?

**Comment by szymonos** [comment]
Update to 0.68.4 hasn't fixed the issue. Still hanging for me and have to restart wslservice every now and then to be able to work.
```
WSL version: 0.68.4.0
Kernel version: 5.15.68.1
WSLg version: 1.0.44
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22623.730
```

**Comment by OneBlue** [comment]
Thank you @schiorean. 

The fact that you managed to reproduce the issue with a different kernel shows that it's not a recent kernel upgrade issue at least.

To give a bit of context what seems to be happened is that the init process is stuck during a syscall while creating a new session.
To understand why, we'll need to look at the kernel stacks.

So do this, can you please: 

* First clear everything by running wsl --shutdown (make sure nothing is running). If this is unresponsive, kill wslservice.exe.

* Then (if not already done) upgrade to wsl 0.68.4 by running: `wsl --update` and undo the changes to .wslconfig (meaning revert to the official kernel)

* Open a shell inside your the system distro (and leave it open) via: `wsl --u root --system`

* Install gdb in that shell via: `tdnf install gdb` (You'll need to do it again because the system distro is not saved between reboots)

* Run the steps you described to get WSL into that "frozen" state in your regular distro (not inside the system distro)

* Once WSL is frozen, use the previously opened shell to dump all the 'init' processes via: `gcore -a $(pgrep init)`
This will generate a few core.* files, please shares those on this issue

* Then please share the output of  (Still in the system shell) ` for pid in $(pgrep init) ; do echo -e "\nProcess: $pid" && for tid in $(ls "/proc/$pid/task") ; do echo "tid: $tid" && cat "/proc/$pid/task/$tid/stack" ; done   ; done` 

* Also please share the output of dmesg in the system shell


With this we should have the kernel stacks of all the threads in the init processes

**Comment by alonbl** [comment]
Hi,

Do you have KB5017328 installed on your system? If yes, is the problem reproduced after revert of KB5017328?
See #6982, the KB5017328 caused a regression that seems similar and is related to hibernate or similar activity, but confirmed that without KB5017328 it does not manifest.

Regards,

**Comment by schiorean** [comment]
@OneBlue attached are the new log files.
[core.zip](https://github.com/microsoft/WSL/files/9764256/core.zip)
[dmesg.txt](https://github.com/microsoft/WSL/files/9764259/dmesg.txt)
[for_pid_output.txt](https://github.com/microsoft/WSL/files/9764260/for_pid_output.txt)
[meminfo.txt](https://github.com/microsoft/WSL/files/9764261/meminfo.txt)

**Comment by michaelarnauts** [comment]
@OneBlue 

```
> wsl --version
WSL version: 0.68.4.0
Kernel version: 5.15.68.1
WSLg version: 1.0.44
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.674
```

[core.zip](https://github.com/microsoft/WSL/files/9794013/core.zip) (all coredumps)
[wsl dump.txt](https://github.com/microsoft/WSL/files/9794014/wsl.dump.txt) (all terminal output)

**Comment by szymonos** [comment]
I've fixed it for myself by unregistering all my WSL distros, removing WSL from Windows Optional Features, adding it again, and creating new WSL distros from scratch.

I believe, that simply recreating WSL distros from scratch would solve my issue, because I think my WSL distros (Debian and fedoraremix) were broken somehow. I exported them before unregistering, but couldn't import them after the process - installation was stuck, but no errors whatsoever.
In the end, I've just copied my home folder from exported tars, so there is no issue there, I didn't plan to use them anyway.

**Comment by OneBlue** [comment]
Thanks a lot @michaelarnauts and @schiorean. With the debugging information you shared we have identified the root cause.

The issue is a [bug in MUSL](https://www.openwall.com/lists/musl/2022/10/06/2) which causes a deadlock in `init`.

This bug only occurs if fork() and aio_* methods are called at the same time AND if malloc() needs to increase the process' memory, so it's pretty rare.

The issue has been reported to the MUSL maintainers, but a fix hasn't been released yet. In the meantime we're working on a workaround inside WSL to avoid the potential deadlock. 

I'll update this issue once the workaround will be released.

**Comment by mwoodpatrick** [comment]
I'm running with

WSL version: 0.70.4.0
Kernel version: 5.15.68.1
WSLg version: 1.0.45
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22623.870

and am still having this issue I ran 

`gcore -a $(pgrep init)`

and got:


```
[New LWP 5]
0x00000000003bc9bd in ?? ()
Failed to open 'core.1' for output.
[Inferior 1 (process 1) detached]
gcore: failed to create core.1

```

Please advise

Are there docs on gcore somewhere? What does the -a option do?

All the help does currently is

```
gcore --help
usage:  gcore [-a] [-o prefix] pid1 [pid2...pidN]
```

It would be helpful if this described what the command did and how the -a option modifies the default action

**Comment by OneBlue** [comment]
@mwoodpatrick: It looks like you were in a directory where gcore wasn't allowed to write. If you need to write dumps I recommend doing it in a directory under `/mnt/c` so you can easily access them from Windows.

**Comment by mwoodpatrick** [comment]
Why was this issue closed I'm still having this issue? Please reopen it.

gcore -a $(pgrep init)
[New LWP 5]
0x00000000003bc9cd in ?? ()
Saved corefile core.1
[Inferior 1 (process 1) detached]
[New LWP 28]
warning: Target and debugger are in different PID namespaces; thread lists and other data are likely unreliable.  Connect to gdbserver inside the container.
0x00000000003bc9cd in ?? ()
Saved corefile core.2
[Inferior 1 (process 2) detached]
0x00000000003bc9cd in ?? ()
Saved corefile core.6
[Inferior 1 (process 6) detached]
[New LWP 27]
warning: Target and debugger are in different PID namespaces; thread lists and other data are likely unreliable.  Connect to gdbserver inside the container.
0x00000000003bc9cd in ?? ()
warning: target file /proc/26/cmdline contained unexpected null characters
Saved corefile core.26
[Inferior 1 (process 26) detached]
0x00000000003bc9cd in ?? ()
Saved corefile core.31
[Inferior 1 (process 31) detached]
0x00000000003bc9cd in ?? ()
Saved corefile core.32
[Inferior 1 (process 32) detached]
root@MarkSpectre14 [ /mnt/c/Users/mlwp/Software/WSL/10_29_2022 ]# ls
core.1  core.2  core.26  core.31  core.32  core.6

[wsl_hang.zip](https://github.com/microsoft/WSL/files/9893475/wsl_hang.zip)

**Comment by schiorean** [comment]
Since I upgraded to 0.70.4 I didn't experience any freeze. All good for me.

**Comment by evakili** [comment]
I see the problem even after updating to 0.70.4.

<details>
<summary>Version Info</summary>

- WSL version: 0.70.4.0
- Kernel version: 5.15.68.1
- WSLg version: 1.0.45
- MSRDC version: 1.2.3575
- Direct3D version: 1.606.4
- DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp

</details>

**Comment by NotTheDr01ds** [comment]
@evakili  and @mwoodpatrick  Since the person who originally reported this issue has confirmed that it is fixed, it seems that you are likely experiencing a different issue.

**Comment by hwine** [comment]
There are a number of us who still have the issue (but I, e.g., don't have good data to post). If anyone does open a new issue, please be sure to mention it here, so us "camp followers" can watch that as well. :smile:

**Comment by androiddisk** [comment]
I have the same problem. No new wsl shell window can be created, and the wsl -- shutdown window is stuck. Even the window cannot be closed.  Version 0.70.4.0 is not downloaded from GitHub. It is the 0.70.4.0 version automatically updated by Windows. It should be the same as GitHub https://github.com/microsoft/WSL/releases/tag/0.70.4
This problem has troubled me for a long time.




```
PS C:\Users\zhong> wsl --version
WSL 版本： 0.70.4.0
内核版本： 5.15.68.1
WSLg 版本： 1.0.45
MSRDC 版本： 1.2.3575
Direct3D 版本： 1.606.4
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows版本： 10.0.22621.674
```


I will cooperate with you if you need me. thank you

**Comment by XhmikosR** [comment]
Unfortunately, this is definitely an issue for me too. I confirmed it on 2 different machines, and it makes WSL totally unusable. `wsl --shutdown` doesn't work either, so the only solution is to kill `wslservice` but it's not a real workaround since VS Code is stuck too...

```
C:\Users\user>wsl --version
WSL version: 0.70.4.0
Kernel version: 5.15.68.1
WSLg version: 1.0.45
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.819
```

**Comment by bowmanjd** [comment]
I, too, had this issue for some time. I got in the habit of closing all WSL windows at the end of the day, and this seemed to help. But I would still occasionally have freezing issues even after installing the fixed WSL version.

So... last week in a terrible and painful mistake, I deleted my WSL virtual disk for the distro I use the most. Since re-creating it, I haven't had this issue at all. Go figure. @XhmikosR, I never had the "totally unusable" experience that you had; it was more of a minor inconvenience. But if it is that bad, you may want to consider redoing your WSL distros.

For what it is worth, I moved from Fedora 36 to Fedora 37. Unsure if that is relevant, though.

**Comment by XhmikosR** [comment]
The thing is that the issue just started to appear for me a few weeks ago. Before that, everything worked fine.

Now, using Docker + VS Code, breaks quite frequently during the day. The only workaround for me is stopping and starting `wslservice`, but it breaks my workflow, totally.

I will try reinstalling Ubuntu, but there are other people having this issue, see also #9114.

**Comment by StewartWon** [comment]
I too have been having issues with this. It always occurs when doing a large c++ cmake build (30mins).  WSL freezes. This started happening a couple of months ago and basically makes WSL useless. Seems like compiling in Visual Studio in Windows and compiling in WSL makes it worse, but that may be a coincidence. This happens with multiple fresh Ubuntu installations too.

**Comment by XhmikosR** [comment]
I uninstalled any WSL Windows updates, removed my distro, disabled Virtual Machine Platform and WSL features and then installed everything again including the latest WSL from the store. I also gave WSL 6GB of RAM instead of 4GB that I was using in .wslconfig. Now it seems I'm not hitting the issue anymore.

**Comment by GeksterOne** [comment]
I have the same with 
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.2364

Windows: 19045.2364. Considering to stop using wsl in favour of Linux itsef. If it haven't fixed after an year seems Microsoft spoiled technology and doesn't know what to do.

**Comment by alonbl** [comment]
On Wed, Dec 28, 2022 at 11:37 AM GeksterOne ***@***.***>
wrote:

> Windows version: 10.0.19045.2364
>
I also experienced this in the past, now I have Windows version:
10.0.22621.963 which is working properly, can you please try to update and
see if it helps?

**Comment by GeksterOne** [comment]
Added this. It helped in case where Pychar worked with files stored in normal file system using python enterpreter from WSL. But didn;t help for Pycharm with projects stored in WSL file system. Product still as raw as meat in my fridge.

**Comment by achs0** [comment]
Happens for me, too. WSL freezes completly while consuming 100% CPU. 
Using Docker Desktop with a local k8s in WSL, which is more in standby because i am currently testing stuff in k8s. 
```
WSL-Version: 1.0.3.0
Kernelversion: 5.15.79.1
WSLg-Version: 1.0.47
MSRDC-Version: 1.2.3575
Direct3D-Version: 1.606.4
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows Version: 10.0.19045.2486

Processor	AMD Ryzen 9 5900X 12-Core Processor, 3701 MHz
RAM                64 GB
```

What only helps for me is to kill WSL in Task-Manager and start everything up again. It's annoying.

**Comment by lawndoc** [comment]
> 

Same problem, same versions for everything

**Comment by funduck** [comment]
Windows 11
Dell XPS 9310
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1105

I get freezes every day but cannot tell what exactly causes them. I work in WSL in VScode, so I catch freezes always there, not in windows apps.
I do not use docker.
I tried to collect logs but not sure if there is anything useful since system just freezes and I can't finalize the script for logs. 
https://drive.google.com/file/d/1ooPJDSywR-ogUjRR9_k6CIqACKIpgMsq/view?usp=sharing

**Comment by mungojam** [comment]
see https://github.com/microsoft/WSL/issues/9454#issuecomment-1384062403 for the brute force command to shutdown WSL. Before that I always had to reboot

**Comment by funduck** [comment]
The problem is that whole Windows11 is frozen and I can't do anything except reboot hardware by holding power button for 10 seconds.

**Comment by samd1993** [comment]
wsl.exe --shutdown works for me but I am unable to run anything for a long time on this.
I wonder if people experiencing this are utilizing multiple cores? Seems to happen to me when I run a CPU intensive program (CPU usage going to 100%)

**Comment by GeksterOne** [comment]
After almost half a year since Wsl stopped working and lack of reaction from Microsoft side I think it time to state that Wsl project is dead. It time to move on towards linux/mac systems for development. We stopped using Windows/wsl in our projects

**Comment by samd1993** [comment]
> After almost half a year since Wsl stopped working and lack of reaction from Microsoft side I think it time to state that Wsl project is dead. It time to move on towards linux/mac systems for development. We stopped using Windows/wsl in our projects

Does using Ubuntu on Windows 10 count as this, or did you switch to actual linux machines

**Comment by GeksterOne** [comment]
mostly macs.

сб, 25 мар. 2023 г., 18:10 Samuel Degregori ***@***.***>:

**Comment by schiorean** [comment]
I am the original reporter of this issue and it has been fixed for a while already. WSL is not dead at all, am using it daily at my day job. 
Your problem is a different problem, please open a new issue.

**Comment by andrei-aprodu-22** [comment]
> After almost half a year since Wsl stopped working and lack of reaction from Microsoft side I think it time to state that Wsl project is dead. It time to move on towards linux/mac systems for development. We stopped using Windows/wsl in our projects

Not dead, but pretty jank.

The freezes are probably related to the hybernate/suspend bug #6982 - I haven't had a freeze in days by keeping the machine on. 

Otherwise you have to kill the Wsl process with `taskkill -IM "wslservice.exe" /F` in Powershell, or reboot.

**Comment by andrei-aprodu-22** [comment]
> After almost half a year since Wsl stopped working and lack of reaction from Microsoft side I think it time to state that Wsl project is dead. It time to move on towards linux/mac systems for development. We stopped using Windows/wsl in our projects

Not dead, but pretty jank.

The freezes are probably related to the hybernate/suspend bug #6982 - I haven't had a freeze in days by keeping the machine on. 

Otherwise you have to kill the Wsl process with `taskkill -IM "wslservice.exe" /F` in Powershell, or reboot.

**Comment by andrei-aprodu-22** [comment]
> After almost half a year since Wsl stopped working and lack of reaction from Microsoft side I think it time to state that Wsl project is dead. It time to move on towards linux/mac systems for development. We stopped using Windows/wsl in our projects

Not dead, but pretty jank.

The freezes are probably related to the hybernate/suspend bug #6982 - I haven't had a freeze in days by keeping the machine on. 

Otherwise you have to kill the Wsl process with `taskkill -IM "wslservice.exe" /F` in Powershell, or reboot.

**Comment by aand18** [comment]
> After almost half a year since Wsl stopped working and lack of reaction from Microsoft side I think it time to state that Wsl project is dead. It time to move on towards linux/mac systems for development. We stopped using Windows/wsl in our projects

Not dead, but pretty jank.

The freezes are probably related to the hybernate/suspend bug #6982 - I haven't had a freeze in days by keeping the machine on. 

Otherwise you have to kill the Wsl process with `taskkill -IM "wslservice.exe" /F` in Powershell, or reboot.

**Comment by lawndoc** [comment]
Hey all, I have had this problem for well over a year and I finally solved it for myself. For me the bug was when WSL generates the `/etc/hosts` file inside of the Linux subsystem. The hosts file generator appended a bad control character of some kind after the line that contained my hostname. Removing the character wasn't enough because WSL would regenerate the file, so I had to create `/etc/wsl.conf` and add

```
[network]
generateHosts=false
```

Then removing the bad character fixed it and WSL works as expected.

I don't have this issue on my home computer, so part of me wonders if this issue happens only on domain-joined systems when the hostname line includes a domain computer name. I have no evidence to back this up of course, but I'd be curious to hear from anyone else who this helps whether or not the system with the issue was domain-joined.

**Comment by Appla** [comment]
after upgraded to https://github.com/microsoft/WSL/releases/tag/2.0.12 this issue is gone

**Comment by alonbl** [comment]
I tried and reproduced the issue with 2.0.14 reliability, disconnect from network cause wslg windows disappears, when running wslg application old windows comes back but unresponsive (xfce4-terminal for example).

```
WSL version: 2.0.14.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.2715
```

**Comment by vlinx** [comment]
try

`wsl --update --pre-release`

**Comment by xz-viewray** [comment]
Just updated to wsl 2.0.14.  Will see if the issue has been fixed.
