### ISSUE TITLE
App Store install of WSL on OS 10.0.19044.2251 fails ... documentation claims 10.0.19041 is minimum requirement

### ISSUE THREAD

**Issue by KarlGBrennan** [microsoft/WSL#9186]
### Version

OS version 10.0.19044.2251 

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Not appliciable

### Distro Version

All

### Other Software

Windows store app WSL

### Repro Steps

Install and Open the WSL app using the App store.
Couldn't be more straightforward

### Expected Behavior

Install completes successfully as OS complies with minimum requirements

### Actual Behavior

Application install fails on Store open with error

Windows version 10.0.19044.2251 does not support the packaged version of Windows Subsystem for Linux.
For information please visit https://aka.ms/wslinstall
Press any key to continue...

### Diagnostic Logs

None available error screen shows
Windows version 10.0.19044.2251 does not support the packaged version of Windows Subsystem for Linux.
For information please visit https://aka.ms/wslinstall
Press any key to continue...

You should also have a review of your support ticket 1039973338 and have a talk with your support organisation about the quality of support regarding App Store products. I toured around 3 different support groups last night before being directed back to a link support.microsoft.com/assist ... which doesn't exist ... shocking stuff

**Comment by KarlGBrennan** [comment]
This has already been done KB5003791 is already installed on the system which is the recommended patch number that is compatible with the release 21H2.
Please advise what is causing this issue and how it can be resolved ... thanks
 
Important: Use EKB [KB5003791](https://support.microsoft.com/en-gb/topic/kb5003791-update-to-windows-10-version-21h2-by-using-an-enablement-package-8bc077be-18d7-4aac-81ce-6f6dad2cd384) to update to Windows 10, version 21H2.

This non-security update includes quality improvements. Key changes include:

This build includes all the improvements from the supported Windows 10, version 20H2 editions.

No additional issues were documented for this release.

**Comment by craigloewen-msft** [comment]
Fixed!
https://github.com/MicrosoftDocs/WSL/commit/dfbc876d49f0d050d52da002dbc33ee26778399c

**Comment by cataggar** [comment]
I saw the announcement https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-in-the-microsoft-store-is-now-generally-available-on-windows-10-and-11/ and then tried to update, but got:

> Windows version 10.0.19045.2251 does not support the packaged version of Windows Subsystem for Linux.
For information please visit https://aka.ms/wslinstall
Press any key to continue...

![image](https://user-images.githubusercontent.com/87583576/203449506-8f68fa7c-3aba-40e1-85e3-c70dc420f022.png)

**Comment by jwender** [comment]
> I've updated the docs to be clearer here: [MicrosoftDocs/WSL@dfbc876](https://github.com/MicrosoftDocs/WSL/commit/dfbc876d49f0d050d52da002dbc33ee26778399c)
> 
> This is a temporary issue as right now you need to check for the latest updates to get access to WSL on the Store. Come mid December all Windows devices will get pushed this update, and so the error message is still valid. Thanks for the feedback!

Well, not even the manual install will install the new wsl.exe ...

**Comment by KarlGBrennan** [comment]
1) That is not a solution
2) Even your documentation is incorrect ... The OS that is being used is 10.0.19044.2215 which meets the minimum criteria
3) I can't wait until mid December for a fix. You have invested zero effort in trying to identify a solution to this issue and are showing complete contempt for the user community/Customers of Microsoft through these actions
4) This issue remains unresolved and open ... to be honest, I am appalled by the attitute and peformance of Microsoft regarding this issue

**Comment by KarlGBrennan** [comment]
Hello

Closing this issue without resolving it is an unacceptable practice and artificially inflates Microsoft’s performance metrics. In my view, best practice is that the induvial who opened the issue/bug is the only person that can close the bug, and only should they fail to respond within a reasonable time after the bug fix is released should the group/person responsible close the ticket with an appropriate to say that no response was received.

As to the justification provided regarding the ticket closure, I cannot believe that a professional organisation would use a change in GitHub documentation as a pretext to close a ticket. For a start the documentation is still incorrect as the OS meets minimum requirements and the app still does not work. Additionally, the main documentation associated with the app in the app store remains unchanged and therefore is misleading.

Finally, I am asking you to remove the closed tag on this item and I will close it once you have released a patch that I have tested and validated

Regards

Karl Brennan

**Comment by kyanha** [comment]
@KarlGBrennan 

Go to https://www.catalog.update.microsoft.com/Search.aspx?q=kb5020030 and download the version of the preview KB hotfix that is appropriate to your machine (x64 or AMD64, which is a concern here because Intel and AMD diverged on their hypervisor security technologies). Install it and reboot.

**Comment by hybrdthry911** [comment]
@kyanha Thanks. I was also on 10.0.19044.2251 and installed this manually and it finally properly install the store version with the --mount features in windows 10.

**Comment by cataggar** [comment]
Thanks @kyanha! I downloaded and installed that KB hotfix. After rebooting, it looks like I'm in business.

```
PS C:\Users\cataggar> wsl --version
WSL version: 1.0.0.0
Kernel version: 5.15.74.2
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.2311
```

The Microsoft Store app shows that it is installed:

![image](https://user-images.githubusercontent.com/87583576/204415036-d8ba07a8-c0ce-4aff-9c0d-03eb8811b250.png)

**Comment by kyanha** [comment]
Hey, @craigloewen-msft? The 'fix' you pushed to the WSL documentation is wrong and does not solve the issue -- or, if it's not wrong, the "install manually" section is wrong, and does not solve the issue.

On a non-Insider, retail track Windows 10 installation (up to and including 21H2), the store version will not install, because KB5020030 is prerequisite. The problem is that KB5020030 is currently in Preview, available only to Insiders unless it's installed directly from the Update Catalog. I'm given to understand that it is going to be pushed to everyone on December's Patch Tuesday, so this should be a temporary state.

But you really need to fix the Install Manually section to explain the KB prerequisite. (I am on 21H2 and was actually offered it on the Store without KB5020030 installed. When I installed it, my already-existing WSL setup stopped working entirely.)

**Comment by kyanha** [comment]
KB5020030 is the update to 22H2, btw. So it's much more appropriate to say that the Store version of WSL requires Windows 10 22H2.
