### ISSUE TITLE
WSL Can't start after enabling systemd

### ISSUE THREAD

**Issue by falcon-Z** [microsoft/WSL#9477]
### Version

10.0.22621.1105

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1

### Distro Version

openSUSE-Leap-15.4

### Repro Steps

Followed Instructions to enble Systemd from this  [Article](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/)

### Set the system flag set in your WSL distro settings

You will need to edit the [wsl.conf](https://docs.microsoft.com/windows/wsl/wsl-config#wslconf) file to ensure systemd starts up on boot.

Add these lines to the /etc/wsl.conf (note you will need to run your editor with sudo privileges, e.g: sudo nano /etc/wsl.conf):

```
[boot]
systemd=true
```

And close out of the nano editor using CTRL+O to save and CTRL+X to exit.

### Final steps
With the above steps done, close your WSL distro Windows and run wsl.exe --shutdown from PowerShell to restart your WSL instances. Upon launch you should have systemd running. You can check this with the command systemctl list-unit-files --type=service which should show your services’ status.

### Expected Behavior

Expected WSL to start with Sytemd enabled

### Actual Behavior

After Restarting WSL i had the following error

```
Catastrophic failure
Error code: Wsl/Service/CreateInstance/E_UNEXPECTED

[process exited with code 4294967295 (0xffffffff)]
```
I cannot access any Resources related to my distro anywhere from terminal to file explorer

### Diagnostic Logs
[WslLogs-2023-01-18_10-47-21.zip](https://github.com/microsoft/WSL/files/10442401/WslLogs-2023-01-18_10-47-21.zip)

_No response_

**Comment by sbradnick** [comment]
I'm not sure if you actually put this:
```
[boot]
system=true
```
in `/etc/wsl.conf`, but the entry _should_ be:
```
[boot]
systemd=true
```
Note it's `systemd=true`, not `system=true`.

**Comment by falcon-Z** [comment]
Sorry, that was a typo due to Autocorrect.  I've corrected it and i am certain i had the right entries in `wsl.conf`

> in `/etc/wsl.conf`, but the entry _should_ be:
> 
> ```
> [boot]
> systemd=true
> ```

**Comment by falcon-Z** [comment]
Just to be sure i tried reinstalling Open SUSE Leap and did the same to enable systemd and after Restarting WSl i experienced the same issue with the same error message

I also tried Open SUSE Tumbleweed and experienced no issues there systemd works as expected

**Comment by sbradnick** [comment]
What version of Leap does Windows report is installed? I can't imagine it makes a huge difference, but I'm curious. Since systemd has been mainstream in WSL (i.e. post v1.0.0), I haven't had issues with it. Early on, there was an issue w/ what `/sbin/init` was pointing to, and that may not have even been with Leap.

![2023-01-17-134251_914x455_scrot](https://user-images.githubusercontent.com/84082961/212984472-943f81a4-70e5-4b36-943b-ae303b852bb9.png)

Also, do you have any `.wslconfig` file in your home directory in Windows?

**Comment by falcon-Z** [comment]
Updated issue with logs see section Diagnostic logs for  the log file

**Comment by falcon-Z** [comment]
@sbradnick app version seems different . in my case
![Screenshot 2023-01-18 104411](https://user-images.githubusercontent.com/28111283/213091732-e1155aea-a1bc-4b8e-8f2d-2adb126b1c9a.png)

> Also, do you have any .wslconfig file in your home directory in Windows?

I dont know what you mean by home directory on windows. If you ean my **user** folder then i dont see a `.wslconfig` file  and i dont think any such file exists in my system

I also had Leap reinstalled to check if `.wslcinfig` exists there and i couldn't find such file.

**Comment by sbradnick** [comment]
> I dont know what you mean by home directory on windows. If you ean my user folder then i dont see a .wslconfig file and i dont think any such file exists in my system

I suppose `%HOMEPATH%` or `$env:HOMEPATH` would be better in Windows ;) `.wslconfig` is a control file/mechanism for **ALL** WSL distros; whereas `<some distro>:/etc/wsl.conf` would be for a specific distro. I just wanted to remove the possibility of something [Windows] system wide interfering.

`154.1.855.0` is what's offered up by the Store[front], but none of them have even been broken in this regard. I will install later versions from our build system from time to time, so that's most likely why you see a different version.

I also don't want to throw out "Well, it works for me." - but that is true. So you can do a fresh install of the distro and when the ONLY thing you do is add:
```
[boot]
systemd=true
```
to `/etc/wsl.conf`, then you get that error?

**Comment by OneBlue** [comment]
Thank @falcon-Z.

I'm not seeing any WSL logs in the file you shared. Did you run wsl.exe while the log collection was running ? 

To be sure, can you run: wsl.exe --shutdown, and run the log collection again (make sure to capture the error)

**Comment by aahahocevar** [comment]
I have the same problem, here is my logs

[WslLogs-2023-02-05_18-55-12.zip](https://github.com/microsoft/WSL/files/10611911/WslLogs-2023-02-05_18-55-12.zip)

**Comment by OneBlue** [comment]
@aahahocevar: I'm not seeing any logs (.etl) files in the trace you sent. Can you please try capturing them again ?

**Comment by sbradnick** [comment]
See https://github.com/microsoft/WSL/issues/9602#issuecomment-1421897547 ; If you're having the same issue in Leap, this is most likely the fix ; I fixed it overall a few months ago (and since I add [my repo](https://build.opensuse.org/package/binaries/home:sbradnick/patterns-wsl) to new installs, in general) I've gotten accustomed to `zypper in -t pattern wsl_systemd` which includes my fix.

**Comment by aahahocevar** [comment]
Nice!, it worked with "**zypper in -t pattern wsl_base**", thanks a lot!

**Comment by Lordxan** [comment]
My WSL instance stopped working because of this line how can i fix it? Is there some kind of switch to start WSL instance without this config?

**Comment by jamesgecko** [comment]
Ran into this on a fresh openSUSE Leap 15.5 installation. It's still a problem, and neither this nor #9602 should be closed imho.

> My WSL instance stopped working because of this line how can i fix it? Is there some kind of switch to start WSL instance without this config?

I was able to recover my installation with [the instructions for mounting the vhdx in #9602](https://github.com/microsoft/WSL/issues/9602#issuecomment-1422492042) and enable systemd by adding the missing `/sbin/init` symlink [also described in the ticket](https://github.com/microsoft/WSL/issues/9602#issuecomment-1421897547).

**Comment by jlriven** [comment]
wsl1 can switch to systemd?
