### ISSUE TITLE
WSL Crash often since my last update (Error code: Wsl/Service/0x8007274c)

### ISSUE THREAD

**Issue by quentinsimon** [microsoft/WSL#9852]
### Windows Version

Microsoft Windows [version 10.0.22621.1413]

### WSL Version

1.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 20.04

### Other Software

WSLg version: 1.0.49
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1413

### Repro Steps

I start my environment with docker-compose -up then I work on different projet using Visual Code
Finally, after one or 2 hours, WSL starts to become unstable until it crashes

### Expected Behavior

No decreased performance

### Actual Behavior

Since I've updated my Windows to the latest version few weeks ago, my WSL implementation is getting slower and slower and I have to reboot it with wsl --shutdown at least one time a day ...
When I get in trouble, my Ubuntu terminal says  "Error code: Wsl/Service/0x8007274c"

![image](https://user-images.githubusercontent.com/5383226/227914003-14238cc2-46f1-4f63-b207-96f24d6aa02b.png)

### Diagnostic Logs

Here my logs
[WslLogs-2023-03-27_12-10-49.zip](https://github.com/microsoft/WSL/files/11077418/WslLogs-2023-03-27_12-10-49.zip)

**Comment by benhillis** [comment]
@QAnders - I have started rolling out https://github.com/microsoft/WSL/releases/tag/1.1.6 to all users which should fix this issue.

**Comment by QAnders** [comment]
> @QAnders - I have started rolling out https://github.com/microsoft/WSL/releases/tag/1.1.6 to all users which should fix this issue.

Thanks, @benhillis !
I'll apply the update and let you know how it plays out...

**Comment by QAnders** [comment]
So far, so good, @benhillis... I'll keep an eye on it and report back if it dies again!

WSL has stayed "alive" during the night, something it hasn't done in a long while... Version seems right:
```
C:\Users\AndersWasen>wsl --version
WSL version: 1.1.6.0
Kernel version: 5.15.90.1
WSLg version: 1.0.50
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.1696
```

**Comment by QAnders** [comment]
@benhillis , nope, sorry to say WSL has crashed while I was away on lunchbreak... :(

The fix does not solve the issue I have...

**Comment by quentinsimon** [comment]
Hi @benhillis,

I've tried your fix but unfortunately my WSL is still crashing at some point
![image](https://user-images.githubusercontent.com/5383226/229119007-8e15ed7e-e03a-4ad1-a6ea-102f1c7c29b2.png)

Here my logs : 
[WslLogs-2023-03-31_14-24-51.zip](https://github.com/microsoft/WSL/files/11121769/WslLogs-2023-03-31_14-24-51.zip)

Thanks to have a look

**Comment by QAnders** [comment]
Same as @quentinsimon I too get another error message now:
```
Error code: Wsl/Service/0x8007274c

[process exited with code 4294967295 (0xffffffff)]
```
Previously (prior to the "fix") the Terminal just closed down and no error was shown anywhere.

**Comment by gabrieleiacono** [comment]
I'm on 1.1.6 and WSL just won't start anymore. The `wsl` simply hangs indefinitely (I stopped the process after 15 minutes), as well as any attempt to launch a distro or Docker. If I press ctrl+c while the distro is loading I get `[process exited with code 3221225786 (0xc000013a)]`.

I have also started encountering these issues since the last update. I'm on Windows 10.0.19044.2728.

Any ideas?

**Comment by QAnders** [comment]
1.1.6 was not an improvement for me, only change was basically that I got another error message when WSL crashed...

I've just added 1.1.7 (latest release) and this far it seems better... 
https://github.com/microsoft/WSL/releases/tag/1.1.7

Not sure if it is related but I got a weird error now where my clock is set to GMT (I am on GMT+2, CET) and the time synchronization isn't working... This seems to have happened after applying 1.1.7 and restarting... 😲

**Comment by QAnders** [comment]
Noticed there's a v1.2.3 already, applied and restarted, but noticed WSL still crashed after coming back from coffee break and waking up laptop... :(

**Comment by QAnders** [comment]
This morning I got the updates:
`2023-01 Update for Windows 11 Version 22H2 for x64-based Systems (KB4023057)`
`Windows Subsystem for Linux WSLg Preview - 1.0.27`

Ok, so, thumbs and fingers crossed but I have now ran the whole day without a crash!

I haven't run this long for a few weeks without a crash so it could finally be fixed...

**Comment by one0oneChen** [comment]
我在自己的win10上也碰到这个问题, 经过查询发现可能与系统自带的openssl.exe有关, 自带的openssl.exe程序会造成VScode的WSL连接插件经常断线, 接着如果用cmd进入wsl, 发现报错 Wsl/Service/0x8007274c

可以尝试用Git/usr/bin/ 路径下的openssl.exe 来取代 windows默认的openssl, 方法是将Git安装目录下的Git/usr/bin/路径加入系统环境变量path中, 并保持系统默认的openssl的环境变量位置在Git/usr/bin/的下方, 重启cmd后, 
输入 ssh -V, 查看返回的ssh版本, 如果是 OpenSSH_9.0p1, OpenSSL 1.1.1q  5 Jul 2022 之类的不含有windows签名的版本就完成了

**Comment by IceRainow** [comment]
WSL crash often on Surface Pro X . (Error code: Wsl/Service/0x8007274c)


WSL 版本： 1.3.15.0
内核版本： 5.15.90.4-1
WSLg 版本： 1.0.55
MSRDC 版本： 1.2.4419
Direct3D 版本： 1.608.2-61064218
DXCore 版本： 10.0.25880.1000-230602-1350.main
Windows 版本： 10.0.23521.1000

**Comment by quentinsimon** [comment]
A little up on that post  @benhillis please 🙏 
My WSL environment is still very unstable and sometimes I have to restart my computer twice. I have updated all my libraries and I think I am up to date ...

![image](https://github.com/microsoft/WSL/assets/5383226/665ac7b1-782a-4526-97e1-8ad37288a416)

WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.2361

Logs : 
[WslLogs-2023-10-09_11-24-34.zip](https://github.com/microsoft/WSL/files/12844348/WslLogs-2023-10-09_11-24-34.zip)

Please if somebody could improve the reliability af WSL would be great !!

**Comment by quentinsimon** [comment]
And we keep going into troubles :(

[WslLogs-2023-10-12_16-46-23.zip](https://github.com/microsoft/WSL/files/12883868/WslLogs-2023-10-12_16-46-23.zip)

**Comment by edsonms-sato** [comment]
Still happening in 2026:
"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Error code: Wsl/Service/0x8007274c"

WSL version: 2.7.10.0
Kernel version: 6.18.33.2-2

Already tried:
[wsl2]
memory=16GB
swap=8GB
